### ISSUE TITLE
[Siga-Doc] Botões "Pesquisar" e "Novo" não aparecem na página inicial do Siga

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#100]
-Ilustração:
![captura_de_tela_012115_122237_pm](https://cloud.githubusercontent.com/assets/4949149/5837671/391aca6a-a168-11e4-9b97-911b1a3b3466.jpg)

-Como reproduzir:
Acessar página inicial do Siga. Erro intermitente.

**Comment by kmacedovarela** [comment]
Este erro ocorre pois os botões estão associados a exibição do módulo Processos Administrativos. Quando este não é exibido, consequentemente, os botões não são. #60

**Comment by Chrystinne** [comment]
@kmacedovarela As vezes, estes botões são exibidos mesmo quando o módulo não é exibido, só que abaixo de "Expedientes", conforme ilustração abaixo:

![captura_de_tela_012115_123019_pm](https://cloud.githubusercontent.com/assets/4949149/5837791/5f5f3656-a169-11e4-912d-d62eeff88a71.jpg)
