### ISSUE TITLE
GERAL: comportamentos comuns nos módulos do Siga

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#1000]
- [ ] Salvamento automático
- [ ] Duplicar
- [ ] Vincular/Desvincular
- [ ] Identificação de contexto (expediente, solicitação, conhecimento, lotação, matrícula, item de configuração...)
- [ ] Cadastro de interessados
- [ ] Rotina de transferência/escalonamento, inclusive em lote

**Comment by esredson** [comment]
Isso vai possibilitar que soluções como a da solicitação TRF2-SR-2015/09747 não precisem ser repetidas entre os módulos. É complexo, mas precisamos implementar passo a passo. Comecei a esboçar a minha sugestão de solução em https://gist.github.com/esredson/d9a5a50fd98aaac2037c4720b35a0d54
