### ISSUE TITLE
SR: marca pendente fica sem pessoa ou lotação associada > pendente()

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#1009]
Isso ocorreu seguindo o seguinte fluxo.
Gravar uma solicitação como rascunho. Na tela de edição do TMP inserir uma pendência. Após, editar essa solicitação e mandar gravar retirando a marcação de rascunho. 

Tem que verificar qual ação tomar: 
Se quando a solicitação está pendente e também em elaboração, não deve ser habilitado o link para editar, ou ao gravar a solicitação sem ser rascunho, terminar a pendência automaticamente, caso ela exista.

**Comment by Chrystinne** [comment]
A estratégia escolhida foi não impedir totalmente a edição da solicitação enquanto há pendência. A única coisa que não pode ser alterada, em uma SR em elaboração com alguma pendência, é que a solicitação deixe de ser rascunho. Nesse caso, é necessário terminar a pendência antes.
