### ISSUE TITLE
[Siga-Doc] Erro ao agendar publicação no DJE

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#101]
Ao tentar fazer um agendamento no DJE ocorre o erro java.lang.NoClassDefFoundError: com/sun/org/apache/xml/internal/serialize/OutputFormat

Como reproduzir:
1. Acesse o documento http://siga-hmg/sigaex/expediente/doc/exibir.action?sigla=JFRJ-POR-2015%2F00001-A
2. Clique no link "Agendar Publicação no DJE"
3. Digite a data de disponibilização para Dia Atual + 2 (Ex: em 21/01/2015 digite 23/01/2015)
4. Clique em OK

Imagem do erro:

![image](https://cloud.githubusercontent.com/assets/2985140/5838241/212128fa-a16d-11e4-9ce2-fd96516a3307.png)

**Comment by kmacedovarela** [comment]
#149
