### ISSUE TITLE
Doc: Possibilitar que usuário realize algumas operações no documento mesmo que não tenha acesso a ele

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#1012]
Possibilitar operações sem que o usuário tenha acesso ao documento:
- [ ] Cancelamento de perfil (interessado, Gestor, Fiscal Administrativo, Fiscal técnico);

**Comment by esredson** [comment]
Ver #568 e #839

**Comment by esredson** [comment]
Ver #1109
