### ISSUE TITLE
Doc: Fazer uma tela para tornar documentos publicáveis no DJE

### ISSUE THREAD

**Issue by adrigrassi** [projeto-siga/siga#1015]
Acrescentar a funcionalidade de incluir dados no BD, nas tabelas siga.ex_tp_doc_publicacao e siga.ex_modelo_tp_doc_publicacao, quando há necessidade de tornar um modelo publicável no DJE.

**Comment by esredson** [comment]
De repente, poderia até ser a mesma de definição das configurações (publicadores, modelos publicáveis, etc)
