### ISSUE TITLE
DOC: Incluir metadados no PDF

### ISSUE THREAD

**Issue by crivano** [projeto-siga/siga#1018]
Tatiana Tanure: - Gostaria de sugerir que o SIGA passe a incluir nos PDFs gerados os metadados do documento (pelo menos título e assunto). Muitos documentos produzidos no SIGA são linkados ao portal e indexados pelo GSA e demais motores de busca.
 
A existência desses metadados possibilita que o snippet apresentado pelo GSA e demais motores de busca seja mais significativo para o usuário que está pesquisando. Quando o metadado título existe, este é utilizado na montagem do snippet apresentado no resultado da busca, caso contrário é exibida a primeira frase encontrada, o que na grande maioria das vezes não representa o documento.

**Comment by esredson** [comment]
TRF2-SR-2016/33802
