### ISSUE TITLE
GERAL: arrumar o tratamento de exceções

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#1025]
Parece que em alguns módulos está sendo usado o AplicacaoExceptionInterceptor e, em outros, usa-se o método exception(), do SigaController. De qualquer forma, quando a AplicacaoException lançada encapsula outra exceção, apenas essa outra está chegando ao erroGeral.jsp.

**Comment by raphaelpaiva** [comment]
Lembrando que a encapsulada geralmente é a mais importante e não deve
deixar de ser reportada!

**Comment by esredson** [comment]
Ver #673
