### ISSUE TITLE
SR: Desconsiderar enter na montagem dos links

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#1029]
Caso seja dado enter após o link, ele está sendo adicionado ao endereço. 

Exemplo:

Ao adicionar o seguinte texto no andamento:

(...) pelo link: https ://github.com/projeto-siga/siga/issues/897

Vamos deixar (...)

Ele monta o link dessa forma:

https ://github.com/projeto-siga/siga/issues/897< br>< br>Vamos

**Comment by rafaela00castro** [comment]
Só para acrescentar um outro exemplo... e o estranho nesse caso é que ele acrescenta a palavra **property** (em destaque na imagem abaixo) antes do texto do link.

_Eu escrevo..._
property name="gcservice.endpoint" value="http://sigagc/link/exemplo/GcExemploService"

property name="gcservice.qname" value="http:/exemplo/ervice.gc.siga.gov.br/"

_E fica..._

![captura_de_tela_112116_024414_pm](https://cloud.githubusercontent.com/assets/8461113/20491576/fa501640-aff8-11e6-8477-999409b17077.jpg)
