### ISSUE TITLE
[Siga-Doc] Erro de encoding na descrição da anotação

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#103]
-Ilustração:
![captura_de_tela_012115_010803_pm](https://cloud.githubusercontent.com/assets/4949149/5838422/89361030-a16e-11e4-9ec2-f83291d2703e.jpg)
 
-Como reproduzir:
Clicar no link "Fazer Anotação" de um documento qualquer (se quiser, pode usar o documento  http://siga-hmg/sigaex/expediente/doc/exibir.action?sigla=JFRJ-MEM-2015/00004-A para efeito de teste); 
Na tela de anotação, preencher o campo "Nota" com um texto contendo caracteres especiais;

**Comment by Chrystinne** [comment]
Relacionado à #76

**Comment by kmacedovarela** [comment]
Associado a #97 , será resolvido quando a issue associada também for.

**Comment by kmacedovarela** [comment]
Resolvido 92079df090efc70aafc9990cc383013318fe834b
