### ISSUE TITLE
WF: java.lang.NullPointerException recorrente lançado no log

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#1030]
Reportado por @raphaelpaiva 

[Server:sigawf-server01] 15:29:02,702 ERROR [org.jboss.as.webservices.invocation.InvocationHandlerJAXWS](http-/172.16.1.72:8580-17) JBAS015594: A invocação do método falhou com a exceção: null: java.lang.NullPointerException

Está periodicamente, várias vezes por segundo. Para por uns 2, 3 segundos e volta a ocorrer. Pensei em alguma chamada agendada, tipo algum Ajax, ou chamada de algum processo que chama um WebService (suspeitei por causo do JAXWS).

Catei no github e achei a issue #172. O Markenson cita uma inconsistência de dados que provoca o NPE.

Não tenho ideia do impacto. De qualquer forma, se for de fato alguma inconsistência, sugiro tratar o NPE (nullcheck ao invés de catch NPE) além de corrigir a inconsistência.

**Comment by esredson** [comment]
#1031

**Comment by raphaelpaiva** [comment]
Depois do deploy de ontem, 5.3.2.6, a stacktrace do erro em questão passou a aparecer (em anexo).

Acho que com isso a #1031 pode ser fechada!

[invocationFailedWF.txt](https://github.com/projeto-siga/siga/files/409273/invocationFailedWF.txt)

**Comment by raphaelpaiva** [comment]
A [linha do erro] `ti.getTask().getTaskController() != null`, leva a crer que o NPE acontece porque `ti` ou  `ti.getTask()` retorna nulo. Como `ti` vem de uma query, e o resultset não é vazio, pois entra no loop, é muito mais provável que `getTask()` retorne nulo, corroborando a tese da inconsistência de dados no banco aferida na #172.

Sugiro investigar por que esta inconsistência acaba acontecendo (outra issue?).

Outra sugestão é encapsular a [query] no WfDao (outra issue?)

[linha do erro]: https://github.com/projeto-siga/siga/blob/4efb964ac461f283519d76b1e76976f879eb8ad5/sigawf/src/main/java/br/gov/jfrj/siga/wf/service/impl/WfServiceImpl.java#L92
[query]: https://github.com/projeto-siga/siga/blob/4efb964ac461f283519d76b1e76976f879eb8ad5/sigawf/src/main/java/br/gov/jfrj/siga/wf/service/impl/WfServiceImpl.java#L83

**Comment by raphaelpaiva** [comment]
Logs de acesso do apache no mesmo segundo em que um dos NPE's aconteceu.

[wf-invocation-sigaex.txt](https://github.com/projeto-siga/siga/files/409683/wf-invocation-sigaex.txt)
[wf-invocation-sigawf.txt](https://github.com/projeto-siga/siga/files/409682/wf-invocation-sigawf.txt)
[wf-invocation-full.txt](https://github.com/projeto-siga/siga/files/409684/wf-invocation-full.txt)

**Comment by Markenson** [comment]
Encontrei uma task instance inconsistente no banco de dados (imagem abaixo) que poderia estar causando esse problema. Porém, essa linha foi criada aproximadamente em 25/08/16 16:40:51,000000000 (hoje) caso o resultado do comando seguinte estiver correto:

```
SELECT SCN_TO_TIMESTAMP(ORA_ROWSCN) from SIGAWF.JBPM_TASKINSTANCE where task_ is null;
```

Não consegui identificar a rotina que permitiu a criação dessa linha, pois ela está sem várias informações importantes (o id do processo ao qual a task instance faz parte). 

![image](https://cloud.githubusercontent.com/assets/2985140/17985058/7e2f2b76-6aea-11e6-80cf-1037e08f1ab4.png)
