### ISSUE TITLE
DOC/WF: mensagem Não Foi Possível Conectar com Wf nem sempre aparece

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#1032]
Em um dos casos, quando a resposta do WF estava, por algum motivo, vindo vazia (response="" e status undefined), a mensagem de erro ao conectar com WF não apareceu

**Comment by raphaelpaiva** [comment]
Não sei se está relatado, mas peguei essa stacktrace no log do doc:

[doc-wf.txt](https://github.com/projeto-siga/siga/files/400318/doc-wf.txt)
