### ISSUE TITLE
GERAL: Rever montagem do prefixo das propriedades

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#1035]
Verificar se parte do prefixo das propriedades correspondente ao órgão poderia ser definida automaticamente. Toda propriedade deveria também ser consultada sem o órgão. Deveria haver um modo padrão de consultar as propriedades.

**Comment by crivano** [comment]
1. já existe uma issue para rever as propriedades: #664
2. modo padrão de consultar propriedades programaticamente ou visualizá-las na interface? Visualizar não é uma boa porque algumas são senhas...
