### ISSUE TITLE
[Siga-Doc] Erro ao visualizar publicação no DJE

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#104]
-Ilustração:
![captura_de_tela_012115_011608_pm](https://cloud.githubusercontent.com/assets/4949149/5838601/ab9a0a7c-a16f-11e4-8d40-2335cbef866c.jpg)

-Como reproduzir:
1. Acessar o documento JFRJ-MEM-2015/00004;
2. Clicar no link "Agendar Publicação no DJE";
3. Clicar no botão "Visualizar publicação";

**Comment by andresousa17** [comment]
Este erro está acontecendo porque documentos do tipo Memorando não são publicados no DJE.

Eu fiz um teste com uma Portaria e o documento gerado está saindo sem conteúdo. 

![image](https://cloud.githubusercontent.com/assets/5269936/5842591/27955ca4-a18d-11e4-836b-61b79ed0cedd.png)

O teste pode ser feito no documento JFRJ-POR-2015/00004.

O documento gerado deveria ser:

![image](https://cloud.githubusercontent.com/assets/5269936/5842532/bd862dc0-a18c-11e4-8066-e28356c82697.png)

**Comment by kmacedovarela** [comment]
Como eu testo a a publicação no DJE?

**Comment by andresousa17** [comment]
1 - Criar um documento Físico do Tipo: Portaria  e Modelo: Portaria
2 - Finalizar o Documento
3 - Fazer o Registro de Assinatura.
4 - Clicar no link "Agendar Publicação no DJE";
5 - Clicar no botão "Visualizar publicação";

**Comment by kmacedovarela** [comment]
@Chrystinne  ou @andresousa17 esse teste pode ser realizado no ambiente de produção beta (lembrando que este ambiente aponta para o banco de produção) ?

**Comment by andresousa17** [comment]
Esse teste do DJE só pode ser feito no ambiente beta com documentos do tipo "Formulário" modelo "Publicação no DJF2R" e preencher o campo lotação de origem com o valor "STI-MJB".

Obs: Para acessar esse formulário vocês precisam entrar como substitutos da SESIA. Já cadastrei essa permissão para vocês.

Para entrar como substituto da SESIA bastar acessar o menu "Siga->Substituir" e clicar no nome da SESIA.

**Comment by kmacedovarela** [comment]
@andresousa17 seria possível você realizar este teste enquanto adiantamos outras issues? Caso o erro ocorra, tomaremos providências.

**Comment by andresousa17** [comment]
@kmacedovarela Fiz o teste e continua dando erro. O documento de publicação está saindo em branco.

**Comment by kmacedovarela** [comment]
Obrigada!

**Comment by kmacedovarela** [comment]
O seguinte erro está ocorrendo:


16:31:40,116 ERROR [stderr] (http-/10.10.0.69:8180-124)
16:31:40,322 ERROR [org.apache.fop.fo.FOTreeBuilder] (http-/10.10.0.69:8180-124) org.xml.sax.SAXParseException; lineNumber: 0; columnNumber: 0; java.lang.IllegalStateException: endElement() called for fo:root where there is no current element.
16:31:40,323 ERROR [stderr] (http-/10.10.0.69:8180-124) SystemId Desconhecido; Linha n°0; Coluna n°0; java.lang.IllegalStateException: endElement() called for fo:root where there is no current element.

tentativas:
utilizar a mesmas versões de biblioteca associadas ao fop
copiar xhtml.dtd e semelhantes, da máquina de produção para garantir que não existem diferenças

O erro ocorre em siga-ex/src/main/java/br/gov/jfrj/itextpdf/FOP.java:111
````
transformer.transform(src, res);
````

Verifiquei o html gerado (siga-ex/src/main/java/br/gov/jfrj/siga/ex/util/GeradorRTF.java:224) tanto na versailles quanto no ambiente atual, e ambos são identicos...

Desconfio de: 
Conflito de bibliotecas utilizadas pelo fop 
Algum detalhe nos arquivos xhtml.dtd e etc. (Permissionamento ou etc..)

**Comment by kmacedovarela** [comment]
Resolvido 
#149
