### ISSUE TITLE
GERAL: tornar mensagens de erro para o usuário mais claras

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#1041]
Por exemplo, quando não se conseguisse arquivar, deveria ser explicado o que exatamente está acontecendo e qual ação pode ser tomada. Talvez, já oferecer a possibilidade de, na própria tela de erro, essa ação ser executada. Por exemplo: "O volume 10 do EOFXXX não pôde ser arquivado porque possui o volume de um outro processo apensado. Clique aqui para desapensar o volume 5 do EOFYYY do volume 10 do EOFXXX."

**Comment by Chrystinne** [comment]
Maravilha essa ideia, @esredson. Além de esclarecer e possibilitar a execução da ação que irá adiantar a vida dos usuários, evitaria que abrissem chamado pra gente. 

Só uma sugestão: poderíamos colocar um checklist na descrição dessa issue, dividindo o problema em 2 partes: 
1- Tornar msgs de erro mais claras; 
2- Possibilitar tomada de ações pelos usuários; 

Porque imagino que a segunda parte vai tomar um certo tempo e a primeira que é bem simples de resolver já traz um ganho considerável, então poderíamos priorizar.

**Comment by raphaelpaiva** [comment]
Existe alguma possibilidade de não ter uma tela de erro? Não sei se é o
caso, mas é muito desconfortável ir pra outra tela por causa de um erro
que, por exemplo, se resolva trocando uma opção num combobox.

Sugiro caixas de mensagens ligadas ao campo com erro, quando for validação
ou um modal.

**Comment by esredson** [comment]
Sem dúvida! Achei que já tínhamos uma issue aberta pra isso, mas parece que não. Abri a https://github.com/projeto-siga/siga/issues/1049.
