### ISSUE TITLE
SR: e-mail de notificação deveria informar por que o usuário está sendo notificado

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#1042]
Com certa frequência, ocorre de um usuário solicitar remoção da lista para a qual é enviada alguma notificação no Siga. É um pouco trabalhoso pesquisar por que o usuário recebeu o e-mail. No próprio corpo, poderia haver a informação do motivo pelo qual ele foi notificado. Por exemplo, "esta mensagem foi enviada a <lotação ou pessoa> porque <você está substituindo a lotação X, atendente dessa solicitação ou outro motivo qualquer>." Aí, se houver a possibilidade de remover a pessoa da lista finalizando uma substituição, pode vir um "clique aqui para terminar a substituição".

**Comment by esredson** [comment]
Aliás, acho que isso deveria acontecer em todo o Siga

**Comment by Chrystinne** [comment]
Boa, @esredson! Ao meu ver, isso melhora muito a experiência do usuário. Acho importante ir abrindo as issues, como você vem fazendo, pra deixarmos registradas essas necessidades de melhorias. Tb acho que vale a pena colocar aqui pontualmente (como checklist) os casos em que usuário é notificado e que poderiam ser encerrados, em todo o Siga. Vou colocar isso na minha lista TO-DO, ok?
