### ISSUE TITLE
SR: alterar forma de filtrar por prioridade na tela de pesquisa

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#1048]
Fomos consultados se existe uma forma de não visualizar solicitações sobre videoconferencia. Uma possível maneira seria mudar a prioridade da solicitação para planejada, e na tela de pesquisa mandar ordenar pela coluna "prior. técnica". Assim essas solicitações ficarão por último, já que é ordenado por ordem alfabética. No entanto, as solicitações somente estariam "destacadas" das outras. Poderíamos melhorar a forma de filtrar as prioridades na tela de pesquisa de solicitações, usando uma das seguintes formas ou outras.

**1ª forma:** : incluir a prioridade máxima, assim na forma como abaixo, excluindo a prioridade planejada nessa pesquisa.

![captura_de_tela_083116_022630_pm](https://cloud.githubusercontent.com/assets/8461113/18139242/ee486eea-6f86-11e6-89e8-d9945426c7d5.jpg)

**2ª forma** : para não visualizar as solicitações com prioridade planejada, bastaria não selecionar o checkbox, como mostra abaixo.

![captura_de_tela_083116_023407_pm](https://cloud.githubusercontent.com/assets/8461113/18139455/fa962ef2-6f87-11e6-8bf5-e6f483b92103.jpg)

**Comment by esredson** [comment]
TRF2-SR-2016/33801
