### ISSUE TITLE
GERAL: mensagens de erro devem ser exibidas na mesma página

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#1049]
Para evitar a troca de tela e, em muitos casos, perda dos dados preenchidos.

**Comment by rafaela00castro** [comment]
Na issue que estou trabalhando (sobre atributos #1010), com as mudanças para fazer requisições por Ajax nas telas de reclassificar/fechar do siga-sr (commit edcd7cc), usei o erroGeralAjax.jsp (criado pela DB1 para "internal server error") e ampliei o seu uso também para as AplicacaoException. 
Existe outras soluções para isso, que podem ser até melhores, mas achei importante sinalizar uma das formas que já existe em um dos módulos do siga sobre essa issue.
