### ISSUE TITLE
[Siga-Doc] Erro ao visualizar documento

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#105]
Ao clicar no botão visualizar documento durante a elaboração do mesmo ocorre o erro java.io.FileNotFoundException: JBWEB000088: The requested resource (/paginas/cabecalho_popup.jsp) is not available

Como reproduzir:
1. Clique no botão Novo na página inicial (abaixo do quadro de documento)
2. Clique no botão "Visualizar Documento"

Ilustrações:

![image](https://cloud.githubusercontent.com/assets/2985140/5838713/59224416-a170-11e4-9264-b1329263e293.png)

![image](https://cloud.githubusercontent.com/assets/2985140/5838722/689daf7a-a170-11e4-9f34-69ad0ca9460e.png)

**Comment by kmacedovarela** [comment]
#137
