### ISSUE TITLE
Aplicações play no ambiente de homologação não estão utilizando DS

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#106]
As aplicações que utilizam Play Framework não estão se conectando ao banco através de datasource.   É necessário ajustar esta configuração

**Comment by kmacedovarela** [comment]
Obs: esta issue está em analise no momento por ser crítica.

**Comment by kmacedovarela** [comment]
O erro que gerou esta issue foi analisado de maneira incorreta. 
- As aplicações PLAY estão utilizando os datasources conforme esperado

O problema identificado e descrito abaixo, se não solucionado, afetará a inclusão de todos os módulos que utilizam Play! Framework, principalmente, no ambiente de produção.

O problema atual é:
As aplicações que utilizam Play! Framework por algum motivo não estão aceitando a propriedade do hibernate "hibernate.default_schema". 
A consequência disto é que quando uma aplicação utiliza um usuário diferente de seu schema, os selects executados para as sequences anotadas com @GeneratedValue, serão sem schema, logo ocasionará em erro ORA-02289.

Exemplo:
Incorreto: select hibernate_sequence.nextval from dual
Correto  : select SIGATP.hibernate_sequence.nextval from dual

Prevejo possíveis soluções para este problema. Continuarei as analises para decidir a melhor saída para o momento atual.

**Comment by kmacedovarela** [comment]
Problema identificado: 

Mais uma intervenção das classes do play em configurações padrões:
Na classe https://github.com/playframework/play1/blob/1.3.x/framework/src/play/db/Configuration.java, no método que se inicia na linha 94, é executada uma lógica para validar as propriedades que serão utilizadas pelo hibernate. Nesta lógica, o play recebe o parâmetro correto "hibernate.default_schema" (que se permanecesse assim, os projetos funcionariam normalmente), e substitui por "hibernate.schema", um valor irrelevante para o hibernate 4.

Uma análise da melhor abordagem será feita, para que não seja necessário mais uma vez, modificar o código do framework devido a um comportamento não desejado e imposto pelo mesmo.

**Comment by kmacedovarela** [comment]
A recomendação é que as aplicações play se adequem ao padrão de configuração de sequence, alterando nos modelos a seguinte configuração para os Ids com geração automatica:

Antes:
@Id 
@GeneratedValue 
public Long id;

Depois:
@Id 
@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "hibernate_sequence_generator") 
@SequenceGenerator(name = "hibernate_sequence_generator", sequenceName="NOMEDOSCHEMA.hibernate_sequence") 
public Long id;

**Comment by jmolivei** [comment]
Para efeito de documentação relato que ontem descobrimos uma forma de contornar o problema da propriedade HIBERNATE.DEFAULT_SCHEMA, que o play 1.3 capturava como HIBERNATE_SCHEMA. Repassamos para a Karina um e-mail explicando uma situação de contorno para o problema que seria configurar a propriedade de forma a enganar o play 1.3 e ele capturar a informação correta. A propriedade deve ser configurada da seguinte forma  HIBERNATE.DEFAULT.DEFAULT_SCHEMA. Isto já foi realizado pela Karina e está funcionando. Acontece que logo depois de enviar o e-mail para a KArina, verificamos na documentação oficial do play que o comportamento do framework estava correto. O play 1.3 sofreu alterações para suportar múltiplos databases. Logo quando ele carrega as configurações do Hibernate para um database apenas , ele procura nas propriedades que se iniciam com os prefixos "db." ou "hibernate." a palavra default e as retira essa palavra carregando esta propriedade no hibernate para o database configurado com "default".  Sempre quando existe somente um database configurado, o play carrega suas configurações procurando esta palavra "default' nas propriedades descritas acima.Logo a forma correta de se configurar as propriedades que iniciam com os prefixos "db." e "hibernate." no play 1.3    se dá desta forma : hibernate.default.default_schema=SIGATP, db.default.user=SIGATP, etc....Segue o link da documentação oficial do play 1.3 https://www.playframework.com/documentation/1.3.x/configuration e este outro link que fala do suporte a múltiplos databases disponível no play 1.3 http://play.lighthouseapp.com/projects/57987/tickets/706-multiple-databasejpa-support

**Comment by kmacedovarela** [comment]
Muito bom, se aplica a todos os módulos play!!! Obrigada João!!
