### ISSUE TITLE
[Siga-Doc] Erro ao exibir Conhecimentos Relacionados

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#107]
Erro intermitente.

-Ilustração:
![captura_de_tela_012115_013952_pm](https://cloud.githubusercontent.com/assets/4949149/5839084/fb630f6a-a172-11e4-810b-2d98b188b9bd.jpg)

**Comment by kmacedovarela** [comment]
@Chrystinne  pode ser pois estamos reiniciando os servidores que disponibilizam este módulo para manutenção e inserção de novas configurações. Vou deixar a issue aberta, para que seja retestada assim que estabilizarmos os serviços;

**Comment by Chrystinne** [comment]
De fato, esse erro ocorreu 2 ou 3 vezes, mas pode ter se repetido por esse motivo. Como já acessei  diversos documentos e não voltou a acontecer, vou fechar a issue.
