### ISSUE TITLE
GC: •	A lista de movimentações do Siga-Gc está desaparecendo subitamente. 

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#1070]
Observado no Internet Explorer

**Comment by Chrystinne** [comment]
O que está ocorrendo nesse caso é que algumas vezes as movimentações em um conhecimento são exibidas na tela enquanto a parte dos conhecimentos relacionados (mais à direita) ainda está carregando. Quando os conhecimentos relacionados tornam-se disponíveis, o conteúdo das movimentações é deslocado para baixo, para ser exibida abaixo da lista dos conhecimentos.

**Comment by Chrystinne** [comment]
A resoluçã da #1154 e da #1156 resolve o problema desta issue.
