### ISSUE TITLE
[Siga-Doc] Erro ao editar Formulário/Comunicações de Alterações de frequência

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#108]
Durante a elaboração de um documento Formulário/Comunicações de Alterações de frequência, as opções adicionais não estão sendo exibidas

Como reproduzir:
1. Crie um novo documento
2. Selecione o tipo Formulário
3. Selecione o modelo Comunicações de Alterações de frequência
4. Nos dados complementares, digite o nome de uma lotação (Ex: SESIA)
5. No campo Frequência ao lado do nome das pessoas altere de "Sem lançamentos" para "Com lançamentos"
6. Nesse momento o sistema deveria abrir algumas opções adicionais

Ilustração:
![image](https://cloud.githubusercontent.com/assets/2985140/5840519/4f230a4c-a17d-11e4-950d-60a392c671c9.png)

**Comment by kmacedovarela** [comment]
Obs. Erro ocorre apenas no IE.

**Comment by kmacedovarela** [comment]
Estava relacionado a problemas de encoding resolvidos em 92079df090efc70aafc9990cc383013318fe834b
