### ISSUE TITLE
SR: Erro ao abrir solicitação

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#1081]
Reportado no chamado TRF2-SR-2016/33649.01. 
O usuário estava substituindo a SECLOT quando obteve o seguinte erro ao tentar abrir chamado no SR.

![erro siga](https://cloud.githubusercontent.com/assets/4949149/18848534/2dd769de-8405-11e6-9aa2-0bf901f63714.png)

**Comment by rafaela00castro** [comment]
Vendo problema de LIE, pois pode ser por conta de alguma alteração que eu fiz na versão 5.3.4.X

**Comment by rafaela00castro** [comment]
Ao gravar a solicitação, se ela não for filha, ou rascunho, depois de pegar um novo número, ele define o tempo de cadastro.
		Mas para definir o tempo de cadastro é necessário saber o horario de trabalho da lotação responsável pelo cadastramento. Como isso ainda está hardcoded, a verificação é feita pela sigla da lotação. No caso, deve-se nessa parte `lotaAtendente.getSigla().startsWith("NTI-SL")` trocar de `getSigla()` para `getSiglaLotacao()`.  Já que o primeiro método chama o `isFechada()` para acrescentar a palavra "(extinta)", sendo essa informação desnecessária para verificação do horário de trabalho.

**Comment by rafaela00castro** [comment]
A solicitação TRF2-SR-2015/17314 trata da implementação da tela de horário para remover definitivamente essa parte hardcoded, Está aguardando priorização.
