### ISSUE TITLE
DOC: Alteração de localidade em algumas lotações

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#1082]
Reportado via chamado TRF2-SR-2016/33721.01.

Localidade de usuários lotados na T2SEASTI e SEPATI está sendo preenchida no Siga como São João de Meriti.

**Comment by esredson** [comment]
#795

**Comment by Chrystinne** [comment]
@esredson Tem mais um chamado sobre esse erro, o TRF2-SR-2016/33785.01, da T2SETI.
