### ISSUE TITLE
[DEV] Disponibilização do sistema no branch develop 

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#109]
Favor disponibilizar versão mais recente do branch develop na Versailles, para facilitar na execução de testes.

**Comment by kmacedovarela** [comment]
@Markenson  @esredson @Chrystinne @rafaela00castro  alguém poderia realizar esta disponibilização?

**Comment by Chrystinne** [comment]
@kmacedovarela Vou fazer

**Comment by kmacedovarela** [comment]
Ok, aguardo fechamento desta issue com urgência.

**Comment by kmacedovarela** [comment]
Senhores, me foi indicado para testar na porta 8280 do servidor de desenvolvimento porém as aplicações que utilizam play não estão disponiveis lá. Alguém poderia disponibilizar a versão do branch develop das aplicações sigagc e sigasr na maquina versailles por gentileza? Obrigada.

**Comment by Chrystinne** [comment]
@kmacedovarela Está disponível na versailles (porta 8280). O Edson acabou de testar e tanto o Siga-Sr quando Siga-Gc estão acessíveis.

**Comment by kmacedovarela** [comment]
Através desta URL não consegui acessar, estou acessando do modo correto? Entrei com o usuário do markenson.

http://versailles:8280/siga/

![capturar](https://cloud.githubusercontent.com/assets/253186/5857578/09b0edc8-a234-11e4-975e-951fc2a51b65.PNG)

**Comment by Chrystinne** [comment]
Realmente, agora o Edson não está mais conseguindo acessar da máquina dele também. Serve o deploy na Sigat?

**Comment by Chrystinne** [comment]
@kmacedovarela Tenta novamente agora na versailles (8280). Pra mim agora está ok.
