### ISSUE TITLE
SR/GC: a lista de relacionados ao exibir solicitação está muito longa

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#1094]
Deveria ser usado o mesmo critério da página de edição de solicitação, pois estão sendo mostrados muitos conhecimentos desnecessários.

**Comment by Chrystinne** [comment]
Testei na versão de produção (com alguns itens de configuração como Siga-Doc) e a lista de conhecimentos relacionados na abertura/edição e exibição de solicitações está idêntica.
