### ISSUE TITLE
[Siga-Doc] Erro ao visualização do despacho

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#110]
-Ilustração:
![captura_de_tela_012115_034845_pm](https://cloud.githubusercontent.com/assets/4949149/5841560/fc98856a-a184-11e4-8d58-b0d09ae3dd99.jpg)

-Como reproduzir:
1. Acessar o documento JFRJ-MEM-2015/00004-A;
2. Clicar no link Despachar/Transferir;
3. Selecionar um despacho;
4. Clicar em "Visualizar Despacho";

**Comment by kmacedovarela** [comment]
Mesmo erro da #105

**Comment by kmacedovarela** [comment]
#137
