### ISSUE TITLE
GC: logo após gravar conhecimento, não o exibe ao selecionar o item de configuração

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#1104]
Reportado pelo João, da DISUT. Após gravar conhecimento âncora, ocorre redirecionamento para a tela de abertura de solicitação. Selecionando-se o item de configuração ao qual o conhecimento está associado como âncora, o conhecimento não aparece.

**Comment by Chrystinne** [comment]
Esse erro não ocorre mais. Caso seja criado um conhecimento âncora, este está sendo inserido na tela de cadastro/edição de SRs, abaixo do campo "Produto, Serviço ou Sistema relacionado à Solicitação", sendo necessário apenas selecionar novamente o IC, após a criação do conhecimento.
