### ISSUE TITLE
[Siga-Doc] Erro na funcionalidade "Esqueci minha senha"

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#111]
Ao utilizar a funcionalidade "Esqueci minha senha" o sistema apresenta a seguinte mensagem de erro: Caused by: java.security.InvalidKeyException: Illegal key size or default parameters

Como reproduzir:
1. Na página de login do siga clique no link "Esqueci minha senha"
2. Digite a matrícula e o CPF da pessoa e clique em OK

OBS: Existe um tratamento para esse tipo de problema na versão anterior do siga emhttps://github.com/projeto-siga/siga/wiki/Erros-Conhecidos#illegal-key-size-or-default-parameters

Imagem:
![image](https://cloud.githubusercontent.com/assets/2985140/5842510/864af64c-a18c-11e4-89a3-1a24e5f82a9e.png)

**Comment by hodrigohamalho** [comment]
Fiz a alterações nas JVMs do Siga DOC.
A única diferença para o que está na wiki é que como usamos JDK 1.7 o link para baixar agora é:
http://www.oracle.com/technetwork/pt/java/javase/downloads/jce-7-download-432124.html

Segue o procedimento utilizado nas máquinas classea, classee e classef.

```
jboss stop
cd /usr/java/jdk1.7.0_71/jre/lib/security
mv local_policy.jar US_export_policy.jar /home/hjbossadmin/
mv /tmp/UnlimitedJCEPolicy.zip .
unzip UnlimitedJCEPolicy.zip
mv UnlimitedJCEPolicy/*.jar .
rm -rf UnlimitedJCEPolicy
rm UnlimitedJCEPolicyJDK7.zip
rm: remove regular file ‘UnlimitedJCEPolicyJDK7.zip’? y
chmod g-x local_policy.jar US_export_policy.jar
jboss start
```

@Markenson testei com minha matrícula e deu certo em hmg, você poderia refazer o seu teste?

**Comment by kmacedovarela** [comment]
Problema resolvido, caso o email não seja enviado, favor abrir nova issue
