### ISSUE TITLE
DOC: sistema não está removendo a dt_fim_mov na transferência de devolução 

### ISSUE THREAD

**Issue by adrigrassi** [projeto-siga/siga#1112]
![image](https://cloud.githubusercontent.com/assets/5265327/20360778/30b913ca-ac1c-11e6-90c5-638f37da6fbf.png)

Verificar o motivo do sistema não estar removendo a dt_fim_mov mesmo quando o documento retorna dentro do prazo.

**Comment by Chrystinne** [comment]
Descobri que o erro ocorre porque uma situação de erro que já havia sido corrigida antes (documentos que foram juntados antes de serem devolvidos) voltou a dar problema porque o código da correção foi removido (por gerar muito processamento e estarmos priorizando melhorar a performance);
