### ISSUE TITLE
GERAL: problema do detach ao instanciar parâmetros

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#1114]
Existe um interceptor `ParametersInstantiatorInterceptor` para "tratar" os parâmetros antes que eles sejam passados para os Controllers da aplicação. Com isso, a através da classe `ObjetoObjectInstantiator` existe um tratamento para buscar a referência no banco (find), caso o ID do objeto seja passado. Logo após, é feito o `detach` para evitar que alterações nesse objeto sejam sincronizadas (flush) com o banco, em possíveis manipulações no Controller e classes de regra de negócio.
```
EntityManager em = ContextoPersistencia.em();
obj = em.find(target.getClassType(), id);
if (obj != null)
    em.detach(obj); // Detached para que não seja acidentalmente salva no banco de dados
```
Como esse detach é "superficial", ou seja, só ocorre no próprio objeto, ainda existe risco de acidentalmente salvar alterações no banco. Ver esquema abaixo, com exemplo de uma solicitação (SrSolicitacao) do Siga-SR:

![captura_de_tela_111716_062955_pm](https://cloud.githubusercontent.com/assets/8461113/20406281/db08f642-acf3-11e6-86a0-74196a34bd9c.jpg)
![captura_de_tela_111716_063621_pm](https://cloud.githubusercontent.com/assets/8461113/20406501/bd5c36bc-acf4-11e6-9a9b-cfcc27a9f116.jpg)

**Comment by rafaela00castro** [comment]
Para saber todo o conteúdo do **persistence context**, basta colocar o código abaixo na View > Display do Eclipse e inspecioná-lo: `((Session) ContextoPersistencia.em().getDelegate()).toString()`.

E para saber se determinado objeto está sendo gerenciado no **persistence context**: `ContextoPersistencia.em().contains(objeto)`

**Comment by esredson** [comment]
Conforme conversamos, seria legal que o Instantiator fizesse o detach recursivo, levando em conta as entidades dependentes. Só é importante testar bem antes dessa alteração, pois impacta muitas rotinas. De qualquer forma, o melhor mesmo seria não precisarmos usar classes do modelo para setar diretamente os valores que vêm do formulário.
