### ISSUE TITLE
DOC: Recursos do editor do siga estão sendo buscados na internet

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#1116]
Recursos do editor do siga estão sendo buscados na internet podendo impactar no bom funcionamento do sistema em caso de incidentes associados à disponibilidade da internet.

![image](https://cloud.githubusercontent.com/assets/2985140/20564362/11c8e32a-b174-11e6-8007-082405351a89.png)

**Comment by jmolivei** [comment]
Os recursos acima são buscados na internet somente quando a configuração CKEDITOR.config.scayt_autoStartup está configurada para true na macro do modelo geral do SIGA ou se o usuário habilitar manualmente o editor click abaixo na opção. 

![habilitarcorretorortograficoaddonsckeditor](https://cloud.githubusercontent.com/assets/5268745/26692261/6c2b5f9e-46d6-11e7-8a18-4132535e2049.png)

Ver solução em issue #1180

**Comment by jmolivei** [comment]
Print dos recursos depois de desabilitado editor interno do ckeditor

![urlckeditor](https://cloud.githubusercontent.com/assets/5268745/26694923/77e9b8e0-46df-11e7-8571-94059aca9e1a.png)
