### ISSUE TITLE
[Siga-Sr] Cadastro de Ação está com problema de duplicação

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#112]
-Ilustração:
![captura_de_tela_012115_045850_pm](https://cloud.githubusercontent.com/assets/4949149/5842798/012089f2-a18f-11e4-84f2-1ee12c9c6194.jpg)

-Como reproduzir:
1. Acessar a página de Cadastro de Ação (http://siga-hmg/sigasr/acao/listar);
2. Clica em Incluir;
3. Preencher código e Título com valores quaisquer;
4. Clicar em Gravar;

**Comment by hodrigohamalho** [comment]
Essa issue não acontece nem no ambiente local, nem em desenvolvimento, tem que verificar porque que está ocorrendo em hmg.

**Comment by hodrigohamalho** [comment]
Testei em homologação e também não está ocorrendo em homologação. Talvez tenha sido solucionado através de outra correção.

Poderia testar novamente @Chrystinne ?

**Comment by Chrystinne** [comment]
@hodrigohamalho Ok. Vou testar.

**Comment by kmacedovarela** [comment]
Validado e ok.
