### ISSUE TITLE
DOC: "Desfazer Desentranhamento" não funciona

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#1120]
Reportado por Misael, CJF: Não está funcionado o botão “Desfazer desentranhamento”. Ou seja, o documento desentranhado não está voltando para o dossiê. O documento está ficando perdido. Não fica nem na caixa do usuário;

**Comment by Chrystinne** [comment]
@esredson Peguei essa issue, mas não consegui reproduzir esse erro no ambiente de desenvolvimento. Desfiz o desentranhamento e o documento voltou para o dossiê. Você chegou a reproduzir esse erro?

**Comment by esredson** [comment]
@Chrystinne, também não consegui simular. Estou fechando a issue, assumindo que, na versão atual, já está ok.
