### ISSUE TITLE
Siga-Doc: Documentos já finalizando estão com a marca "Em elaboração"

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#1124]
O Siga está mantendo a marca "em elaboração" na parte geral dos documentos, mesmo após a sua finalização. Após finalizá-lo, o Siga adiciona a marca "Aguardando andamento" na 1ª via, mas mantém em elaboração a parte geral. Mesmo após arquivar o documento, a marca "Em elaboração" permanece na parte geral, ficando a 1ª via arquivada. 

- Reproduzi o erro nas seguintes situações:

1. Documento interno produzido com uma única movimentação de finalização;
![tela1](https://cloud.githubusercontent.com/assets/4949149/20800402/8b7e3efa-b7cc-11e6-9e49-1cfc45b0e777.png)

2. Documento externo com movimentações de: 1- Anexação, 2- Assinatura do anexo e 3- Finalização;
![tela2](https://cloud.githubusercontent.com/assets/4949149/20800411/8e6c7582-b7cc-11e6-94d1-87655c01ced1.png)

**Comment by Chrystinne** [comment]
Chamado aberto reportando esse problema: JFRJ-SR-2016/50130.02

![captura_de_tela_120116_015403_pm](https://cloud.githubusercontent.com/assets/4949149/20800739/a2829e42-b7cd-11e6-8fe0-6c5bb8b66f8e.jpg)

**Comment by esredson** [comment]
@Chrystinne, uma forma de acompanhar as ocorrências disso, enquanto não é resolvido, é a seguinte: 
select * from siga.ex_documento d inner join siga.ex_mobil m on d.id_doc = m.id_doc inner join corporativo.cp_marca mar on m.id_mobil = mar.id_ref where dt_finalizacao is not null and id_marcador = <id do "Em Elaboracao"; acho que é 1>

**Comment by Chrystinne** [comment]
Beleza, @esredson. 
Olhando no banco tem 2 entradas para o marcador Em elaboração (1 e 61). 

select * from siga.ex_documento d inner join siga.ex_mobil m on d.id_doc = m.id_doc inner join corporativo.cp_marca mar on m.id_mobil = mar.id_ref where dt_finalizacao is not null and id_marcador = 1
A query acima está retornando 337 ocorrências.

Obrigada!

**Comment by rafaela00castro** [comment]
O sistema está fazendo todo o processo para excluir as marcas corretamente, o problema é que no momento de commitar a transação no banco para persistir as alterações, essa transação está nula. O método `finalizar()` no ExBL.java inicia a transação com o método `iniciarAlteracao();` , só que ao criar uma via ou um volume, esses métodos chamam o `concluirAlteracao(mob);` que além de atualizar as marcas também faz o commit da transação, chamando o método `commitTransacao()`. Esse método define o valor da transição como `null` logo após o commit. 

Então resumindo, é necessário chamar novamente o método `iniciarAlteracao();` para iniciar uma transação antes de chamar o método `concluirAlteracaoDoc(doc);`, que é o responsável por atualizar as marcas no geral após a criação de uma via ou volume.

**Comment by rafaela00castro** [comment]
Analisando o código não consegui identificar em que momento começou esse problema da marca 'Em elaboração' ainda ficar atrelada ao mobil 'Geral'. Alterei um pouco a query feita pela Chrys para não me preocupar se o documento está finalizado ou não, e somente verificar se existe mobil Geral com a marca em elaboração. E existem 26.817 casos.

```
select count(*) from siga.ex_mobil mobil inner join corporativo.cp_marca marca
  on mobil.id_mobil = marca.id_ref
  where mobil.id_tipo_mobil = 1 and marca.id_tp_marca = 1 and marca.id_marcador = 1;
```
