### ISSUE TITLE
DOC: documento sem ser capturado com "autenticado por" ao visualizar impressão

### ISSUE THREAD

**Issue by adrigrassi** [projeto-siga/siga#1126]
Ao visualizar impressão, está vindo na estampa do documento "autenticado por" no lugar da assinatura referenciando a uma movimentação de autenticação de pdf. 
obs: a expressão "autenticado por" somente pode ocorrer para documentos capturados autenticados.  Não existe autenticação de documento sem ser capturado.

**Comment by rafaela00castro** [comment]
Commit [6fb91f9]
