### ISSUE TITLE
[Siga] [Siga-Wf] [Siga-Doc] [Siga-Cd] Erro nos webservices

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#113]
Ao consumir os webservices do SIGA-GI a resposta do sistema é a seguinte:

faultcode:soap:Client
faultstring: Unexpected wrapper element {http://service.gi.siga.jfrj.gov.br/}acesso found.   Expected {http://impl.service.gi.siga.jfrj.gov.br/}acesso.

Como reproduzir (foi utilizada  a ferramenta SOAP UI para os testes - http://www.soapui.org):
1. Crie um novo projeto apontando para o seguinte WSDL: http://siga-hmg/siga/servicos/GiService?WSDL
2. Chame o método acesso com os seguintes parâmetros: 
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://service.gi.siga.jfrj.gov.br/">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:acesso>
         <!--Optional:-->
         <arg0>RJ13286</arg0>
         <!--Optional:-->
         <arg1>RJSESIA</arg1>
         <!--Optional:-->
         <arg2>SIGA-DOC</arg2>
      </ser:acesso>
   </soapenv:Body>
</soapenv:Envelope>
```
3. O resultado deveria ser: ```{"SIGA-DOC": "Pode"}```

Ilustrações:

ERRO:
![image](https://cloud.githubusercontent.com/assets/2985140/5843133/7ebe04f0-a191-11e4-89e7-49cba29a9da0.png)

SUCESSO:
![image](https://cloud.githubusercontent.com/assets/2985140/5843151/90c1aaf8-a191-11e4-8848-b325bd611c95.png)

Esse problema pode estar relacionado ao da issue #98

**Comment by hodrigohamalho** [comment]
![capturar](https://cloud.githubusercontent.com/assets/252998/5845685/431ee7ac-a1a5-11e4-97d5-2e36c6dbf281.PNG)

@Markenson fiz o teste conforme você disse e deu o cenário esperado. Poderia testar novamente? 
PS: não mudei nada pra que isso funcionasse.

**Comment by Markenson** [comment]
Testei aqui e continou com erro. Vou atualizar meu SOAP UI pra ver se é problema do cliente.

**Comment by Markenson** [comment]
Fiz uma noma importação do WSDL e funcionou. Uma coisa que está diferente é a tag <soap.address> que na siga-hmg está colocando o ip e a porta da máquina e na sigat, por exemplo, está resolvendo o nome da máquina e na porta padrão. Se for possível, é melhor que a tag <soap.address>  seja alterada para usar o nome em vez do ip. 

na siga-hmg: <soap:address location="http://10.10.0.68:8380/siga/servicos/GiService"/>
na sigat: <soap:address location="http://sigat/siga/servicos/GiService"/>

**Comment by hodrigohamalho** [comment]
Configuração feita via cli:
/profile=sigadoc/subsystem=webservices:write-attribute(name=wsdl-host,value=siga-hmg)
/profile=sigadoc/subsystem=webservices:write-attribute(name=wsdl-port,value=80)

ficou assim: <soap:address location="http://siga-hmg:80/siga/servicos/GiService"/>

Qualquer outra coisa a gente reabre a issue, fecharei por enquanto.
