### ISSUE TITLE
SR: erro na numeração da solicitação

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#1137]
A numeração foi reiniciada na virada do ano, por conta da alteração indicada na issue #605. No entanto, quando uma solicitação filha foi gerada a partir de uma solicitação de 2016, por exemplo, TRF2-SR-2016/**54547**.02, a numeração de 2017 passou a continuar a partir da numeração dessa solicitação filha ( TRF2-SR-2017/**54548**).

**Comment by esredson** [comment]
Conforme conversa com @rafaela00castro, aumentar para 6 a quantidade de dígitos do sequencial.

**Comment by adrigrassi** [comment]
Fazendo a seguinte query:
select max(num_solicitacao) from sigaSr.Sr_Solicitacao where id_orgao_usu = 3 and num_sequencia is null and NUM_SOLICITACAO < 90000 and  extract(YEAR FROM dt_reg) = 2017;
Verificamos que os últimos números de cada orgão são (no momento):
TRF2: 48401
SJRJ: 60951
SJES: 8858

**Comment by adrigrassi** [comment]
Para verificarmos a quantidade de chamados abertos no ano de 2016 executamos a seguinte query:

select extract(MONTH FROM dt_reg) as mes, count(*) from sigaSr.Sr_Solicitacao where id_orgao_usu = 3 and num_sequencia is null and extract(YEAR FROM dt_reg) = 2016 and num_solicitacao is not null
group by extract(MONTH FROM dt_reg)
order by mes

TRF2:
1	1577
2	1763
3	1890
4	1805
5	1869
6	1910
7	2278
8	968
9	2018
10	1971
11	1728
12	1118

SJRJ:

1	2373
2	2310
3	2739
4	2121
5	2183
6	2433
7	2383
8	1588
9	2345
10	2297
11	1891
12	947

**Comment by adrigrassi** [comment]
Em 2017 os valores para a SJRJ foram:

1	1683
2	1752
3	2294
4	1667
5	2060
6	526

**Comment by adrigrassi** [comment]
Portanto estimando-se um total de 3000 chamados por mês, até o final de 2017 iríamos chegar ao número 80000. Dentro do limite suportado pelo Banco de Dados. Por ora, não há a necessidade de alteração na estrutura de BD.

**Comment by rafaela00castro** [comment]
A numeração do siga-sr foi reiniciada com sucesso em 2018.
