### ISSUE TITLE
GERAL: substituição recém-cadastrada nem sempre fica visível no menu

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#1138]
Para simular, cadastrar uma substituição no Siga-Doc, ir à página inicial e entrar novamente no Siga-Doc. A substituição não aparece.

**Comment by Chrystinne** [comment]
Outro problema com a substituição, reportado hoje no chamado JFRJ-SR-2017/51488.01, é que o link Substituir algumas vezes não carrega a lista de possíveis substitutos;
