### ISSUE TITLE
DOC: Assinatura externa digital não está funcionando

### ISSUE THREAD

**Issue by adrigrassi** [projeto-siga/siga#1147]
Ao acessar o endereço para autenticar documentos com o código referente à assinatura externa do anexo (vide conhecimento TRF2-GC-2017/00078) e clicar no botão Assinar nada acontece! Aparentemente, esta funcionalidade não foi adaptada às novas atualizações da assinatura digital.

**Comment by esredson** [comment]
7dc701a573f4ffd2de8
