### ISSUE TITLE
[Siga-Sr] Cadastro de designação

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#115]
-Ilustração:
![captura_de_tela_012115_062645_pm](https://cloud.githubusercontent.com/assets/4949149/5844443/0f4ba9b0-a19b-11e4-80fe-dcc41d914e0a.jpg)

-Como reproduzir:
1. Acessar http://siga-hmg/sigasr/designacao/listar;
2. Clicar em Incluir;
3. Preencher os campos em destaque na ilustração acima e dar "tab" ou simplesmente tirar o foco deste campo;

**Comment by hodrigohamalho** [comment]
Corrigido.
