### ISSUE TITLE
SR: mudar lógica para não gerar erro na abertura de solicitação

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#1151]
Atualmente, ao selecionar uma ação que possui o título com parenteses, como por exemplo: _Requisitar a troca de dados da fase/movimento 12 **(**intimação/publicação**)**_, dá o erro abaixo na gravação da solicitação:
![image](https://cloud.githubusercontent.com/assets/8461113/22751634/536b297a-ee1c-11e6-94d0-1e8c22c7aa6a.png)

**Comment by rafaela00castro** [comment]
Para evitar o erro, removi os parênteses do título das ações. 

Necessário fazer refactoring no método `carregarLotacaoDaAcao()` que está no `classificacao.tab` na seguinte parte:

`var siglaLotacao = opcaoSelecionada.html().split(/[)|(]+/)[1]; //[ "(", "SEDGET", ")" ]`

**Comment by Chrystinne** [comment]
Esse trecho de código também gera erro ao tentar escalonar uma solicitação escolhendo-se uma ação com parênteses no assunto (erro reportado no chamado TRF2-SR-2017/42579.01).
