### ISSUE TITLE
Tela de Cadastro de Modelos

### ISSUE THREAD

**Issue by andresousa17** [projeto-siga/siga#116]
O Codemirror e os quadros de configuração do modelo não estão carregando.

Como Acessar esta tela:

1 - Entrar no módulo Documentos
2 - Acessar o menu "Ferramentas->Cadastro de Modelos"

Obs: As vezes essa tela está funcionando no IE. No Chrome e no Firefox não funcionou nenhuma vez.

Tela com Erro 
![image](https://cloud.githubusercontent.com/assets/5269936/5844681/04cc08c0-a19d-11e4-9a65-2b7a0347ba7e.png)

Tela Funcionando

![image](https://cloud.githubusercontent.com/assets/5269936/5844714/442d433a-a19d-11e4-820c-a68617681fe7.png)

**Comment by kmacedovarela** [comment]
Resolvido configurando-se a permissão ao acesso ao codemirror
c93fcafae9609d4f55e79fd76c400a2081e87bf0
