### ISSUE TITLE
DOC: Não é possível autenticar documento capturado com senha

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#1168]
Reportado por Cabral (EB), via e-mail, em 27 de março de 2017 17:32:

"(...) não consigo autenticar com senha um documento capturado, quando o usuário não é o subscritor ou um dos cossignatários.

Contudo, a Sra Adriana informa ser possível autenticar o documento capturado que não possui um subscritor ou signatário. Tendo em vista que o TRF2 somente utiliza assinatura ou autenticação com certificado digital, existe a possibilidade de ser um erro de implementação da autenticação com senha?

**Comment by jacob-cabral** [comment]
Prezados, boa tarde!

Eu (Cabral - EB) não consigo autenticar documentos com senha, sem que o usuário do SIGA seja, ao menos, cossignatário do documento. Porém, ao tentar autenticar o mesmo documento capturado, utilizando um certificado digital válido, logrei êxito. Neste caso de sucesso, adotei os seguintes procedimentos:

1. o documento de um terceiro (requerente que solicita a abertura de processos nos postos de atendimento ao público externo) foi capturado;
1. em seguida, esse documento capturado foi autenticado pelo usuário do SIGA (atendente do posto), sem que este fosse subscritor ou cossignatário do mesmo documento.

A execução dos mesmos procedimentos, utilizando o recurso de autenticação com senha, não funciona, sendo exibida a seguinte mensagem de validação: Só é permitida a assinatura digital do subscritor e dos cossignatários do documento.
