### ISSUE TITLE
Migrar jobs que rodam no "cron"

### ISSUE THREAD

**Issue by hodrigohamalho** [projeto-siga/siga#117]
Não me lembro quais são e nem em quais máquinas estão esses jobs, mas lembro que eles existem, então essa issue é para não esquecermos de migra-los.

**Comment by kmacedovarela** [comment]
Alguém da equipe poderia elencar quais são estes JOBS, com seu respectivo repositório?

**Comment by Markenson** [comment]
Os projetos que estão agendados no CRON são:

**siga-cp-sinc** (repo:*github*)		 - importa dados do XML para o corporativo
**siga-cp-sinc-ext-filter** (repo:*k*) - remove informações sensíveis do XML antes de ser exportado para empresa externa.
**siga-cp-sinc-ext-ldap**	(repo:*k*) - importa dados do corporativo para o Active Diretory
**siga-cp-sinc-ext-matrix**	(repo:*k*) - importa dados do corporativo para as catracas dos prédios
**siga-ext-receber-dje**	(repo:*k*) - importa informações de publicação no DJE

Os deploys estão na máquina SCENIC nos respectivos endereços:

```
/home/tomcat/siga-cp-sinc.one-jar.jar
/home/tomcat/pcservice/siga-cp-sinc-ext-filter.jar
/home/tomcat/siga-cp-sinc-ext-ldap.one-jar.jar
/home/tomcat/sinc-matrix.jar
/home/tomcat/atualizarPublicacaoDJE.jar
```


O repositório K está no endereço:

```K:\ADMINISTRACAO\STI\CSIS\SESIA\01 Repositorios\_git_jfrj_ext```

**Comment by crivano** [comment]
@Markenson , será que isso já está concluído?

**Comment by hodrigohamalho** [comment]
https://docs.google.com/spreadsheets/d/1_50aFzoNgQW4w6_7iP_CqMNsE7QPPjP0yxS3bN1oPIg/edit#gid=1592496762

De acordo com essa planilha elaborada pelo Markenson só falta o xml do PC Service, não sei qual a pendência para ativar este serviço, mas só tem ele pendente.

**Comment by Markenson** [comment]
Pessoal,

Isso está concluído sim. O sinc da PC service não é mais necessário já que
estamos usando o siga-sr em vez do sistema da PC. Só precisamos avisar ao
pessoal da rede para remover os acessos ao FTP relacionados a esse serviço
(se não me engano está na linha de comando do cron)

Em qua, 29 de jul de 2015 17:38, Rodrigo Ramalho da Silva <
notifications@github.com> escreveu:

>
> https://docs.google.com/spreadsheets/d/1_50aFzoNgQW4w6_7iP_CqMNsE7QPPjP0yxS3bN1oPIg/edit#gid=1592496762
>
> De acordo com essa planilha elaborada pelo Markenson só falta o xml do PC
> Service, não sei qual a pendência para ativar este serviço, mas só tem ele
> pendente.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/projeto-siga/siga/issues/117#issuecomment-126088507>.
>
-- 
Atenciosamente,
Markenson Paulo França

**Comment by kmacedovarela** [comment]
Como indicado, a demanda está concluída.
