### ISSUE TITLE
GERAL: Permissão de substituição em lotações diretamente subordinadas

### ISSUE THREAD

**Issue by fernvalverde** [projeto-siga/siga#1175]
Chamado TRF2-SR-2017/46148

Acerto para permitir que uma pessoa em determinada lotação possa dar permissão de substituição para pessoas de lotações diretamente subordinadas.

**Comment by jmolivei** [comment]
Cenário antes da alteração. E-LINKDATA está subordinado diretamente a COSISA. Eu, lotado na COSISA, estou cadastrando um substituto para E-LINKDATA.

![cadastrarsubstituicaoantes](https://cloud.githubusercontent.com/assets/5268745/26598651/558c2d12-454c-11e7-873f-00bc71bc46a8.png)


Cenário após alteração realizada pelo commit 8842adeb633bf4edf6491f3912167e17e2d683f6

![cadastrarsubstituicaodepois](https://cloud.githubusercontent.com/assets/5268745/26598968/486e7dc8-454d-11e7-811f-70f5a8b327d3.png)

**Comment by jmolivei** [comment]
@adrigrassi Testado na siga-dev.
