### ISSUE TITLE
[Siga-Gc] Erro ao excluir conhecimento 

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#119]
-Ilustração:
![captura_de_tela_012215_120558_pm](https://cloud.githubusercontent.com/assets/4949149/5856982/07d1e9a8-a22f-11e4-885c-f8545a10c211.jpg)

-Como reproduzir:
1. Criar um novo conhecimento ou acessar um conhecimento existente (http://siga-hmg/sigagc/app/exibir?sigla=TMPGC-2149);
2. Clicar em "Duplicar";
3. Clicar em "Excluir";

**Comment by kmacedovarela** [comment]
Não recebi mais erros, acredito que tenha sido resolvido. Caso o erro volte a acontecer, favor reabrir a issue.

ao executar obtive a seguinte saida

21:23:48,514 INFO  [br.gov.jfrj.siga.ex.util.PublicacaoDJEBL] (http-/10.10.0.69:8180-2) DJE Busca Publicacoes 19/01/2015:<?xml version="1.0" encoding="utf-8"?><RETORNOPUBLICACAO />
21:23:53,538 INFO  [br.gov.jfrj.siga.ex.util.PublicacaoDJEBL] (http-/10.10.0.69:8180-2) DJE Busca Publicacoes 19/01/2015:<?xml version="1.0" encoding="utf-8"?><RETORNOPUBLICACAO />
21:23:56,780 INFO  [br.gov.jfrj.siga.ex.util.PublicacaoDJEBL] (http-/10.10.0.69:8180-2) DJE Busca Publicacoes 19/01/2015:<?xml version="1.0" encoding="utf-8"?><RETORNOPUBLICACAO />
21:24:17,255 INFO  [br.gov.jfrj.siga.ex.util.PublicacaoDJEBL] (http-/10.10.0.69:8180-3) DJE Busca Publicacoes 19/01/2015:<?xml version="1.0" encoding="utf-8"?><RETORNOPUBLICACAO />
21:24:17,514 INFO  [br.gov.jfrj.siga.ex.util.PublicacaoDJEBL] (http-/10.10.0.69:8180-3) DJE Busca Publicacoes 19/01/2015:<?xml version="1.0" encoding="utf-8"?><RETORNOPUBLICACAO />
21:24:17,698 INFO  [br.gov.jfrj.siga.ex.util.PublicacaoDJEBL] (http-/10.10.0.69:8180-3) DJE Busca Publicacoes 19/01/2015:<?xml version="1.0" encoding="utf-8"?><RETORNOPUBLICACAO />
21:24:17,853 INFO  [br.gov.jfrj.siga.ex.util.PublicacaoDJEBL] (http-/10.10.0.69:8180-3) DJE Busca Publicacoes 19/01/2015:<?xml version="1.0" encoding="utf-8"?><RETORNOPUBLICACAO />

**Comment by kmacedovarela** [comment]
Reabrindo issue, erro técnico.

**Comment by kmacedovarela** [comment]
@esredson este mesmo erro ocorre na sigat, você poderia verificar?

**Comment by Chrystinne** [comment]
Resolvido problema de integridade referencial na base HOMOLO.
