### ISSUE TITLE
SR: pegar o atendente atual ao exibir as marcas na tela de exibição

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#1192]
Na tela de exibição da solicitação, quando existe uma pessoa responsável pelo atendimento da demanda, a marca não está mostrando a "pessoa atual".

**Comment by rafaela00castro** [comment]
Diferente do caso resolvido pelo commit ea53572, onde o problema estava na própria chamada da EL, nesse caso o problema está no método `getMarcadoresEmHtml(DpPessoa pess, DpLotacao lota)` da classe SrSolicitacao. Esse método é chamado pela "tela" `exibir.jsp`.

No método `getMarcadoresEmHtml`  onde está:
`String nome = mar.getDpPessoaIni().getDescricaoIniciaisMaiusculas();`

deveria ser:
`String nome = mar.getDpPessoaIni().getPessoaAtual().getDescricaoIniciaisMaiusculas();`

**Comment by Chrystinne** [comment]
@rafaela00castro Tem algum chamado aberto onde eu possa testar a correção? Ou outra forma de testar?
