### ISSUE TITLE
[Siga-Sr] Gravação dos próximos andamentos da solicitação está duplicada

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#120]
-Ilustração:
![captura_de_tela_012215_122409_pm](https://cloud.githubusercontent.com/assets/4949149/5857286/92449c82-a231-11e4-8862-35b24c91d043.jpg)

-Como reproduzir:
1. Acessar a solicitação JFRJ-SR-2015/00043 (pode tentar ir pelo link http://siga-hmg/sigasr/solicitacao/exibir?id=436&todoOContexto=false&ocultas=false);
2. Preencher andamento com texto qualquer e clicar em "Gravar";

**Comment by kmacedovarela** [comment]
Não está mais ocorrendo.  Caso ocorra, favor reabrir
