### ISSUE TITLE
GI: Webservice retona dados apenas de pessoas que já se autenticaram

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#1201]
O método GiServiceImpl.dadosUsuario() retorna apenas dados de pessoas que já se autenticaram no sistema. Se uma pessoa não se autenticou no sistema, a resposta é vazia. O ideal é que este método retorne as informações mesmo se a pessoa nunca se autenticou no sistema.

OBS: Teste realizado com SoapUi

REFs: 

https://github.com/projeto-siga/siga/blob/3fd5b63161ec86b6c4f4f1529115e9230fc7d963/siga-cp/src/main/java/br/gov/jfrj/siga/gi/service/impl/GiServiceImpl.java#L84

TRF2-SR-2017/51693

**Comment by jmolivei** [comment]
Implementação concluída. Segue cenário

![dadossemautenticacaoretornados](https://user-images.githubusercontent.com/5268745/44347822-3efea100-a46f-11e8-801a-5c451792af4d.gif)
