### ISSUE TITLE
SR: Introdução de espaços em links

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#1208]
Ao inserir o link abaixo no andamento do chamado TRF2-SR-2017/53136 , espaços foram inseridos ocasionando a "quebra" do link.

http://vmpgitlab.jf.trf2.gov.br/sigarh/siga-rh/raw/master_jboss6_maven/projeto-sigarh-master/SigaRH/src/main/resources/db/sigarh_campoCNS_001.sql

**Comment by rafaela00castro** [comment]
Uma forma de resolver seria usar a propriedade CSS _word-wrap_ para quebrar as palavras.  Mais detalhes [aqui](https://developer.mozilla.org/pt-BR/docs/Web/CSS/word-wrap)

**Comment by Chrystinne** [comment]
Resolvido!

![captura_de_tela_100517_022116_pm](https://user-images.githubusercontent.com/4949149/31240874-742c1cbe-a9d8-11e7-9df6-96afee09516e.jpg)
