### ISSUE TITLE
[Siga-Sr] Inclusão de pendência duplicada

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#121]
-Ilustração:

![captura_de_tela_012215_123056_pm](https://cloud.githubusercontent.com/assets/4949149/5857403/a4a2a95e-a232-11e4-834e-6c1fbe226fef.jpg)

-Como reproduzir:
1. Acessar a solicitação JFRJ-SR-2015/00045.02 (pode tentar ir pelo link http://siga-hmg/sigasr/solicitacao/exibir?id=440&todoOContexto=false&ocultas=false);
2. Clicar em Incluir Pendência;
3. Preencher com dados quaisquer e clicar em "Gravar";

**Comment by kmacedovarela** [comment]
Não está mais ocorrendo.
