### ISSUE TITLE
[Siga-Sr] Erro 500 ao fechar solicitação e ao incluir em lista

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#122]
-Como reproduzir:

Opção "Incluir em lista":
1. Criar uma nova solicitação ou acessar uma existente (pode tentar pelo link http://siga-hmg/sigasr/solicitacao/exibir?id=445&todoOContexto=false&ocultas=false);
2. Clicar no link "Incluir em Lista", selecionar uma das listas e clicar no botão "Selecionar lista";

Opção "Fechar":
1. Clicar no link "Fechar"

**Comment by kmacedovarela** [comment]
Testei no chrome e no IE agora e não ocorreu, pode ter sido apenas manutenção nos servidores, se ocorrer novamente favor reabrir.
