### ISSUE TITLE
Erro na Chamada de WebServices no Formulário de Solicitação de Deslocamento

### ISSUE THREAD

**Issue by andresousa17** [projeto-siga/siga#123]
Não está funcionando a chamada dos Webservices de consulta de cidades e de dados Bancários no modelo "Formulário - Formulário de Solicitação de Deslocamento".

Como reproduzir Erro no campo Cidade:

1 - Clicar no botão Novo na tela inicial.
2 - Selecionar o Tipo "Formulário"
3 - Selecionar o Modelo "Formulário de Solicitação de Deslocamento"

Página com Erro no Campo Cidade

![image](https://cloud.githubusercontent.com/assets/5269936/5858575/63aa36f2-a23b-11e4-85c4-1e6b029b0dc1.png)

Como reproduzir Erro no campo Dados Bancários:

1 - Clicar no botão Novo na tela inicial.
2 - Selecionar o Tipo "Formulário"
3 - Selecionar o Modelo "Formulário de Solicitação de Deslocamento"
4 - Preencher o Campo Proposto com a matrícula RJ13989
5 - Selecionar o Campo "Fora da região metropolitana (para saber se o local do evento está fora da região metropolitana consulte aqui os mapas de Brasília; Espírito Santo; Rio de Janeiro) "
6 - Selecionar o Campo "Dados para pagamento de diárias"

![image](https://cloud.githubusercontent.com/assets/5269936/5858724/7c83a0c2-a23c-11e4-9d86-7cbfc7f737c6.png)

Observações:

1 - Os webservices ficam nos endereços "http://academico.engsupport.eti.br/servicos/cidades.asmx" para cidades e "http://vmwebjip2008.trf.net/wsconsultadadosbancarios/service1.asmx" para Dados Bancários.
2 - A macro "Webservice" do Freemarker chama os métodos "webservice" e "parseXML" da classe "FuncoesEl.java" para acessar os serviços.

**Comment by kmacedovarela** [comment]
@andresousa17  Coloquei breakpoint nestes métodos webservice e parseXML da classe FuncoesEl.java e quando executo ambos os fluxos nenhum dos dois métodos é chamado. Na segunda feira se você puder, verei com você como é funcionamento dessas macros.

**Comment by kmacedovarela** [comment]
@andresousa17  conhece este erro? 
19:28:25,710 ERROR [freemarker.runtime] (http-localhost/127.0.0.1:8443-2) Error executing FreeMarker template: freemarker.core._MiscTemplateException: Macro "texto" has no such argument: somenteLeitura

The failing instruction (print stack trace for 24 more):
==> @texto titulo="Banco" var=("banco" + ...  [in template "Formulário de Solicitação de Deslocamento" at line 369, column 29]

**Comment by kmacedovarela** [comment]
O erro acima ocorre localmente (mclaren), mas não ocorre no ambiente de homologação.

6f796ae2503e07c84b585540ceebadd36a9415f2
