### ISSUE TITLE
Warn sobre performance na máquina de produção

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#124]
Para não esquecer de resolver.

15:08:04,574 WARN  [org.jgroups.protocols.UDP] (ServerService Thread Pool -- 53) JGRP000014: the send buffer of socket DatagramSocket was set to 640KB, but the OS only allocated 212,99KB. This might lead to performance problems. Please set your max send buffer in the OS correctly (e.g. net.core.wmem_max on Linux)
15:08:04,575 WARN  [org.jgroups.protocols.UDP] (ServerService Thread Pool -- 53) JGRP000014: the receive buffer of socket DatagramSocket was set to 20MB, but the OS only allocated 212,99KB. This might lead to performance problems. Please set your max receive buffer in the OS correctly (e.g. net.core.rmem_max on Linux)
15:08:04,575 WARN  [org.jgroups.protocols.UDP] (ServerService Thread Pool -- 53) JGRP000014: the send buffer of socket MulticastSocket was set to 640KB, but the OS only allocated 212,99KB. This might lead to performance problems. Please set your max send buffer in the OS correctly (e.g. net.core.wmem_max on Linux)
15:08:04,576 WARN  [org.jgroups.protocols.UDP] (ServerService Thread Pool -- 53) JGRP000014: the receive buffer of socket MulticastSocket was set

**Comment by AndDeluiz** [comment]
Alteradas configurações de kernel para adequação aos requisitos da aplicação no ambiente de produção.

#==============================================================================#
# JBoss Settings                                                               #
#==============================================================================#

# Do less swapping
# Default: vm.swappiness = 30
vm.swappiness = 20

# Default: vm.dirty_ratio = 30
vm.dirty_ratio = 60

# Default: vm.dirty_background_ratio = 10
vm.dirty_background_ratio = 2

# Increase size of file handles and inode cache.
# Default: fs.file-max = 794477
fs.file-max = 2097152

# Default receive buffer size.
# Default: net.core.rmem_default = 212992
net.core.rmem_default = 524288

# Max receive buffer size.
# Default: net.core.rmem_max = 212992
net.core.rmem_max = 20480000

# The maximum number of "backlogged sockets".
# Default: net.core.somaxconn = 128
net.core.somaxconn = 1024

# Default send buffer size.
# Default: net.core.wmem_default = 212992
net.core.wmem_default = 524288

# Max send buffer.
# Default: net.core.wmem_max = 212992
net.core.wmem_max = 655360

# Allow reuse of sockets in TIME_WAIT state for new connections
# only when it is safe from the network stack’s perspective.
# Default: net.ipv4.tcp_tw_reuse = 0
net.ipv4.tcp_tw_reuse = 1

#==============================================================================#

**Comment by AndDeluiz** [comment]
Alteradas configurações de sistema (/etc/sysctl.d/99-sysctl.conf) para atendimento as demandas de aplicativo.
