### ISSUE TITLE
PRODESP: Alteração de layout das telas "Novo Usuário" e "Esqueci minha Senha"

### ISSUE THREAD

**Issue by vezequiel** [projeto-siga/siga#1249]
Itens destacados do cartão trello original 19*

7) Retirar o texto que está entre parênteses que é exibido como auxiliar para preenchimento do campo matrícula. Existem dois pontos mapeados: 

Tela de Logon do sistema
"Falha de autenticação! XX é a sigla do seu órgão (T2, RJ, ES, etc.) 99999 ? o número da matrícula."

Tela Novo Usuário:   
"Ex.: XX99999, onde XX é a sigla do seu órgão (T2, RJ, ES, etc.) e 99999 é o número da sua matrícula"

-----------------------------------
8) Retirar todas informações referentes ao Método 2 das telas “Sou um novo usuário” e “Esqueci minha senha”.

----------------------------------
9) Retirar o texto “Método 1 - Envio de senha nova para o e-mail” das telas: 
     a) “Sou um novo usuário” 
     b) “Esqueci minha senha”.

![image](https://user-images.githubusercontent.com/45595881/49446788-19966880-f7bc-11e8-98d8-d5059dd7f9b2.png)

![image](https://user-images.githubusercontent.com/45595881/49446800-2024e000-f7bc-11e8-9656-af032a449a53.png)

![image](https://user-images.githubusercontent.com/45595881/49446823-274bee00-f7bc-11e8-8984-7354f7131a4e.png)

**Comment by crivano** [comment]
Para realizar essas alterações, a sugestão é criar parâmetros que, quando informados, alteram o comportamento do sistema e os textos apresentados.

Se os parâmetros forem omitidos, tudo deve permanecer como está hoje.

Por favor, indiquem o nome dos parâmetros que vcs pretendem criar para que possamos avaliar e possivelmente sugerir alterações antes que a implementação seja realizada.

**Comment by vezequiel** [comment]
Segue sugestão do nome da propriedade "siga.somenteMetodo1" que deverá controlar o comportamento dessa tela.

**Comment by crivano** [comment]
É interessante que o nome do parâmetro siga uma lógica de formação e agrupamento. Como essas páginas são relativas à gestão de identidades, sugiro prefixar com siga.gi.

Além disso, vejo que existem várias solicitações e não apenas a exclusão do método 2, poderia ser algo assim:

siga.gi.omitir.metodo2

siga.gi.texto.novo.usuario=Ex.: XX99999, onde XX é a sigla do seu órgão (T2, RJ, ES, etc.) e 99999 é o número da sua matrícula
siga.gi.texto.login=Falha de autenticação! XX é a sigla do seu órgão (T2, RJ, ES, etc.) 99999 ? o número da matrícula.

Quando quiser que não apareça nada basta não informar o parâmetro. Ou usar o valor que foi preenchido quando quiser definir um texto próprio.

(Esse é um caso particular em que acho que vale mais a pena alterar o funcionamento do Siga quando o parâmetro não é informado. Isso se justifica pois o texto que existe lá é mesmo específico para o TRF2.)
