### ISSUE TITLE
PRODESP: Alteração do layout do Cadastro de Lotação

### ISSUE THREAD

**Issue by vezequiel** [projeto-siga/siga#1252]
SIGA > Ferramenta 
Menu: 
 

**Requisito**
1)	Esse item de menu deve estar liberado somente para: Administrador de Configurações (ZZ), Administrador do Órgão e Administrador Local (ou Setorial).

**Tela de Pesquisa**
SIGA > Ferramenta > Cadastro de Lotação
 
![image](https://user-images.githubusercontent.com/45595881/50014777-05b4e880-ffac-11e8-92a6-3756e00009cb.png)

**Tela de Inclusão**
  
![image](https://user-images.githubusercontent.com/45595881/50014770-fdf54400-ffab-11e8-874f-3e8183815a60.png)

Requisito

Regras para Inclusão de novo registro
1)	Abaixo do campo (texto) “Nome” inserir o texto informativo:
“(Nome da lotação: Não cadastrar lotações abreviadas, inserir nome oficial constituído em legislação)”;
2)	Abaixo do campo (texto) “Sigla” inserir o texto informativo:
“(Sigla: Letras maiúsculas)”;
3)	Abaixo do texto “Sigla” inserir o texto “Localidade”;
4)	Inserir campo (combo) contendo a lista de municípios do Estado (UF) do cadastro de Órgão e permitir a seleção de um município da lista. Campo obrigatório;
5)	Abaixo do texto “Localidade” inserir o texto “Situação”;
6)	Inserir botões de seleção (radiobutton) com as opções: Ativo e Inativo. Opção default do sistema: “Ativo”. 
7)	Permitir ao usuário a alteração da situação do registro da Lotação para inativo somente se não existir usuários e documentos vinculados. Caso contrário exibir mensagem: “Inativação não permitida. Existem documentos e usuários vinculados nessa Lotação”.
8)	A lista de Órgão (combo) deve estar aberta somente para Administrador de configurações (ZZ), para os demais usuários deverá exibir o órgão a que está vinculado o usuário;
9)	Manter os campos e as regras já existentes.

**Tela de Alteração**
 
![image](https://user-images.githubusercontent.com/45595881/50014749-ecac3780-ffab-11e8-99d8-a24829c725dd.png)

**Requisito**
Regras para Alteração de registro:

1)	Abaixo do campo (texto) “Nome” inserir o texto informativo:
“(Nome da lotação: Não cadastrar lotações abreviadas, inserir nome oficial constituído em legislação)”;
2)	Abaixo do campo (texto) “Sigla” inserir o texto informativo:
“(Sigla: Letras maiúsculas)”;
3)	Abaixo do texto “Sigla” inserir o texto “Localidade”;
4)	Inserir campo (combo) contendo a lista de municípios do Estado (UF) do cadastro de Órgão e permitir a seleção de um município da lista. Campo obrigatório;
5)	Abaixo do texto “Localidade” inserir o texto “Situação”;
6)	Inserir botões de seleção (radiobutton) com as opções: Ativo e Inativo. Opção default do sistema: “Ativo”.
7)	Permitir ao usuário a alteração da situação do registro da Lotação para inativo somente se não existir usuários e documentos vinculados. Caso contrário exibir mensagem: “Inativação não permitida. Existem documentos e usuários vinculados nessa Lotação”.
8)	Manter os campos e as regras já existentes.

**Comment by crivano** [comment]
Esse cadastro não é usado pelo TRF2, portanto, acho que vcs podem alterar como desejarem.

**Comment by crivano** [comment]
Sobre o questionamento de @gigami10 , acredito que incluir ID_LOCALIDADE na tabela CP_LOTACAO não seja um problema, desde que esse ID possa ser nulo.
