### ISSUE TITLE
PRODESP: Cadastro de Lotação - Carga de Dados em lote 

### ISSUE THREAD

**Issue by vezequiel** [projeto-siga/siga#1253]
Item 1 do cartão 23*

1)	Permitir upload de lista de lotações em csv e txt.
Requisito:
1)	Na tela de inclusão de registros deve ser inserido novo botão <Carga de Planilha> ;
2)	Ao clicar no botão <Carga de Planilha> o sistema deverá exibir a Tela de Carga;
3)	A Tela de Carga deverá ter um texto de orientação para preparo da planilha de dados que serão carregados no sistema; Nesta tela o usuário deverá indicar o arquivo a ser carregado;
4)	O sistema deverá consistir formato dos dados; duplicidades com registros já cadastrados (Nome e Sigla) no mesmo Órgão; validar localidade (Município); 
5)	A carga deverá ser efetivada somente se não existirem inconsistências em toda a planilha;
6)	Se existirem inconsistências, o sistema deverá exibi-las em arquivo formato TXT.

Protótipo
Tela de Inclusão
 
![image](https://user-images.githubusercontent.com/45595881/50346647-20daa780-051a-11e9-97b6-b64da332c881.png)

Tela de Carga de Planilha
 
![image](https://user-images.githubusercontent.com/45595881/50346662-2801b580-051a-11e9-9b4c-6432bf01ca7a.png)

Texto de orientação para carga de planilha:
•	Somente esta liberada a carga de planilhas no formato Excel: “XLSX”
•	O conteúdo dos dados contidos na planilha é de responsabilidade do usuário;
•	Após realizar a carga, os dados serão inseridos automaticamente na base de dados;
•	O sistema consistirá a existência de duplicidade dos dados confrontando a planilha com o banco de dados;
•	A planilha deve conter os seguintes campos/formatos:
       	Nome: máximo de 100 caracteres alfanuméricos (letras e números)
       	Sigla: máximo de 20 caracteres alfanuméricos (letras e números)
       	Localidade: máximo de 256 caracteres alfanuméricos. Somente nome de Municípios existentes no Estado.

**Comment by crivano** [comment]
Olá, sobre esse issue eu não tenho muito a acrescentar. Atualmente toda a importação do Siga se baseia em consumir um XML e talvez vcs possam produzir um XML e usar a rotina atual de importação, mas é só uma ideia.

Outra ideia seria permitir que o XML fosse submetido nessa interface, também. Assim, seria bem mais fácil do que ter que executar o aplicativo externo de importação. O que vcs acham?

**Comment by deniserp** [comment]
Renato, você vê algum problema em importar em formato cvs ou xls para carga de dados

**Comment by crivano** [comment]
Os dados são complexos para ser representados na forma de uma simples
tabela.


Em sex, 8 de mar de 2019 16:53, deniserp <notifications@github.com>
escreveu:
