### ISSUE TITLE
Menu das aplicações play diferem do menu das outras aplicações 

### ISSUE THREAD

**Issue by jmolivei** [projeto-siga/siga#126]
O menu principal do SIGA, quando acessado por contextos de aplicação em PLAY, está diferente do menu principal do SIGA acessado pelas outras aplicações. Isso se deve , porque estas informações, assim como o Titular e o Substituto eram carregadas pelo módulo siga-play-module , que na versão para o EAP 6 não contempla estas alterações, por causa que essas informações  precisam de autenticação.

**Comment by kmacedovarela** [comment]
Problema realmente acontece e está relacionado a forma como o siga-play-module faz chamadas para o siga para obter o menu, pois é barrado pelo picketlink. Necessita de analise e reimplementação de trecho do código.

**Comment by kmacedovarela** [comment]
Não será reimplementado devido à migração para VRaptor. A correção foi realizada nos projetos da NUSAD (sigatp e sigase), caso exista interesse, favor consultar a solução com João.
