### ISSUE TITLE
PRODESP - Documentos Juntados

### ISSUE THREAD

**Issue by vezequiel** [projeto-siga/siga#1260]
Documentos Juntados

1.	Incluir campo tipo checkbox “Documento que integra composto”. Opções:
        a.	Se não marcado, manter cadastro como é apresentado hoje;
        b.	Se marcado, desabilitar os campos “Classificação” e “Nível de Acesso”.

2.	Caso a descrição do FreeMarker esteja vazia, o documento apresentará a descrição do documento 
        principal ao qual foi juntado.

3.	Quando um documento com esse atributo habilitado for incluído em outro as informações, 
        classificação, nível de acesso e descrição serão herdadas do documento principal.

4.	Os campos “Classificação” e “Descrição” não serão apresentados aos usuários no momento da 
        inclusão do documento.

**Comment by crivano** [comment]
Olá, não entendi onde ficaria esse campo e gostaria de mais informações.
Obrigado.

Em qua, 23 de jan de 2019 11:58, vezequiel <notifications@github.com>
escreveu:

**Comment by vezequiel** [comment]
Prezado Renato, essa decisão deverá ser tomada por quem está criando o modelo. Assim, tal marcação definirá quais modelos aparecerão em "Novo Documento" (documento principal) e quais em "Incluir Documento" (documentos juntados) para seleção do usuário. Dessa forma, o novo campo ficará no modelo.
