### ISSUE TITLE
PRODESP - Pessoa (Usuário) com múltiplos perfis

### ISSUE THREAD

**Issue by vezequiel** [projeto-siga/siga#1264]
1) Permitir o cadastro de N perfis para o usuário (Pessoa), considerando o primeiro como principal; Órgão; Cargo; Função de Confiança; Lotação.

2) Inserir na barra superior à direita, junto ao nome do usuário, um botão que permita a seleção de outra Lotação (perfil) do usuário.

**Comment by crivano** [comment]
É possível usar o recurso da substituição para que um usuário possa atuar
em mais de uma lotação.

Para que o mesmo usuário tenha outro cargo e outra função de confiança,
seria necessário fazer uma alteração no sistema.

Em sex, 15 de mar de 2019 às 15:46, vezequiel <notifications@github.com>
escreveu:
