### ISSUE TITLE
Warn sobre performance na máquina de homologação

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#127]
Para não esquecer de resolver.

15:08:04,574 WARN org.jgroups.protocols.UDP JGRP000014: the send buffer of socket DatagramSocket was set to 640KB, but the OS only allocated 212,99KB. This might lead to performance problems. Please set your max send buffer in the OS correctly (e.g. net.core.wmem_max on Linux)
15:08:04,575 WARN org.jgroups.protocols.UDP JGRP000014: the receive buffer of socket DatagramSocket was set to 20MB, but the OS only allocated 212,99KB. This might lead to performance problems. Please set your max receive buffer in the OS correctly (e.g. net.core.rmem_max on Linux)
15:08:04,575 WARN org.jgroups.protocols.UDP JGRP000014: the send buffer of socket MulticastSocket was set to 640KB, but the OS only allocated 212,99KB. This might lead to performance problems. Please set your max send buffer in the OS correctly (e.g. net.core.wmem_max on Linux)
15:08:04,576 WARN org.jgroups.protocols.UDP JGRP000014: the receive buffer of socket MulticastSocket was set

**Comment by AndDeluiz** [comment]
Alteradas configurações de kernel (/etc/sysctl.d/99-sysctl.conf) para atendimento as demandas da aplicação em todo o ambiente de HMG.
