### ISSUE TITLE
macro extensaoBuscaTextualbs4" at line 4, column 3

### ISSUE THREAD

**Issue by williamchitto** [projeto-siga/siga#1280]
Estou tendo o seguinte erro na tela de pesquisar documentos 

13:30:26,420 ERROR [freemarker.runtime] (http-localhost/127.0.0.1:8080-2) Error executing FreeMarker template: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==> extensaoBuscaTextualbs4  [in template "macro extensaoBuscaTextualbs4" at line 4, column 3]

**Comment by jmolivei** [comment]
Respondemos no forum como proceder. Inserirmos no arquivo default.ftl para a próxima versão do docker.
