### ISSUE TITLE
Repositorio http://nexus.fdvs.com.ar/content/groups/public/siga desativado

### ISSUE THREAD

**Issue by wendellclive** [projeto-siga/siga#1284]
Prezados Boa Tarde,

No processamento para Atualização do Módulo SIGA-EXT está apresentando a conexão time-out.

`2020-03-06 14:24:17,058 WARN Worker-724: Building org.eclipse.m2e.core.internal.embedder.EclipseLogger - Failure to transfer com.corinis.external:webdav-servlet:2.1.0-SNAPSHOT/maven-metadata.xml from http://nexus.fdvs.com.ar/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of fdvsolution.public has elapsed or updates are forced. Original error: Could not transfer metadata com.corinis.external:webdav-servlet:2.1.0-SNAPSHOT/maven-metadata.xml from/to fdvsolution.public (http://nexus.fdvs.com.ar/content/groups/public/): connect timed out`

Existe algum outro repositório alternativo para substituir o abaixo descrito?

```
<repository>
	    	<id>fdvsolution.public</id>
	    	<url>http://nexus.fdvs.com.ar/content/groups/public/</url
</repository>

```

**Comment by wendellclive** [comment]
.

**Comment by ilines** [comment]
Bom dia, você conseguiu resolver isso?
