### ISSUE TITLE
Erro na url de Atualização do Documentos Publicados no DJE

### ISSUE THREAD

**Issue by andresousa17** [projeto-siga/siga#129]
Existe um sistema na máquina senic chamado "atualizarPublicacaoDJE.jar" que acessa a url "http://siga/sigaex/externo/atualizar_publicacao.action" para atualizar os documentos que foram publicados no DJE.

Quando apontamos para o endereço na siga-hmg o sistema está retornando para o sigaidp. Esta url precisa estar aberta.

Como Testar:
1 - Importar o projeto siga-ext-receber-dje
2 - Na classe Main alterar as linhas:
     58:   params = "data=19012015&secao=SJES&tipoCaderno=A";
     61:   URL url = new URL("http://siga-hmg/sigaex/externo/atualizar_publicacao.action");

O campo retorno na linha 90 deve ficar com o xml retornado do tribunal.
Exemplo do XML de retorno

<?xml version="1.0" encoding="utf-8"?><RETORNOPUBLICACAO />

**Comment by hodrigohamalho** [comment]
esse que roda com cron?

**Comment by andresousa17** [comment]
Roda no cron

**Comment by kmacedovarela** [comment]
Não recebi mais erros, acredito que tenha sido resolvido. Caso o erro volte a acontecer, favor reabrir a issue.

ao executar obtive a seguinte saida

21:24:17,698 INFO  [br.gov.jfrj.siga.ex.util.PublicacaoDJEBL] (http-/10.10.0.69:8180-3) DJE Busca Publicacoes 19/01/2015:<?xml version="1.0" encoding="utf-8"?><RETORNOPUBLICACAO />21:24:17,853 INFO  [br.gov.jfrj.siga.ex.util.PublicacaoDJEBL] (http-/10.10.0.69:8180-3) DJE Busca Publicacoes 19/01/2015:<?xml version="1.0" encoding="utf-8"?><RETORNOPUBLICACAO />


2f876d9d378d74f20fe7a93f4c163322552b0678
d131f4ffa164a12ff6dfed6e90fa7d0927367ece
