### ISSUE TITLE
Automatizar a troca das referencias do server na hora do deploy

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#13]
No arquivo picketlink.xml existe a referência pro nome do servidor em questão. 
Criar uma configuração no maven (ou propriedade do jboss? ) pra que ele descobrisse dinamicamente este dado, eliminando a necessidade de ter que trocar sempre que for recompilar o projeto.

**Comment by Markenson** [comment]
Apenas para referência futura: talvez possa ser usado um "Configuration Provider"

REF: https://docs.jboss.org/author/display/PLINK/SAML2+Configuration+Providers
