### ISSUE TITLE
[Duvida] arquivos no /home/jboss/

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#130]
@Markenson  no siga properties existem várias propriedades referenciando arquivos, semelhante a propriedade abaixo:
"siga.cd.ext.politica.oid.2.16.76.1.7.1.2.1" - "/home/jboss/sigadoc_resource/policy/icp-brasil/v1/cades/PA_AD_RT.der"/

Estes arquivos são utilizados ou já estão "deprecated"?

**Comment by Markenson** [comment]
São utilizados ainda.
