### ISSUE TITLE
Copiar arquivos policies para servidores de desenvolvimento

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#132]
Mesmo que #131 porém no ambiente com docker.

**Comment by hodrigohamalho** [comment]
Local:
/usr/java/jdk1.7.0_71/jre/lib/security

Endereço do arquivo com os libs: classea:/home/hjbossadmin/UnlimitedJCEPolicyJDK7.zip

**Comment by AndDeluiz** [comment]
Arquivos copiados para imagem (build-00020).
Favor testar.

**Comment by kmacedovarela** [comment]
O teste só pode ser realizado por alguém da equipe, uma vez, que é necessário testar o fluxo de assinatura. 
Para tal, deve-se disponibilizar a versão mais recente do siga no ambiente de dev.
