### ISSUE TITLE
Migrar o com.ittru.legacy.jb4-cfx_1.1.0.war

### ISSUE THREAD

**Issue by hodrigohamalho** [projeto-siga/siga#133]
Esse war, não encontrei os fontes. Pelo que sei nem mesmo foi desenvolvido pela equipe do siga. Alguém sabe onde tá esses fontes?

@Markenson  @crivano  ?

**Comment by Markenson** [comment]
Acho que não temos mesmo porque foi desenvolvido pela ittru. Se não me engano elea iam liberar os fontes. Se já liberaram devem estar com o @crivano

**Comment by crivano** [comment]
Esse WAR não está funcionando direto? Até onde sei ele não tem muitas dependências.

**Comment by hodrigohamalho** [comment]
não funcionou jogando direto não

**Comment by crivano** [comment]
Então vamos deixar isso quieto até que a migração esteja concluída.
