### ISSUE TITLE
[Siga] Quadros repetidos

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#134]
Ao entrar no SIGA o quadro de expediente deixou de ser exibido e passou a exibir o mesmo quado do processo administrativo. Isso ocorre de forma intermitente.

Como reproduzir:

Basta fazer login no SIGA

Exemplo:
![quadros repetidos](https://cloud.githubusercontent.com/assets/2985140/5882930/07ebae90-a335-11e4-863b-9d6db887a449.png)

**Comment by hodrigohamalho** [comment]
#114 #82

**Comment by Markenson** [comment]
Só pra ilustrar, ocorre entre outros módulos tb.

![image](https://cloud.githubusercontent.com/assets/2985140/5883040/03120d3c-a336-11e4-84bf-22b85a3c135b.png)

**Comment by hodrigohamalho** [comment]
Corrigido. Caso volte a acontecer favor reabrir a issue.
