### ISSUE TITLE
[Equipe SigaDOC] Verificar geração de documentos - Diferentes encodings no banco

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#136]
É necessário que a equipe verifique como lidar com a geração de documentos quando utilizando bancos com encodings diferentes. Erro impacta diretamente no ambiente de homologação

Problema relatado no fechamento da issue #92

**Comment by kmacedovarela** [comment]
Obs: existem fluxos que exibem o mesmo texto no ambiente de homologação, que não possuem este erro, como por exemplo:

Acessar: http://siga-hmg/sigaex/expediente/doc/editar.action
Clicar em: visualizar documento.

**Comment by hodrigohamalho** [comment]
https://developer.jboss.org/thread/199128

Pode ajudar.

**Comment by Markenson** [comment]
@kmacedovarela Você tem alguma URL de exemplo que esteja apresentando o problema?

**Comment by kmacedovarela** [comment]
@Markenson quando me deparar com uma, volto a postar.

**Comment by kmacedovarela** [comment]
@Markenson 
Teste na versailles:8280 e na sigat o seguinte procedimento, verá que na versailles, o erro de encoding ocorre em um dado recuperado do banco (modelo geral).

- Logar no sistema
- Acessar tela de criação de novo documento
- Clicar com o botão direito no browser e exibir o código fonte da página
- buscar pelo trecho (control + F )
````
CKEDITOR.stylesSet.add('siga_ckeditor_styles',[
````

Logo abaixo verá que na versailles, é exibido o texto com erro de encoding, e na sigat não.
name:'TÃ?Æ?Ã?Â­tulo',
name:'SubtÃ?Æ?Ã?Â­tulo',

**Comment by kmacedovarela** [comment]
Na própria tela é exibido.. 
http://versailles:8280/siga/modelo/listar.action

**Comment by Markenson** [comment]
@kmacedovarela 


O problema do encoding não parece estar relacionado ao banco de dados e sim a forma que o navegador apresentou os dados para o usuário (e depois o usuário enviou os dados alterados para o banco de dados). Comparei as configurações de encoding dos bancos de desenvolvimento, homologação e produção e estão iguais, conforme descrito abaixo:

```
SELECT * FROM NLS_DATABASE_PARAMETERS order by PARAMETER;
```
```
NLS_CALENDAR			GREGORIAN
NLS_CHARACTERSET		WE8MSWIN1252		<--------
NLS_COMP				BINARY
NLS_CURRENCY			$
NLS_DATE_FORMAT			DD-MON-RR
NLS_DATE_LANGUAGE		AMERICAN
NLS_DUAL_CURRENCY		$
NLS_ISO_CURRENCY		AMERICA
NLS_LANGUAGE			AMERICAN
NLS_LENGTH_SEMANTICS	BYTE
NLS_NCHAR_CHARACTERSET	AL16UTF16			<--------
NLS_NCHAR_CONV_EXCP		FALSE
NLS_NUMERIC_CHARACTERS	.,
NLS_RDBMS_VERSION		11.2.0.4.0
NLS_SORT				BINARY
NLS_TERRITORY			AMERICA
NLS_TIME_FORMAT			HH.MI.SSXFF AM
NLS_TIMESTAMP_FORMAT	DD-MON-RR HH.MI.SSXFF AM
NLS_TIMESTAMP_TZ_FORMAT	DD-MON-RR HH.MI.SSXFF AM TZR
NLS_TIME_TZ_FORMAT		HH.MI.SSXFF AM TZR
```


Veja como o modelo geral foi editado no banco de dados de desenvolvimento (o que está sendo utilizado pela versailles, siga-dev e desenvolvimento local):
```
data	id do modelo	trecho de texto

<26/11/14	< 2100			... caracteres numéricos e não numéricos, visto que a função irá colher ...
06/01/15	2100			... caracteres numéricos e não numéricos, visto que a função irá colher ...
06/01/15	2101			... caracteres numÃ©ricos e nÃ£o numÃ©ricos, visto que a funÃ§Ã£o irÃ¡ colher ...
06/01/15	2102			... caracteres numÃƒÂ©ricos e nÃƒÂ£o numÃƒÂ©ricos, visto que a funÃƒÂ§ÃƒÂ£o irÃƒÂ¡ colher ...
27/01/15	2120			... caracteres numÃ?Æ?Ã?Â©ricos e nÃ?Æ?Ã?Â£o numÃ?Æ?Ã?Â©ricos, visto que a funÃ?Æ?Ã?Â§Ã?Æ?Ã?Â£o irÃ?Æ?Ã?Â¡ colher ...
```
Perceba que a letra **é** da palavra **numéricos** teve as seguintes transformações:

1) é			(1 caracter)

- Nenhuma transformação

2) Ã©			(2 caracteres) 

- é foi convertido para Ã©

3) ÃƒÂ©			(4 caracteres) 

- Ã foi convertido em Ãƒ
- © foi convertido para Â©
								
4) Ã?Æ?Ã?Â©		(8 caracteres) 

- Ã foi convertido para Ã?
- ƒ foi convertido para Æ?
- Â foi convertido para Ã?
- ©  foi convertido para Â©


Provavelmente havia um servidor mal configurado (versailles, siga-dev ou algum eclipse local) que apresentou os dados de forma errada e, após gravá-los, enviou os textos embaralhados de volta para o banco de dados. 

Será que existe alguma configuração no servidor de aplicação (ou no apache) que defina a alteração do encoding ao enviar a página para o usuário?

**Comment by kmacedovarela** [comment]
Faz sentido Markenson! Obrigada.

Existem sim, devem ser adicionadas as propriedades de sistema:

org.apache.catalina.connector.USE_BODY_ENCODING_FOR_QUERY_STRING = true
org.apache.catalina.connector.URI_ENCODING = UTF-8

E deve-se setar o JBoss para utilizar o encoding via JVM também com o parametro
````
 -Dfile.encoding=utf-8
````
A configuração no JBoss ficaria semelhante a abaixo..

````
...
    </extensions>

    <system-properties>
        <property name="org.apache.catalina.connector.USE_BODY_ENCODING_FOR_QUERY_STRING" value="true" boot-time="true"/>
        <property name="org.apache.catalina.connector.URI_ENCODING" value="UTF-8" boot-time="true"/>
 ..... 
    </system-properties>
````


Como o problema foi identificado, vou fechar a issue e a equipe pode resolver os problemas de encoding que forem encontrando no banco de desenvolvimento, conforme forem encontrando, concorda?

**Comment by Markenson** [comment]
OK, @kmacedovarela.
