### ISSUE TITLE
Separar siga.war na instância 03

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#137]
Por questões de urgência na disponibilização dos ambientes, como forma de mitigação dos erros #105 e #110 o sistema siga foi disponibilizado na mesma instância que o sigaex. 

Este não é o planejado para a arquitetura do SIGA, e o problema será analisado com calma assim que possível

**Comment by hodrigohamalho** [comment]
Corrigido.

**Comment by kmacedovarela** [comment]
A issue poderá ser fechada quando o siga.war for separado no ambiente de produção.

**Comment by hodrigohamalho** [comment]
Entrou em produção hoje.
