### ISSUE TITLE
[Siga-Doc] Editor de textos indisponível ao alterar o tipo do destinatário do documento

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#139]
Ao editar um novo documento, se alterar o destinatário o editor de textos deixa de ser exibido

Como reproduzir:

1. Crie um novo documento
2. Altere o tipo de destinatário para "Matrícula"

Imagem:
![image](https://cloud.githubusercontent.com/assets/2985140/5901499/1d44b206-a55a-11e4-8307-5341b3ff246e.png)

**Comment by kmacedovarela** [comment]
O comportamento indesejado foi inserido no código, não era referente a migração em si. 
commit: 90d99fd707a30efaf745b61d0e4115859574b786

Para solucionar este problema em específico. Revertido conforme conteúdo existente no arquivo edita.jsp no commit no branch master:
aed2e3e3c1bd3e884cc9465aef97aeba1e8960d9
