### ISSUE TITLE
Proxy Error no primeiro acesso depois de iniciar o servidor

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#140]
Primeiro acesso a um módulo, as vezes lança esse erro no apache em menos de 20 segundos:

Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /sigatp/.
Reason: Error reading from remote server

**Comment by Andredsf** [comment]
Problema resolvido.

Foram alterados os valores de 3 parâmetros no Mod_Cluster/Networking, são eles;

Socket Timeout: = 30

Stop Context Timeout: = 30

Ping: 31
