### ISSUE TITLE
Erros de encoding em código

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#141]
Algumas classes com formato cp1252 ou iso-8859-1 estão com problema de encoding no texto da própria classe, jsp, ftl, etc.. 
Desta maneira, mensagens de erro são exibidas com caracteres errados.

**Comment by hodrigohamalho** [comment]
Como no JBoss em produção (o antigo inclusive) está setado para UTF-8, o correto seria no pom.xml de cada projeto (ou no master), adicionar o seguinte trecho de código:

```
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
  </properties>
```

Isso obriga o maven a compilar tudo como UTF-8, o que pude verificar é que no código do sigagc por exemplo, tem classes em diversos formatos, com isso algumas coisas funcionam outras não.

Quando não tem encoding setado o maven vai deixar o encoding o qual o arquivo foi salvo em outras palavras vai manter o da IDE. 

Tentei fazer um build aqui, forçando o encoding pra UTF-8, e deu vários erros de compilação, teria que ir substituindo cada caractere deste até que fossem solucionado todos, no final teriamos o projeto inteiro apenas com um formado de encoding. Só depois disso vejo uma maneira definitiva de solucionar este problema.

**Comment by kmacedovarela** [comment]
Vou fechar esta issue, e caso erros de encoding ocorram, devem ser reportados e serão tratados um a um, até que possamos ver isto com calma.
