### ISSUE TITLE
[Siga-Doc] Assinatura em lote (digital) não está funcionando

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#142]
Após realizar a assinatura em lote, nenhum documento é efetivamente assinado.

Como reproduzir

1. Clique em Siga/Módulos/Documentos
2. Clique em Documentos/Assinar em lote
3. Selecione pelo menos 1 documento
4. Clique em assinar em lote 
5. A barra de progresso indica que o processo de assinatura está ocorrendo
6. Ao acessar o documento, percebe-se que ainda não foi assinado.

imagem:
![image](https://cloud.githubusercontent.com/assets/2985140/5902592/d3e03d5c-a562-11e4-9775-3d8df7bf7933.png)

**Comment by hodrigohamalho** [comment]
Corrigido.
As urls que montagem as requisições dos certificados eram montadas considerando as portas local do servidor. Com isso quando a requisição era submetidas ao apache, ia com a porta do deploy no jboss, algo parecido com isso:

siga-hmg:8180/sigaex

O apache só responde na porta 80 e 443, não entende o que é 8180.
O que fiz foi relativizar todas urls, pra pegar a partir do contexto, ex:
/sigaex/resto-da-url....
