### ISSUE TITLE
[Siga-Doc] Assinatura em lote (com senha) não está funcionando

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#143]
Após realizar a assinatura em lote, nenhum documento é efetivamente assinado.

Como reproduzir:

1. Clique em Siga/Módulos/Documentos
2. Clique em Documentos/Assinar em lote
3. Selecione pelo menos 1 documento
3. Clique em assinar com senha
5. A barra de progresso indica que o processo de assinatura está ocorrendo
6. Ao acessar o documento, percebe-se que ainda não foi assinado.

imagem:
![image](https://cloud.githubusercontent.com/assets/2985140/5902592/d3e03d5c-a562-11e4-9775-3d8df7bf7933.png)

Esse problema pode estar relacionado com #142

**Comment by hodrigohamalho** [comment]
Corrigido.
