### ISSUE TITLE
link "esqueci minha senha" não funciona

### ISSUE THREAD

**Issue by herval2003** [projeto-siga/siga#146]
![esqueciminhasenha](https://cloud.githubusercontent.com/assets/8865562/5905367/d9b1d2cc-a576-11e4-84ef-cbb859345db3.jpg)

**Comment by herval2003** [comment]
![maisdetalhes](https://cloud.githubusercontent.com/assets/8865562/5905397/fc588dde-a576-11e4-9c04-dd85bd061227.jpg)

**Comment by herval2003** [comment]
![mensagemerro01](https://cloud.githubusercontent.com/assets/8865562/5905410/194718f2-a577-11e4-8ee2-f5d64fe42a9d.jpg)

**Comment by kmacedovarela** [comment]
Este erro foi corrigido nas versões mais recentes porém, devido à urgência da disponibilização do ambiente de produção, têm se priorizado a atualização do ambiente espelho ao produção: homologação.

Assim o ambiente de desenvolvimento for atualizado, acredito que este erro seja solucionado. 
Volto nesta issue assim que possível.

**Comment by herval2003** [comment]
O username é o mesmo para os ambientes de homologação, desenvolvimento e produção. Porém a password teve que ser recadastrada três vezes. No ambiente siga-dev eu não consegui fazê-lo; deu esse erro dos .jpg acima.

**Comment by herval2003** [comment]
:-),
Abraços, Herval. (3218-9092)

________________________________
De: Karina Macedo Varela [notifications@github.com]
Enviado: segunda-feira, 26 de janeiro de 2015 16:20
Para: projeto-siga/siga
Cc: Herval Lemos Do Amaral Junior
Assunto: Re: [siga] link "esqueci minha senha" não funciona (#146)


Este erro foi corrigido nas versões mais recentes porém, devido à urgência da disponibilização do ambiente de produção, têm se priorizado a atualização do ambiente espelho ao produção: homologação.

Assim o ambiente de desenvolvimento for atualizado, acredito que este erro seja solucionado.
Volto nesta issue assim que possível.
