### ISSUE TITLE
TRF2 - Sistema está perdendo parâmetros de pesquisa

### ISSUE THREAD

**Issue by adrigrassi** [projeto-siga/siga#1464]
O listar documentos com parâmetros de pesquisa o sistema não está armazenando alguns parâmetros, como a espécie e modelo.

**Comment by Dinarde** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [1464* - Incluir no editor de texto o recurso nota de rodapé.](https://trello.com/c/b0zhNvy6/709-1464-incluir-no-editor-de-texto-o-recurso-nota-de-rodap%C3%A9)
