### ISSUE TITLE
Pesquisa de documento não retorna documento pesquisado

### ISSUE THREAD

**Issue by gmbbarreto** [projeto-siga/siga#148]
A funcionalidade pesquisa documento não retornou o documento JFRJ-DES-2015/00647 no novo ambiente ("http://siga-beta/siga").

**Comment by kmacedovarela** [comment]
Esta pesquisa é a barrinha de busca no topo direito do siga?

**Comment by kmacedovarela** [comment]
Issue #102 duplicada.

**Comment by hodrigohamalho** [comment]
Corrigido.
