### ISSUE TITLE
Copiar arquivos de template (xhtml.dtd) para docker

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#150]
Copiar para a pasta /home/jboss/ 

xhtml.dtd
xhtml-symbol.ent
xhtml-special.ent
xhtml-lat1.ent

**Comment by AndDeluiz** [comment]
Aguardando disponibilização de novos items para que seja feito um único deploy de imagem.

**Comment by kmacedovarela** [comment]
Essas duas issues estão associadas pois pode ser gerada uma nova imagem já com todas as alterações. #162

**Comment by AndDeluiz** [comment]
Alterações efetuada no build-00022 do appserver.
