### ISSUE TITLE
[Siga-Doc] [Siga-Wf] O workflow não está sendo criado ao criar uma SEC

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#158]
Quando um documento com o tipo "Solicitação Eletrônica de Contratação" é assinado, este não está criando o fluxo no siga-wf.

Como reproduzir:
- Na página inicial do SIGA clique no botão **Novo** (abaixo do quadro de documentos)
- Preencha os seguinte campos:
  - Selecione o tipo "Digital"
  - subscritor: RJ13286
  - Destinatário: Matrícula RJ13286
  - Tipo:Solicitação Eletrônica de Contratação
  - Descrição: Teste
- Clique no botão OK
- Clique no link Finalizar
- Clique no link Assinar
- Clique no botão "Assinar com senha"
- Digite a matrícula RJ13286

Acima do documento deveria aparecer a tarja do SIGA-WF, semelhante a imagem abaixo:

![image](https://cloud.githubusercontent.com/assets/2985140/5960870/859b3e4e-a7bf-11e4-9e66-1ce556c5d52d.png)

**Comment by kmacedovarela** [comment]
Devido a uma exceção lançada pelo jbpm no processamento dos feriados o workflow não era gerado. Este erro nao ocorria na versão existente, porém durante a migração do sigawf o jbpm foi atualizado em consequência da atualização para hibernate 4.

fa61feed098be332b3d0a09f1e51f30ec16dea96

**Comment by kmacedovarela** [comment]
O problema ocorre pois a chamada via javascript a partir d o sigaex para o sigawf precisa passar pela autenticação do picketlink. Este problema independe da separação das instâncias.

**Comment by kmacedovarela** [comment]
#199 ambas as issues estão com problema no IE
