### ISSUE TITLE
[SigaDOC]Teste de agendamento no DJE em produção

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#161]
No ambiente de homologação, não consegui reproduzir o fluxo com sucesso (nem na sigat), porém o erro que estava ocorrendo que gerava o documento em formato incorreto foi corrigido.

Gostaria de saber se vocês poderiam testar o agendamento no ambiente de produção, com fluxo semelhante ao reportado em #101 :

http://siga-beta/siga

#149

**Comment by andresousa17** [comment]
Testei em http://siga-beta/siga e o conteúdo do documento continua saindo em branco.

**Comment by kmacedovarela** [comment]
Amanhã verificarei os logs, e te procuro para testarmos novamente.

**Comment by kmacedovarela** [comment]
Resolvido, testei com a rafaela.

Faltavam os arquivos nas máquinas de produção:
xhtml.dtd
xhtml1-transitional.dtd
xhtml-lat1.ent
xhtml-symbol.ent
xhtml-special.ent
xhtml1-strict.dtd
