### ISSUE TITLE
[Docker] atualização do standalone.xml

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#162]
Propriedades no standalone.xml foram atualizadas, da forma como está configurado o docker é necessário atualizar a imagem.

Atentar-se para não esquecer de salvar o arquivo (atentando-se a remover os deploys, exceto ojdbc6 e ckeditor ) antes de gerar nova imagem.

**Comment by hodrigohamalho** [comment]
resolvi essa issue já, se tiver faltando alguma coisa, favor reabrir.

**Comment by kmacedovarela** [comment]
É necessário copiar também um novo módulo criado. 

copiar o diretorio fop para opt/jboss/modules/sigadoc/

 Diretorio: https://github.com/projeto-siga/siga/tree/migracao-jboss6/configuracao/modulo/sigadoc/fop/

Alteração decorrente de:
https://github.com/projeto-siga/siga/issues/149

**Comment by kmacedovarela** [comment]
É necessário ainda uma atualização.

**Comment by hodrigohamalho** [comment]
Tem que atualizar o módulo sigadoc/ext também.

Também é necessário copiar os documentos da assinatura digital:
/home/resource na classea.

Após isso verificar e atualizar as variáveis do certificado para apontarem para esse endereço.

**Comment by kmacedovarela** [comment]
Fazer também o tunning de JVM referente ao random

**Comment by AndDeluiz** [comment]
Alterações efetuadas no build-00022 do appserver.
