### ISSUE TITLE
Scripts de inicialização

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#163]
Ao executar com usuário hjbossadmin

[hjbossadmin@xxxxx ~]$ jboss-sigarh  start
Starting jboss-as: xxxxxx/jboss-custom.sh: line 121: /tmp/jboss-console-sigarh-dc.log: Permission denied

comportamento correto ao executar o script com outro usuário seria um dos dois descritos abaixo:
1. Pede a senha do usuário jboss e prossegue com execução
2. Dá mensagem de erro, e solicita que o script seja executado com root ou jboss.

**Comment by AndDeluiz** [comment]
Corrigido e adicionado tratamento de erro de escrita para console log file.
