### ISSUE TITLE
[SIGARH-Benefícios] Erro ao acessar qualquer função do sistema

### ISSUE THREAD

**Issue by lupercioferraz** [projeto-siga/siga#167]
![image](https://cloud.githubusercontent.com/assets/10778261/5982712/231a103a-a8ad-11e4-9352-c4307cbd21a3.png)

**Comment by kmacedovarela** [comment]
Em standby.

**Comment by kmacedovarela** [comment]
Adicionado trecho 

````
			<param-name>crossDomainSessionSecurity</param-name>
			<param-value>false</param-value>       
````

No web.xml da aplicação, na servlet dwr-invoker. 
O erro ocorre devido à chamadas entre servidores diferentes, e o DWR tenta bloquear.
