### ISSUE TITLE
[SIGARH-Cadastro-Treinamento] Erro ao tentar fazer alguma consulta no sistema

### ISSUE THREAD

**Issue by lupercioferraz** [projeto-siga/siga#168]
![image](https://cloud.githubusercontent.com/assets/10778261/5982760/a00b9d70-a8ad-11e4-9c98-f3be2c4a6d82.png)

**Comment by kmacedovarela** [comment]
Em standby.

**Comment by kmacedovarela** [comment]
Em standby.

**Comment by kmacedovarela** [comment]
Adicionado trecho 

````
			<param-name>crossDomainSessionSecurity</param-name>
			<param-value>false</param-value>       
````

No web.xml da aplicação, na servlet dwr-invoker. 
O erro ocorre devido à chamadas entre servidores diferentes, e o DWR tenta bloquear.
