### ISSUE TITLE
[siga-play-module] Atualizar banco

### ISSUE THREAD

**Issue by hodrigohamalho** [projeto-siga/siga#169]
19:09:41,419 INFO  [stdout] (http-/0.0.0.0:8080-8) Caused by: java.sql.SQLSyntaxErrorException: ORA-00904: "THIS_1_"."ID_UNIDADE_ATENDIMENTO": identif
icador invalido

@Markenson começou a aparecer este erro sendo disparado pelo siga-play-module, sabe se tem alguém atualizando o banco ou que mexeu nessa parte recente?

**Comment by Markenson** [comment]
Parece que o banco de desenvolvimento está diferente de homologação. @esredson existe essa possibilidade?

**Comment by esredson** [comment]
Sim! Sorry. Consertei agora.

**Comment by kmacedovarela** [comment]
A princípio está OK, qualquer coisa reabrimos a issue!
Obrigada!
