### ISSUE TITLE
[SIGARH-Cadastro-Treinamento] Erro ao tentar fazer alguma consulta no sistema

### ISSUE THREAD

**Issue by lupercioferraz** [projeto-siga/siga#170]
O mesmo erro 'Session Error' está ocorrendo em Homologação quando é feito consulta/alteração de dados.

**Comment by kmacedovarela** [comment]
Lupércio, você poderia abrir os erros com exemplos de como reproduzir o erro? Tentei reproduzir da seguinte maneira e nao deu erro:

Acessei o siga tr: http://siga-hmg/sigatr/
No menu cadastros, cliquei na primeira opção: área capacitação
cliquei em "Alterar" , na primeira linha, confirmei

O erro mencionado não ocorreu.

**Comment by kmacedovarela** [comment]
Adicionado trecho 

````
			<param-name>crossDomainSessionSecurity</param-name>
			<param-value>false</param-value>       
````

No web.xml da aplicação, na servlet dwr-invoker. 
O erro ocorre devido à chamadas entre servidores diferentes, e o DWR tenta bloquear.
