### ISSUE TITLE
SigaRH-AQ

### ISSUE THREAD

**Issue by moisesoliveirasilva** [projeto-siga/siga#171]
Quando tanto cadastrar um curso novo para servidor, dá o erro conforme está na figura.

Dados do formulário:
![image](https://cloud.githubusercontent.com/assets/10811740/6005108/ebcc7638-aaee-11e4-9747-02ed55e89852.png)

Erro:
![image](https://cloud.githubusercontent.com/assets/10811740/6005118/fb23e558-aaee-11e4-8e68-6bd5e681e466.png)

**Comment by kmacedovarela** [comment]
Você poderia testar novamente? Não consegui reproduzir o erro, o curso foi incluído com sucesso.

Se o erro ocorrer, favor *reabrir* a issue.

![capturar](https://cloud.githubusercontent.com/assets/253186/6009169/80690170-ab0e-11e4-8528-0b165bf4586d.PNG)
