### ISSUE TITLE
PCRJ_79 - Campo Modelo está estourando a tela.

### ISSUE THREAD

**Issue by ivangsilverio** [projeto-siga/siga#1713]
Quando se cadastra um novo documento, caso a tela esteja numa resolução menor, o campo Modelo está estourando a tela.

EVV:
https://www.youtube.com/watch?v=NziP6-868To

[[PROCESSO_RIO-79] Campo Modelo está estourando a tela. - IplanRio JIRA.pdf](https://github.com/projeto-siga/siga/files/6036434/PROCESSO_RIO-79.Campo.Modelo.esta.estourando.a.tela.-.IplanRio.JIRA.pdf)

**Comment by andrem-carvalho** [comment]
![Erro-novo-documento-modelo](https://user-images.githubusercontent.com/78379805/109046634-bbfbd880-76b3-11eb-9b80-140ddeb79f4f.png)
