### ISSUE TITLE
[Importante[Siga-DOC] A busca de documentos não está funcionando

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#176]
O fluxo reportado na issue #102 não está funcionando no branch develop (nem na versailles nem em localhost). 
Gostaria de solicitar a correção por parte de alguém da equipe devido ao maior knowhow.

Assim que esta issue for fechada, prosseguiremos com a correção do erro reportado nas issues  #102  e #148 referentes a migração (é um erro diferente, associado ao picketlink).

**Comment by andresousa17** [comment]
Corrige a montagem da variável urlBase que estava dando erro na concatenação da porta.

String urlBase = getRequest().getScheme() + "://" + getRequest().getServerName() + ":" + getRequest().getServerPort();

O erro agora está dando quando utilizamos o protocolo HTTPS. Quando utilizamos HTTP funciona.

**Comment by kmacedovarela** [comment]
Ok, obrigada!

**Comment by kmacedovarela** [comment]
@andresousa17  quando fizer alguma correção, favor referenciar o commit ou pelo menos o branch em que foi realizada a alteração para facilitar o rastreamento.

**Comment by kmacedovarela** [comment]
Fiz o merge com branch develop e o problema foi resolvido localmente, obrigada.
