### ISSUE TITLE
TRF2-GC-2021004398 - Problema ao editar um conhecimento no GC

### ISSUE THREAD

**Issue by jmolivei** [projeto-siga/siga#1780]
O SIGA-GC não está permitindo edição de conhecimentos. O SIGA-GC grava, mas exibe a edição anterior.

No arquivo abaixo o problema está  claro. O SIGA-GC grava, mas exibe a edição anterior.

![edicao-anterior](https://user-images.githubusercontent.com/5268745/113947809-dca26c80-97e1-11eb-89d1-326396834ac3.gif)

chamado aberto no GLPI -  https://chamados.trf2.jus.br/front/ticket.form.php?id=2021004398

**Comment by Chrystinne** [comment]
O erro acontecia porque o sistema atualiza a informação com base nas movimentações (atualizando o campo "inf.id" com base no id da última movimentação de edição, "mov.arq.id"). 

No entanto, para que tal atualização proceda de forma correta, a lista de movimentações precisa vir na ordenação esperada pelo algoritmo. (A estrutura de dados da lista de movimentações é um TreeSet, que ordena os elementos pela data da movimentação e, como segundo critério, pelo id). 

Entretanto, ocorre que, no momento da adição da última movimentação de edição na lista, o id desta movimentação era 0, o que fazia com que o elemento não ficasse na ordem correta na lista de movimentações e, consequentemente, a rotina de atualização da informação não atribuísse o seu id à informação.

O problema foi resolvido atualizando a lista de movimentações (Treeset) com a adição do elemento correspondente à última edição na própria rotina "atualizarInformacaoPorMovimentacoes", quando o id da última edição do conhecimento já havia sido setado (sendo diferente de zero).

**Comment by Chrystinne** [comment]
Pra aumentar a eficiência do algoritmo, fiz um refactoring no código anterior, para reordenar a lista de movimentações removendo e adicionando a movimentação que estava fora de ordem, após ter seu id inicializado.
