### ISSUE TITLE
TRF2-GC - Imagens não aparecem nos links públicos

### ISSUE THREAD

**Issue by jmolivei** [projeto-siga/siga#1788]
As imagens que são anexadas em um conhecimento não aparecem na mesma visualização do link público.

Exemplo :

link público
https://siga.jfrj.jus.br/sigagc/public/app/exibir/TRF2GC202100041 

link autenticado
https://siga.jfrj.jus.br/sigagc/app/exibir/TRF2GC202100041

**Comment by Chrystinne** [comment]
@jmolivei Tem algum chamado aberto pra essa issue para a gente referenciar aqui?

**Comment by Chrystinne** [comment]
O problema já foi corrigo em commits anteriores da correção da funcionalidade de edição de conhecimentos.
