### ISSUE TITLE
Antecipando correção de erro referente ao aumento dos acessos 

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#180]
Verificar se já foram feitas, e se não foram, aplicar as seguintes configurações (adaptadas conforme necessidade) para o ambiente de produção, em todas as máquinas com instâncias de servidores JBoss e Apache.

https://access.redhat.com/solutions/18064

**Comment by AndDeluiz** [comment]
Configurações de limites e kernel.pid_max foram efetuadas nas máquinas JBoss de DEV, HMG e PROD. Nenhuma configuração foi alterada para os servidores apache ou imagens Docker.
Tomei como base a configuração da produção atual em JBoss EAP 5.
