### ISSUE TITLE
Siga-GC: Conhecimento continua com a marca "Em elaboração" após a sua finalização

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#1810]

**Comment by Chrystinne** [comment]
Nome do conhecimento também continua como TMPGC.

**Comment by Chrystinne** [comment]
https://user-images.githubusercontent.com/4949149/115298264-a21ac700-a133-11eb-90c2-c1105a7439aa.mp4

**Comment by jmolivei** [comment]
@Chrystinne George acabou de me falar isso. Ai quando fui abri vi que voce ja tinha aberto.
