### ISSUE TITLE
[Apache] Erro ao acessar http://siga-beta/siga

### ISSUE THREAD

**Issue by hodrigohamalho** [projeto-siga/siga#184]
O apache só está direcionando as requisições quando o link é passado com uma barra no final:
http://siga-beta/siga/

Quando é acessado:
http://siga-beta/siga

Da um 404.

O mesmo erro não acontece em homologação.

**Comment by Andredsf** [comment]
Foi encontrado um problema no modulo mod_cache do apache. Para resolver este problema o conteúdo do mod_cache foi deletado e reconstruido novamente.


systemctl stop httpd
rm -rf /var/cache/httpd/mod_cache/*.*
systemctl  start httpd
