### ISSUE TITLE
PCRJ_582 - upload multiplo de anexos

### ISSUE THREAD

**Issue by ivangsilverio** [projeto-siga/siga#1887]
Desenvolver a funcionalidade para possibilitar o upload em lote de arquivos

requisito:
https://siga.jfrj.jus.br/sigagc/public/app/exibir/TRF2GC202100070

Em reunião com o Comitê, esta pendência foi definida como prioritária. Entendo que ela deve ser devolvida por pull request, portanto deve ser iniciada apenas o pós o merge com desenv

O requisito não trata da questão de assinaturas e autenticações concomitantes. Esse comportamento será mantido. Como tratado na reunião do dia 28/5 com o comitê técnico, no caso de erro na operação, pode ser lançado um novo movimento sem prejuízo do anterior. Uma assinatura, depois uma autenticação, ou o contrário.

Hoje é possível juntar o anexo sem assinar e autenticar, isso continuará possível.

No caso de erro em um arquivo, o sistema deve informar o erro indicando o arquivo e a operação não deverá seguir.

Caso o usuário não altere a descrição, o sistema deve aceitar apenas o nome do arquivo neste atributo.
Esse comportamento foi ratificado em uma mensagem no grupo do comitê interinstitucional dia 28/05/21

"
...
Re: Anexar em lote
por SIMONE BARBOSA - sexta, 28 Mai 2021, 14:06
Boa tarde Sergio,

A proposta satisfaz o pedido de anexação em lote, ressaltando que o item 2 (edição do campo - descrição para cada item selecionado), seja facultativo, pois no caso da Sepex não será necessário, visto que na nomeação dos arquivos anexados (item 1) já conterão todos as informações indispensáveis.

...
"

https://colabore.trf2.jus.br/mod/forum/discuss.php?d=56

Observações:
1) hoje, se o volume tiver 199 páginas e for executado um upload de um anexo com 10 páginas, e se o número máximo de páginas estiver configurado para 200, o primeiro volume terá 209 páginas. Isso não foi alterado

2) o módulo de upload abre e fecha volumes automaticamente

**Comment by andrem-carvalho** [comment]
As seguintes propriedades deverão ser configuradas no standalone.xml :
qtd.max.arquivo.anexado.upload => Indica a quantidade maxima de arquivos por upload. Tem como valor defaul 1.
qtd.max.arquivo.anexado.upload => Tamnho maximo do upload arquivo(s). Tem como valor default 5000000 bytes.

**Comment by andrem-carvalho** [comment]
Upload multiplos arquivos
- arquivos PDF
- Qtd de arquivos por upload  definida na propriedade : qtd.max.arquivo.anexado.upload 
- Tamanho do upload definido na propriedade : pdf.tamanho.maximo
![image](https://user-images.githubusercontent.com/78379805/124279834-549cdc00-db1e-11eb-8783-d47078375b01.png)

Usuário escolhe os arquivos a serem anexados
![image](https://user-images.githubusercontent.com/78379805/124280466-15bb5600-db1f-11eb-977d-8fc5ba6e1126.png)

Conforme definição do requisito  por padrão a descrição é preenchida com o nome do arquivo.
![image](https://user-images.githubusercontent.com/78379805/124280679-5b781e80-db1f-11eb-8754-7eea96c46da6.png)

Será permitido alterar essa descrição.
![image](https://user-images.githubusercontent.com/78379805/124280726-692da400-db1f-11eb-9eff-8c0733ebb6b1.png)

Após upload
![image](https://user-images.githubusercontent.com/78379805/124280831-87939f80-db1f-11eb-88d1-38a628c5cbb2.png)
