### ISSUE TITLE
Erro ao buscar um Grupo no Siga-Serviços 

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#189]
Erro que ocorre no [siga-beta] e no [siga-hmg], e não ocorre em produção [siga/siga].
Para reproduzir o erro, seguir os seguintes passos:
- Dentro do módulo do siga-serviços, entrar no menu administração > designação;
- Ir para o final na página, e clicar no botão incluir;
- No campo Solicitante, selecionar "grupo" e digitar sti_trf2 (ver imagem).
- Verificar que não aparece a descrição do grupo como padrão desses campos "seleção". Clicando no botão [...] é possível verificar o erro ao buscar o perfil de acesso do Siga-GI (ver imagem)

![captura_de_tela_021115_054032_pm](https://cloud.githubusercontent.com/assets/8461113/6154895/44bbc888-b216-11e4-9fa4-49e3f013842b.jpg)

Obs.: Esses grupos no SIGA-GI são chamados de Grupo de Perfil de Acesso. Para verificar a listagem de grupos desse tipo por dentro do siga-gi, basta ir no menu SIGA > Gestão de Identidade > Perfil de Acesso.

**Comment by kmacedovarela** [comment]
O erro está sendo ocasionado pois está sendo chamada uma action inexistente: 
http://siga-hmg/siga/perfil/buscar.action?propriedade=perfilcpGrupo&sigla=
````
 Could not find action: There is no Action mapped for namespace /perfil and action name buscar. Check if there is such an action name with such namespace defined in the xwork.xml and also if such an action class exists. Check also the log to see if the action class is successfully loaded. - [unknown location]
````

O correto seria chamar 
http://sigat/siga/gi/perfil/buscar.action?propriedade=perfilcpGrupo&sigla=

**Comment by hodrigohamalho** [comment]
bom dia, irei resolver.

**Comment by kmacedovarela** [comment]
Resolvido em 9370b90272f5414603383e5d5117d9000534f1e0

**Comment by kmacedovarela** [comment]
Agora, apesar de abrir a caixa de busca, ao digitar a consulta e pressionar "tab' o auto complete não está funcionando.

**Comment by hodrigohamalho** [comment]
Deixe comigo!

**Comment by hodrigohamalho** [comment]
Resolvido.

**Comment by kmacedovarela** [comment]
Voltou a ocorrer conforme informado em #197

**Comment by kmacedovarela** [comment]
Resolvido em homologação, entrará no próximo deploy em produção
