### ISSUE TITLE
Erro na substituição 

### ISSUE THREAD

**Issue by adrigrassi** [projeto-siga/siga#190]
Ao substituir um usuário ou uma lotação as aplicações play não estão carregando.

**Comment by kmacedovarela** [comment]
#187 duplicado

**Comment by kmacedovarela** [comment]
Já identifiquei a solução para o problema, disponibilizarei versão corrigida para teste ainda hoje.

**Comment by kmacedovarela** [comment]
Quando chamado por uma aplicação play, não estava sendo identificada a named query configurada via arquivo hbm.xml

Foi configurado então também a named query via annotation na classe DpSubstituicao.java

7510d1aa4261216d6234362dd8c6e1c65e8bacd2
