### ISSUE TITLE
EX - Problemas na geração do Boletim Interno 

### ISSUE THREAD

**Issue by adrigrassi** [projeto-siga/siga#1904]
O cabeçalho do Boletim Interno (tanto SJRJ e SJES) está sobrepondo o rodapé conforme imagem abaixo.
![BoletimInterno](https://user-images.githubusercontent.com/5265327/125857934-04b2a8f7-2b45-4c59-bcff-636d4ecfddf3.JPG)

**Comment by jmolivei** [comment]
resolvido acrescentado tag  no inicio do modelo do BIE

![image](https://user-images.githubusercontent.com/5268745/126808738-a2901d94-df5a-417e-8920-acba888e58e4.png)
