### ISSUE TITLE
Erro ao carregar os módulos

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#192]
Mesmo após pressionar F5, os módulos apresentam o erro da figura abaixo:

![image](https://cloud.githubusercontent.com/assets/2985140/6271943/6bcd915a-b84b-11e4-994b-a38d7861aa8f.png)

Ferramenta do chrome não apresenta erro:

![image](https://cloud.githubusercontent.com/assets/2985140/6272015/da4cb6ba-b84b-11e4-9e6e-110b861ba38c.png)

**Comment by kmacedovarela** [comment]
O erro acontece sempre que você loga?

**Comment by kmacedovarela** [comment]
Acabou de acontecer aqui também, vou verificar.

**Comment by hodrigohamalho** [comment]
Esse erro (é pra ser) muito específico. Seria somente quando ocorre uma indisponibilidade no IDP corrente e o apache redireciona para o outro. 

Creio que a melhor solução seria clusterizar o sigaidp.

**Comment by hodrigohamalho** [comment]
Na verdade tem um outro caso também que ele ocorre, é caso o servidor do IDP seja reiniciado. Esse caso pode ser melhor tratado, vou analisar.
