### ISSUE TITLE
Erro ao incluir item e ação através do campo seleção no SIGA-SR

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#193]
Erro que ocorre no [siga-beta] e no [siga-hmg], e não ocorre em produção [siga/siga].
Para reproduzir o erro, seguir os seguintes passos:

Dentro do módulo do siga-serviços, entrar no menu administração > designação;
Ir para o final na página, e clicar no botão incluir;

- Clicar no botão incluir do Item de Configuração (ver passo 1 da figura);
- Na janela modal que será aberta, digitar um item válido (ver passo 2 da figura) (Em produção testar com 01.01.01). 
- O comportamento esperado quando esse input perder o foco, já que esse código digitado é válido na base, é que o sistema encontre o item e coloque a descrição ao lado, sem precisar abrir a janela pop-up.  

O mesmo ocorre para a inclusão de "ações". (ver passo 3 da figura)

![captura_de_tela_021915_065303_pm](https://cloud.githubusercontent.com/assets/8461113/6275719/89d7557e-b868-11e4-8e47-2ad2667b4ebd.jpg)

**Comment by kmacedovarela** [comment]
Mesmo problema da outra caixinha, mas sobre outro namespace.

**Comment by kmacedovarela** [comment]
URL que está sendo chamada:
http://siga-beta/siga/item/selecionar.action?url=%2Fsiga%2Fitem%2Fselecionar.action&propriedade=itemitemConfiguracao&sigla=01.01.01

O correto seria:
http://siga-beta/sigasr/item/selecionar?sigla=01.01.01&prefixo=&nome=itemConfiguracao&

**Comment by kmacedovarela** [comment]
Testei no siga-beta, e está OK.
