### ISSUE TITLE
Erro no módulo de Relatórios

### ISSUE THREAD

**Issue by lupercioferraz** [projeto-siga/siga#194]
Ao tentar entrar em qualquer relatório (Módulos->Pessoas->Benefícios->Relatórios) ocorre um erro.
![image](https://cloud.githubusercontent.com/assets/10778261/6286545/c885de12-b8ef-11e4-99a4-13a1981a97d8.png)

**Comment by kmacedovarela** [comment]
O erro ocorria devido a referencias para um nome jndi incorreto, dentro da aplicação.
Exemplo:
atual:     java:/SigaBeneficiosDS
correto: java:/jboss/datasources/SigaBeneficiosDS

Alterei as referencias e fiz o commit. Ja disponibilizei a nova versão em homologação.
@lupercioferraz Quando você deseja que o deploy seja realizado no ambiente de produção beta?

**Comment by kmacedovarela** [comment]
Resolvido, pendente apenas de deploy no siga-beta.

**Comment by kmacedovarela** [comment]
Deploy realizado em produção.

**Comment by crivano** [comment]
@kmacedovarela só para constar, corrigi recentemente um bug de relatórios atualizando a versão do dynamicjasper para a mais nova. A correção não está no branch OSI_FS000011_FIX.
