### ISSUE TITLE
Quadros não carregam no IE

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#196]
Ao fazer login no SIGA, via Internet Explorer, os quadros não estão aparecendo.

Como reproduzir:

Basta fazer o login

**Comment by kmacedovarela** [comment]
Analisando.

**Comment by kmacedovarela** [comment]
Acredito que solucionei o problema. O siga-beta precisará ser parado para disponibilização de nova versão.

**Comment by kmacedovarela** [comment]
Resolvido
