### ISSUE TITLE
Erro ao gravar uma designação no SIGA-SR

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#197]
Erro que ocorre no [siga-beta] e no [siga-hmg], e não ocorre em produção [siga/siga].
Para reproduzir o erro, seguir os seguintes passos:

Dentro do módulo do siga-serviços, entrar no menu administração > designação;
Ir para o final na página, e clicar no botão incluir;

Preencher todos os campos. Em produção os valores exibidos na figura podem ser usados durante os testes.

Ao final, clicar no botão Ok para visualizar a mensagem de erro que informa que alguns campos obrigatórios não foram preenchidos.

Obs.: Verificar novamente a issue fechada #189, que não está mostrando a descrição do grupo após o input perder o foco, nessa versão atual.

![captura_de_tela_022315_040117_pm](https://cloud.githubusercontent.com/assets/8461113/6334708/345ebef6-bb75-11e4-8bef-f9d6514d5544.jpg)

**Comment by kmacedovarela** [comment]
@rafaela00castro , caso erros voltem a ocorrer, pode reabrir a issue para facilitar o rastreamento. Já reabri a issue 189. 

Com relação a este erro 197, ele também está acontecendo em localhost. Então não é algo específico de ambiente, o que facilita o rastreamento do problema. Devido a issues mais críticas que estou solucionando no momento, gostaria de saber se alguém da equipe pode assumir este erro? @rafaela00castro, @esredson ou alguém mais?

````
16:47:57,981 ERROR [stderr] (http-localhost/127.0.0.1:8080-6) java.lang.Exception: designacao.atendente;designacao.preAtendente;designacao.posAtendente;designacao.equipeQualidade;

16:47:57,981 ERROR [stderr] (http-localhost/127.0.0.1:8080-6) 	at controllers.Application.validarFormEditarDesignacao(Application.java:364)

16:47:57,981 ERROR [stderr] (http-localhost/127.0.0.1:8080-6) 	at controllers.Application.gravarDesignacao(Application.java:842)
````

**Comment by esredson** [comment]
Pessoal, esse erro não deveria mais estar acontecendo. Parece ser algum resquício de código antigo, visto que não há mais validação de pré-atendente e pós-atendente. Por exemplo, buscar a string "preAtendente" no workspace deve retornar apenas alguns matches que não têm relação com essa tela aí. Acredito que deva parar de ocorrer no próximo merge.

**Comment by kmacedovarela** [comment]
@esredson, apenas a titulo de informação o branch migracao-jboss6 está atualizado com o branch develop. Acabei de fazer o pull e o merge e nenhuma alteração foi baixada.

**Comment by esredson** [comment]
@kmacedovarela, realmente, nesse momento o develop estava desatualizado também. Pouco depois, fiz um merge de outro branch para o develop.

**Comment by kmacedovarela** [comment]
Apenas para registrar: o erro que ocorre agora é que a designação é salva em branco

**Comment by kmacedovarela** [comment]
#202

**Comment by kmacedovarela** [comment]
Fechado para evitar duplicidade, será resolvido junto com issue #202
