### ISSUE TITLE
SigaTreinamento

### ISSUE THREAD

**Issue by moisesoliveirasilva** [projeto-siga/siga#198]
No sigatr homologação http://siga-hmg/sigatr, no menu Planejamento -> Turma -> Incluir -> Quando seleciono uma opção no combo Área de Capacitação, dá o seguinte erro: "Session Error".

No sigatr produção http://siga-beta/sigatr, a usuária relatou um erro no cadastro de nova turma (Planejamento -> Turma -> Incluir ), mas não enviou detalhes. Vou tentar simular.

**Comment by kmacedovarela** [comment]
Associado a  #170
Problema solucionado em homologação. Vou realizar o deploy em produção.

**Comment by kmacedovarela** [comment]
Deploy realizado no siga-beta.
