### ISSUE TITLE
Ao cadastrar solicitação, não aparece a lista de conhecimentos relacionados

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#199]
Para simular, clicar em Módulos -> Serviços e, na tela seguinte, escolher um item de configuração qualquer. O correto é que, à direita, apareça um quadro com o título Conhecimentos Relacionados, obtido do Siga-Gc.

**Comment by kmacedovarela** [comment]
O problema tem a ver com chamadas entre módulos, principalmente entre módulos com play framework. 
Sob análise.

**Comment by kmacedovarela** [comment]
Iniciando trabalhos nesta issue.

**Comment by kmacedovarela** [comment]
Só pode ser resolvido após #202

**Comment by hodrigohamalho** [comment]
Resolvido.

Toda chamada ao PassAjaxResponseToFunction e ReplaceInnerHTMLFromAjaxResponse, deve ser substituído por chamadas ao Siga.ajax.

**Comment by kmacedovarela** [comment]
Erro no I.E.

**Comment by hodrigohamalho** [comment]
No internet explorer as vezes aparece a página de estatistica geral. 
Antes disso ele trás o resultado que deveria ser mostrado mas por algum motivo parece que ele faz um novo request pra essa nova página e sobrescreve o resultado correto pelo errado, talvez um HTTP 302 ? Vou terminar essa analise e corrijo o problema.

O complicado é que tenho dificuldades pra reproduzir, no meu ambiente local quase sempre funciona...
