### ISSUE TITLE
PCRJ_1394 - Processos sobrestados porém na situação aguardando andamento

### ISSUE THREAD

**Issue by ivangsilverio** [projeto-siga/siga#2015]
Investigar problema de Processos sobrestados porem na situação aguardando andamento, aparentemente isto ocorreu após a implantação da nova versão. Na verdade os processos ficam nas duas situações.
Olhando a mesa, percebemos que documentos constam nas situações de Aguardando andamento e Sobrestado. 
![PROCESSO_RIO-1394-tela2-mesa](https://user-images.githubusercontent.com/78379805/143447849-16826a57-175c-447e-8ff5-a5e710b993d5.PNG)

Podemos notar a presença das marcas na exibição do documento
![PROCESSO_RIO-1394-tela1](https://user-images.githubusercontent.com/78379805/143448387-d47c6224-7b34-4468-8171-b59dfecc032b.PNG)

Testes realizados na versão .21/22 (PCRJ), .27 (TRF2)  e 10.1.0.1

Query para localizar documentos com as duas marcas (sobrestado e aguardando andamento)

[QueryJiraPROCESSO-RIO-1394-DocumentosAguardandoAndamentoESobrestados.txt](https://github.com/projeto-siga/siga/files/7598702/QueryJiraPROCESSO-RIO-1394-DocumentosAguardandoAndamentoESobrestados.txt)

**Comment by ivangsilverio** [comment]
Analisando classe ExMarcadorBL  método cacular, possivelmente reremos que criar um método removerIncompativeis

**Comment by crivano** [comment]
Corrigido no merge da release 10.0.27 com a develop.
