### ISSUE TITLE
Sugestão de alteração na regra: Pode Juntar

### ISSUE THREAD

**Issue by dinarde** [projeto-siga/siga#2027]
Conforme informado, houve uma única quebra da versão 21 para a versão 27, onde se o subscritor fosse de outra área e ele fosse o finalizador do documento a ser juntado, o sistema não estava mais juntando, o que divergia do comportamento anterior.

O commit 50619891c7ed8bf88002f8b3323d0cd59535a5a4 feito pelo TRF2 solucionou este problema específico, onde foi corrigido o cálculo de atendente do documento para o ponto de partida do documento não tramitado ser a partir da movimentação de criação (Finalização).

A correção está disponível na versão 10.0.27.11.

Foi sugerida complementarmente uma alteração na regra da Juntada Automática, para que em caso o subscritor do documento seja de outra área (não atendente) ele possa juntar o documento independente dele ter finalizado ou não o documento filho. Então sempre o subscritor do documento irá fazer a Juntada Automática antes de verificar se pode ou não movimentar o documento:

Regra Atual:
&& podeMovimentar(titular, lotaTitular, mob)

......
E pode movimentar o documento filho
......

Sugestão:
&& ((mob.doc().getExMobilPai() != null && mob.doc().isSubscritorOuCosignatario(titular)) || podeMovimentar(titular, lotaTitular, mob))

......
*E [ (documento filho possui um documento pai e usuário autenticado é o subscritor do documento) OU (pode movimentar o documento filho) ]*

![image](https://user-images.githubusercontent.com/20362170/145212914-2f780cbc-3cfb-4e7f-9fd8-6a8689219595.png)

**Comment by ivangsilverio** [comment]
Prezado Dinarde,
    temos uma demanda na Prefeitura do Rio de Janeiro pedindo exatamente esta alteração.  É desta forma que outros sistemas operam, um exemplo é o Sistema Eletrônico de Informações  - SEI

**Comment by dinarde** [comment]
Regra aprovada em SP e seguirá para implementação e testes e Pull Request
