### ISSUE TITLE
sigarhlotacao - homologação - erro

### ISSUE THREAD

**Issue by robertodsm** [projeto-siga/siga#203]
(http://siga-hmg/sigarhlotacao/paginas/home.jsf)

Ao se selecionar a opção "Página Inicial" no menu "Siga", é exibida a seguinte mensagem:

Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

**Comment by kmacedovarela** [comment]
Alinhado com Marcos Fragoso, está sob análise do mesmo.

**Comment by kmacedovarela** [comment]
Resolvido pelo Marcos Fragoso.
