### ISSUE TITLE
Busca textual do Siga abrindo pop-up

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#205]
Busca textual do Siga abrindo pop-up, conforme ilustração abaixo:

![captura_de_tela_030215_121743_pm](https://cloud.githubusercontent.com/assets/4949149/6443513/2208a9c2-c0d6-11e4-8742-4138f12d049d.jpg)

**Comment by kmacedovarela** [comment]
@Chrystinne  identifiquei, poderia testar em homologação para verificar se o erro ocorre, antes que eu realize o deploy da versão corrigida (apenas para garantir) ?

**Comment by Chrystinne** [comment]
@kmacedovarela Só não consegui fazer a busca pelo mesmo do documento, já que eles estão em bases diferentes. Mas realizei a busca por outros documento, estando no Siga_SR, no ambiente de homologação, e não consegui reproduzir o erro.

**Comment by kmacedovarela** [comment]
Realizei as alterações nos commits 70dd7de5d5d102b7215aaf6f6d135b5ba8c8faec e 788483a1ab075d244f5ada1d55b2397c34df7fd0 . Assim que a versão for disponibilizada em produção, volto a pedir para você testar

**Comment by Chrystinne** [comment]
@kmacedovarela Blz

**Comment by kmacedovarela** [comment]
@Chrystinne  realizei o deploy da alteração, testei pelo IE e o erro não ocorreu. Caso volte a ocorrer favor reabrir a issue.
