### ISSUE TITLE
Erro na tela inicial do Siga - módulo Workflow

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#207]
![captura_de_tela_030315_103644_am](https://cloud.githubusercontent.com/assets/4949149/6463474/3083e406-c191-11e4-8485-3335527d7ff4.jpg)

**Comment by kmacedovarela** [comment]
Sabe reproduzir?

**Comment by kmacedovarela** [comment]
Ocorreu devido a manutenções de segurança na máquina. Voltaremos a fazer as manutenções no período da noite ou amanhã cedo.

**Comment by Chrystinne** [comment]
Pelo que conversei com o @Markenson, acredito que esses problemas estão associados ao carregamento dos módulos, então vou acrescentar este problema semelhante:

![captura_de_tela_030415_120303_pm](https://cloud.githubusercontent.com/assets/4949149/6486008/9c827354-c266-11e4-899b-9b42f06bad6c.jpg)

**Comment by Markenson** [comment]
Essa issue está relacionada ao problema da #134

**Comment by kmacedovarela** [comment]
Acabei de reiniciar o servidor e pode estar relacionado, mas vou deixar a issue aqui pois este comportamento não pode ocorrer independente do status dos servidores.

**Comment by Markenson** [comment]
@hodrigohamalho, como você está mais por dentro desse problema, assim que possível, dê uma prioridade a essa issue.

**Comment by kmacedovarela** [comment]
Os dois erros mencionados ainda ocorrem com vocês?

**Comment by Chrystinne** [comment]
O erro que está dando nesse momento é que ele não carrega as informações do Siga-GC

![captura_de_tela_030615_043333_pm](https://cloud.githubusercontent.com/assets/4949149/6534737/8aed1036-c41e-11e4-9521-976c3a49a0c7.jpg)

**Comment by Chrystinne** [comment]
Dando refresh na tela, ele carrega

**Comment by kmacedovarela** [comment]
[INFO] Esse erro ocorre quando o sigatp emite um erro, e por um motivo que não entendi ainda, influencia na exibição do sigagc. 
Para mitigar o problema vou separar a instância com os projetos sigatp e sigase (irá entrar em produção), que pertencem a outra equipe com o objetivo de o erro de um sistema não impactar no erro de outro.

**Comment by Chrystinne** [comment]
Está ocorrendo com o Siga-Sr também. Segue o print que tirei quando entrei agora no Siga. 

![captura_de_tela_030915_101216_am](https://cloud.githubusercontent.com/assets/4949149/6555458/0f34737a-c645-11e4-9903-5ee6dfb08c12.jpg)


Quando dei refresh, ficou ok.

**Comment by hodrigohamalho** [comment]
Sei o que é, irei corrigir.

Obrigado.

**Comment by hodrigohamalho** [comment]
Corrigido, se o erro voltar a acontecer favor reabrir essa issue. fce0b7086f5099ae37015ee585ee265f8aeb295f

**Comment by Chrystinne** [comment]
Vou reabrir a issue considerando não apenas o Siga-WF, mas quaisquer erros nos carregamentos dos módulos, ok?

![captura_de_tela_031015_102107_am](https://cloud.githubusercontent.com/assets/4949149/6575618/2b539a0c-c70f-11e4-8d71-ea822ac1ce92.jpg)

**Comment by kmacedovarela** [comment]
Ok, obrigada Chrystinne.

**Comment by hodrigohamalho** [comment]
Corrigido.
