### ISSUE TITLE
Erro ao assinar documentos (com capicom)

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#208]
O erro abaixo ocorre ao assinar documentos mesmo quando não está usando a assinatura java:

![image](https://cloud.githubusercontent.com/assets/2985140/6464551/bc4bf174-c199-11e4-9578-95b6b8e8857f.png)

**Comment by kmacedovarela** [comment]
Consegue reproduzir em homologação @Markenson ?

**Comment by kmacedovarela** [comment]
Ao inicializar o JBoss não carregou corretamente a biblioteca bc prov que está configurada como um módulo. Ao reiniciar, a assinatura com capicom funcionou normalmente
