### ISSUE TITLE
Erro de invalid license

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#209]
O erro de invalid license ocorre ao tentar carregar as licenças da extensão do editor de textos XStandard. Para solucionar, deve-se fazer o deploy dos arquivos que apresentaram erro 404 na imagem abaixo.

![image](https://cloud.githubusercontent.com/assets/2985140/6464666/8f1fb8d8-c19a-11e4-85a7-0e4f1d96e4e7.png)

**Comment by kmacedovarela** [comment]
A pasta foi obtida na spin, transformada em um pacote war, e disponibilizado em hmg e prod.
