### ISSUE TITLE
Permitir debug remoto nas máquinas de produção

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#210]
Verificar possibilidade de habilitar debug remoto, via eclipse, nas máquinas de produção.

**Comment by kmacedovarela** [comment]
Existe a possibilidade sim, irei te passar as configurações necessárias.

Atenciosamente,
Karina Macedo Varela  | JBoss Middleware Consultant

Cel: +55 61 8434-0656
PGP: 1F24 6737 9E63 D39D 69FF  91AA BBAE C760 5B99 60BE

Em 3 de março de 2015 11:54, Markenson <notifications@github.com> escreveu:

**Comment by kmacedovarela** [comment]
A configuração será documentada na wiki. O servidor não terá debug habilitado por padrão, caso seja necessário, deverão ser realizadas as devidas alterações.
