### ISSUE TITLE
Mapa da tramitação aparece gigante

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#212]
Acessando pelo endereço http://siga-antigo/sigaex/expediente/doc/exibir.action?sigla=JFRJ-EOF-2015/00119, o mapa no quadro Tramitação, à direita, aparece normal. Porém, pelo endereço http://siga/sigaex/expediente/doc/exibir.action?sigla=JFRJ-EOF-2015/00119, aparece grande demais. Testado no Chrome e no IE9.
![novo](https://cloud.githubusercontent.com/assets/5264319/6486881/c9f1ce4c-c26c-11e4-9fa9-867924cb5b16.png)
![antigo](https://cloud.githubusercontent.com/assets/5264319/6486883/cc3449a0-c26c-11e4-8fb3-6e5eea53780f.png)

**Comment by esredson** [comment]
Adriana notou ontem... Parece que nenhum de nós viu esse problema antes.

**Comment by kmacedovarela** [comment]
Verificando rapidamente, parece que o height e width  são calculados a cada vez que se acessa a página. (Exibe.jsp:550 em diante) 

   Será que algo foi alterado em algum destes commits? 
https://github.com/projeto-siga/siga/commits/master/sigaex/src/main/webapp/paginas/expediente/exibe.jsp

**Comment by esredson** [comment]
Talvez. André (@andresousa17), estou dando uma olhada nas alterações no exibe.jsp pra ver se alguma delas pode ter causado o problema.

**Comment by kmacedovarela** [comment]
Obrigada!!

**Comment by Markenson** [comment]
O erro parece estar relacionado à versão do jquery. Por ora, foi colocada uma instrução javascript nativa. (commit 9ac442d6b8f1b2a058fc2d4306d7c981240a961a)
