### ISSUE TITLE
Ambiente de desenvolvimento não relê JSP corretamente

### ISSUE THREAD

**Issue by crivano** [projeto-siga/siga#214]
Olá, sei que Karina e Rodrigo estão ocupados com os erros da produção, mas, quando for possível, gostaria que vocês tentassem resolver um problema que atrapalha bastante o desenvolvimento, principalmente quando se faz uma troca de branch.

Problema: alguns JSPs e TAGs não são recompilados pelo JBoss quando o git troca o branch.

Passo a passo: 
1) fiz a troca do branch
2) marquei todos os projetos no eclipse e mandei fazer "refresh"
3) fiz maven update project de todos os projetos
4) exclui todos os projetos do servidor (Add and Remove...)
5) fiz um clean
6) adicionei novamente os projetos
7) executei e notei que estava dando erro no JSP.
8) abri o arquivo JSP, acrescentei um espaço e salvei.
9) testei novamente e o JSP carregou normalmente.

Se o problema fosse em um JSP único, seria fácil de resolver. Mas, com todas das taglibs e todos os jsps que existem no sistema torna-se praticamente impossível e muito improdutivo.

Em tempo, já tentei a sugestão da Karina de alterar o standalone.xml conforme abaixo e não resolveu.

        <subsystem xmlns="urn:jboss:domain:web:1.5" default-virtual-server="default-host" instance-id="siga" native="false">
            <configuration>
                <jsp-configuration development="true" keep-generated="false" check-interval="1"/>
            </configuration>
         </subsystem>

Obrigado, Renato

**Comment by hodrigohamalho** [comment]
Parece muito ser bug do eclipse (com o plugin do maven) e a forma com que ele gerencia os deploys. 

Na verdade o eclipse gerência de forma muito ruim os deploys no application server, não há muito o que se tenha a fazer no JBoss além da configuração citada por você.

O que fiz aqui foi alterar os arquivos diretamente no diretório deployments do JBoss, por exemplo:
C:\Desenvolvimento\jboss-eap-6.2.3\standalone\deployments\siga.war (Altero o arquivo jsp aqui dentro) e sempre é recarregado.
Então provavelmente o que está acontecendo é o eclipse não estar reconhecendo que houve qualquer alteração no arquivo e não replicar pra pasta do JBoss assim o JBoss não enxerga nenhuma mudança neste arquivo (que de fato pra ele não teve mesmo).

O que podemos fazer é testar outras versões do eclipse, ou até mesmo outras alternativas como por exemplo o JBoss Developer Studio, Netbeans.. etc.

**Comment by kmacedovarela** [comment]
Verificar se isto pode ajudar:
https://access.redhat.com/solutions/18374

**Comment by crivano** [comment]
Esse problema era causado por haver duas taglibs diferentes com o mesmo identificador. Resolvi trocando de localhost/sigalibs para localhost/jeelibs.
