### ISSUE TITLE
Timeout das aplicações

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#215]
Foi apontado por um usuário que o timeout está menor que 30 minutos.

**Comment by hodrigohamalho** [comment]
https://access.redhat.com/solutions/283763

**Comment by kmacedovarela** [comment]
Alterado no web.xml das aplicações. Testei em localhost e aparentemente funcionou. No próximo deploy as aplicações deverão ser disponibilizadas já com esta correção.

**Comment by kmacedovarela** [comment]
Solicitado aumentar para duas horas.

**Comment by hodrigohamalho** [comment]
Na sexta-feira todos o horário das máquinas (system-time) de homologação e produção foram sincronizados. 
Fiz diversos testes tantos nos módulos normais quanto play e todos os timeouts funcionaram de forma esperada.
Logo acredito que antes de alterar o timeout pra 2 horas ou aumentar, deveria ser feita uma análise no ambiente das pessoas que estão reclamando do timeout pois parece ser um problema pontual para algum segmento de rede específico, logo se aumentar pra 2 ou 10 horas não importa eles vão continuar sendo deslogado de forma prematura...

**Comment by hodrigohamalho** [comment]
@Markenson algum usuário ainda continua reclamando disso?

**Comment by Markenson** [comment]
@hodrigohamalho Eu cheguei a conversar com o Bernardo na semana passada (da seção que estava reclamando) e ele disse que estava melhor. Será que somente a ataulização com NTp não foi suficiente?

**Comment by hodrigohamalho** [comment]
Hum, pode ter sido. Sistema também deu uma melhorada em relação a estabilidade, pode ter sido um dos fatores também...

Vou fechar a issue, se alguém voltar a reclamar a gente reabre e investiga isso mais a fundo.

**Comment by Markenson** [comment]
OK. Vamos providenciar o aumento do tempo de sessão?

**Comment by hodrigohamalho** [comment]
Acho que podemos aumentar pra 1 hora invés de ir direto pra 2, o que acha?

Dai entra no próximo release...

**Comment by Markenson** [comment]
Fica bom assim. Vamos colocar 1 hora.

**Comment by hodrigohamalho** [comment]
Done: f6ff8c992973a116bff31eda2ee28570a81e4c44

**Comment by Markenson** [comment]
@hodrigohamalho Vi que essas alterações foram feitas no web XML (então o timeout será por aplicação, certo?). Não seria melhor ser fosse feita uma configuração no jboss para que ficasse independente da aplicação?

**Comment by hodrigohamalho** [comment]
seria interessante mesmo, sei que sempre a aplicação pode sobrescrever o valor definido no servidor, mas desconheço uma forma de fazer isso no Jboss EAP 6. Vou dar uma pesquisada melhor ou até mesmo abrir um chamado pra ver como faz isso.

**Comment by crivano** [comment]
Vcs gostam mesmo de trabalhar, hein?! Até no sábado! :)
Em 11/04/2015 14:22, "Rodrigo Ramalho da Silva" <notifications@github.com>
escreveu:

**Comment by Markenson** [comment]
Pow, tava zerando meus e-mails... Não me liguei que Rodrigo era tarado. Sugestão: cuidado com ele. Kkkkkkkkkkk

**Comment by hodrigohamalho** [comment]
hauhuahua tem tempo ruim não !

**Comment by hodrigohamalho** [comment]
É realmente não é possível mais fazer essa configuração no JBoss EAP 6.2.3.

Ele até tem um timeout padrão de 30 minutos mas é Hard coded, já corrigiram isso mas só está disponível no EAP 6.4.
