### ISSUE TITLE
http://siga.corp.jfrj.gov.br/ ?

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#216]
Navegando pelo siga, vi em um conhecimento ( http://siga/sigagc/app/exibir?sigla=TRF2-GC-2014/00043 )  o seguinte link:
http://siga.corp.jfrj.gov.br/sigagc/app/exibir?sigla=TRF2-GC-2014%2F00010

Este link deve continuar válido @Markenson ?

**Comment by Chrystinne** [comment]
@kmacedovarela Sim, links nesse formato tem que funcionar. Na verdade, a gente não sabe exatamente como o pessoal que usa o Siga em órgãos exteriores configura o DNS. Pelo que estou vendo, essa é a forma como os usuários do TRF acessam. No ES, por exemplo, pode ser diferente.

**Comment by kmacedovarela** [comment]
Para resolver esse problema, será necessário alterar as propriedades tornando-as relativas:

Ex:
Antes:     <property name="idp.url" value="http://siga/sigaidp/"/>
Depois:   <property name="idp.url" value="http://siga/sigaidp/"/>

Vou realizar as alterações em produção, e quando os servidores forem reiniciados, a alteração passará a valer.

**Comment by kmacedovarela** [comment]
Aparentemente essa abordagem está com problemas no funcionamento com mais de uma instância, estou validando no ambiente de homologação antes de subir para produção.

**Comment by kmacedovarela** [comment]
A alteração precisa ser feita também no DC do SigaRH, logo, será necessário reiniciar todas as instâncias em um mesmo período (nao necessariamente ao mesmo tempo).
   Executarei esta modificação pela manhã quando o sistema tem menos usuários.

**Comment by kmacedovarela** [comment]
Resolvido.

**Comment by kmacedovarela** [comment]
Com a solução de #229,  amanhã realizarei novamente as alterações pela manhã.

**Comment by hodrigohamalho** [comment]
Essa issue já foi corrigida através da remoção da url do picketlink.xml, deixando somente a referencia para os contextos.
