### ISSUE TITLE
[Siga-Sr]Erro ao tentar criar Nova Solicitação

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#217]
Na página inicial do Siga, cliquei em "Nova" (Solicitação)

![captura_de_tela_031015_094719_am](https://cloud.githubusercontent.com/assets/4949149/6575130/9b0fec88-c70a-11e4-94a7-810ce7d2c520.jpg)

**Comment by kmacedovarela** [comment]
Vou verificar

**Comment by kmacedovarela** [comment]
@Chrystinne pode testar novamente?

**Comment by kmacedovarela** [comment]
Ocorreu devido a erro no DS.
