### ISSUE TITLE
Tarjas do workflow duplicadas

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#218]
As tarjas do workflow estão aparecendo duas vezes para alguns documentos.

Como reproduzir

Na página inicial, digite eof08 para acessar o documento.

Visualização do problema:

![image](https://cloud.githubusercontent.com/assets/2985140/6575552/7b004786-c70e-11e4-9c18-ff0eaeb32e60.png)

**Comment by kmacedovarela** [comment]
Deixo a versão ou volto para anterior sem a tarja?

**Comment by kmacedovarela** [comment]
Consegui reproduzir o erro com este documento.

**Comment by kmacedovarela** [comment]
Causa identificada.

**Comment by kmacedovarela** [comment]
Resolvido no commit acima, assim que possível realizaremos o deploy.

**Comment by kmacedovarela** [comment]
Deploy realizado
