### ISSUE TITLE
[Siga-WF] Relatórios do workflow não estão funcionando

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#220]
- Erro reportado por usuário no Siga-Sr (JFRJ-SR-2015/01524);

- Passo-a-passo do teste realizado:
   1. Acessar relatórios de Serviço Extraordinário, através do menu (Relatórios -> Apresentar métricas -> Serviço Extraordinário); 
   2. Preencher o formulário de Estatística de procedimento. Usei os seguintes dados:
     Procedimento iniciado de: 01/01/2014 até 01/01/2015
     Procedimento finalizado de: 01/01/2014 até 01/01/2015
     (mantive os demais dados)
   3. Clicar em Gerar relatório;

-Iustração do erro:
![captura_de_tela_031215_125223_pm](https://cloud.githubusercontent.com/assets/4949149/6621662/a859c65e-c8b6-11e4-93d2-4738594c593d.jpg)

- No Siga-antigo, o relatório é gerado corretamente, conforme ilustração:
![captura_de_tela_031215_125357_pm](https://cloud.githubusercontent.com/assets/4949149/6621694/da631164-c8b6-11e4-9f44-71d19adf0e00.jpg)

**Comment by kmacedovarela** [comment]
Favor testar em produção, não temos acesso.

**Comment by Chrystinne** [comment]
Não estou conseguindo testar. Acessando o link http://siga/sigawf/task.action, a opção "Relatórios" da barra de menu não está mais acessível pra mim, nem quando substituo outras lotações.

![captura_de_tela_031315_110213_am](https://cloud.githubusercontent.com/assets/4949149/6639713/a5588f3e-c970-11e4-8f7a-ce4d79361f66.jpg)

**Comment by hodrigohamalho** [comment]
@Markenson isso tem a ver com aquelas permissões que você esteve alterando?

**Comment by Markenson** [comment]
@hodrigohamalho estamos com algum problema nessa permissão. Estou vendo aqui e te aviso quando achar uma solução.

**Comment by Markenson** [comment]
Pra mim tb acontece isso...

**Comment by Chrystinne** [comment]
@hodrigohamalho Testei agora no Siga e o relatório foi gerado corretamente.

**Comment by hodrigohamalho** [comment]
fera, é a dependência do jasper duplicada, exclui ela no pom este erro não deve mais acontecer.
