### ISSUE TITLE
Erro no Campo de Busca

### ISSUE THREAD

**Issue by andresousa17** [projeto-siga/siga#221]
Quando pesquisamos um documento na produção na página principal http://siga/siga/principal.action
o campo de busca funciona.

Pesquisa do documento TMP1414611

![image](https://cloud.githubusercontent.com/assets/5269936/6622220/2f2b4e48-c8ba-11e4-9c5c-0c14e84eae1f.png)

Quando pesquisamos dentro do módulo sigaex não funciona. 

Ex: Na página http://siga/sigaex/expediente/doc/listar.action?primeiraVez=sim a pesquisa do documento TMP1414611

![image](https://cloud.githubusercontent.com/assets/5269936/6622314/a1a6cb28-c8ba-11e4-9e56-b28d89aed2f7.png)

Eu verifiquei que a url utilizada na pesquisa na tela inicial é

http://siga/siga/generico/selecionar.action?propriedade=buscar_generico&sigla=TMP1414611&idp=null

e na tela dentro do sigaex fica sem o parâmetro idp

http://siga/siga/generico/selecionar.action?propriedade=buscar_generico&sigla=TMP1414611

**Comment by hodrigohamalho** [comment]
Não estou conseguindo reproduzir, vou procurar o @andresousa17 para me ajudar.

**Comment by hodrigohamalho** [comment]
Consegui resolver aqui, esse erro já foi solucionado mas o deploy ainda não foi feito em produção. Será realizado amanhã pela manhã.
