### ISSUE TITLE
Erro ao fazer Logoff pela página do SigaSr

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#222]
Procedimento:
-Entrar no SigaSr (http://siga/sigasr/solicitacao/editar);
-Clicar em Loggof pelo Menu principal do Siga.

Obs.: No Siga-antigo esse erro não ocorre.

**Comment by hodrigohamalho** [comment]
Este erro parece ser intermitente.

Tem um outro erro conhecido que talvez possa ter sido esse fluxo, que é o seguinte:
1. Entra no siga
2. Entra no sigasr
3. Entra no sigaex
4. Alguém faz o undeploy do sigasr
5. Usuário clica em logout a partir do sigaex
6. A aplicação vai chamar o Global Logout que consiste em ir em cada contexto que já foi aberto (siga/sigasr/sigaex) e efetuar um logout.
7. Porém quando chega no módulo que estiver indisponível ele não conseguirá chamar a url de logout como consequência o fluxo será interrompido e o logout não será efetuado.

Vou fechar a issue caso o erro volte a acontecer favor reabrir.
