### ISSUE TITLE
Remover ou alterar a land page do siga

### ISSUE THREAD

**Issue by hodrigohamalho** [projeto-siga/siga#227]
http://siga

Cai na página do welcome-root do Jboss, não acho que seja interessante isso principalmente em produção.

**Comment by kmacedovarela** [comment]
Habilitado em homologação. Amanhã cedo vou verificar em produção.

**Comment by kmacedovarela** [comment]
Para habilitar foi necessário configurar o proxy pass no apache e configurar o enable-welcome-root do virtual server do jboss como falso.

**Comment by kmacedovarela** [comment]
Verificar o comportamento em HMG
