### ISSUE TITLE
Apache: problema com logs

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#228]
@Andredsf favor solucionar o problema que está ocorrendo no apache:

O diretório de logs mais uma vez está quase em 100% e isso provavelmente está influenciando no funcionamento do serviço. Está uma demanda prioritária.

**Comment by Andredsf** [comment]
O problema estava no log dos modulos deflate e cache do apache. 
Os dois foram desabilitados.

**Comment by hodrigohamalho** [comment]
@Andredsf desabilitados? Creio que seja importante as informações de error gerado por estes logs, então acho que o mais correto seria alterar o loglevel dos módulos em questão pra ERROR ou WARN.

**Comment by Andredsf** [comment]
Não !! farei a configuração de logrotate que é uma outra tarefa, fechei este chamado pq problema do indicado foi resolvido.
