### ISSUE TITLE
Problemas intermitentes no campo de busca

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#229]
Diversos usuários estão reclamando que a busca pelo número do documento (no campo superior direito) às vezes funciona e às vezes não. Precisamos fazer testes exaustivos para garantir que essa caixa funcione 100% das vezes. 

Não sei se pode ser a causa, mas percebi que as reclamações vieram de pessoas que estão em redes mais distantes que o padrão (Brasília e São Cristóvão). Precisamos fazer testes para garantir que essa busca não está sendo afetada pela latência da rede.

**Comment by Markenson** [comment]
Percebi também que quando há um espaço ele não consegue fazer a busca. Talvez falte um trim.

**Comment by Markenson** [comment]
Acabamos de receber do usuário o feedback do usuário dizendo que o siga-antigo está funcionando ok.

**Comment by kmacedovarela** [comment]
Procede, consegui reproduzir inclusive no chrome. Estou tentando identificar um fluxo que o erro sempre ocorra pra facilitar a rastreabilidade da causa.

**Comment by kmacedovarela** [comment]
Como reproduzir:
Atualizar a pagina algumas vezes, o resultado fica intermitente. 

http://siga/siga/generico/selecionar.action?propriedade=buscar_generico&sigla=JFRJ-SR-2015/00275&idp=sLfVz58M-exuJYdcMy9-J4%2BP.acadia%3Asigadoc-server03

**Comment by kmacedovarela** [comment]
O mesmo comportamento pode ser reproduzido em hmg
http://siga-hmg/siga/generico/selecionar.action?propriedade=buscar_generico&sigla=JFRJ-SR-2015/00054

**Comment by hodrigohamalho** [comment]
Entendido, resolverei!

**Comment by Markenson** [comment]
Mais detalhes do usuário:

"O problema acontece várias vezes em momentos diferentes ao longo do dia, seja com texto copiado e colado (de txt, de doc, de pdf ou do próprio Siga) seja digitando o número do expediente. Depois de dar enter ou de clicar na lupa, o que foi digitado ou colado some do campo e nada acontece. Então fico digitando ou colando o número do expediente até que de repente o sistema responde."

**Comment by kmacedovarela** [comment]
Procede.

**Comment by kmacedovarela** [comment]
Ainda está com o problema da busca com espaço

**Comment by hodrigohamalho** [comment]
Esse eu não corrigi ainda. Vou ver se mato hoje.

**Comment by kmacedovarela** [comment]
Voltou a ocorrer, é possível reproduzir em homologação

**Comment by hodrigohamalho** [comment]
vou verificar.

**Comment by hodrigohamalho** [comment]
A alteração da issue #216 quebrou essa correção.

Vou gerar um hotfix com a correção.

**Comment by hodrigohamalho** [comment]
https://github.com/projeto-siga/siga/tree/hotfix-4.0.3.3

Hotfix gerado.

**Comment by kmacedovarela** [comment]
Implantado

**Comment by kmacedovarela** [comment]
Ainda ocorre. Ate que se resolva o problema de maneira definitiva, uma sugestão do @Markenson  foi verificar a possibilidade de liberar o acesso a URL chamada pelo campo de busca,  uma vez o que o retorno da mesma é uma string que só é processada posteriormente para a recuperação dos dados em si.

**Comment by crivano** [comment]
Perfeito. Se o retorno não contiver a descrição, apenas a sigla do documento, melhor ainda. Poderá ficar para sempre como uma url pública.

**Comment by hodrigohamalho** [comment]
ótimo! farei aqui

**Comment by kmacedovarela** [comment]
@hodrigohamalho isso foi corrigido correto?

**Comment by hodrigohamalho** [comment]
Foi sim: cf9d523acebec96ea22bad9dd19e4d1d5e69f9d8
porém ainda não foi disponibilizado, amanhã faço isso.

**Comment by hodrigohamalho** [comment]
Feito, está em homologação e dev. Entrará em produção no próximo deploy.

**Comment by Markenson** [comment]
Não está funcionando em produção.

**Comment by kmacedovarela** [comment]
Testei com o documento TMP-1479811	 e funcionou markenson. O que está ocorrendo é o caso intermitente, ou nunca está funcionando?

**Comment by kmacedovarela** [comment]
Segundo informado pelo @Markenson 

1) A forma reduzida não funciona "mem01" mas a completa sim "JFRJ-MEM-2015/00001"
2) Do siga sr nada funciona, nem a completa. ex:  JFRJ-SR-2015/02727

**Comment by kmacedovarela** [comment]
@Markenson isso está ok? Podemos fechar a issue?

**Comment by Markenson** [comment]
Está OK. Pode fechar.

**Comment by hodrigohamalho** [comment]
João reproduziu em produção...

**Comment by kmacedovarela** [comment]
@Markenson você tem algum posicionamento a respeito da ocorrência deste erro?

**Comment by Markenson** [comment]
1. Na produção não tem havido reclamações. 
2. Na classec250 tem ocorrido com um pequena frequência.
