### ISSUE TITLE
Apache externo

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#231]
É necessario configurar o apache para acesso via internet.

**Comment by kmacedovarela** [comment]
@crivano e @Markenson ,

   Alinhando internamente com a equipe de mentoring, chegamos a conclusão de que no cenário atual seria interessante mantermos a própria naked, apenas ajustando as configurações para se adequar ao novo ambiente. 
   Não temos o intuito de parar o serviço (e virar a chave) até que todas as configurações estejam finalizadas, ou seja, a atuação não impactaria na disponibilidade do siga para a web.

Vocês tem alguma restrição com relação a esta decisão?

**Comment by Markenson** [comment]
Não há restrições em manter o serviço web na Naked. O importante é que durante o processo de configuração o serviço se mantenha disponível. Caso isso não seja possível, favor nos comunicar com  antecedência qualquer indisponibilidade prevista.

**Comment by hodrigohamalho** [comment]
A máquina foi entregue?

**Comment by kmacedovarela** [comment]
Ainda não.

Atenciosamente,
Karina Macedo Varela  | JBoss Middleware Consultant

Cel: +55 61 8434-0656
PGP: 1F24 6737 9E63 D39D 69FF  91AA BBAE C760 5B99 60BE

2015-03-30 14:53 GMT-03:00 Rodrigo Ramalho da Silva <
notifications@github.com>:

**Comment by hodrigohamalho** [comment]
O apache foi configurado.
Como teste inicial apontamos para os JBoss de homologação até que a gente garanta que tudo está funcionando como deveria nesse apache.

Pedimos que a equipe do siga efetue os testes nesse apache para que possamos finalmente apontar para o JBoss de produção, segue o link:

http://belina.jfrj.jus.br/

**Comment by hodrigohamalho** [comment]
@Markenson poderia testar novamente a assinatura?

**Comment by kmacedovarela** [comment]
@hodrigohamalho como está isso? Está finalizado?

**Comment by hodrigohamalho** [comment]
todos os bugs reportados foram resolvidos a única pendencia que existe é o apontamento dos nomes "siga-hmg" para "sigat", não conseguiremos manter os dois.
Como está tendo um treinamento, combinamos de fazer isso na quinta. Lembrando que após essa alteração o siga-hmg irá parar de funcionar.

**Comment by kmacedovarela** [comment]
Issues relacionadas. #254

**Comment by hodrigohamalho** [comment]
5b693f6ce47d86d6eae35db5264775237b1bc818

**Comment by kmacedovarela** [comment]
Ambiente de produção: OK. Nenhum erro foi reportado até o momento.

Ambiente de homologação: Aguardando decisão da infra sobre como será externalizado o ambiente de homologação.

**Comment by kmacedovarela** [comment]
Segundo testes realizado pela equipe, ambos os ambientes estão acessiveis e funcionando externamente. Qualquer alteração por parte da infra no funcionamento da arquitetura será avisado.
