### ISSUE TITLE
[Apache] Configuração cache/deflate

### ISSUE THREAD

**Issue by hodrigohamalho** [projeto-siga/siga#232]
A configuração do mod cache precisa ser revista tanto em homologação quanto em produção, pois os arquivos de css e javascript não estão sendo cacheados e/ou "gzipados" de forma adequada.

Considero isso prioritário tento em vista que tem regiões do Brasil que tem o link de acesso limitado ao siga (ex: Brasília).

**Comment by AndDeluiz** [comment]
Pessoal, fiz as alterações pertinentes nos arquivos de configuração de mod_cache e mod_deflate no ambiente de HMG. Fiz alguns testes com sucesso. Como não tenho conhecimento de uso do sistema, peço que testem se tudo está funcionando corretamente para depois passarmos para produção.
Enquanto isso vou deixar esse issue aberto para acompanhamento.

**Comment by hodrigohamalho** [comment]
@Markenson acha que isso é um caso pra um hotfix mais pro fim da semana?

**Comment by hodrigohamalho** [comment]
@Markenson ping.

**Comment by Markenson** [comment]
@hodrigohamalho e @AndDeluiz,

Fiz uns testes rápidos e parece estar tudo ok na HMG. Podem aplicar em produção.

**Comment by AndDeluiz** [comment]
@Markenson, tentei reproduzir o bug do PDF em HMG e não consegui com as suas instruções. O documento retornado sempre é o mesmo.
Temos como pedir para que o usuário tente reproduzir em HMG? Há disponibilidade do mesmo documento no ambiente HMG?

**Comment by Markenson** [comment]
@AndDeluiz Não temos disponibilidade do mesmo documento em HMG. Podemos combinar de ativar em produção por um período específico e verificarmos se há alguma incidência de chamados (limpando o cache do apache antes para evitar algum problema). O que acha?

**Comment by AndDeluiz** [comment]
@Markenson Podemos seguir por essa linha de atuação sem nenhum problema. Seria interessante verificar a disponibilidade do usuário que foi afetado e fazer um teste conjunto. Vou lhe procurar para falarmos sobre o assunto.

**Comment by AndDeluiz** [comment]
@Markenson, só para alinhar, vamos subir as configurações em PROD novamente no dia 20/04 as 9:00 e acompanhar o funcionamento. Podemos seguir com essa agenda ?

**Comment by Markenson** [comment]
Sim.

**Comment by AndDeluiz** [comment]
Depois dos problemas acontecidos em 20/04, após ativação das configurações, estou analisando os dados coletados. Já verifiquei que uma configuração efetuada não estava considerando a query string em métodos GET. Acertei essa configuração hoje em HMG e vou acompanhar. Em paralelo, continuo analisando os dados coletados.

**Comment by AndDeluiz** [comment]
**UPDATE**

Analisei os dados capturados e tudo certo no tráfego entre a máquina do usuário e o servidor Apache. Não existem erros, então o problema realmente é de configuração.
A alteração nas configurações feita em HMG segue em funcionamento sem nenhuma reclamação. O cache no servidor Apache agora guarda os objetos associando também a *query string*.

![image](https://cloud.githubusercontent.com/assets/5882479/7501909/34f7c73c-f40e-11e4-8fd7-7459f640aa6a.png)

@Markenson, poderia conduzir testes com assinatura de documentos para ver se o problema ocorrido em PROD se repete em HMG após essa configuração ?

**Comment by AndDeluiz** [comment]
Sobre o problema no qual o IE9 não faz cache de objetos CSS, HTML, PNG, dentre outros, mesmo o Apache estando configurado para fazer cache destes objetos, verifiquei que no novo ambiente EAP 6 sempre vem no **RESPONSE** HEADER a diretiva **Cache-Control: no-cache**, assinalada pelo ambiente EAP 6. @hodrigohamalho está verificando se a inserção dessa diretiva é feita pela aplicação ou pelo JBoss.
Assim, o IE9 interpreta corretamente o cabeçalho enviado pois utiliza a API WinInet. Essa API atua como um intermediário (proxy) entre origem e destino e, portanto, deve interpretar a diretiva Cache-Control. Ver: https://msdn.microsoft.com/en-us/library/windows/desktop/aa383928(v=vs.85).aspx.
O Chrome não utiliza esta API com este fim, por isso funciona corretamente.

**Comment by hodrigohamalho** [comment]
Vendo com o @AndDeluiz o comportamento do Apache x Aplicação, foi verificado que os cabeçalhos:

* Cache-control
* Expires

Estão sendo inseridos pela aplicação SIGA. Isso faz com que ocorra mal funcionamento do mecanismo de cache. Tem que analisar onde e quem está setando essas propriedades e forçar sua remoção.

**Comment by AndDeluiz** [comment]
Obtivemos progresso com testes do mecanismo de cache com o IE9.

* Retiramos o cabeçalho ETag quando é utilizado o mod_deflate.
* Reinicializamos os valores para o cabeçalho Cache-control, descartando o que o JBoss envia e atribuindo max-age e private para Cache-control.

Com essas medidas conseguimos fazer com que o IE9 tivesse o comportamento esperado. Precisamos analisar agora o uso do Cache-control detectando onde ele é inserido pela aplicação e alterando quando necessário para que a manipulação não seja feita arbitrariamente pelo Apache.

**Comment by hodrigohamalho** [comment]
Identifiquei que os parâmetros:
* Cache-control: no-cache 
* Prama: no-cache 

Estão sendo inseridos pelo Picketlink. Vou verificar a possibilidade de remove-los.

**Comment by hodrigohamalho** [comment]
Acho que é problema de interpretação da especificação do SAML 2 pelo time do picketlink, veja a especificação: http://docs.oasis-open.org/security/saml/Post2.0/sstc-saml-binding-simplesign-cd-04.html
```
HTTP proxies and the user agent intermediary should not cache SAML protocol messages. To ensure this, the following rules SHOULD be followed.
When returning SAML protocol messages using HTTP 1.1, HTTP responders SHOULD:
Include a Cache-Control header field set to "no-cache, no-store".

Include a Pragma header field set to "no-cache".

There are no other restrictions on the use of HTTP headers.
```

Porém esse filter deles inclui esse cabeçalho em todo request.

**Comment by hodrigohamalho** [comment]
Abri um chamado junto ao suporte da Red hat: #01444151

**Comment by Markenson** [comment]
Boa!

**Comment by Andredsf** [comment]
Form alteradas as configurações no arquivo mod_cache.conf.

CacheIgnoreCacheControl Off
CacheIgnoreNoLastMod Off

e foram comentadas as opções mod_deflates.conf

   #Header set Cache-Control "max-age=3600, public"
   #Header unset Etag
   #Header unset Expires

O resultado desta ação demostrou que apenas no browser Chrome o processo ocorre corretamente.

**Comment by AndDeluiz** [comment]
O uso concorrente dos módulos não produz o efeito esperado das funcionalidades devido a manipulação dos cabeçalhos pelos módulos.
A solução encontrada e que produziu os efeitos esperados foi a ativação do mod_cache no servidor Apache HTTP e a compressão de dados (gzip) nos servidores de aplicação JBoss. As configurações encontram-se em testes no ambiente HMG.
