### ISSUE TITLE
Erro no template de documento

### ISSUE THREAD

**Issue by hodrigohamalho** [projeto-siga/siga#233]
Ao acessar a seguinte url em homologação: http://siga-hmg/sigaex/expediente/doc/exibir.action?sigla=TMP-475557

Dispara o seguinte erro:
![bug sigaex](https://cloud.githubusercontent.com/assets/252998/6789224/9f18be72-d17d-11e4-918b-95b18a0ea1cc.PNG)

Caso não seja realmente um bug pode fechar a issue.

**Comment by kmacedovarela** [comment]
@Markenson  ou @crivano  essa issue procede ou pode ser fechada?

**Comment by Markenson** [comment]
@hodrigohamalho e @kmacedovarela não é um bug.
