### ISSUE TITLE
Atualizar propriedades do jboss no docker

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#234]
É necessário atualizar a imagem do docker, com as novas propriedades para corrigir o problema descrito em #216

**Comment by kmacedovarela** [comment]
O arquivo /opt/docker/build/siga-appserver-standalone/opt/jboss/sigadoc/configuration/standalone.xml foi atualizado. @AndDeluiz  poderia gerar uma nova imagem ?

**Comment by AndDeluiz** [comment]
@kmacedovarela imagem atualizada com ID build-00024.
Me avise quando deseja que seja executada.
