### ISSUE TITLE
Fechar recursos no projeto inteiro

### ISSUE THREAD

**Issue by hodrigohamalho** [projeto-siga/siga#235]
É necessário procurar por todas as referências de objetos que após o uso deverão ser fechados no código de preferência em blocos finally.

Exemplo de objetos:
* ByteArrayOutputStream
* File

São raríssimos as vezes que esses objetos são liberados no código, isso pode deixar esses objetos inelegíveis para coleta de lixo, causando memory leak.

**Comment by crivano** [comment]
File em si não precisa ser fechado. Output e Input Streams foram revistos. ByteArray Streams não precisam ser fechadas.

**Comment by raphaelpaiva** [comment]
@crivano desculpa abrir de novo, mas sou cético nesses casos. Não custa fechar. O Garbage Collector nem sempre é confiável, além de que, fechando sempre liberamos recursos e previnimos leaks. Principalmente com arquivos, que podem causar locks...

**Comment by crivano** [comment]
@raphaelpaiva , só não estou fechando os ByteArrayInputStream, esses não usam arquivos nem fazem nenhum tipo de lock.
