### ISSUE TITLE
SR- Usuário com permissão em uma lista de prioridades de consulta não consegue visualizar a lista

### ISSUE THREAD

**Issue by jmolivei** [projeto-siga/siga#2355]
Cenário informado.

![image](https://github.com/projeto-siga/siga/assets/5268745/f55554eb-f0d1-456a-a7b2-a6d78767046c)

Com essas permissões o usuario poderia consultar a lista abaixo

![image](https://github.com/projeto-siga/siga/assets/5268745/9aa67181-b3ec-4bea-ae8a-ae02470573ed)

mas ao tentar consultar a lista posicionando o cursor no nome da listagem ele não fica habilitado para clique

![image](https://github.com/projeto-siga/siga/assets/5268745/0728aeac-033c-4547-87cd-c4507a035e0f)

ou se tentar atraves do link conhecido passado por quem criou a lista - https://siga.jfrj.jus.br/sigasr/app/solicitacao/exibirLista/1547

![image](https://github.com/projeto-siga/siga/assets/5268745/f531dda3-da2b-442b-86d7-10175363c9f0)

**Comment by cassioaugusto01** [comment]
Bug corrigido.
Telas demonstrando a visualização da lista funcionando corretamente.

Menu:
![0  - menu](https://github.com/projeto-siga/siga/assets/37603843/0bff43c8-5d55-4e2b-8ad2-e3470ccb7404)

Pesquisa de listas sendo exibida
![1 - pesquisa de listas sendo exibida](https://github.com/projeto-siga/siga/assets/37603843/f039128c-f8d6-46bb-a44a-cd625bfd667a)

Usuario em uma lotação que possui permissão consegue ver a lista
![2 - usuario da cosadm consegue ver a lista](https://github.com/projeto-siga/siga/assets/37603843/b1a252ff-75bc-4442-bdb5-8c713a638cdb)

Lista em modo de edição
![3 - lista em modo de edição](https://github.com/projeto-siga/siga/assets/37603843/29bdf6e4-b9b0-439c-ad68-3aff5059b357)

Permissões sendo exibidas corretamente
![4 - permissões sendo exibidas corretamente](https://github.com/projeto-siga/siga/assets/37603843/1c8a1d0a-2737-4348-8d7e-ba699df1bb56)
