### ISSUE TITLE
Inicializar cache no startup da aplicação

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#236]
No sigasr e sigagc, inicializar o cache no startup da aplicação, e não no primeiro acesso.

**Comment by hodrigohamalho** [comment]
Não foi possível fazer isso usando CDI porque o play tem sua própria gerência. Tem que estudar como fazer isso da maneira PLAY, talvez seja melhor deixar isso de lado tendo em vista que os projetos estão sendo migrado pra Vraptor.

**Comment by kmacedovarela** [comment]
Deverá ser analisado após migração das aplicações para vraptor.
