### ISSUE TITLE
GC-Erro ao listar lotação na pesquisa de conhecimentos

### ISSUE THREAD

**Issue by jmolivei** [projeto-siga/siga#2364]
Cenário de erro na visualização antes da correção

![image](https://github.com/projeto-siga/siga/assets/5268745/2beb618a-9d5b-4059-8664-31c8bb663a4d)

**Comment by MLSalesSantos** [comment]
Foi realizada a alteração na classe listar.jsp
na linha 87 onde exibia lotação inicial foi alterada para lotação 

![tela com a modificação realizada](https://github.com/projeto-siga/siga/assets/36673210/f509a8ca-674b-4aa2-96e9-184a4c5d2ad7)
