### ISSUE TITLE
Transformar o siga-busca-textual em módulo

### ISSUE THREAD

**Issue by hodrigohamalho** [projeto-siga/siga#237]
Conforme discutimos via email ficou decidido que o siga-busca-textual deveria ser configurado como módulo.

Atualmente o mesmo está como uma dependência opcional no pom.xml do projeto sigaex.

**Comment by kmacedovarela** [comment]
Tinha um módulo criado nas máquinas de homologação que não estava funcionando. Comentei a linha do textual, que continua disponibilizado como jar.

**Comment by hodrigohamalho** [comment]
Configuração feita.
