### ISSUE TITLE
Analisar o gc.log dos servidores em produção

### ISSUE THREAD

**Issue by hodrigohamalho** [projeto-siga/siga#238]
Já temos uma semana de gc.log. Tem que recolher e analisar esses logs pra verificar como está a gerência de memória principalmente nas aplicações mais críticas (sigaex).

**Comment by kmacedovarela** [comment]
Os logs de algumas instâncias não estão sendo devidamente coletados, vou ajustar estas configurações para que a analise seja possível.

**Comment by kmacedovarela** [comment]
Foi habilitado o log apenas no servidor do sigaex em uma das máquinas de produção. O problema é que sempre que o servidor é reiniciado, o log é sobrescrito. (No cenário **atual**, isso é crítico).
Foi aberto um chamado no access para verificar as devidas possibilidades.

**Comment by kmacedovarela** [comment]
Sobre o gc.log ser sobrescrito ao reiniciar o server: https://access.redhat.com/solutions/1325293
