### ISSUE TITLE
O número da versão nã oestá sendo exibida na página inicial

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#239]
Provavelmente passou a ocorrer depois que que a página de login passou para o siga-idp. Isso é feito por um plugin no pom.xml

![image](https://cloud.githubusercontent.com/assets/2985140/6927033/f2510844-d7c0-11e4-9fb2-60796230edcf.png)

**Comment by kmacedovarela** [comment]
Entrou no branch develop hoje.

**Comment by Markenson** [comment]
Valeu! Nem tive tempo de ver! :)
