### ISSUE TITLE
[Crítico] Alteração na solução de cache

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#241]
Conforme conversa iniciada por e-mail, é necessário que a equipe tome providência a respeito do seguinte item :

   Gargalo na aplicação que possivelmente é uma das causas das quedas do sigaex quando com muitos usuários simultâneos. 

**br.gov.jfrj.siga.cp.bl.CpConfiguracaoBL:130**
private **synchronized** void atualizarCache(Long idTipoConfig) {

   Este método está gerando lock em diversas threads, aumentando o consumo de CPU, e por consequência causando lentidão e até indisponibilidade do serviço.é necessário tomar alguma providência a respeito do funcionamento deste método.

**A seguinte atualização foi realizada segundo solicitação de @crivano  **
13760f20b4d2d1276f46a10bcbdc89cc401d73df

Informação extra:
Exemplo de log exibido quando a instância do sigaex atinge um alto consumo de CPU por muito tempo, fica lento, e *cai*:
````
15:28:58,495 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper) ARJUNA012117: TransactionReaper::check timeout for TX 0:ffff0a0a0048:-5373dc95:551b1e01:12e1e in state  RUN
15:28:58,501 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper Worker 0) ARJUNA012095: Abort of action id 0:ffff0a0a0048:-5373dc95:551b1e01:12e1e invoked while multiple threads active within it.
15:28:58,502 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper Worker 0) ARJUNA012108: CheckedAction::check - atomic action 0:ffff0a0a0048:-5373dc95:551b1e01:12e1e aborting with 1 threads active!
15:28:58,502 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper Worker 0) ARJUNA012121: TransactionReaper::doCancellations worker Thread[Transaction Reaper Worker 0,5,main] successfully canceled TX 0:ffff0a0a0048:-5373dc95:551b1e01:12e1e
````

**Comment by Markenson** [comment]
@kmacedovarela o que você acha de logarmos o idTipoConfig para saber se ocorre somente com um tipo? Pergunto isso porque pode ser que um determinado tipo demore mais do que outros para serem atualizados no cache. Se isso for verdadeiro, podemos verificar se realmente é necessária a presença desse tipo no cache.

**Comment by kmacedovarela** [comment]
Foi alinhado em conversa com @Markenson , que deverá ser incluido um trecho no código para tentar logar o id do tipo de conf e o id da thread

**Comment by kmacedovarela** [comment]
Senhores, está acontecendo um comportamento que acredito que não seja esperado: o método synchronized está sendo chamado duas vezes e executando todo o procedimento para qualquer alteração de configuração.

Como reproduzir (com debug e breakpoint no método em questão é possivel verificar o comportamento claramente):
1. Logar no siga, e acessar a tela de configuração de permissões
2. O método será invocado.
3. Acessar a tela inicial
3. O método será invocado novamente e realizará a mesma quantidade de alterações.

**Comment by crivano** [comment]
Precisaremos realmente rever todos os lugares onde o cache é invalidado. Pesquisei no código e achei vários lugares onde isso é feito sem que haja necessidade. 

Acredito que a solução ideal seja criar um método que grava uma configuração e já disponibiliza ela no cache. Dessa forma, reler o cache seria realizado apenas como o primeiro passo do ThreadFilter, e nunca ocorreria dentro do escopo de uma transação.

Essa alteração é grande e o teste é bem complexo. @Markenson , você acha que devemos fazer isso logo ou podemos aguardar para fazer direto na versão com VRaptor?

**Comment by Markenson** [comment]
@crivano Acho melhor aguardar, pois fazer um merge disso pode ser bem complicado. O que acha de avaliarmos se os recursos de cache disponíveis pelo próprio servidor de aplicação nos atenderia? Se for viável, remover esse código de dentro do nosso sistema certamente tornaria o sistema mais robusto.

**Comment by crivano** [comment]
A princípio, acho que serializar e deserializar todos esses objetos, em
todas as chamadas, deve ser desnecessariamente lento. A questão da rotina
síncrona está aí apenas para evitar que vários threads façam a mesma
operação desnecessariamente. Poderíamos remover o lock, se fosse o caso,
mas tenho a impressão que usar o cache do JBoss será ainda mais custoso.

2015-04-28 21:49 GMT-03:00 Markenson <notifications@github.com>:

**Comment by Markenson** [comment]
@crivano  Concordo que serializar/desserializar é um custo. Mas já que vamos ter que mexer nisso (e é complexo) seria bom termos certeza se isso é mesmo um problema antes de descartar a possibilidade, pois pode ser que a ferramenta tenha algo otimizado para essas operações ou talvez algum recurso interessante que desconhecemos. Talvez o @hodrigohamalho e @kmacedovarela tenham o caminho das pedras pra dizer se vale à pena ou não.

Sem o lock provavelmente o erro não existiria, mas acho que o cache vai ficar inconsistente se simplesmente o removermos do código atual. Na verdade, independente do tipo de cache que estivermos utilizando (solução própria ou do servidor) acho que se encontramos uma solução sem usar o lock já deve melhorar muito.

**Comment by crivano** [comment]
@Markenson , concordo que não devemos descartar a possibilidade.

Me parece que o maior problema está na recarga do cache durante uma operação. Algo que acontece, tipicamente, quando gravamos uma nova configuração e precisamos que o cache esteja atualizado para que possamos prosseguir com o processamento. Isso pode ser evitado se, ao gravar a configuração já pudermos incluí-la no cache instantaneamente. Nesse caso, não haveria lock e nem mesmo na próxima solicitação seria atualizado o cache. A atualização do cache só ocorreria quando outra instância do JBoss percebesse que seu cache está defasado, mas isso ficaria no ThreadFilter e antes de iniciar uma transação de BD.

Se o cache estiver serializado e precisarmos atualizá-lo no meio de um request, acredito que será ainda mais complicado. Ou seja, de qualquer forma, quer serializemos ou não, penso que precisaremos ser capazes de incluir ou excluir uma configuração do cache pontualmente e no meio de um request.

Que tal implentarmos isso e depois avaliarmos se já foi o suficiente para resolver ou se precisaremos melhor ainda mais?

**Comment by Markenson** [comment]
ok.

**Comment by crivano** [comment]
@Markenson , podemos fechar esse issue?

**Comment by Markenson** [comment]
@crivano Por mim sim.
