### ISSUE TITLE
Exibição com formatação incorreta de documento

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#246]
Pessoal, segue erro reportado por usuário. 

O layout da página fica quebrado quando exibido determinado documento. Ocorre também no siga-antigo.

http://siga-antigo/sigaex/expediente/doc/exibir.action?sigla=TRF2-PAR-2015/00137
http://siga/sigaex/expediente/doc/exibir.action?sigla=TRF2-PAR-2015/00137

**Comment by Markenson** [comment]
Esse problema foi causado pois o usuário provavelmente copiou e colou o conteúdo de um editor de textos avançado (word, por exemplo). O usuário deveria ter copiado e colado para o bloco de notas para remover a formatação. Como o PDF está correto, essa issue será encerrada.
