### ISSUE TITLE
Apache externo ambiente de homologação

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#247]
Verificar melhor estratégia para disponibilizar externamente o ambiente de homologação. Hoje a maquina azera serve como apache interno e externo da maquina sigat.

**Comment by hodrigohamalho** [comment]
acho que podiamos fazer pela naked também

**Comment by kmacedovarela** [comment]
Apenas uma observação: esse ambiente não necessita de autenticação como o ambiente de produção, quando acessado externamente.

**Comment by kmacedovarela** [comment]
Esclarecimento: o apache do ambiente de homologação nao tem autenticação com certificado, como por exemplo na naked.

**Comment by hodrigohamalho** [comment]
Feito: http://sigat.jfrj.jus.br
