### ISSUE TITLE
Configurar url do sigarh-ajuda em desenvolvimento

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#248]
É necessário acrescentar a URL do sigarh-ajuda na imagem do apache do ambiente de desenvolvimento (está com mod_proxy).

contexto: sigarhajuda
sistema: sigarh

**Comment by kmacedovarela** [comment]
Já fiz a alteração no arquivo  /opt/docker/build/siga-webserver-standalone/etc/httpd/conf.d/sigarh.conf
É necessário apenas gerar nova imagem do webserver e subir.

**Comment by AndDeluiz** [comment]
Imagem gerada com novas configurações e contêiner ativado.
