### ISSUE TITLE
Siga-Treinamento

### ISSUE THREAD

**Issue by moisesoliveirasilva** [projeto-siga/siga#249]
Existe um portal de educação onde os servidores se inscrevem para os cursos. No botão de inscrição há uma url para o siga-treinamento, por exemplo (http://siga/sigatr/publico/preInscrever.action?idTurma=4110). Se o usuário clica nesse botão e não estiver logado, abre a tela de login,
mas depois disso a página é carregada com o sequinte erro: Matrícula e ID da Turma obrigatórios.
Colei essa url no browser utilizando o siga-antigo e não deu esse problema.
Vcs poderiam verificar, por favor.

**Comment by kmacedovarela** [comment]
O erro realmente ocorre.
Após pressionar f5, o sistema se comporta como esperado.

**Comment by kmacedovarela** [comment]
Exemplo de url para reproduzir o problema em desenvolvimento:
http://siga/sigatr/publico/preInscrever.action?idTurma=704

**Comment by moisesoliveirasilva** [comment]
Verifiquei que a tela de login no siga-antigo, a url é essa: http://siga-antigo/siga/redirect.action?uri=%2Fsigatr%2Fpublico%2FpreInscrever.action%3FidTurma%3D4110
E no siga, a url é essa: http://siga/sigaidp/

**Comment by hodrigohamalho** [comment]
Todo mecanismo de autenticação foi reescrito, então isso é pra ser diferente mesmo @moisesoliveirasilva .

**Comment by kmacedovarela** [comment]
Moisés, você consegue reproduzir o problema em desenvolvimento e homologação?

**Comment by kmacedovarela** [comment]
O problema ocorre apenas no ambiente de produção.

**Comment by kmacedovarela** [comment]
Como o problema não é trivial e só ocorre no ambiente de produção será necessário realizar debug. Para nao prejudicar o acesso dos usuários, a investigação só sera realizada em momentos que o sistema estiver com uma menor quantidade de acessos.

**Comment by hodrigohamalho** [comment]
@moisesoliveirasilva esse erro ainda acontece?

**Comment by moisesoliveirasilva** [comment]
@hodrigohamalho , acabei de testar e o problema ainda ocorre.

**Comment by hodrigohamalho** [comment]
@moisesoliveirasilva poderia gerar um pacote com os seguintes parâmetros no webwork?

```
webwork.dispatcher.parametersWorkaround=false
webwork.url.includeParams=none
webwork.configuration.xml.reload=true
```

**Comment by kmacedovarela** [comment]
@hodrigohamalho  favor verificar situação desta demanda quando possível.

**Comment by crivano** [comment]
Fechei por RH não usa esses issues.
