### ISSUE TITLE
WF: Necessitando restart após redeploy

### ISSUE THREAD

**Issue by hodrigohamalho** [projeto-siga/siga#250]
o @Markenson identificou que ao fazer redeploy no ambiente de homologação a instância do sigawf precisa ser reiniciada pra funcionar normalmente.

Mesmo respondendo com HTTP 200 o quadro do siga na página inicial fica vazio.

**Comment by kmacedovarela** [comment]
Testei em localhost e não ocorreu a tela branca.

**Comment by kmacedovarela** [comment]
O problema também não ocorre na versão vraptor em localhost. Quando a versão VRaptor for disponibilizada no ambiente de homologação eu testo isso novamente.

**Comment by Markenson** [comment]
@kmacedovarela Acho que esse está dito como sigawf, mas parece ser o problema atual do sigaex, né?

**Comment by kmacedovarela** [comment]
O problema também acontecia no SigaWF, é necessário testar na nova versão com vraptor no ambiente de hmg (com mts instâncias) para constatar. 
Não consegui reproduzir no ambiente de desenvolvimento.

**Comment by Markenson** [comment]
OK.
