### ISSUE TITLE
SIGATP em homologação não está logando devidamente

### ISSUE THREAD

**Issue by hodrigohamalho** [projeto-siga/siga#253]
No log parece conter apenas mensagens do JBoss.

**Comment by kmacedovarela** [comment]
Aguardando pela equipe da nusad exemplo de log que deveria ser exibido, e não está .

**Comment by kmacedovarela** [comment]
Foi constatado que o sigatp não está logando nem no ambiente local de desenvolvimento. Foi acertado que a equipe irá analisar a aplicação e caso seja necessário, podemos reabrir essa issue.
