### ISSUE TITLE
Comportamento inesperado na SIGAT

### ISSUE THREAD

**Issue by hodrigohamalho** [projeto-siga/siga#254]
Recentemente o DNS SIGAT passou a apontar pro ambiente de homologação fornecendo acesso externo para os usuários.
Ao alterar as configurações para apontar pra esse novo DNS o SigaGC/SigaSR e SigaWF pararam de funcionar.

Tem que investigar o porque desse comportamento.

Caso seja alterado as referências de siga-hmg pra sigat, lembrar que o SigaRH faz os apontamentos do webservice para siga-hmg também.

**Comment by hodrigohamalho** [comment]
@Markenson o DNS siga-hmg vai morrer ou ficarão os dois?

**Comment by Markenson** [comment]
@hodrigohamalho Acho que fica a nosso critério. Se for mais simples manter um só, basta pedirmos à SERED para manter apenas o sigat. Caso contrário, não vejo problemas em manter os dois.

Deveríamos tentar fazer com que as aplicações sejam independente do nome do host e, onde não for possível, seria bom registrarmos no wiki para sabermos em situaçoes futuras.

**Comment by hodrigohamalho** [comment]
Manter um só é mais simples.
Existem várias propriedades (herdadas do siga.properties) que considera o link completo pro apache. ex:
```
<property name="siga.ex.assinatura.codeBasePath" value="http://siga-hmg/siga-ext-assinatura"/>
<property name="siga.ex.assinatura.messagesUrlPath" value="http://siga-hmg/siga-ext-assinatura"/>
<property name="siga.ex.assinatura.policyUrlPath" value="http://siga-hmg/siga-ext-assinatura"/>
```

Se quiser manter os dois links teriamos que revisar todas as propriedades que possuem valor absoluto das urls filtrar as que realmente são usadas, depois disso relativiza-las.

**Comment by Markenson** [comment]
Por simplicidade, então vamos manter apenas o sigat (temos que avisar ao pessoal da SEGEP). Depois é bom abrir uma issue para acertar essas referências hard nas properties.

**Comment by hodrigohamalho** [comment]
ok, vou providenciar isso.

**Comment by hodrigohamalho** [comment]
A alteração que solucionará esse problema irá inviabilizar o siga-hmg, deixando disponível *apenas* o DNS sigat. 
No ambiente siga-hmg está ocorrendo alguns treinamentos previstos pra acabar na quarta, para não prejudicar o andamento destes treinamentos iremos fazer a alteração para sigat somente quinta-feira.

**Comment by kmacedovarela** [comment]
Foram realizadas as devidas alterações no JBoss, aguardo a confirmação da infra sobre o apontamento do endereço  para o apache correto.

**Comment by kmacedovarela** [comment]
SigaWF, SigaGC e SigaSR estão agora sendo normalmente exibidos na sigat.jfrj.jus.br

**Comment by crivano** [comment]
@kmacedovarela será que pode configurar um redirect para que http://sigat.jfrj.jus.br redirecione para http://sigat.jfrj.jus.br/siga ?

**Comment by kmacedovarela** [comment]
Opa, achei que estivesse ok. vou reabrir a issue #227  referente a isto

**Comment by kmacedovarela** [comment]
Favor testar @crivano qualquer problema reabrir a issue.
