### ISSUE TITLE
Script para facilitar deploy nos ambientes

### ISSUE THREAD

**Issue by hodrigohamalho** [projeto-siga/siga#257]
O processo de deploy hoje está muito custoso, ainda mais com o SigaDOC onde cada release é feito o deploy de todos os módulos. 

Seria interessante criarmos um script que automatizasse esse processo.

**Comment by kmacedovarela** [comment]
Acompanhar #266

**Comment by kmacedovarela** [comment]
No momento a tarefa está sendo delegada para funcionários específicos que estão aprendendo o processo normal de deploy.
Vou fechar essa issue a princípio até que sejam definidas as equipes responsáveis por este procedimento. Quando este problema se tornar prioritário volto a reabrir a issue.
