### ISSUE TITLE
Problema na visualização de .rtf nos ambientes de desenvolvimento e homologação 

### ISSUE THREAD

**Issue by adrigrassi** [projeto-siga/siga#259]
Ao clicar no botão visualizar publicação no ato do agendamento de publicação DJE o sistema abre o word com a seguinte mensagem: 
"JavaScript is disabled. We strongly recommend to enable it. Click the button below to continue."

**Comment by adrigrassi** [comment]
Pessoal, descobrimos que esse problema somente acontece na classeE e o erro é o seguinte:
13:09:50,532 ERROR [stderr] (http-/10.10.0.68:8180-1) (LocalizaÃ§Ã£o de erro des                                                                                                 conhecido)java.io.FileNotFoundException: /opt/jboss-eap-6.2/xhtml.dtd (No such f                                                                                                 ile or directory)
Os arquivos a serem adicionados são:
xhtml.dtd
xhtml-lat1.ent
xhtml-special.ent
xhtml-symbol.ent

**Comment by kmacedovarela** [comment]
Ah sim, é um erro conhecido. Vou verificar assim que possível.

**Comment by kmacedovarela** [comment]
Os arquivos foram adicionados, favor testar novamente.

**Comment by adrigrassi** [comment]
Karina,

Já está funcionando!  Pode fechar a issue!
Obrigada,
Adriana

2015-05-06 13:34 GMT-03:00 Karina Macedo Varela <notifications@github.com>:
