### ISSUE TITLE
[SIGARH] Banco permutas se perde no redirecionamento do sigaidp

### ISSUE THREAD

**Issue by hodrigohamalho** [projeto-siga/siga#260]
Ao acessar deslogado o /sigarh-bancopermutas o usuário é redirecionado para o IDP, informa as credenciais e é direcionado para o sigaidp/ invés de ser redirecionado de volta para o /sigarh-bancopermutas/....

**Comment by kmacedovarela** [comment]
[INFO] Este problema não acontece no ambiente de desenvolvimento.

**Comment by hodrigohamalho** [comment]
Na verdade acho que esse problema é no sigaidp, estava testando local e está acontecendo pra todos os módulos.
Em desenvolvimento provavelmente está funcionando porque está com uma versão antiga do sigaidp.

**Comment by djalmasilvajr** [comment]
Pessoal,
Seria possível fazer o teste em produção?  O cliente deste módulo está aguardando para amanhã estar disponibilizado em produção.  Talvez lá não tenha este problema.

**Comment by kmacedovarela** [comment]
Sim Djalma, vou iniciar a criação das instâncias para o sigarh banco permutas em produção. é para disponibilizar o war que já está na pasta deploy?

**Comment by djalmasilvajr** [comment]
sim

**Comment by kmacedovarela** [comment]
Aviso quando estiver ok.

**Comment by djalmasilvajr** [comment]
ok

**Comment by kmacedovarela** [comment]
@hodrigohamalho o problema em questão está sendo causado pelo projeto siga-libs. Favor verificar e ajustar as devidas atualizações do último commit.

**Comment by hodrigohamalho** [comment]
Resolvido em: 003e6db136dce4ac971b16b824cbd8b1536a4404

Esse problema foi bem nada a ver, antes ao incluir uma biblioteca javascript eu incluia assim:
/siga/javascript/nomedalib.js

agora eu deixei o link já com a barra, e só passo o resto do nome:
siga/javascript/nomedalib.js

Não entendi direito mas isso resolveu.
