### ISSUE TITLE
Erro na carga do JackRabbit, branch: vraptor.

### ISSUE THREAD

**Issue by crivano** [projeto-siga/siga#261]
@hodrigohamalho @kmacedovarela , não sei porque o JBPM quer carregar o JCR, mas o fato é que está dando esse erro abaixo. Tem alguma possibilidade de acrescentar essa dependência como um módulo ou algo assim?

09:44:20,502 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/sigawf].[default]] (http-localhost/127.0.0.1:8080-4) JBWEB000236: Servlet.service() for servlet default threw exception: java.lang.ClassNotFoundException: javax.jcr.Node from [Module "deployment.sigawf.war:main" from Service Module Loader]

**Comment by hodrigohamalho** [comment]
A gente pode configurar como módulo essa dependência, mas não vejo muita utilidade nisso porque só o sigawf usa o JBPM... 

Acho que seria mais adequado inserir como uma dependência da aplicação mesmo no pom.

**Comment by crivano** [comment]
@hodrigohamalho parece que resolveu. Tks!
