### ISSUE TITLE
Configurar usuários e permissões no DC

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#263]
Habilitar e configurar o rbac.

**Comment by kmacedovarela** [comment]
@luiz-antonio é necessário definir:

Quais serão os usuários?
O que cada usuário poderá fazer?

Esta demanda será executada por nós ou você executará?

Uma vez definidos os usuários e permissões, deve-se decidir se serão utilizados "grupos", conforme a necessidade.

As roles podem ser visualizadas na documentação oficial, tópico 10.8.4. The Standard Roles
.   https://access.redhat.com/documentation/en-US/JBoss_Enterprise_Application_Platform/6.2/html-single/Administration_and_Configuration_Guide/index.html#sect-Securing_the_Management_Interfaces_with_Role-Based_Access_Control
  
Resumidamente o procedimento para habilitar o rbac será:

1. Habilitar o rbac via CLI
2. Configurar os grupos (se for utilizado) via interface de gerenciamento do JBoss e suas respectivas roles
2. Adicionar usuários via script add-user.sh.
3. Caso o usuário tenha configurações específicas (que não estão configuradas no grupo), acessar a interface de gerenciamento e configurar estas roles.

**Comment by luiz-antonio** [comment]
Segue o solicitado:

GRUPOS          ROLES                      USUÁRIOS
--------------  -------------------               --------------------
MENTORING    SuperUser                 Karina, Rodrigo
SEINAP		 SuperUser	           luiz.simoes, rodrigo.ferreira
OPERADORES Operator, Monitor     marcio.martins, flavio.sampaio
LIBERACAO	  Deploy                      cristiane.viana, paulo.duarte
DESENV-SIGA     Audit, Deploy(siga)  markenson.franca, rafaela.nascimento, adriana.almeida, andre.silva, chrystinne.fernandes,  edson.sales, renato.crivano, ruben.rose,
DESENV-RH       Audit, Deploy(rh)    flavia.correia, ilara.fumo, marcos.fragoso, lupercio.ferraz, moises.oliceira,roberto.mendonca,  djalma.goncalves, carolina.ramos, aldeci.moura, carlos.oliveira


A demanda pode ser executada por vocês, eu apenas acompanho.

Conforme acima, já faremos as configurações dos grupos. Note que como temos domínios separados para SIGADOC e SIGARH, as configurações de DESENV podem ser específicas.

**Comment by luiz-antonio** [comment]
Falta criar os usuários do grupo "mentoring" em homologação. Estes, melhor deixar com a Karina e o Rodrigo.

**Comment by kmacedovarela** [comment]
Feito. 
A documentação da execução será realizada pelo @luiz-antonio.

**Comment by kmacedovarela** [comment]
Feito para o ambiente de homologação.

**Comment by moisesoliveirasilva** [comment]
Luiz,

Meu usu�rio est� moises.oliceira, mas o correto seria moises.oliveira

Abra�os.

Mois�s
________________________________________
De: luiz-antonio [notifications@github.com]
Enviado: ter�a-feira, 12 de maio de 2015 11:17
Para: projeto-siga/siga
Assunto: Re: [siga] Configurar usu�rios e permiss�es no DC (#263)

Segue o solicitado:

GRUPOS ROLES USU�RIOS

________________________________

MENTORING SuperUser Karina, Rodrigo
SEINAP SuperUser luiz.simoes, rodrigo.ferreira
OPERADORES Operator, Monitor marcio.martins, flavio.sampaio
LIBERACAO Deploy cristiane.viana, paulo.duarte
DESENV-SIGA Audit, Deploy(siga) markenson.franca, rafaela.nascimento, adriana.almeida, andre.silva, chrystinne.fernandes, edson.sales, renato.crivano, ruben.rose,
DESENV-RH Audit, Deploy(rh) flavia.correia, ilara.fumo, marcos.fragoso, lupercio.ferraz, moises.oliceira,roberto.mendonca, djalma.goncalves, carolina.ramos, aldeci.moura, carlos.oliveira

A demanda pode ser executada por voc�s, eu apenas acompanho.

Conforme acima, j� faremos as configura��es dos grupos. Note que como temos dom�nios separados para SIGADOC e SIGARH, as configura��es de DESENV podem ser espec�ficas.

�

**Comment by luiz-antonio** [comment]
Moisés,

mil desculpas! vou acertar.

Grande abraço,
Luiz Antonio
