### ISSUE TITLE
Habilitar o RBac no ambiente de produção

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#265]
Habilitar o rbac e configurar os devidos usuários no ambiente de produção.

**Comment by Markenson** [comment]
Pessoal, só por precaução, seria bom que fosse agendado para uma data que não a mesma de deploy das aplicações para evitarmos problemas.

**Comment by luiz-antonio** [comment]
Perfeito!

Peço desculpas por este transtorno e também paciência nesses estágios iniciais de assimilação dos serviços, pois até estarmos totalmente habilitados às tarefas e alinhados com a rotina do desenvolvimento possivelmente ainda atrapalharemos um pouco. Conforme o andamento, faremos também outros ajustes que venham a ser necessários.

Neste aspecto, atribuiremos permissão na homologação de reinício dos serviços também para o grupo de desenvolvimento, visto os problemas constantes nos DEPLOYS do sigadoc-webwork e do sigawf que necessitam de reinício do servidores .

**Comment by Markenson** [comment]
Não precisa se desculpar, Luiz. Sabemos que faz parte do processo.  Particularmente, considero uma ótima iniciativa criar esses perfis!

**Comment by kmacedovarela** [comment]
Realizado pelo Luiz Garcia
