### ISSUE TITLE
URIEncoding

### ISSUE THREAD

**Issue by crivano** [projeto-siga/siga#267]
Olá @hodrigohamalho  e @kmacedovarela , não estou conseguindo especificar o charset que deve ser utilizado pelo JBoss para fazer o parse das URLs de um GET.

Antigamente configurávamos o URIEncoding="UTF-8" em um <connector>.

Encontrei isso na internet:

https://developer.jboss.org/message/720331

Como devemos fazer agora? Ou isso é um problema do VRaptor?

Em tempo, esse erro problema ocorreu em meu ambiente de desenvolvimento.

Obrigado!

**Comment by kmacedovarela** [comment]
Olá Crivano,

Tente as seguintes configurações:
No standalone.xml:
        <property name="org.apache.catalina.connector.URI_ENCODING" value="UTF-8" boot-time="true"/>
        <property name="org.apache.catalina.connector.USE_BODY_ENCODING_FOR_QUERY_STRING" value="true" boot-time="true"/>


No jboss-web.xml:
Adicionar os parametros de encoding à valvula do picketlink. Segue exemplo de um jboss-web.xml abaixo:

<jboss-web>
	<security-domain>sp</security-domain>
	<context-root>nome-do-projeto</context-root>
	<valve>
		<class-name>org.picketlink.identity.federation.bindings.tomcat.sp.ServiceProviderAuthenticator
		</class-name>
		<param>
			<param-name>characterEncoding</param-name>
			<param-value>UTF-8</param-value>
		</param>
	</valve>
</jboss-web>

**Comment by kmacedovarela** [comment]
Resolvido!

Nota: No modo standalone a propriedade boot-time não é necessária
