### ISSUE TITLE
URL de autenticação de documentos restrita pelo picketlink

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#268]
A url http://siga/sigaex/autenticar.action não deve exigir autenticação. Inclusive, essa url não pode exigir certificado digital quando acessada via internet, pois isso impede que pessoas externas à justiça autentiquem os documentos.

**Comment by kmacedovarela** [comment]
@Markenson  estou verificando a questão da URL. 

A princípio estamos sem acesso à maquina que dá acesso externo devido aos ocorridos da última sexta feira. Assim que possível analisaremos as configurações necessárias para evitar a autenticação via acesso externo.

**Comment by kmacedovarela** [comment]
Acredito que após colocar esta correção em produção tudo deva funcionar normalmente.

 O certificado é solicitado na belina pois a url do idp é invocada, e esta é uma url privada. Uma vez que o acesso à sigaex\autenticar.action for liberada no IDP, tudo deverá funcionar sem precisar de configurações adicionais no apache.

#aec04becdc35c354e763e3a7d11cdf5faf318880

**Comment by kmacedovarela** [comment]
Testei em produção e esta issue está resolvida.

**Comment by Markenson** [comment]
Na verdade, a url que deve ser testada é https://sigap.jfrj.jus.br/sigaex/autenticar.action (a url anterior está apontando para o jboss5). Embora a página de autenticidade esteja abrindo, ao digitar um número a ser consultado, o PDF do documento não está sendo exibido. Por exemplo, digite 1420229-1539.

**Comment by kmacedovarela** [comment]
Procede, vou analisar.

**Comment by kmacedovarela** [comment]
6d2931bee88a0b08c9659e93e0100c373eea9cf5 . Reabrir se necessário
