### ISSUE TITLE
Link de transferência de documentos não está funcionado no IE

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#269]
O erro 404 aparece ao clicar no link "despachar\transferir" no internet explorer e no firefox. No chrome funciona corretamente.

![image](https://cloud.githubusercontent.com/assets/2985140/7730753/771a3ca0-fef2-11e4-94ff-30811c9763db.png)

![image](https://cloud.githubusercontent.com/assets/2985140/7730770/89bfaa34-fef2-11e4-8a88-a63b703fc15c.png)

**Comment by Markenson** [comment]
Pessoal,

será que pode ser um deploy problemático?

**Comment by Markenson** [comment]
Acabei de testar na hmg e está ok.

**Comment by kmacedovarela** [comment]
Em análise.

**Comment by kmacedovarela** [comment]
O problema ocorria apenas na arocs. 
Apagando as pastas data / tmp / servers, e reiniciando as instâncias tudo normalizou.
