### ISSUE TITLE
SIGA-DOC: funcionando apenas na porta 8443

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#272]
Não está sendo possível acessar o siga-doc na porta 8080, apenas na 8443.

Módulo sigaex não funciona: http://localhost:8080/siga
Módulo sigaex funciona: http://localhost:8443/siga

**Comment by Markenson** [comment]
Alterado o arquivo picketlink.xml f5e212562ab9572dcec0a49f4cc396b8c753ce7b

**Comment by kmacedovarela** [comment]
Exato!! 

Fechou.
