### ISSUE TITLE
[siga-dev:8480] Erro ao fazer login

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#273]
Obtive esse erro ao tentar fazer login. Percebi que estava usando a senha errada e consegui acessar normalmente, mas acho importante reportar o erro mesmo assim:

 ![erro_login](https://cloud.githubusercontent.com/assets/4949149/8089064/f26d29c8-0f7b-11e5-815b-5e681a20b85e.png)

**Comment by andresousa17** [comment]
O erro estava na taglib <%@ taglib uri="http://localhost/sigatags" prefix="siga"%> que foi substituída pela taglib <%@ taglib uri="http://localhost/jeetags" prefix="siga"%>. Fiz a correção na página loginInvalido.jsp
