### ISSUE TITLE
[siga-dev:8480] Erro ao criar novo usuário

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#274]
Erro ao clicar em "Sou um novo usuário":

 
![erro_ao_criar_senha_siga-dev](https://cloud.githubusercontent.com/assets/4949149/8089139/5e3631cc-0f7c-11e5-9d7f-75b3f78b641c.png)

**Comment by Markenson** [comment]
Corrigido no commit e7443bfc58ad81eb4a6ed0a8245b048fbc43ee04
