### ISSUE TITLE
[Siga-Gc] Erro ao abrir conhecimento

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#275]
Erro intermitente. Consegui acessar o conhecimento na segunda tentativa.

![captura_de_tela_061015_022621_pm](https://cloud.githubusercontent.com/assets/4949149/8089195/c1659d96-0f7c-11e5-81ab-cdd675163843.jpg)

**Comment by kmacedovarela** [comment]
O problema pode estar ocorrendo pois está com uma quantidade reduzida de conexões no pool para não sobrecarregar o banco. Vou aumentar mais um pouco, se ocorrer novamente  favor reabrir.

**Comment by kmacedovarela** [comment]
@luiz-antonio  a conta do sigagc está novamente locked em homologação.

Caused by: java.sql.SQLException: ORA-28000: the account is locked

Favor verificar

**Comment by Chrystinne** [comment]
@kmacedovarela Ok, Karina. Quando fizer isso, avisa, por favor, pra que eu posssa continuar testando.

**Comment by kmacedovarela** [comment]
@Chrystinne a alteração foi realizada, precisamos aguardar liberação da conta por parte da equipe de banco.

**Comment by Chrystinne** [comment]
@kmacedovarela Ok.

**Comment by luiz-antonio** [comment]
Bloqueio do usuário SIGAGC no banco de homologação desbloqueado.

**Comment by Chrystinne** [comment]
@luiz-antonio Blz! Testei aqui e estou conseguindo acessar. Obrigada.

**Comment by Chrystinne** [comment]
Não estava conseguindo abrir o conhecimento porque a conta do Siga-Gc estava bloqueada na base de homologação por causa das tentativas de acesso sem sucesso. Problema resolvido.
