### ISSUE TITLE
[Siga-Gc] Criação de classificação ao formatar texto (mudar cor)

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#279]
Obs.: Este erro já estava ocorrendo antes da migração para o vraptor.

Ao editar um conhecimento, quando alteramos a cor da fonte, ao gravar o documento, está sendo cadastrada uma classificação para o conhecimento com a cor da fonte.

**Comment by Chrystinne** [comment]
Problema resolvido.

![captura_de_tela_091715_025609_pm](https://cloud.githubusercontent.com/assets/4949149/9941526/47e1193c-5d4c-11e5-896c-269e72b0e4bf.jpg)

**Comment by crivano** [comment]
Gostei da foto para provar! :)
