### ISSUE TITLE
SIGA-DOC: modelos JSP não estão disponíveis na versão vraptor

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#280]
Por exemplo, o modelo seguinte existe em produção atualmente e não está na versão do Vraptor

sigaex/src/main/webapp/paginas/expediente/modelos/solicitacaoHoraExtra.jsp

**Comment by crivano** [comment]
Acredito que a solução seja simplesmente copiar o diretório inteiro de modelos do master para o vraptor.

**Comment by andresousa17** [comment]
Copiei toda a pasta expediente do master para o vraptor conforme indicado pelo @crivano  e funcionou

**Comment by Markenson** [comment]
Arquivos alterados para utf-8 no commit 98d5e66f1099449670b1c6715227ac6e7c4b6909
