### ISSUE TITLE
[SIGARH] Aplicação fazendo upload de arquivos no local errado

### ISSUE THREAD

**Issue by hodrigohamalho** [projeto-siga/siga#281]
Não sei ao certo qual aplicação que está fazendo upload de maneira errada, mas como é possível verificar na imagem abaixo os arquivos estão sendo salvos no diretório /opt/jboss e o nome do arquivo está ficando no formato  PATH + nome do arquivo no formato Windows.

![capturar](https://cloud.githubusercontent.com/assets/252998/8135268/5fa89202-110c-11e5-968e-e247fe3a0ee0.PNG)

**Comment by kmacedovarela** [comment]
Se não estiver fixo na aplicação, vale ressaltar que talvez a aplicação esteja utilizando a propriedade user.dir, que atualmente aponta para /opt/jboss-eap-6.2.

**Comment by hodrigohamalho** [comment]
Pode ser também o uso de caminho relativo, se não for especificado um nó raíz é utilizado o diretório em que o servidor foi iniciado no caso o /opt/jboss/bin, se na aplicação tiver um "../" por exemplo cairia nesse diretório aí...

**Comment by crivano** [comment]
Fechei pois a equipe do RH não usa esses issues.
