### ISSUE TITLE
SIGA-DOC: Texto de código exibido na página de criação de documentos

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#290]
Ao clicar em NOVO, a seguinte tela aparece

![image](https://cloud.githubusercontent.com/assets/2985140/8214400/5668d1b0-14ff-11e5-8c86-760f6a4f3880.png)

**Comment by andresousa17** [comment]
O erro estava na uso das tags do webwork ww:if e ww:else. Estas tags foram substituídas por c:choose.
