### ISSUE TITLE
[Siga-Doc] Transferência com data de retorno não está funcionando

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#293]
Ao transferir um documento especificando uma data de retorno, não estão sendo criadas as marcas "A devolver" e "Aguardando devolução".

**Comment by Chrystinne** [comment]
Commits a28c629722, de640aabf48, e43efeda29c, b362005035ea9 não vieram do branch develop para o vraptor

**Comment by Chrystinne** [comment]
Além dos commits que não vieram, o problema está na persistência da data de devolução. Mesmo que o usuário preencha este campo, não está sendo persistido no banco.

**Comment by andresousa17** [comment]
@Chrystinne  fiz testes com o documento TRF2-FOR-2015/00002 e o sistema gerou as marcas  "A devolver" e "Aguardando devolução" corretamente. Tem como você testar mais uma vez para ver se o erro continua ?
