### ISSUE TITLE
SIGA-DOC: Email de notificação de movimentação não está com o servidor correto

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#295]
Ao receber um e-mail de notificação, cliquei no link e percebi que não funcionava.

![image](https://cloud.githubusercontent.com/assets/2985140/8217696/5a4e1c98-1515-11e5-9a17-8a37026316d9.png)

**Comment by andresousa17** [comment]
É preciso incluir a seguinte propriedade no siga.properties 

siga.ex.desenv.url=http://localhost:8080/sigaex
