### ISSUE TITLE
[Siga-Doc] Alteração de campo atendente na transferência não surte efeito no IE

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#296]
Campo atendente só está recebendo dados relacionados ao "Órgão Integrado". Alterar atendente para "Matrícula" não surte efeito.

**Comment by andresousa17** [comment]
Fiz testes e consegui transferir para pessoa e lotação.

**Comment by Chrystinne** [comment]
No Chrome funciona normalmente. Erro ocorre apenas no IE.

**Comment by andresousa17** [comment]
O erro estava na linha console.log('submetendo...'); no método javascript sbmt(). Está linha foi removida.
