### ISSUE TITLE
SIGA: caracteres errados em esqueci minha senha

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#300]
Ao testar a funcionalidade "esqueci minha senha" a página estava conforme imagem abaixo:

![image](https://cloud.githubusercontent.com/assets/2985140/8217982/af6d08d2-1516-11e5-9273-e3144798133d.png)

**Comment by andresousa17** [comment]
O charset da página estava em ISO-8859-1 e foi alterado para UTF-8.
