### ISSUE TITLE
DOC: Modelos do freemarker ainda fazem referência a urls do webwork

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#302]
@andresousa17 detectou que existem urls nos modelos freemarker que apontam para o webwokk (*.action)

Trechos encontrados até o momento:
```
 var url = '${acaoBusca}/buscar.action?propriedade=${var}${tipoSel}&sigla='+encodeURI(sigla)+'${selecaoParams!}';

var url = '${acaoBusca}/selecionar.action?var=${var}${tipoSel}&sigla='+encodeURI(sigla)+'${selecaoParams!}';

<td><a href="javascript:void(0)" onclick="javascript: window.open('/sigaex/expediente/doc/exibir.action?popup=true&id=${ex.idDoc!}', '_new', 	'width=700,height=500,scrollbars=yes,resizable')">${ex.codigo!}</a></td>

<a href="/sigaex/expediente/mov/cancelar_pedido_publicacao_boletim.action?sigla=${ex.sigla!}">Cancelar Pedido</a>


onclick="javascript: window.open('/sigaex/expediente/doc/exibir.action?popup=true&id=${ex.idDoc!}', '_new', 'width=700,height=500,scrollbars=yes,resizable')">${ex.codigo!}</a></td>


onclick="javascript: window.open('/sigaex/expediente/doc/exibir.action?popup=true&id=${item.mob.exDocumento.idDoc}', '_new', 'width=700,height=500,scrollbars=yes,resizable')">${item.mob.sigla}</a>

```

**Comment by crivano** [comment]
Marcado com "wontfix" porque não podemos fazer essa correção enquanto a versão não estiver em produção. Alterar isso faria com que a versão anterior do SIGA-DOC parasse de funcionar.

**Comment by Markenson** [comment]
@crivano,

Se não me engano, o @andresousa17 mapeou as urls para que respondam também pelo mapeamento antigo. Isso resolveria esse problema.

**Comment by andresousa17** [comment]
@Markenson @crivano 
A versão do vraptor está aceitando as duas urls. Quando nós desabilitarmos a versão antiga temos que alterar o freemarker e retirar as urls antigas do vraptor.

**Comment by crivano** [comment]
@andresousa17 Podemos fechar esse issue, então?

**Comment by crivano** [comment]
@andresousa17 
Em tempo, essa ideia de aceitar as duas urls foi excelente! Parabéns!
