### ISSUE TITLE
SIGA-GI: A página de permissões inicia sem campo de seleção

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#304]
Ao clicar em SIGA/Gestão de Identidades/Configurar Permissões a caixa não é exibida:

![image](https://cloud.githubusercontent.com/assets/2985140/8219714/5ec3d35a-1522-11e5-9075-eaa506540510.png)

**Comment by andresousa17** [comment]
O problema foi corrigido com a inserção do seguinte script no fima da página para carregar o campo de seleção de perfil.

<script> 
		muda_escolha(document.getElementById("idAbrangencia"));
	</script>
