### ISSUE TITLE
[Siga-Doc] Erro na Juntada de Documento

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#308]
Não aparece campo a ser preenchido com número do documento:

![captura_de_tela_061915_023800_pm](https://cloud.githubusercontent.com/assets/4949149/8259157/dbc93b96-1690-11e5-980a-48e16d4dffc1.jpg)

**Comment by crivano** [comment]
Estranho, isso eu tenho certeza que já tinha testado. É muita coisa...

Em sex, 19 de jun de 2015 às 14:39, Chrystinne <notifications@github.com>
escreveu:

**Comment by Chrystinne** [comment]
@crivano tem um detalhe. Se vc selecionar o outro elemento da lista ("Documento externo ao Siga"), o campo aparece.

**Comment by andresousa17** [comment]
Com a criação das tag siga:escolha e siga:opcao é necessário adicionar o seguinte script no final da página para poder carregar uma opção como selecionada:

<script> 
	muda_escolha(document.getElementById("idDocumentoEscolha"));
</script>
