### ISSUE TITLE
Erro ao prosseguir com uma tarefa no Workflow

### ISSUE THREAD

**Issue by adrigrassi** [projeto-siga/siga#313]
N�o Foi Poss�vel Completar a Opera��o

could not delete timers by name 'tempWfTarefa' for Token(94481)
 

Unable to resolve entity name from Class [org.jbpm.context.exe.variableinstance.UnpersistableInstance] expected instance/subclass of [org.jbpm.context.exe.VariableInstance]

**Comment by crivano** [comment]
Estávamos gravando uma variável no contexto que era do tipo StringQualquer. Como esse tipo não é serializable, dá o erro de UnpersistableInstance. A solução foi tomar o cuidado de converter para String antes de gravar a variáve.
