### ISSUE TITLE
ECLIPSE: reinício do servidor a cada edição de classe

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#320]
Na edição de uma classe java o servidor reinicia toda a instância do jboss e isso faz com que o navegador perca a sessão. Ao alterar um jsp isso não ocorre.

@andresousa17 me corrija se escrevi algo errado.
@kmacedovarela e @hodrigohamalho sabem como evitar isso?

**Comment by kmacedovarela** [comment]
O @andresousa17  está enfrentando este problema? Assim que ele chegar vou verificar com ele na máquina dele.

**Comment by andresousa17** [comment]
@kmacedovarela eu também estou com esse problema sempre que atualizo uma classe. Nos jsp não tem esse problema.

**Comment by kmacedovarela** [comment]
Foi constatado que o problema na verdade é pois o módulo sigaex para de funcionar após redeploy.

**Comment by kmacedovarela** [comment]
#321
