### ISSUE TITLE
Verificar causa de problema em redeploy do módulo SigaEX

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#321]
O re-deploy do projeto sigaex.war não funciona.

Verificar.

**Comment by Markenson** [comment]
Pode estar relacionada à issue #250

**Comment by Markenson** [comment]
Resolvido nos commits abaixo.
13719cc6 
010454d3
1c83f8ac

**Comment by Markenson** [comment]
Detalhe: é necessário atualizar os seguintes arquivos ao fazer o deploy:

siga-ext.jar
siga-ext-busca-textual.jar
