### ISSUE TITLE
DOC: Assinar Anexo com Senha.

### ISSUE THREAD

**Issue by andresousa17** [projeto-siga/siga#327]
Na tela de assinar anexo o campo para a assinatura com senha não está ficando visível para preencher a matrícula e a senha

![image](https://cloud.githubusercontent.com/assets/5269936/8557800/0532627a-24d6-11e5-845c-e479532830f2.png)

**Comment by crivano** [comment]
Corrigido fazendo scroll to top antes de abrir a dialogbox.
