### ISSUE TITLE
[SigaRH] Arquivos salvos em local indevido

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#332]
Problema: Arquivos de upload do SigaRH (não sabemos especificamente o módulo ainda) estão sendo salvos em $JBOSS_HOME. 

Alertar responsáveis e se necessário auxiliar no processo de troca.

**Comment by hodrigohamalho** [comment]
Acho que essa issue é duplicada: https://github.com/projeto-siga/siga/issues/281

**Comment by kmacedovarela** [comment]
Issue duplicada.
