### ISSUE TITLE
Erro ao usar a caixa de busca quando acessando pela internet

### ISSUE THREAD

**Issue by crivano** [projeto-siga/siga#333]
A caixa de busca é chamada por HTTP, enquanto a página principal vem por HTTPS. O browser bloqueia.

Mixed Content: The page at 'https://sigap.jfrj.jus.br/siga/principal.action' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://sigap.jfrj.jus.br/sigasr/solicitacao/gadget?idp=4X73DvBgXwplIV3JQPFRvltc.accelo%3Asigadoc-server03'. This request has been blocked; the content must be served over HTTPS.

**Comment by hodrigohamalho** [comment]
@crivano Como é a pesquisa que tem que fazer pra reproduzir o erro em questão, tenho tentado e não tenho conseguido.

**Comment by crivano** [comment]
@hodrigohamalho quando entro pela internet, em siga.jfrj.jus.br, usando o certificado digital para acessar, a caixa não funciona.

Primeiro dá o erro que descrevi acima. Depois que estabiliza, simplesmente não consegue localizar nada. O selecionar.action volta "0".

Se desejar, posso compartilhar minha tela no hangout.
