### ISSUE TITLE
SIGA-CP: verificar necessidade das configurações do c3po

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#335]
Os parâmetros abaixo estão definidos nas properties do siga e provavelmente sem uso (estão sendo referenciados em aplicações de sincronismos e alguns códigos de testes). Precisamos verificar a real necessidade e efetuar a remoção caso não haja necessidade deles. 

```
c3p0.max_size 
c3p0.max_statements 
c3p0.min_size 
homolo.c3p0.timeout
```

**Comment by esredson** [comment]
Tratando na #664
