### ISSUE TITLE
Erro no visualizar html do dossiê 

### ISSUE THREAD

**Issue by andresousa17** [projeto-siga/siga#337]
Está dando erro na versão html ao visualizar dossiê

![image](https://cloud.githubusercontent.com/assets/5269936/8709314/de506042-2b17-11e5-9f1a-3c6d3a169ca1.png)

**Comment by andresousa17** [comment]
@crivano este erro de null no visualizar dossiê está acontecendo porque o Pattern em ProcessadorHtml.java método bodyonly foi alterado de

Pattern.compile("<body[^>]*>\\s*+(.*?)\\s*+</body>",

para 

Pattern.compile("<body[^>]*>\n(\\s*+.*?)\\s*+</body>",

no commit Indentação automática de modelos clicando ctrl+i

A diferença está nesta parte \n(

**Comment by crivano** [comment]
será que acrescentando uma interrogação depois do \n já resolve? ficaria
assim:

```
Pattern.compile("]*>\n?(\s*+.*?)\s*+"
```

Em qua, 15 de jul de 2015 às 19:14, andresousa17 <notifications@github.com>
escreveu:

**Comment by andresousa17** [comment]
vou testar

**Comment by andresousa17** [comment]
Funcionou.
