### ISSUE TITLE
Configurar plugin maven jboss 

### ISSUE THREAD

**Issue by hodrigohamalho** [projeto-siga/siga#34]
Referência: https://docs.jboss.org/jbossas/7/plugins/maven/latest/

Acho que o uso desse plugin poderia ser bem proveitoso, principalmente para fazer deploy no ambiente de dev sem precisar acessar as máquinas.

Algo mais ou menos assim:
```
mvn package jboss:deploy -Pdev
```

**Comment by kmacedovarela** [comment]
É necessário rever essa necessidade uma vez que agora no ambiente de desenvolvimento são utilizados conteineres docker criados de maneira dinâmica sempre surge uma nova necessidade.   
  Após um posicionamento sobre a responsabilidade dos deploys, podemos voltar a elencar esta issue como necessária/prioritária e reabri-la quando julgar apropriado.
