### ISSUE TITLE
[Siga-Gc] Erros no Notificar

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#341]
A opção "Notificar" está com vários erros:

- Campo de texto duplicado;
- Erro ao notificar Pessoa.
- Erro ao notificar Lotação;

**Comment by Chrystinne** [comment]
Erro: java.lang.NoClassDefFoundError: org/apache/jsp/tag/meta/http_003a/localhost/jeetags/cabecalho_tag


Erro original:

**Comment by Chrystinne** [comment]
![erro_notificar_pessoa](https://cloud.githubusercontent.com/assets/4949149/8853456/25802a5a-3131-11e5-8919-0d0337999cdb.png)

**Comment by Chrystinne** [comment]
![botao_repetido_notificar](https://cloud.githubusercontent.com/assets/4949149/8853494/590180e0-3131-11e5-89dd-8ebd9246fece.png)

**Comment by crivano** [comment]
Oi, acho que criei uma tag especificamente para isso. Ela deve estar com defeito, ou a página deve estar usando a tag errada. Seria bom conferir com a página de listagem...

**Comment by Chrystinne** [comment]
@crivano Sim, resolvi essa duplicação. 

Agora está dando outro erro ao notificar lotação (failed to lazily initialize a collection of role: br.gov.jfrj.siga.dp.DpLotacao.dpPessoaLotadosSet, could not initialize proxy - no Session) ao enviar o e-mail. O notificar Pessoa está ok, inclusive enviando e-mail.

**Comment by Chrystinne** [comment]
Tou debugando pra ver o que é.
