### ISSUE TITLE
Problema no getResourceAsStream

### ISSUE THREAD

**Issue by crivano** [projeto-siga/siga#348]
O getResourceAsStream não está funcionando. O trecho abaixo funciona debugando no eclipse mas não funciona na instância de homologação.

```
		InputStream stream = FreemarkerDefault.class.getClassLoader()
				.getResourceAsStream(
						"br/gov/jfrj/siga/ex/util/" + "default.ftl");
		String template;
		try {
			template = IOUtils.toString(stream, "UTF-8");
			return template;
		} catch (IOException e) {
			e.printStackTrace();
			return null;
		} finally {
			IOUtils.closeQuietly(stream);
		}
```

**Comment by hodrigohamalho** [comment]
Qual url você acessa pra debugar este trecho @crivano ?

**Comment by crivano** [comment]
Por exemplo, vá no sigaex e peça para exibir um documento qualquer. A /exibir já usa esse código...

**Comment by hodrigohamalho** [comment]
@crivano Essa "instância de homologação" que você diz é qual?

**Comment by hodrigohamalho** [comment]
O Nullpointer devido aos arquivos não encontrados é por conta do padrão do maven.

No diretório src/main/java o maven acredita que só tera arquivos .java, arquivos diferentes dessa extensão serão desconsiderados e perdidos no build.

Portanto qualquer arquivo que não seja .java deverão ser colocados dentro de src/main/resources.

Commit de referência: #ae53caa55fd09a01949fb49aad0ff5817335b697

**Comment by hodrigohamalho** [comment]
Ainda resta um NPE na classe FreemarkerSimplesDefault.java, na linha 15. O mesmo procura uma propriedade siga.debug.default.template.pathname mas essa propriedade não está definida nessa instância.

@crivano qual valor essa propriedade deveria ter?

**Comment by crivano** [comment]
O correto seria que não fosse gerado um NPE nesse caso. Será que dá para
colocar um try?

Em seg, 27 de jul de 2015 às 16:07, Rodrigo Ramalho da Silva <
notifications@github.com> escreveu:

**Comment by hodrigohamalho** [comment]
Estranho porque parece que já tem lá, vou dar uma atualizada nos deploys dessa instância pra garantir que estamos atualizados.

**Comment by hodrigohamalho** [comment]
Acho que era algum módulo desatualizado mesmo, 
atualizei tudo lá e parece que resolveu, poderia testar e dar o feedback @crivano  ?

**Comment by crivano** [comment]
Agora está 100%.
