### ISSUE TITLE
GC: Notificar Lotação não funciona na Produção (erro ao enviar e-mail)

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#354]
LazyInterceptorHandler

![captura_de_tela_072815_071159_pm](https://cloud.githubusercontent.com/assets/4949149/8945284/8633c5bc-355c-11e5-9cca-c6403cb120e7.jpg)

**Comment by crivano** [comment]
É bom passar isso para @kmacedovarela ou @hodrigohamalho .

@luiz-antonio , você está recebendo essas atualização, certo?

**Comment by luiz-antonio** [comment]
SIm !

**Comment by Chrystinne** [comment]
@kmacedovarela @hodrigohamalho, vocês chegaram a dar uma olhada nisso?

**Comment by Chrystinne** [comment]
@kmacedovarela @hodrigohamalho, vocês chegaram a dar uma olhada nisso?

**Comment by kmacedovarela** [comment]
Como reproduzir o erro?

**Comment by Chrystinne** [comment]
@crivano  Agora percebi que só está dando erro quando tento notificar minha lotação (SEMGET). A notificação de outras lotações está funcionando.

@kmacedovarela, Para reproduzir, você pode acessar qualquer conhecimento visível para você e notificar a lotação SEMGET:

Exemplo:
- Acessar http://siga-dev:8380/sigagc/app/notificar/TMPGC16005;
- Preencher a lotação SEMGET;
- Clicar em Notificar;

**Comment by Chrystinne** [comment]
Além da mensagem "Não foi possível se conectar ao servidor de e-mail!", agora deu o erro abaixo:

![captura_de_tela_090315_111626_am](https://cloud.githubusercontent.com/assets/4949149/9660812/fc495242-522d-11e5-9c22-1dbba8139850.jpg)

**Comment by kmacedovarela** [comment]
@Chrystinne  o problema não ocorreu no ambiente de homologação, poderia confirmar a informação pra mim? 

http://siga-hmg/sigagc/app/exibir/TMPGC2771

POrém ocorreu o seguinte erro:
[Server:sigadoc-server02] 11:25:34,473 ERROR [stderr] (http-/10.10.0.69:8280-1) Caused by: java.sql.SQLSyntaxErrorException: ORA-00942: a tabela ou view não existe

**Comment by Chrystinne** [comment]
@kmacedovarela Pois é. Não ocorre no ambiente de homologação, só no de produção.

**Comment by kmacedovarela** [comment]
O erro acontece em produção pois os destinatários estão cadastrados incorretamente. O array retorna dois valores: 
[0] - chrystinne.fernandes@jfrj.jus.bradriana.almeida@jfrj.jus.br
[1] - adriana.almeida@jfrj.jus.br

Sendo que o primeiro registro estando incorreto gera o seguinte erro:
javax.mail.internet.AddressException: Domain contains illegal character in string ``chrystinne.fernandes@jfrj.jus.bradriana.almeida@jfrj.jus.br''

Este problema deve ser resolvido na aplicação.
