### ISSUE TITLE
SR: Ao gravar solicitação, lança Lazy Exception quando há campos obrigatórios não preenchidos

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#357]

**Comment by esredson** [comment]
Não ocorre sempre. Será que é só quando há acordos vinculados?

**Comment by rafaela00castro** [comment]
Não estou conseguindo reproduzir o erro. Mesmo quando escolho um atendente com acordo vinculado, como a SEDGET (no ambiente desenv).

**Comment by rafaela00castro** [comment]
último teste realizado no dia 18/09/15 às 19:20. Novamente não consegui reproduzir o erro reportado.
