### ISSUE TITLE
[SIGA-GI] Verificar permissão de acesso aos submenus do GI

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#367]
- Submenus liberados para acesso como Rafaela (SEDGET) em siga/siga
![captura_sem_titulo_080415_012554_pm](https://cloud.githubusercontent.com/assets/8461113/9066154/57c02c66-3aac-11e5-993a-437f0acab6cf.jpg)

- Submenus liberados para acesso como Rafaela (SEDGET) em classec250:8380 (produção com vraptor)
![captura_sem_titulo_080415_013632_pm](https://cloud.githubusercontent.com/assets/8461113/9066411/d3ff6aac-3aad-11e5-9245-356024064b32.jpg)

**Comment by andresousa17** [comment]
O erro estava pois o projeto siga não estava passando pelo filtro HiternateThreaFilter antes das solicitações
