### ISSUE TITLE
[Siga-sr] Atualizar cache ao alterar designação

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#368]
Após alterar o atendente de uma designação, essa alteração não é refletida na listagem de Ações + Atendentes na tela de Cadastro de Solicitações.
É necessário atualizar o cache após gravar uma designação.

**Comment by rafaela00castro** [comment]
No caso, a alteração da designação foi realizada na spin:8080/siga. No endereço siga/siga a listagem de Ações + Atendente aparece atualizada. Na classec250:8480/siga não...

**Comment by esredson** [comment]
@rafaela00castro, isso também está acontecendo com os outros tipos de configuração. Está sendo necessário reiniciar o servidor para as configurações valerem. Amanhã, se você não estiver trabalhando nesse problema, dou uma olhada.

**Comment by rafaela00castro** [comment]
Resolvido pelo Edson no commit: [1a9d53d]
