### ISSUE TITLE
DOC: Erro ao clicar nos despachos pendentes de assinatura

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#370]
Foi reportado pelo George (email qua 05/08/2015 13:22) que ocorreu o erro NoClassDefFoundError ao clicar nos despachos pendentes de assinatura conforme imagem abaixo. O erro é intermitente e após teclar F5 a página foi exibida corretamente.

![erro_siga](https://cloud.githubusercontent.com/assets/2985140/9091483/f2dabb74-3b76-11e5-9e3c-f5e769a195d3.png)

**Comment by crivano** [comment]
Fechado por ser igual ao #389
