### ISSUE TITLE
SIGA-DOC: pdfs anexados estão com a marca de "inválido"

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#372]
Provavelmente é apenas uma configuração e não deve impactar quando for efetivamente para a produção. Issue aberta apenas por desencargo de consciência.

![image](https://cloud.githubusercontent.com/assets/2985140/9099119/96373e64-3ba4-11e5-802f-a07ebef6d767.png)

**Comment by crivano** [comment]
Oi, isso é uma configuração para que não haja confusão entre os documentos
da base de produção e das outras bases.

Em qua, 5 de ago de 2015 às 19:03, Markenson <notifications@github.com>
escreveu:
