### ISSUE TITLE
[Siga-Doc] Modelo e outros itens estão habilitados para edição com o documento finalizado  

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#376]
Em siga/siga

![captura_sem_titulo_080715_014355_pm](https://cloud.githubusercontent.com/assets/8461113/9140831/598c6bee-3d0a-11e5-9bf7-541058b81cae.jpg)

Em classec250:8380/siga

![captura_sem_titulo_080715_014505_pm](https://cloud.githubusercontent.com/assets/8461113/9140844/83d4e552-3d0a-11e5-8c9f-edfd267d78d4.jpg)

**Comment by rafaela00castro** [comment]
@andresousa17 não vou "descartar" o documento agora para vc usá-lo como teste. 
Acessar: http://classec250:8380/sigaex/app/expediente/doc/editar?sigla=TRF2-MEM-2015/03899&

**Comment by andresousa17** [comment]
@rafaela00castro  Não consegui testar neste documento porque está dando erro ao apontar para a produção, mas eu tinha outros documentos na base de desenvolvimento e funcionou. Se quiser pode cancelar este seu documento. Obrigado.
