### ISSUE TITLE
SIGA: Session is closed

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#379]
Após ocorrer uma exception o sistema apresenta "Session is closed" de forma intermitente. 

Pensávamos que inicialmente (issue #374) só ocorria na funcionalidade de substituição, mas ocorreu com  @andresousa17 apenas ao navegar entre o siga-sr e a página inicial.

**Comment by andresousa17** [comment]
O erro estava pois o projeto siga não estava passando pelo filtro HiternateThreaFilter antes das solicitações
