### ISSUE TITLE
SIGA: Assinatura digital não funciona com o sistema rodando atrás do Apache

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#385]
A página de assinatura digital está fazendo referência explícita do nome do servidor/porta o que causará problema durante o processo de assinatura digital se o sistema estiver rodando atrás do apache. Quando a página é retornada a variável jspserver (dentre outras) utiliza a informação do servidor que está atendendo a requisição. Quando a versão entrar no load balancer, provavelmente essa informação mudará a cada servidor que responder a requisição.

Precisamos identificar também se existe esse tipo de referência em outros pontos do sistema.

Veja, por exemplo, https://github.com/projeto-siga/siga/blob/vraptor/sigaex/src/main/webapp/WEB-INF/page/exMovimentacao/aAssinar.jsp#L84

**Comment by hodrigohamalho** [comment]
@Markenson já tinha corrigido esse comportamento na versão antes do vraptor  fd5ce94b41c381e4dfb469966c66fc40f72d6a2a . Vou Refazer o merge desses arquivos.

**Comment by Markenson** [comment]
Obrigado @hodrigohamalho!

**Comment by crivano** [comment]
Pessoal, acho que isso já está corrigido no branch bluc. Mas, como ainda
não decidimos ser irá para a produção agora, precisará ser refeito.

Em qui, 20 de ago de 2015 às 16:50, Markenson <notifications@github.com>
escreveu:

**Comment by Markenson** [comment]
Beleza, @crivano! Se lembra de algum local que tenha algo parecido que deveríamos testar?

**Comment by crivano** [comment]
Oi, @markenson, não me lembro de nenhum outro lugar...

Em qui, 20 de ago de 2015 às 18:53, Markenson <notifications@github.com>
escreveu:

**Comment by Markenson** [comment]
Rodrigo corrigiu no commit 3424764e191725e5640ea5ce8087bbdab7a663b0
