### ISSUE TITLE
DOC: Problemas nos modelos desenvolvidos com JSP + webwork  

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#388]
Exemplo desse tipo de problema foi relatado no chamado JFRJ-SR-2015/16103 (http://siga/sigasr/solicitacao/exibir/37152):

"O formulário Publicação DJE (geral - o acessado pela SID-CIPE-SEPED, que é mais completo) está com um pequeno bug no campo [tipo de matéria]: se por algum motivo precisamos editar ou alterar qualquer outro campo ou o próprio formulário ele reseta a seleção feita e muda para "ato", que é a primeira opção. Precisamos por isso ficar sempre corrigindo e colocando o tipo de matéria de novo."

Como resolver: Migrar código específico do webwork para vraptor.

**Comment by andresousa17** [comment]
Este problema foi corrigido no commit 2af3b73505a68d0e935ecc8f9b3980f9fcad0328
