### ISSUE TITLE
SR: Tela em branco ao fazer refresh na página

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#391]
A tela fica da seguinte maneira ao clicar F5 no navegador:

![image](https://cloud.githubusercontent.com/assets/2985140/9471835/93ac0ed4-4b28-11e5-80e7-24db92c30f0e.png)

**Comment by Markenson** [comment]
Ao exibir o código fonte no final da página, o seguinte erro foi ocultado:

```
	Erro: javax.el.ELException: JBWEB006013: Error calling function ''f:podeGerirAlgumGrupo''<br>
		<br>
		<br>
	
		<pre>
	Erro original:
	</pre>

```

**Comment by Markenson** [comment]
Detalhe extra: eu estava substituindo um usuário, conforme a imagem.

**Comment by Markenson** [comment]
O erro ocorre ao acessar o SIGA-SR

**Comment by rafaela00castro** [comment]
Na verdade o erro ocorre ao montar o menu por dentro do módulo siga-serviços. Erro similar acontece no GC #400 

![captura_sem_titulo_082815_073450_pm](https://cloud.githubusercontent.com/assets/8461113/9558411/d9c9fe90-4dbb-11e5-951d-f0a05e8f9cc0.jpg)

**Comment by rafaela00castro** [comment]
Issue resolvida no commit  [509ba28]

**Comment by kmacedovarela** [comment]
:smiley: Que bom!! 
Sugiro fazer deploy em homologação para corrigir outras também outras aplicações como sigatp e sigade
