### ISSUE TITLE
DOC:  Visualização de portaria na fila do BIE

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#395]
O seguinte erro foi reportado por Sonia Pestana, por e-mail, qua 26/08/2015 14:23.

Ao clicar na portaria da fila do BIE pra ver o conteúdo, ele dá erro:

![image](https://cloud.githubusercontent.com/assets/2985140/9532756/f8fa7066-4ce3-11e5-8f28-4ca65c959be7.png)

**Comment by andresousa17** [comment]
Os modelo e as urls serão corrigidos posteriormente na issue #302
