### ISSUE TITLE
DOC: BIE gerado sem a imagem do cabeçalho

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#396]
Reportado por Sonia Pestana, por email/lync, qua 26/08/2015 17:31:

"(...) BIE foi gerado sem a imagem do cabeçalho..."

![image](https://cloud.githubusercontent.com/assets/2985140/9532877/a9b85800-4ce4-11e5-9076-a1386e158ee5.png)

**Comment by andresousa17** [comment]
O problema foi resolvido no commit SHA: cf4f0c3f61e0eb7cc0e2e56fc7a17a4c1aac8ad0
