### ISSUE TITLE
DOC: Modelo em JSP com ww:

### ISSUE THREAD

**Issue by andresousa17** [projeto-siga/siga#403]
Alguns modelos que estão em produção mas aind estão com JSP estão fazendo referência a componentes do webwork

**Comment by andresousa17** [comment]
Erro foi descoberto através do chamado JFRJ-SR-2015/16103

**Comment by crivano** [comment]
Falei com o André e os que ainda fazem referência ao WebWork são modelos que não usamos mais na produção.
