### ISSUE TITLE
GI: Não consigo logar com minha matrícula

### ISSUE THREAD

**Issue by crivano** [projeto-siga/siga#405]
Digo que esqueci a senha e recebo uma senha que depois o próprio Siga não reconhece. Será que alguém pode testar para ver se o problema é específico comigo?

**Comment by crivano** [comment]
Isso acontece na SIGAT...

**Comment by andresousa17** [comment]
@crivano era um problema com seus dados na tabela de identidade. Já foi corrigido.Você já pode pedir nova senha. 
Se a senha não chegar espera um pouco para limpar o cache pois tive que mudar seu email para o sistema enviar para o meu email.
