### ISSUE TITLE
DOC: As marcas não são apresentadas corretamente no quadro de vias

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#409]
Reportado por Simone, via telefone. Documento de exemplo: TRF2-MCI-2015/00028

![image](https://cloud.githubusercontent.com/assets/2985140/9738704/235cde6e-5623-11e5-999a-dee16add0cfa.png)

**Comment by crivano** [comment]
Testar depois que estiver no canário.

**Comment by crivano** [comment]
Gostei de ver: trabalho em conjunto! :)

Em qui, 4 de fev de 2016 18:55, Markenson <notifications@github.com>
escreveu:
