### ISSUE TITLE
IDP: Definir como será disponibilizada a KeyStore

### ISSUE THREAD

**Issue by crivano** [projeto-siga/siga#412]
Para que o IDP possa funcionar com o GSA (Google Search Appliance), precisei habilitar a assinatura digital, XML-DSIG, da assertion. E, para que ocorra a assinatura, é necessário referenciar um arquivo do tipo "keystore" no picketlink.xml, bem como fornecer as senha de acesso.

```
	<PicketLinkIDP xmlns="urn:picketlink:identity-federation:config:2.1"
                   SupportsSignatures="true">
		<IdentityURL>${idp.url::http://localhost:8080/sigaidp/}</IdentityURL>
		<Trust>
			<Domains>google.com,172.16.1.105,${idp.trusted.domains::localhost}</Domains>
		</Trust>
		<KeyProvider
			ClassName="org.picketlink.identity.federation.core.impl.KeyStoreKeyManager">
			<Auth Key="KeyStoreURL" Value="/jbid_test_keystore.jks" />
			<!-- <Auth Key="KeyStorePass" Value="store123" /> -->
			<Auth Key="KeyStorePass" Value="MASK-O1P+U1Domeec8lCaoIkTGg==" />
			<!-- <Auth Key="SigningKeyPass" Value="test123" /> -->
			<Auth Key="SigningKeyPass" Value="MASK-AJbh4WmHwy8=" />
			<Auth Key="SigningKeyAlias" Value="servercert" />
			<Auth Key="salt" Value="18273645" />
			<Auth Key="iterationCount" Value="11" />
			<ValidatingAlias Key="localhost" Value="servercert" />
			<ValidatingAlias Key="127.0.0.1" Value="servercert" />
			<ValidatingAlias Key="csis-trf-10" Value="servercert" />
 			<ValidatingAlias Key="10.34.5.76" Value="servercert" />
		</KeyProvider>
	</PicketLinkIDP>
```

As questões são:
1) Como faremos a configuração das propriedades SupportsSignatures, KeyStorePass, etc?
2) Como e onde faremos o deploy do arquivo jbid_test_keystore.jks?

**Comment by crivano** [comment]
Seria muito bom se pudéssemos ter isso funcionando logo, pois facilitaria muito os testes que estamos fazendo de integração entre o GSA e o SIGA-DOC.

**Comment by kmacedovarela** [comment]
Olá @crivano ,

Conforme alinhamos:

As propriedades podem ser descritas da seguinte maneira no picketlink.xml:
<Auth Key="KeyStorePass" Value="${idp.kspass::setadefaultkeypass}" />

E no JBoss, podemos setar os respectivos valores, através de system properties. 

A respeito do path, iremos usar o path absoluto a princípio. Já temos um diretório padrão nos três ambientes que inclusive já é utilizado para este proposito.

**Comment by crivano** [comment]
Picketlink.xml do IDP alterado nesse commit:

https://github.com/projeto-siga/siga/commit/90c358c8c99a046dfe8dd6d777d37a0cfd65ada9

**Comment by crivano** [comment]
Exemplo de propriedades para configurar o IDP para assinar com o [certificado de exemplo] (https://github.com/jboss-developer/jboss-picketlink-quickstarts/tree/master/picketlink-federation-saml-idp-with-signature/src/main/resources) do picketlink quickstarts:

```
        <property name="idp.url" value="http://localhost:8080/sigaidp/"/>
        <property name="idp.supports.signatures" value="true"/>
        <property name="idp.keystore.url" value="/jbid_test_keystore.jks"/>
        <property name="idp.keystore.pass" value="MASK-O1P+U1Domeec8lCaoIkTGg=="/>
        <property name="idp.signing.key.pass" value="MASK-AJbh4WmHwy8="/>
        <property name="idp.signing.key.alias" value="servercert"/>
        <property name="idp.salt" value="18273645"/>
        <property name="idp.iteration.count" value="11"/>
        <property name="idp.validating.alias.1" value="csis-trf-10"/>
        <property name="idp.validating.alias.2" value="10.34.5.76"/>
        <property name="idp.validating.alias.3" value="10.34.5.76"/>
```

**Comment by crivano** [comment]
Além disso, para que possamos gerar member-of attributes para o GSA, precisamos alterar o rolesQuery do JBoss para isso aqui:

```
<module-option name="rolesQuery" value="with ids as (select p.id_pessoa_inicial pid, l.id_lotacao_ini lid, i.id_orgao_usu ouid from cp_identidade i, dp_pessoa p, dp_lotacao l where i.login_identidade = ? and i.id_pessoa = p.id_pessoa and l.id_lotacao = p.id_lotacao and i.his_dt_fim is null and data_cancelamento_identidade is null) select 'sigausuario', 'Roles' from dual union select case n when 1 then 'P' || ids.pid when 2 then 'L' || ids.lid when 3 then 'O' || ids.ouid end as value, 'Roles' from (select rownum n from (select 1 from dual connect by level &lt;= 3)) ofs, ids union select sigla_grupo, 'Roles' from ids, dp_pessoa ps, cp_grupo g, cp_configuracao c where c.id_pessoa = ps.id_pessoa and ps.id_pessoa_inicial = ids.pid and c.id_grupo = g.id_grupo and c.dt_fim_vig_configuracao is null and g.id_tp_grupo = 3 and c.id_tp_configuracao = 203"/><module-option name="hashAlgorithm" value="MD5"/>
```

**Comment by Markenson** [comment]
@crivano e @kmacedovarela como ficou a versão final das configurações necessárias? Precisamos lançar na página de versões do siga e atualizar a imagem do docker.

**Comment by crivano** [comment]
@Markenson , caso as propriedades sejam omitidas, o idp funciona como fazia antes, sem assinar as assertivas. No caso do próprio SIGA, as assertivas não precisam ter assinatura. Portanto, sugiro que a imagem do docker não seja alterada.

As propriedades que foram incluídas são exatamente essas acima, para fins de documentação. Posso lançar na página de versões ou vc faz?

**Comment by Markenson** [comment]
@crivano Pelo menos adiante, acho que colocar no docker seria uma boa para não afastarmos muito a configuração do nosso ambiente de produção. 

Além das propriedades o que você acha de criarmos uma página no wiki explicando brevemente como funciona essa integração do GSA com o SIGA? Seria uma oportunidade para todos entenderem (e até para esclarecer para órgãos que queiram usar no futuro).

**Comment by Markenson** [comment]
@crivano Se quiser, eu posso tentar fazer e depois você dá um corrigida. Com isso, posso tentar entender como funciona. O que acha?

**Comment by crivano** [comment]
@Markenson , acho uma ótima! Podemos fazer juntos. Começa aí e me avisa que complemento.

**Comment by Markenson** [comment]
Beleza, então!
