### ISSUE TITLE
DOC: Ao refazer BIE as informações resumidas da publicação não são exibidas

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#418]
Reportado por Sonia Pestana, via e-mail (seg 21/09/2015 16:57):

Devido ao ocorrido na semana passada, as portarias efetivamente publicadas em 15-09, após o “refazimento”, mantém o devido andamento de  publicadas PORÉM perderam a informação na tela inicial do documento, à direita

Exemplo: JFRJ-POR-2015/00641

![img1](https://cloud.githubusercontent.com/assets/2985140/10023450/9a302ad6-6128-11e5-96dd-6c719bd902c4.png)

Como deveria aparecer (ilustrando, como exemplo, usando a POR644):
![img2](https://cloud.githubusercontent.com/assets/2985140/10023453/a0923392-6128-11e5-9484-8bfc0c6f7ccf.png)

**Comment by andresousa17** [comment]
Ao duplicar BIE os documentos estavam saindo de um boletim e indo para o outro.
