### ISSUE TITLE
SR: Na versão vraptor, ao fechar solicitação, além de ser exibida mensagem de erro (que também ocorre na versão Play), o fechamento não se efetiva

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#419]

**Comment by rafaela00castro** [comment]
@esredson vc estava certo, não era o problema da pendência estar ativa ao fechar automaticamente. Na versão vraptor o terminar pendencia estava ocorrendo antes de fechar. O problema era fechar automaticamente a solicitação principal que já estava fechada.
