### ISSUE TITLE
DOC: Atualização de dados para BIE/DJE

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#424]
O seguinte problema foi relatado por Sonia Pestana (email, qua 23/09/2015 15:00):

"(...) Os campos com nome do DIRFO e áreas precisam ter os conteúdos atualizados"

**Comment by esredson** [comment]
Os dados aparentemente já foram atualizados. Estão conforme o BIE disponível na axor. Caso necessário, podem abrir chamado informando os novos dados. De qualquer forma, trata-se de mudar o default, pois o gestor, ao produzir o BIE, tem a opção de alterar os dados que vêm preenchidos automaticamente nos campos da entrevista.
