### ISSUE TITLE
DOC: Pesquisa de configurações por órgão está retornando todos os órgãos

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#427]
![image](https://cloud.githubusercontent.com/assets/2985140/10197964/4e80cf34-6770-11e5-8b89-df50678c525d.png)

![image](https://cloud.githubusercontent.com/assets/2985140/10197992/683d8afc-6770-11e5-8f35-dd6ac812936b.png)

**Comment by andresousa17** [comment]
Corrigido
