### ISSUE TITLE
DOC: Problema na pesquisa por data e signatário

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#429]
Foi reportado por Sonia Pestana (email tssesia@ qua 30/09/2015 16:01):
"(...)
Tenho tido problemas com as buscas no SIGA-DOC e hoje pude pegar um caso concreto para melhor rastreamento.

Por exemplo: eu sei que existe um memorando (JFRJ-MEM-2015/11147) que foi finalizado e assinado hoje pela Diretora, matrícula 15544.

No entanto, se eu tento chegar nele por meio da busca, colocando a data e o signatário, a pesquisa não traz nenhum resultado.
"

![image](https://cloud.githubusercontent.com/assets/2985140/10204735/d76b821c-6793-11e5-847a-c2661fbcb627.png)

![image](https://cloud.githubusercontent.com/assets/2985140/10204763/0944c55a-6794-11e5-9443-bbd8e996c1de.png)

**Comment by andresousa17** [comment]
Corrigido
