### ISSUE TITLE
Testar transferência com pendências de assinatura

### ISSUE THREAD

**Issue by andresousa17** [projeto-siga/siga#432]
Testar se documentos digitais com pendências de assinaturas de anexo e despacho está funcionando corretamente

- [ ] Anexos pendentes de assinatura
- [ ] Despachos pendentes de assinatura

**Comment by Chrystinne** [comment]
@andresousa17 Testei essa funcionalidade na siga-dev:8380. Está sendo possível transferir documentos com anexo pendente de assinatura.
Testei no TRF2-MEM-2015/05065.

**Comment by Chrystinne** [comment]
![captura_de_tela_100515_031134_pm](https://cloud.githubusercontent.com/assets/4949149/10289156/5eba3726-6b73-11e5-9160-e27eae639554.jpg)

**Comment by Chrystinne** [comment]
Também está permitindo transferir o documento com despacho pendente de assinatura. Testei com o TRF2-MEM-2015/05066.

**Comment by Chrystinne** [comment]
![captura_de_tela_100515_031633_pm](https://cloud.githubusercontent.com/assets/4949149/10289305/11024626-6b74-11e5-80de-f2481962c3ce.jpg)

**Comment by Chrystinne** [comment]
![captura_de_tela_100515_031720_pm](https://cloud.githubusercontent.com/assets/4949149/10289327/2c8cfa44-6b74-11e5-9c24-d7b45afe0155.jpg)

**Comment by andresousa17** [comment]
@Chrystinne tem que verificar se a máquina possui a seguinte propriedade cadastrada
siga.ex.dataInicioObrigacaoDeAssinarAnexoEDespacho

O siga só exige assinatura de documentos que foram feitos depois dessa data. Quando a data não existe ele deixa transferir qualquer documento.

Você pode testar na sua máquina colocando essa propriedade.

**Comment by Chrystinne** [comment]
@andresousa17 Blz. Vou testar.

**Comment by Chrystinne** [comment]
@andresousa17 Fiz os teste. Acrescentei a propriedade siga.ex.desenv.dataInicioObrigacaoDeAssinarAnexoEDespacho=01/01/2015 no siga.properties e estou aopntando pra desenv, mas continua dando o mesmo erro.

**Comment by Chrystinne** [comment]
@andresousa17 Agora sim, funcionou. 

Neste caso, como você falou, para resolver este problema, é só incluir a propriedade no siga.properties:

siga.ex.dataInicioObrigacaoDeAssinarAnexoEDespacho=[DATA]

com a mesma data  que está definida hoje na produção.

**Comment by Chrystinne** [comment]
![captura_de_tela_100515_065015_pm](https://cloud.githubusercontent.com/assets/4949149/10294682/380a836e-6b92-11e5-8308-b0cb563d8b5e.jpg)

**Comment by andresousa17** [comment]
@Chrystinne agora está correto. Temos que pedir ao Luiz Antônio para verificar a data que está na produção e o @Markenson  pode cadastrar na classec250.

**Comment by crivano** [comment]
@Markenson , @andresousa17 e @Chrystinne , essa issue já pode ser fechada?

**Comment by Chrystinne** [comment]
@crivano Mandei e-mail pro @luiz-antonio pedindo pra ele verificar e, se necessário, adicionar a propriedade no canário.

**Comment by crivano** [comment]
@Chrystinne , tks.

**Comment by Chrystinne** [comment]
A versão canário ainda não possuía a propriedade siga.ex.dataInicioObrigacaoDeAssinarAnexoEDespacho. @raphaelpaiva a criou com o mesmo valor da versão 4.x. A atualização irá ocorrer no próximo reboot do Jboss, às 19h.

**Comment by Chrystinne** [comment]
Resultado do teste, após a adição da propriedade: 

![impede_transferencia_de_docs_com_pendencia](https://cloud.githubusercontent.com/assets/4949149/12784499/a9920c38-ca6e-11e5-8efe-a9793c263049.png)
