### ISSUE TITLE
DOC: Lista de lotações não é exibida ao agendar publicação no DJE

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#440]
Ao agendar publicação no DJE, caso o formulário a ser publicado tenha, por exemplo, o prefixo "RJ" no nome da lotação, a lista de lotações e o botão "agendar publicação" não é exibido.

**Comment by adrigrassi** [comment]
Na realidade, a criação de um documento de publicação no DJE sendo o subscritor de um órgão e a lotação de origem de outro orgão, momento em que acontece o erro, não ocorre em produção. Esse erro é passível de ocorrer também quando duplicamos um documento deste tipo onde a lotação de origem está extinta. Porém também é uma situação inusitada.
