### ISSUE TITLE
DOC: Pesquisa e Visualização de Documentos

### ISSUE THREAD

**Issue by teulalio** [projeto-siga/siga#442]
Srs,

A pesquisa por documentos no SIGA DOC exibe várias vezes o mesmo DOC, a qtde está relacionada a situação que o mesmo encontra-se e/ou já passou. Tem que ser assim mesmo?

Não seria melhor visualizar apenas uma linha com as informações mais recentes sobre o documento?
O usuário que quiser mais detalhes sobre o "ciclo de vida" do DOC teria que clicar no mesmo.

A tela abaixo mostra a pesquisa para 1 documento, mas e qdo a base de dados crescer, a tela vai ficar muito extensa.

![sigaresultpesquisa](https://cloud.githubusercontent.com/assets/11743297/10318623/bb513d2c-6c40-11e5-9775-c017ca8021cf.png)

Atc,

**Comment by crivano** [comment]
Olá Teulalio,

Realmente nesse caso parece um pouco confuso, mas não vejo como melhorar isso.

Essa pesquisa localiza várias vias e indica, quando é o caso, a situações diferentes que uma mesma via pode ter.

No exemplo que você mandou, fica claro que ela está aguardando andamento na UIAPL mas está com prazo estourado e deve ser encaminhada para a SETIC. Assim que for encaminhada, o número de linhas será bem menor. Apresentará apenas a informação que está aguardando andamento na SETIC.

Existe a possibilidade de ocultamos algumas marcações, como é feito no SIGA-Gestão de Conhecimento, será que você se anima para fazer essa contribuição?

Como anda a implantação aí no TJPE?

Abs, Renato
