### ISSUE TITLE
SR: na coluna teor na lista de prioridade do SIGA-GO está aparecendo "item não informado"...

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#445]
...mesmo o item existindo quando vc entra na solicitação.
![captura_de_tela_100715_023727_pm](https://cloud.githubusercontent.com/assets/8461113/10345556/eed6884e-6d00-11e5-8620-5a5ce6dcc6c0.jpg)

**Comment by esredson** [comment]
Não ocorre mais.
