### ISSUE TITLE
Cabeçalho do SIGA com texto diferente

### ISSUE THREAD

**Issue by rodrigo-ferreira** [projeto-siga/siga#447]
Senhores,

Observei que o cabeçalho está apresentando caracteres estranhos e diferente entre os ambientes. 
Já verificamos as propriedades no Jboss de homologação e não encontramos nada de estranho.

Segue abaixo a imagem do ambiente de homologação:
![logohmg](https://cloud.githubusercontent.com/assets/13545857/10373795/f71d21f0-6dc5-11e5-8440-f95ff8fd4da5.PNG)

Aqui temos a imagem do ambiente de produção:
![logoprog](https://cloud.githubusercontent.com/assets/13545857/10373801/fda5d396-6dc5-11e5-9c26-bd9670fa3690.PNG)

**Comment by rafaela00castro** [comment]
Olá pessoal!
Favor acrescentar a property abaixo na versão vraptor:
```
siga.cabecalho.titulo=Justiça Federal
```
 E acertá-la nas máquinas de produção!

**Comment by kmacedovarela** [comment]
Obrigada Rafaela vamos verificar.
