### ISSUE TITLE
GI: criar uma forma de buscar dados de usuário sem a necessidade de informar sua senha

### ISSUE THREAD

**Issue by baylon** [projeto-siga/siga#449]
Precisamos de uma forma de buscar os mesmos dados retornados pelo método 

_public String login(String matricula, String senha)_

do web service 

siga-cp/src/main/java/br/gov/jfrj/siga/gi/service/impl/GiServiceImpl.java

sem a necessidade de informar a senha; como a autenticação do módulo GO (desenvolvido em .NET) será realizada pelo SIGA-IDP, não teremos mais acesso à senha do usuário.

Conforme conversa com @Markenson , pensamos em 3 opções de solução:

1 - retornar o mesmo JSON pelo próprio IDP, como resposta ao login: foi descartada por implicar no tráfego dos dados do usuário pela rede.

2 - criar um método que simplesmente não peça a senha: criei na minha branch do siga, em

https://github.com/baylon/siga/commit/9924a810adb3a08d2ad633c75134bd850b40bed5

o método 

_public String dadosUsuario(String matricula)_

porém acredito que qualquer usuário / sistema que tenha acesso ao web service terá acesso a esses dados relativos a qualquer usuário de que se conheça a matrícula; preciso da ajuda de vocês para dimensionar o quão problemático é isso.

3 - solução 2 + desenvolver alguma solução de assinatura / segurança para o web service, o que demanda tempo + esforço.

Criei a issue para incluirmos o @crivano na conversa.

**Comment by crivano** [comment]
Opção 4: incluir no resultado SAML todas essas informações.

De qualquer forma, acho que o método 2 também funciona, desde que não haja nenhuma informação confidencial. O que acredito ser o caso.

Que tal implementarmos o método 2 e fecharmos a issue?

**Comment by Markenson** [comment]
@crivano e @baylon 

Se não for necessário, para o item 2 é melhor tirar informações como rg, cpf e endereço.

**Comment by baylon** [comment]
@crivano a opção 4 seria a opção 1 que eu não soube explicar direito. 

As informações que estão hoje protegidas por senha são institucionais - IDs de pessoa, nome, e-mail, dados de lotação, de cargo e de função de confiança. Concordo que não são sensíveis ao servidor mas sim à instituição. 

Posso pedir o merge desse branch em que já implementei a solução 2, o que acham?

**Comment by crivano** [comment]
Com certeza @Markenson , endereço nem pensar! :)

**Comment by crivano** [comment]
@baylon Sim, pode mandar o pull-request! Ou fazer o merge direto se preferir. :)
