### ISSUE TITLE
DOC: Email de Transferência de Documentos Físicos

### ISSUE THREAD

**Issue by andresousa17** [projeto-siga/siga#460]
Fiz transferência de um documento físico na máquina hmg e o sistema enviou email. JFRJ-FOR-2015/00106-A

**Comment by crivano** [comment]
@andresousa17 , qual é exatamente o problema?

**Comment by andresousa17** [comment]
@crivano em documentos físicos o sistema não deveria mandar email de transferência.

Eu criei essa issue para verificar se é um  erro no código da migração do vraptor ou alguma configuração na máquina da hmg.

**Comment by crivano** [comment]
@andresousa17 , tks.
