### ISSUE TITLE
DOC: importar documentos via SMTP

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#462]
Permitir que o SIGA-DOC capture um documento enviado por e-mail.

**Comment by crivano** [comment]
@Markenson , considerando que é um tipo de documento capturado, se desejar posso pegar essa issue para fazer.

**Comment by Markenson** [comment]
Beleza, pode pegar então.

**Comment by esredson** [comment]
TRF2-SR-2016/33901
