### ISSUE TITLE
GERAL: Tornar os gráficos do SIGA opcionais

### ISSUE THREAD

**Issue by crivano** [projeto-siga/siga#463]
Em algumas situações os gráficos podem ocupar tempo/banda desnecessariamente. A pedido de Gustavo e George, podemos fazer com que sejam opcionais. Talvez colocando um cookie no browser para indicar que devem ser desabilitados ou usando outra estratégia.

**Comment by crivano** [comment]
Uma opção ainda melhor consiste em gerar os gráficos em um micro-service. Dessa forma não sobrecarrega nem a rede nem o browser.

**Comment by raphaelpaiva** [comment]
Como é feito hoje? (só curiosidade, não tem pressa pra responder :))

**Comment by crivano** [comment]
@raphaelpaiva usamos uma biblioteca JS chamada viz.js. A conversão do formato .DOT do GraphViz para SVG é feita pelo browser.

**Comment by crivano** [comment]
@raphaelpaiva, @luiz-antonio e @markenson: encontrei um micro-service disponível em Docker que faz exatamente a conversão de SVG para DOT. Existe alguma chance de levantarmos esse serviço para que possamos resolver está issue?

**Comment by esredson** [comment]
Acredito que não se aplique mais, visto que o Renato já deixou a carga assíncrona.
