### ISSUE TITLE
Siga-Sr: Erro ao tentar entrar na lista de chamados

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#465]
Estou tendo este erro desde ontem. Ocorreu algumas vezes. Quando dou refresh, volta ao funcionamento normal.

![captura_de_tela_102315_112713_am](https://cloud.githubusercontent.com/assets/4949149/10693790/381a853a-7979-11e5-86d9-c00bfe1894ac.jpg)

**Comment by Chrystinne** [comment]
@esredson @kmacedovarela Vcs tem tido esse erro tb?

**Comment by esredson** [comment]
Comigo sempre aconteceu algo parecido, que ainda não vi em outro ambiente a não ser o meu, mas que talvez tenha alguma ligação com esse aí. Quando eu interrompo a execução num debug e deixo pausado por muito tempo, passa a ocorrer de modo intermitente o erro "ABORTED is not a valid state"
