### ISSUE TITLE
DOC: Não é possível acessar uma via após a letra Z

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#470]
O SIGA tem um limite de vias, pois permite apenas a via A até a via Z. Quando um número superior de vias é criada, o usuário fica com problemas para acessá-la.

Por exemplo:

Imagem 1:
![image](https://cloud.githubusercontent.com/assets/2985140/10771148/5fc89418-7cd6-11e5-9584-513128d0c1aa.png)

Imagem 2:
![image](https://cloud.githubusercontent.com/assets/2985140/10771242/e7076814-7cd6-11e5-9d7a-f0fdf53a3634.png)

Imagem 3:
![image](https://cloud.githubusercontent.com/assets/2985140/10771164/75d358ba-7cd6-11e5-8bae-098e0c978778.png)

Imagem 4:
![image](https://cloud.githubusercontent.com/assets/2985140/10771210/b758b442-7cd6-11e5-9698-0a339e5759f6.png)

**Comment by crivano** [comment]
@Markenson, o problema aqui não é acessar um via além da letra Z, mas sim que elas não poderia ter sido criadas. Vou acrescentar uma validação para impedir a criação de mais de 20 vias!

**Comment by Markenson** [comment]
@crivano Mas o que fazer se forem necessárias mais de 20 vias?

**Comment by crivano** [comment]
@Markenson: o conceito de via não foi criado para que existam infinitas cópias. Para isso, serão necessárias outras implementações. Em especial, já está no topo da lista de demandas da SED a criação do conceito de cópia. A quantidade de cópias será ilimitada.

**Comment by crivano** [comment]
@Markenson: só para complementar, já havia uma restrição na quantidade de vias, o problema é que por algum motivo conseguiram burlá-la.

**Comment by Markenson** [comment]
@crivano Beleza!
