### ISSUE TITLE
Pesquisa de classificação com palavras acentuadas

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#48]
Ao digitar uma palavra acentuada no campo "Classificação documental" ao criar um novo documento o texto está com o encoding alterado. Por exemplo, ao digitar a palavra "férias" abre-se a janela de pesquisa com a palavra "FÃ©RIAS".

**Comment by kmacedovarela** [comment]
O problema de encoding foi resolvido em 92079df090efc70aafc9990cc383013318fe834b
