### ISSUE TITLE
GC: erro ao criar link quando tem uma classificação

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#481]
Bernardo tentou criar um link externo no conhecimento TRF2-GC-2015/00107 através do botão de hiperlink do ckeditor. E recebeu um erro de "java.NullPointerException".

![captura_de_tela_110415_082933_pm](https://cloud.githubusercontent.com/assets/8461113/10976425/ed281506-83d2-11e5-9dfe-3387ad3e9a85.jpg)

Ao retirar a classificação, [ @servico, @sr-item-1-21:softwares, @sr-item-2-85:softwares-aplicativos-e-sistemas-operacionais-para-estacao-de-trabalho, @sr-item-3-84:microsoft-windows, #SETMIC, #software, #programa ], conseguiu criar o link.

**Comment by rafaela00castro** [comment]
Observação do Edson: verificar se esse conhecimento está estourando o tamanho do campo classificação no banco. Às vezes o tamanho fica muito limitado pra classificação.

**Comment by esredson** [comment]
Se estiver relacionado, ver issue #576

**Comment by Chrystinne** [comment]
Provavelmente esse erro está relacionado com a issue 576 sim. A SEABAD vai fazer a alteração que resolve a 576 na produção, hoje, após o expediente. Amanhã volto a testar a criação de links externos pra verificar se o problema foi resolvido.

**Comment by Chrystinne** [comment]
Como a #576 já foi resolvida e acredito que era aquele erro que causava o problema reportado aqui nessa issue, vou fechá-la.
