### ISSUE TITLE
DOC: Formulário de entrada de pessoal não seleciona data

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#482]
Ao elaborar um documento Fomulário/Entrada de Pessoal, ao selecionar uma data através do calendário, o sistema mantém o campo em branco. 

A maneira alternativa de resolver o problema é digitar o valor na própria caixa.

![image](https://cloud.githubusercontent.com/assets/2985140/11007780/6442ab0c-84b3-11e5-863a-27db00d62e49.png)

**Comment by crivano** [comment]
Constatei que basta trocar em default.ftl, na macro "data", onblur por onchange="javascript:verifica_data(this, true);${jreler!}". Farei a alteração no default.ftl, mas ainda assim será necessário alterar no bd de produção e de homologação.

**Comment by crivano** [comment]
Já foi alterado na homologação e só poderemos alterar na produção quando estiver concluído: TRF2-SR-2016/20059

**Comment by raphaelpaiva** [comment]
@crivano 

Os valores estão iguais tanto no apache quanto no jboss. Em ambos ambientes estão com o valor padrão: ilimitado e 2MB, respectivamente. Posso aumentar no JBoss, tem idéia do tamanho do post?

Sabe onde/quando foi alterado em homologação? Chequei as configurações do domain e do apache...

**Comment by crivano** [comment]
@raphaelpaiva: agora funcionou perfeito. Pode fechar a solicitação. Tks!
