### ISSUE TITLE
GERAL: Caixa de pesquisa não avisa sobre eventuais problemas

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#484]
A caixa de pesquisa no canto superior direito SIGA, quando não encontra um documento ou dá erro durante a consulta, não indica se o objeto não foi encontrado ou se há algum problema na aplicação. Como o número do documento, solicitação, conhecimento, etc. simplesmente desaparece quando há um erro ou não é encontrado, o usuário fica sem saber o motivo de não ter localizado o objeto. Esse problema fica evidente quando o usuário tem a certeza que o documento (solicitação, etc) existe e tenta pesquisá-lo, porém com a sessão do navegador expirada.

**Comment by crivano** [comment]
agora estamos enviando o usuário para uma busca textual GSA quando o código fornecido não é reconhecido com um objeto do SIGA.

**Comment by Markenson** [comment]
@crivano, mas ainda não há indicativo de perda de sessão. Quando a sessão é perdida, a caixa simplesmente retorna, como era antes.

**Comment by crivano** [comment]
@Markenson , a caixa não precisa mais de login. Quando a pessoa escreve alguma coisa e clica TAB ou RETURN, o sistema faz um redirect para o elemento desejado. Nessa ocasião, o login e solicitado se a sessão estiver expirada.

**Comment by Markenson** [comment]
@crivano Eu estava com a tela do siga aberta na página inicial, digitei o número de um documento (ou solicitação, não me lembro bem) e pressionei TAB. Nesse momento, o que eu escrevei se apagou e o sistema não redirecionou para outra página. Pelo que você disse ele deveria ter redirecionado para a tela de login, certo?

**Comment by crivano** [comment]
@Markenson , isso foi no canário? Porque lá sempre direciona para a busca do GSA quando não encontra um elemento do Siga. Se vc fizer isso em outro ambiente, quando não encontra o elemento, simplesmente apaga como vc reportou.

**Comment by Markenson** [comment]
@crivano Foi no canário sim. Melhor aguardar pra ver se ocorre novamente. Se for o caso, eu lanço aqui na issue.
