### ISSUE TITLE
GERAL: Criar uma infraestrutura para chamadas internas feitas pelas aplicações

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#494]
O SIGA possui rotinas que se conectam, via HTTP, no próprio servidor de aplicação (auto-chamada). Porém, dependendo da arquitetura do ambiente (em cluster, por exemplo) não é possível conectar ao próprio servidor que origina a chamada (por causa da diferença de portas TCP). Para contornar essa dificuldade, essa chamada precisa ser direcionada para um servidor web (apache) que depois encaminha a solicitação para algum servidor de aplicação. 

O encaminhamento para o servidor web funciona corretamente, mas em arquiteturas mais complexas também pode causar problemas. Por exemplo, se existirem dois apaches, um interno e outro externo (na internet, que exige que o usuário tenha tokens com certificados digitais) as chamadas devem ser encaminhadas apenas para o apache interno, mesmo que originadas da internet. 

Uma solução de contorno simples consiste em colocar o nome do servidor web (apache) dentro do arquivo /etc/hosts da máquina que contém o servidor de aplicações de modo que sempre o servidor web especificado seja acionado, em vez de outros servidores web. Embora seja uma solução simples, ele tende a ter um gerenciamento complexo, pois exige documentação para cada ambiente de como está configurado o sistema.

Esta issue foi aberta para reunirmos propostas e implementarmos um maneira adequada de lidar com esses tipos de problemas.

**Comment by Markenson** [comment]
A primeira proposta que temos (descrita no e-mail do @luiz-antonio.qui 19/11/2015 18:32) seria criar um nome ("sigawebservice", por exemplo) para o host que responde às auto-chamadas ou webservices. Os aplicativos deveriam utilizar esse nome sempre que precisassem consumir algum serviço externo à própria aplicação. Isso eliminaria a necessidade de gerência dos arquivos /etc/hosts e padronizaria a forma de chamar serviços externos.

**Comment by crivano** [comment]
@Markenson , essa questão já foi resolvida no ambiente canário. Todas as chamadas internas foram direcionadas para siga.jfrj.jus.br e o httpd redireciona para uma instância que possua o webservice em questão.

**Comment by Markenson** [comment]
Blz!
