### ISSUE TITLE
SIGA-WF: Incluir confirmação no encerramento do fluxo

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#501]
O SIGA-WF não permite restaurar um processo que tenha sido encerrado. Uma medida para prevenir a finalização por acidente seria acrescentar uma confirmação de encerramento do fluxo.

**Comment by Markenson** [comment]
Essa issue foi criada por causa do problema descrito em JFRJ-SR-2015/24452

**Comment by esredson** [comment]
TRF2-SR-2016/33898
