### ISSUE TITLE
DOC: Erro em montaQueryConsultaporFiltro na SIGAT

### ISSUE THREAD

**Issue by crivano** [projeto-siga/siga#508]
@Markenson , será que isso está relacionado aquele problema que vc notificou por email?

![siga_-_erro_geral](https://cloud.githubusercontent.com/assets/4137623/11535818/b3f1f290-98fc-11e5-96a0-398bd4816f20.png)

**Comment by Markenson** [comment]
Tem sim @crivano. Houve uma atualização na interface do siga-ext que causa esse problema.

**Comment by crivano** [comment]
Testei novamente em 2015-12-10 e o erro persiste.
