### ISSUE TITLE
DOC: Erro na exibição de um documento na SIGAT

### ISSUE THREAD

**Issue by crivano** [projeto-siga/siga#510]
![csis-trf-10](https://cloud.githubusercontent.com/assets/4137623/11536404/76c59ff4-98ff-11e5-8a23-b8412c89a8ad.png)

**Comment by crivano** [comment]
Fiz várias experiências e não consegui resolver. Eis o que aprendi:

O problema ocorre porque o hibernate verifica a session para saber se precisa fazer um flush antes de executar o SQLQuery que busca sysdate.

O erro ocorre quando é chamada um query que busca um documento por alguns filtros.

O trecho de código abaixo já produz o erro, mesmo que o mobil.setSigla seja suprimido do código.

```
Date dt = ExDao.getInstance().dt();
final Query query = getSessao().getNamedQuery(
        "consultarPorSiglaDocumento");
query.setProperties(flt);
final List<ExDocumento> l = query.list();
dt = ExDao.getInstance().dt();
```
​
o primeiro dt() funciona, o segundo não funciona.

**Comment by crivano** [comment]
Não estou lembrado quando foi resolvido, mas parou de acontecer.

**Comment by crivano** [comment]
Voltou a ocorrer conforme relatado na issue #572

**Comment by crivano** [comment]
Como reproduzir: na base de produção, acesse o documento RJ-OFI-2006/00041.

http://localhost:8080/sigaex/app/expediente/doc/exibir?sigla=RJ-OFI-2006/00041

**Comment by crivano** [comment]
Boas notícias, consegui reproduzir esse erro fora do JBoss. Conectado com a base de produção, basta fazer:

```
	public void testBugFoundSharedReferencesToACollection() {
		ExDao.iniciarTransacao();
		
		ExMobilDaoFiltro flt = new ExMobilDaoFiltro();
		flt.setSigla("TRF2-MEM-2013/00001-A");
		ExMobil mob = ExDao.getInstance().consultarPorSigla(flt);
		System.out.println(mob);
		
		System.out.println(ExDao.getInstance().listarOrgaosUsuarios());
	}
```

Se não iniciar a transação, o erro não acontece.

**Comment by crivano** [comment]
Depois de muito trace dentro do Hibernate, consegui identificar uma possível causa. Quando estamos dentro de uma transação e antes de fazer uma consulta qualquer, o Hibernate faz flush de todas as alterações que estão na memória. Isso é necessário para garantir que a consulta levará em conta as alterações que foram realizadas na session atual. Para fazer o flush ele acessa os getters de todos os objetos, para verificar se existe alguma alteração a ser salva.

O problema é que o getter getExNivelAcesso() atualiza seu valor e persiste o objeto quando é acessado e seu valor é nulo. Provavelmente isso é um anti-pattern e não deveria ter sido codificado dessa forma, mas é um caso muito peculiar e o erro é bem pouco aparente.

Havia um método chamado getExNivelAcessoDoDocumento que retornava a propriedade do banco de dados. Alterei o nome desse método para getExNivelAcesso e alterei o getExNivelAcesso para ficar como getExNivelAcessoAtual.

**Comment by raphaelpaiva** [comment]
Lógica no getter é sim um anti-pattern. Justamente por ser peculiar e pouco aparente que é um anti-pattern. Olha o trabalho que deu! :smile: 

Outro anti-pattern é ter lógica em classes de modelo. Conversei um pouco com o @esredson sobre isso e ele explicou que era um legado do play. É importante salientar, que trocar de ferramenta/tecnologia, mas manter a mentalidade não adianta muito. O Play funciona dessa forma pra facilitar a prototipagem, mas dá um tiro no MVC :sob:

**Comment by crivano** [comment]
Ahaha, @raphaelpaiva , sabia que vc ia comentar isso! :)

**Comment by raphaelpaiva** [comment]
:laughing:
