### ISSUE TITLE
SR: erro ao tentar cadastrar ação na versão vraptor (serie1cabrio)

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#514]
![captura_de_tela_120415_073835_pm](https://cloud.githubusercontent.com/assets/8461113/11602067/9c29863c-9abe-11e5-9c8d-c0c97ad75059.jpg)

**Comment by rafaela00castro** [comment]
Necessário inserir configuração abaixo na serie1cabrio para que o web service do SIGA-GC seja chamado e não dê o erro acima.
````
Inserir properties no standalone.xml
			<property name="gcservice.endpoint" value="http://ip-da-maquina:porta/sigagc/servicos/GcService?wsdl"/>
			<property name="gcservice.qname" value="http://impl.service.gc.siga.jfrj.gov.br/"/>
			<property name="gcservice.servicename" value="GcService"/>
````

@kmacedovarela ou @rodrigo-ferreira

**Comment by kmacedovarela** [comment]
Certo @rafaela00castro . 
Favor abrir um chamado no sigasr para que algum dos integrantes da seinap possa executar. Assim que resolvido eu fecho a issue!

Obrigada!

**Comment by rafaela00castro** [comment]
Ok, @kmacedovarela!
