### ISSUE TITLE
DOC: brasao2.png não encontrado

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#516]
O seguinte erro foi exibido na console do serie1cabrio:

15:06:12,326 ERROR [stderr] (http-/0.0.0.0:8080-13) java.io.FileNotFoundException: /home/jboss/contextpath/imagens/brasao2.png (No such file or directory)

**Comment by Markenson** [comment]
Aparentemente o erro ocorreu ao encerrar um volume:

```
15:06:12,303 INFO  [com.aryjr.nheengatu.pdf.PDFDocument] (http-/0.0.0.0:8080-13) extractVisibleComponents
15:06:12,304 INFO  [com.aryjr.nheengatu.pdf.PDFDocument] (http-/0.0.0.0:8080-13) p
15:06:12,304 INFO  [com.aryjr.nheengatu.pdf.PDFDocument] (http-/0.0.0.0:8080-13) 11.0
15:06:12,304 INFO  [com.aryjr.nheengatu.pdf.PDFDocument] (http-/0.0.0.0:8080-13) 16.5
15:06:12,304 INFO  [com.aryjr.nheengatu.pdf.PDFDocument] (http-/0.0.0.0:8080-13) extractVisibleComponents
15:06:12,305 INFO  [com.aryjr.nheengatu.pdf.PDFDocument] (http-/0.0.0.0:8080-13) text: PROCESSO RJ-EOF-2010/02108.02
15:06:12,306 INFO  [com.aryjr.nheengatu.pdf.PDFDocument] (http-/0.0.0.0:8080-13) p
15:06:12,306 INFO  [com.aryjr.nheengatu.pdf.PDFDocument] (http-/0.0.0.0:8080-13) 11.0
15:06:12,306 INFO  [com.aryjr.nheengatu.pdf.PDFDocument] (http-/0.0.0.0:8080-13) 16.5
15:06:12,306 INFO  [com.aryjr.nheengatu.pdf.PDFDocument] (http-/0.0.0.0:8080-13) extractVisibleComponents
15:06:12,307 INFO  [com.aryjr.nheengatu.pdf.PDFDocument] (http-/0.0.0.0:8080-13) text: CERTIDÃO
15:06:12,307 INFO  [com.aryjr.nheengatu.pdf.PDFDocument] (http-/0.0.0.0:8080-13) p
15:06:12,308 INFO  [com.aryjr.nheengatu.pdf.PDFDocument] (http-/0.0.0.0:8080-13) 11.0
15:06:12,308 INFO  [com.aryjr.nheengatu.pdf.PDFDocument] (http-/0.0.0.0:8080-13) 16.5
15:06:12,308 INFO  [com.aryjr.nheengatu.pdf.PDFDocument] (http-/0.0.0.0:8080-13) extractVisibleComponents
15:06:12,308 INFO  [com.aryjr.nheengatu.pdf.PDFDocument] (http-/0.0.0.0:8080-13) text: Certifico que, nesta data, encerrei o volume 23 do processo em epígrafe.
15:06:12,309 INFO  [com.aryjr.nheengatu.pdf.PDFDocument] (http-/0.0.0.0:8080-13) p
15:06:12,309 INFO  [com.aryjr.nheengatu.pdf.PDFDocument] (http-/0.0.0.0:8080-13) 11.0
15:06:12,310 INFO  [com.aryjr.nheengatu.pdf.PDFDocument] (http-/0.0.0.0:8080-13) 16.5
15:06:12,310 INFO  [com.aryjr.nheengatu.pdf.PDFDocument] (http-/0.0.0.0:8080-13) extractVisibleComponents
15:06:12,310 INFO  [com.aryjr.nheengatu.pdf.PDFDocument] (http-/0.0.0.0:8080-13) text: Rio de Janeiro, 10 de dezembro de 2015.
15:06:12,311 INFO  [com.aryjr.nheengatu.pdf.PDFDocument] (http-/0.0.0.0:8080-13) p
15:06:12,311 INFO  [com.aryjr.nheengatu.pdf.PDFDocument] (http-/0.0.0.0:8080-13) 11.0
15:06:12,311 INFO  [com.aryjr.nheengatu.pdf.PDFDocument] (http-/0.0.0.0:8080-13) 16.5
15:06:12,312 INFO  [com.aryjr.nheengatu.pdf.PDFDocument] (http-/0.0.0.0:8080-13) extractVisibleComponents
15:06:12,312 INFO  [com.aryjr.nheengatu.pdf.PDFDocument] (http-/0.0.0.0:8080-13) text: FERNANDO ANTONIO GRUBER DOS SANTOS
15:06:12,313 INFO  [com.aryjr.nheengatu.pdf.PDFDocument] (http-/0.0.0.0:8080-13) text: Assistente II
15:06:12,326 ERROR [stderr] (http-/0.0.0.0:8080-13) java.io.FileNotFoundException: /home/jboss/contextpath/imagens/brasao2.png (No such file or directory)

```

**Comment by crivano** [comment]
@kmacedovarela , o war é explodido pelo JBoss de produção? Existe alguma maneira de acessar um arquivo que faz parte do war? No caso, o brasao2.png é um arquivo que está dentro do sigaex.war e precisamos saber qual o path que ele está no disco para criar um documento. Alguma dica de como possa ser feito? Obrigado.

**Comment by kmacedovarela** [comment]
@crivano  você poderia destacar pra mim um exemplo de código em que a imagem é carregada?

**Comment by crivano** [comment]
@kmacedovarela , esse é o ponto do código que foi desabilitado quando passamos do WebWork para o VRaptor:

https://github.com/projeto-siga/siga/blob/vraptor/siga-ex/src/main/java/br/gov/jfrj/itextpdf/Documento.java#L912

Quem realmente usa essa referência para o arquivo é um conversor de HTML para PDF chamado Nheengatu, sobre o qual não temos muito controle.

**Comment by crivano** [comment]
Olá @kmacedovarela , como anda essa issue? Podemos trabalhar nela ou tento resolver com o Luiz?

**Comment by kmacedovarela** [comment]
@crivano minhas atividades estão interrompidas, esta issue não teve nenhum andamento

**Comment by crivano** [comment]
@luiz-antonio : será que você pode me ajudar nesse issue?

**Comment by raphaelpaiva** [comment]
@crivano Como a imagem está dentro do jar do sigaex, ela será carregada pro classpath. Será que você não consegue carregá-lo pelo próprio classloader?

    this.getClass().getClassLoader().getResourceAsStream("/imagens/brasao2.png");

Já testou algo parecido?

**Comment by crivano** [comment]
@raphaelpaiva , é que não sou eu que uso o recurso, eu passo um HTML com um IMG SRC="xxx" para uma biblioteca que transforma o HTML em PDF. Ela espera que a imagem esteja em um endereço de disco. Por isso que preciso saber qual é o path do brasao2.png.

**Comment by raphaelpaiva** [comment]
@crivano entendi. Não conheço o vraptor, mas no seam dava pra carregar uma imagem para uma url dinamicamente, não sei se existe algo parecido. De qualquer forma, nesse caso eu vejo duas soluções:

1. Criar um repositório para o conteúdo estático. Isto pode ser um .war mesmo para ser deployado junto com o siga, expondo os recursos a partir de uma url padrão, tipo siga/static/images/brasao.png. Era a abordagem que utilizávamos no meu projeto anterior.
2. Servir o conteúdo estático empacotado no sigaex através de um webservice. Desse modo, se expõe uma url que carrega um recurso do classpath.

O que acha?

**Comment by crivano** [comment]
@raphaelpaiva , não entendi as suas propostas. Como é que vou conseguir saber o diretório onde o arquivo se encontra? Não vejo isso possível nem na 1 nem na 2.

**Comment by raphaelpaiva** [comment]
@crivano não seria por disco, mas via url. Apesar de ser possível, navegar pelos diretórios de trabalho do jboss é uma gambiarra tremenda, além de não termos garantia nenhuma de que o arquivo está legível (o path ser aleatório, por deploy) e também que em versões futuras do jboss será no mesmo lugar.

A vantagem de acessar via URL é que vamos aproveitar toda a infraestrutura atual, sem nos preocuparmos com replicação e sincronia, o que precisaríamos fazer com uma solução de repositório em disco.

**Comment by raphaelpaiva** [comment]
@crivano Carregar via URL é um problema? Se for, uma outra coisa que eu pensei seria ler o arquivo que você precisar (brasao ou outros) do classpath e gravar em disco dinamicamente, numa pasta /var/siga/imagens ou /tmp/siga/imagens.
