### ISSUE TITLE
Siga-Doc: Busca não responde

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#517]
A busca do Siga não funcionou para o processo JFRJ-EOF-2014/01573.01, no ambiente canário. pelo endereço axor/siga funcionou normalmente.

**Comment by crivano** [comment]
Testei novamente e respondeu em menos de 1 segundo. A página de exibição demorou uns 10s para carregar, mas é um processo gigantesco, com 17 volumes.
