### ISSUE TITLE
Siga-Doc: siga/sigarhdadosdadastrais indisponível

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#518]
![captura_de_tela_121115_041626_pm](https://cloud.githubusercontent.com/assets/4949149/11751747/883318d2-a022-11e5-9473-e436acf5a470.jpg)

**Comment by Chrystinne** [comment]
Caminho: Siga -> Módulo -> Pessoas -> Consultas

**Comment by raphaelpaiva** [comment]
Resolvido. Havia uma propriedade com a url errada (sigarhdados'd'adastrais ao invés de dados'c'adastrais).
