### ISSUE TITLE
GC: Permitir que urls antigas estejam disponíveis na versão vraptor

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#519]

**Comment by crivano** [comment]
Que urls?

**Comment by Markenson** [comment]
Os links de acesso aos conhecimentos (enviado por email, referência em outros conhecimentos, etc) estão quebrados porque a nova versão  aplicação suporta apenas o novo formato de URL.

**Comment by crivano** [comment]
Isso seria possível de criar, mas acho que o melhor seria corrigir as referências. Termos dois links diferentes para o mesmo conhecimento não me parece uma boa. Os novos emails e o conhecimentos atuais já estão apontando para as urls corretas?

@Markenson , teria alguns exemplos de problemas para que possamos analisar?

**Comment by Markenson** [comment]
@crivano O problema é que o pessoal já migrou diversos conhecimentos na versão antiga. E eles teriam um grande trabalho se precisassem remapear todas as URLs.

Vou perguntar ao Bernardo se ele pode nos passar alguns exemplos de URL.

**Comment by Markenson** [comment]
**Resumo:**

Existem liks que apontam para http://siga/sigagc/app/exibir?sigla=TRF2-GC-2015%2F00264
Porém, a nova versão só aceita http://siga/sigagc/app/exibir/TRF2GC201500264

Eles teriam que trocar todas as urls do portal por causa disso.

**Detalhe:**
Resposta do Bernado, por email em qua 16/12/2015 11:15

"(...) Quanto a quebra da retrocompatibilidade dos links, a base antiga tem os links para os artigos no SIGA-GC, a mudança na formação dos links não preservou o legado, isso é muito ruim ainda mais num momento de migração.
	
http://elegance:8080/portal/base-de-conhecimento/suporte-de-ti/perguntas-frequentes


B16 - Drivers de Dispositivos
http://elegance:8080/portal/base-de-conhecimento/suporte-de-ti/perguntas-frequentes/drivers-de-dispositivos

http://siga/sigagc/app/exibir?sigla=TRF2-GC-2015%2F00264



Você pode testar qualquer outro artigo da categoria B (no Plone).

"

**Comment by Chrystinne** [comment]
Como não consegui reproduzir o erro, liguei pro Bernardo e vimos que este problema já foi resolvido.
