### ISSUE TITLE
GI: Gravação na tela Perfil de Acesso direciona para página em branco

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#520]
Ao clicar no botão Gestão de Identidade -> Perfil de Acesso -> Incluir (Lotação) -> Gravar, o endereço siga/app/gi/perfil/gravar é chamado mas a gravação não é feita - a página fica em branco.

**Comment by crivano** [comment]
@esredson , fiz o teste e funcionou perfeitamente. Vou fechar a issue. Se você encontrar novamente o mesmo erro, por favor especifique qual a lotação e qual o perfil que está dando problema.
