### ISSUE TITLE
Problema no Cache-Control

### ISSUE THREAD

**Issue by crivano** [projeto-siga/siga#521]
Notei que a versão vraptor está gerando dois header de "Cache-Control" e isso faz com que o SIGA não mantenha nenhum recurso http no client-cache. Vejam por exemplo os headers retornados para:

http://serie1cabrio.corp.jfrj.gov.br/siga/imagens/logo.png

```
HTTP/1.1 304 Not Modified
Date: Mon, 14 Dec 2015 17:58:54 GMT
Server: Apache-Coyote/1.1
Connection: Keep-Alive
Keep-Alive: timeout=15, max=100
ETag: W/"9230-1416927898000"
Expires: Wed, 31 Dec 1969 21:00:00 BRT
Cache-Control: no-cache
Cache-Control: max-age=3600
````

O correto seria ter apenas o max-age=3600, conforme está configurado no web.xml. 

@luiz-antonio e @kmacedovarela , seria isso um problema do VRaptor, do JBoss ou do Apache?

**Comment by kmacedovarela** [comment]
@crivano segundo o header, o objeto estava em cache ( 304 ), porém não no apache, pois o apache desta máquina não possui cache habilitado.

o que foi notado durante as configurações do ambiente de homologação (realizadas pelo @AndDeluiz) é que o "no-cache" estava sendo inserido pelo picketlink e que afetava o cache no apache e no IE9 (devido ao mecanismo de cache deste browser no windows) .

Atualmente, temos o ambiente "siga-hmg" configurado com cache + gzip. A configuração estava sob testes e aguardando autorização para ser implantada no ambiente de produção.

**Comment by crivano** [comment]
@kmacedovarela , algumas coisas deveriam ficar no cache do cliente, tipo "public", como por exemplo as imagens, javascripts, css, etc. Outras coisas não podem ter cache, como as páginas geradas pelo vraptor.

Do jeito que está agora, nada fica no cache. E isso não é bom! :)

**Comment by AndDeluiz** [comment]
@crivano, o objeto utilizado para exemplo estava no cache local. Tanto que a origem respondeu com HTTP 304 a requisição. Caso não estivesse no cache local o cliente receberia HTTP 200.
Quanto a haverem dois cabeçalhos cache-control, isso deve ser verificado em conjunto pois a inserção destes cabeçalhos é feita pela aplicação, pelo JBoss ou algum módulo utilizado pela plataforma, como o Picketlink. No issue #232 o Rodrigo já havia detectado que o Picketlink manipula o cabeçalho cache-control.

**Comment by crivano** [comment]
Solução: o ideal seria que o picketlink não estivesse inserindo esse header de cache-control: no-cache. Testaremos identificar onde isso está acontecendo, para ver se é possível corrigir esse comportamento. Se não for possível, tentaremos usar o mod_rewrite do apache para eliminar os headers do picket-link quando for detectado que os header de cache-control:max-age estão presentes.

**Comment by crivano** [comment]
@luiz-antonio , @AndDeluiz , @kmacedovarela : O picketlink não estava inserindo os headers de no-cache. Na verdade era o JBoss, na classe AuthenticatorBase. Incluí os um parâmetro a mais no jboss-web.xml e o problema foi resolvido. Vide commit https://github.com/projeto-siga/siga/commit/b1097fd309107a1434fe0282795b8bd582bf3f0d
