### ISSUE TITLE
SR: Anexos só funcionam no CHROME

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#524]
Reportado (lia lync) por @luiz-antonio que anexos do siga-sr só estão abrindo no Chrome (Exemplo: TRF2SR201517703)

**Comment by rafaela00castro** [comment]
@luiz-antonio e @Markenson fiz testes agora nessa solicitação de exemplo e consegui baixar no IE. Antes de baixar efetivamente no IE aparece a tela abaixo. Vocês poderiam tentar fazer essa operação novamente? Sabem dizer se essa issue é na versão 4.x ou na 5.x?

![captura_de_tela_020316_031301_pm](https://cloud.githubusercontent.com/assets/8461113/12790264/9e3b5370-ca88-11e5-882c-abe1200f54e8.jpg)

**Comment by Markenson** [comment]
@rafaela00castro Acabei de testar na 5.x e funcionou normalmente. Não testei na 4.x porque está fora no momento. Acho que essa issue pode ser fechada e reaberta caso volte a ocorrer. O que acha?

**Comment by rafaela00castro** [comment]
De acordo!
