### ISSUE TITLE
IDP: siga/sigaidp URL não responde quando usuário já está logado

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#527]
Após realizar o login e acessar http://siga/sigaidp/, nada é exibido dando a impressão de que o sistema está parado. 

Na versão anterior era exibido uma tela com a opção "sigadoc" ou "sigarh" por falta de melhores ideias para esta tela. Como este é o root do sigaidp, sistema de autenticação, não colocamos redirecionamento automatico para nenhum sistema.

**Comment by crivano** [comment]
Curiosamente não consegui resolver esse problema. O welcome-file-list não funcionou.
