### ISSUE TITLE
Lista de solicitações não condiz com o indicado

### ISSUE THREAD

**Issue by rodrigo-ferreira** [projeto-siga/siga#533]
Estou utilizando a versão Versão: 4.2.4.10 do siga e percebo que a lista de solicitações no siga serviços não está sendo apresentada.
Na tela do siga serviços, na minha conta, vejo a seguinte informação:
![image](https://cloud.githubusercontent.com/assets/13545857/11904786/bf0878b6-a5a9-11e5-9922-3a69cf41d258.png)
Ao clicar nos itens (por exemplo os itens na lotação) o resultado é 
![image](https://cloud.githubusercontent.com/assets/13545857/11904844/04752336-a5aa-11e5-8c00-cf1da1e9d22a.png)

**Comment by esredson** [comment]
Esse problema ocorre na versão 4.x. Como a versão está prestes a ser substituída para todos os usuários, acreditamos ser melhor não nos empenhar em buscar uma solução neste momento.
