### ISSUE TITLE
GERAL: Problema na gerência de transações (transaction reaper)

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#534]
O problema foi inicialmente identificado nesta issue através da análise de thread dumps sempre que a aplicação travava. Nesta issue, foi identificado uma das possíveis causas de lentidão no sistema: https://github.com/projeto-siga/siga/issues/241 

   Foi identificado ao longo do tempo que na verdade ocorria um timeout sempre que qualquer operação demorava para ser executada, em qualquer módulo do SigaDOC. 
    Identificamos que o sigadoc utiliza a system property "jta.transaction.timeout.value", para estabelecer o valor máximo de tempo que uma transação pode durar.   Foi aumentado o valor deste timeout para que a aplicação suportasse requisições mais demoradas, sem precisar ser reiniciada com tanta frequência.

   O comportamento esperado em caso de timeout de uma transação, é que a aplicação faça o rollback, e continue funcionando normalmente. Porém foi verificado (o @Markenson pode detalhar melhor este tópico), que devido ao funcionamento do código do SIGA na versão EAP6 do JBoss , quando ocorre o timeout de uma transação, os próximos requests continuam utilizando a mesma transação que já foi encerrada pelo JBoss, ou seja, o funcionamento do sistema é 100% prejudicado até que seja reinicializado. 

Algumas referências utilizadas ao longo do processo de identificação e tentativas de solução do problema:
https://access.redhat.com/solutions/68829 - After a transaction timeout I am repeatedly getting "Transaction is not active" with ActionStatus.ABORTED in JBoss.
https://access.redhat.com/solutions/645963 - Timeout and abort WARN log messages from TransactionReaper in JBoss EAP 6 
https://access.redhat.com/solutions/875403  - Example Hibernate and Transactions subsystem interaction when Transaction Reaper ABORTS a Transaction in JBoss 
https://access.redhat.com/solutions/18425 -  Transaction abort and timeout messages in JBoss EAP

**Comment by crivano** [comment]
Realizei inúmeros testes na tentativa de reproduzir esse erro no ambiente de desenvolvimento, usando JMeter e a versão 4.x (WebWork) do Siga e não obtive sucesso. Para simular a lentidão, parei cada uma das aplicações no debugger e aguardei. O erro de Transaction Reaper ocorre, claro, mas depois o sistema se recupera e todos os threads do JBoss voltam a operar normalmente.

Caso alguém tenha interesse em usar o JMeter para estressar o SIGA, o arquivo JMX está anexo.

[siga-login-e-teste-basico.jmx.zip](https://github.com/projeto-siga/siga/files/112756/siga-login-e-teste-basico.jmx.zip)

**Comment by raphaelpaiva** [comment]
@crivano Acabou de ocorrer. Segue o log em anexo.
[transactionReaper-2016-02-01.txt](https://github.com/projeto-siga/siga/files/112798/transactionReaper-2016-02-01.txt)

**Comment by crivano** [comment]
@raphaelpaiva , obrigado, te dou uma posição amanhã.

**Comment by crivano** [comment]
@raphaelpaiva , não dá para concluir nada a partir desse log. Estava conversando ontem com o @Markenson e concluímos que a melhor opção seria uma análise do log do httpd, pois poderíamos ver quais as urls que demoraram para ser executadas, e quais foram chamadas e geraram o problema.

Removi as linhas duplicadas e fica claro que nem existem tantos eventos logados, considerando que o espaço de tempo é de aprox. 1h. Veja o arquivo anexo.

Se conseguir um log do httpd, por favor, nos passe para que possamos avaliar. O ideal seria ter uma ferramenta para ver isso, pois fica muito difícil olhar linha-a-linha.

[transactionReaper-2016-02-01-rdl.txt](https://github.com/projeto-siga/siga/files/114018/transactionReaper-2016-02-01-rdl.txt)

**Comment by Markenson** [comment]
@raphaelpaiva Posso fechar esta issue ou ainda estão ocorrendo erros de transaction reaper na versão 5.x?

**Comment by raphaelpaiva** [comment]
Pode fechar, Marks!

**Comment by Markenson** [comment]
Valeu! Fechando...
