### ISSUE TITLE
Caixa de busca não funciona quando utilizando duas instâncias isoladas

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#536]
Caixa de busca não funciona quando utilizando o módulo em uma instância separada do sigaidp.

Cenário de exemplo:

Instância 1, com os seguintes pacotes:
[1.1] SigaIDP
[1.2] Siga
[1.3] SigaEX

Instância 2, com os seguintes pacotes:
[2.1] SigaEX

-> Ao acessar o sistema através de um balancer (apache, no caso), http://siga/siga, a instância 1 carrega o [1.1] SigaIDP e o [1.2] Siga, e a instância 2 carrega o [2.1] SigaEX.  [Comportamento OK]

-> Ao realizar a busca de um documento pela caixa de busca, o sistema [1.2] Siga, realiza uma chamada para [1.3] SigaEX, quando na verdade deveria chamar [2.1] SigaEX. 

Solução temporária:
Até que esse comportamento seja identificado no código do siga e proposta uma solução, o sistema 1.3. SigaEX permanecerá habilitado (e está sendo utilizado apenas para a consulta, uma vez que o usuário é sempre redirecionado pelo apache para 2.1. SigaEX) 

Observação: a porta de debug já está ativada em ambas as instâncias caso seja necessário utilizar para investigação

**Comment by crivano** [comment]
Acredito que a solução seja direcionar a chamada interna também para o balancer. E que não exista a necessidade de login para essa chamada. O que vocês acham, podemos seguir nessa direção?

**Comment by crivano** [comment]
Já estou trabalhando em não precisar do login conforme #522

**Comment by crivano** [comment]
@raphaelpaiva @luiz-antonio , alguém saberia dizer se esse bug foi observado na versão do vRaptor? É que o vRaptor chama a url de seleção de documentos repetindo o nome de máquina. Ou seja, se a aplicação está em siga/siga, a caixa de busca chamará siga/siga/app/generico/selecionar e o controller do selecionar chamará siga/sigaex/app/expediente/selecionar. Portanto, a chamada seria direcionada para o balancer e deveria funcionar normalmente.

**Comment by raphaelpaiva** [comment]
@crivano Nós voltamos a ter o ex na canário na instância junto com todas as outras, isolando apenas o tp. Vou testar isso depois do expediente essa semana.

**Comment by crivano** [comment]
@raphaelpaiva @luiz-antonio , estou considerando que todas as alterações de código necessárias já estão concluídas. Se esse problema continuar ocorrendo, favor me avisar. Ou unassign esse task. Deixo eles agora com vcs.

**Comment by crivano** [comment]
Considerando que se passaram alguns dias e todo o funcionamento da caixa foi refeito, inclusive agora passando pelo httpd para encaminhar para a instância certa, estou fechando esse issue.
