### ISSUE TITLE
DOC: Erro na geração do documento

### ISSUE THREAD

**Issue by crivano** [projeto-siga/siga#539]
Erro intermitente quando acessamos uma url do tipo:

http://siga/sigaex/app/arquivo/exibir?popup-true&id=15268411&arquivo=JFRJEOF201301395.02V03:15268411.pdf&

**Comment by crivano** [comment]
@raphaelpaiva e @luiz-antonio , testei na minha máquina e mesmo apontando para o oracle de produção o erro não aconteceu.

Isso e importante: testei na serie1cabrio:

- quando uso a porta 80, o erro acontece vez sim, vez não
- quando uso a porta 8080, o erro não acontece nunca

**Comment by luiz-antonio** [comment]
Vamos olhar o Apache! Está configurado somente para PROXY, Mas pode ter algum problema.

**Comment by luiz-antonio** [comment]
Há um "erro" na cahe. Apesar da configuração do MOD_CACHE ser idêntica à da AXOR, o problema ocorre na serie1cabrio. Configuração de MOD_CACHE desabilitado.

**Comment by luiz-antonio** [comment]
Usando:  CacheDisable /sigaex/app/arquivo/exibir também funciona e com o MOD_CACHE ativado. Resta saber sobre outros acessos a PDF. @crivano poderia verificar se há proceso semelhante?

**Comment by crivano** [comment]
@luiz-antonio , não encontrei outros erros e fechei essa issue.
