### ISSUE TITLE
DOC: Tempo da transferência simples é de 4-5 segundos

### ISSUE THREAD

**Issue by crivano** [projeto-siga/siga#542]
Esse problema foi reportado por Gustavo. Fiz minhas próprias medições e o resultado é ainda pior do que o original.

Para transferir o TRF2-MRU-2015/00008 de SESGET para SEDGET demora em média 11 segundos. O cancelamento da mesma movimentação chega a demorar 15s. Detalhe, esse é um documento simples e sem nenhum anexo.

No ambiente de desenvolvimento, que deveria ser muito mais lento pois roda Windows e está mais longe do Oracle, os tempos nunca passam de 2 segundos.

Claramente existe um problema aí e precisamos resolvê-lo.

@raphaelpaiva e @luiz-antonio , será que vocês podem assumir essa issue?

**Comment by raphaelpaiva** [comment]
@rodrigo-ferreira podemos ver juntos essa semana?

**Comment by luiz-antonio** [comment]
Fiz uma memória de reunião para testar. SEMPRE na transferência e no "desfazer" ocorre:


13:52:27,638 INFO  [siga.conf.cache] (http-/0.0.0.0:8080-29) Cache de configurações inicializado via WfConfiguracaoBL em 13519ms
13:52:28,564 WARN  [org.hibernate.engine.internal.StatefulPersistenceContext] (http-/0.0.0.0:8080-29) HHH000179: Narrowing proxy to class org.jbpm.graph.node.TaskNode - this operation breaks ==
13:52:28,569 WARN  [org.hibernate.engine.internal.StatefulPersistenceContext] (http-/0.0.0.0:8080-29) HHH000179: Narrowing proxy to class org.jbpm.graph.node.TaskNode - this operation breaks ==
13:52:28,573 WARN  [org.hibernate.engine.internal.StatefulPersistenceContext] (http-/0.0.0.0:8080-29) HHH000179: Narrowing proxy to class org.jbpm.graph.node.TaskNode - this operation breaks ==
13:52:28,696 WARN  [org.hibernate.engine.internal.StatefulPersistenceContext] (http-/0.0.0.0:8080-29) HHH000179: Narrowing proxy to class org.jbpm.graph.node.TaskNode - this operation breaks ==
13:52:28,697 WARN  [org.hibernate.engine.internal.StatefulPersistenceContext] (http-/0.0.0.0:8080-29) HHH000179: Narrowing proxy to class org.jbpm.graph.node.TaskNode - this operation breaks ==
13:52:28,697 WARN  [org.hibernate.engine.internal.StatefulPersistenceContext] (http-/0.0.0.0:8080-29) HHH000179: Narrowing proxy to class org.jbpm.graph.node.TaskNode - this operation breaks ==
13:52:28,698 WARN  [org.hibernate.engine.internal.StatefulPersistenceContext] (http-/0.0.0.0:8080-29) HHH000179: Narrowing proxy to class org.jbpm.graph.node.TaskNode - this operation breaks ==
13:52:28,698 WARN  [org.hibernate.engine.internal.StatefulPersistenceContext] (http-/0.0.0.0:8080-29) HHH000179: Narrowing proxy to class org.jbpm.graph.node.TaskNode - this operation breaks ==
13:52:28,699 WARN  [org.hibernate.engine.internal.StatefulPersistenceContext] (http-/0.0.0.0:8080-29) HHH000179: Narrowing proxy to class org.jbpm.graph.node.TaskNode - this operation breaks ==
13:52:28,699 WARN  [org.hibernate.engine.internal.StatefulPersistenceContext] (http-/0.0.0.0:8080-29) HHH000179: Narrowing proxy to class org.jbpm.graph.node.TaskNode - this operation breaks ==
13:52:28,699 WARN  [org.hibernate.engine.internal.StatefulPersistenceContext] (http-/0.0.0.0:8080-29) HHH000179: Narrowing proxy to class org.jbpm.graph.node.TaskNode - this operation breaks ==
13:52:28,700 WARN  [org.hibernate.engine.internal.StatefulPersistenceContext] (http-/0.0.0.0:8080-29) HHH000179: Narrowing proxy to class org.jbpm.graph.node.TaskNode - this operation breaks ==
13:52:28,700 WARN  [org.hibernate.engine.internal.StatefulPersistenceContext] (http-/0.0.0.0:8080-29) HHH000179: Narrowing proxy to class org.jbpm.graph.node.TaskNode - this operation breaks ==
13:52:28,770 WARN  [org.hibernate.engine.internal.StatefulPersistenceContext] (http-/0.0.0.0:8080-29) HHH000179: Narrowing proxy to class org.jbpm.graph.node.TaskNode - this operation breaks ==
13:52:28,771 WARN  [org.hibernate.engine.internal.StatefulPersistenceContext] (http-/0.0.0.0:8080-29) HHH000179: Narrowing proxy to class org.jbpm.graph.node.TaskNode - this operation breaks ==

**Comment by crivano** [comment]
@luiz-antonio , obrigado por perceber esse erro. O WF está recarregando as configurações a cada request! Isso deve estar fazendo o SIGA ficar mesmo muito lento no canário. Já estou trabalhando na correção.

```
13:52:27,638 INFO siga.conf.cache Cache de configurações inicializado via WfConfiguracaoBL em 13519ms
```
