### ISSUE TITLE
[webwork] NPE no teste de disponibilidade

### ISSUE THREAD

**Issue by raphaelpaiva** [projeto-siga/siga#543]
O NPE ocorre quando uma matrícula que não existe é passada. Acontece na classe ExGadgetAction, na linha 109:

    DpPessoa pes = daoPes(param("matricula"));

`pes` fica nulo, pois a matrícula não existe e estoura o NPE. Deveria exibir um erro de autenticação ao invés de um NPE.

**Comment by raphaelpaiva** [comment]
Esqueci de perguntar... Esse teste existe no vRaptor?

**Comment by crivano** [comment]
Existe, sim. Esse erro não chega a ser relevante, pois ele significa que a pessoa usou o teste da maneira errada. O teste precisa que o parâmetro matrícula esteja presente na query-string.

**Comment by luiz-antonio** [comment]
@crivano a quantidade de registros no log é muito grande, atrapalha a visualização dos erros "reais". Quanto mais dessas entradas em LOG eliminarmos, melhor para identificarmos os problemas.

**Comment by crivano** [comment]
@luiz-antonio , esse é aquele erro porque estão usando a url de testes com minha matrícula antiga? Será que vc não consegue identificar qual a origem dessa requisição? Vou alterar o vraptor, mas o webwork nem roda aqui na minha máquina.

**Comment by raphaelpaiva** [comment]
@crivano é esse mesmo. Conheço esse sentimento, aqui o webwork tb não rodou hahahah

**Comment by crivano** [comment]
para o vraptor já está feito: https://github.com/projeto-siga/siga/commit/43a1ed5a118de7d5891db599c49dee86b7be0299

**Comment by crivano** [comment]
Fechei pq não vamos corrigir para o WebWork e no vRaptor já está ok.
