### ISSUE TITLE
ORA-00942: a tabela ou view não existe

### ISSUE THREAD

**Issue by raphaelpaiva** [projeto-siga/siga#551]
Não tenho certeza se é no cp ou no wf.

A stacktrace está em anexo.

[exceptionTabelaNaoExiste.txt](https://github.com/projeto-siga/siga/files/90728/exceptionTabelaNaoExiste.txt)

**Comment by luiz-antonio** [comment]
WF

De: Raphael Paiva [mailto:notifications@github.com]
Enviada em: quinta-feira, 14 de janeiro de 2016 15:13
Para: projeto-siga/siga
Assunto: [siga] ORA-00942: a tabela ou view não existe (#551)


Não tenho certeza se é no cp ou no wf

A stacktrace está em anexo

exceptionTabelaNaoExistetxt<https://githubcom/projeto-siga/siga/files/90728/exceptionTabelaNaoExistetxt>

**Comment by crivano** [comment]
@luiz-antonio e @raphaelpaiva , o problema ocorre no WF:

´´´
15:07:11,694 ERROR [stderr] (http-/0.0.0.0:8080-10)     at br.gov.jfrj.siga.wf.vraptor.WfInterceptor.intercept(WfInterceptor.java:37)
´´´

O query é bastante simples e envolve uma única tabela: CORPORATIVO.CP_MODELO

Provavelmente a questão é que a conexão do WF não tem mapeada essa tabela. Sugiro pedir a SEABAD para fazer um GRANT SELECT para que o usuario sigawf_con consiga ver corporativo.cp_modelo.

**Comment by raphaelpaiva** [comment]
@luiz-antonio como fazemos? Abrimos um chamado pra isso?

**Comment by luiz-antonio** [comment]
Fiz  agora há pouco.

**Comment by crivano** [comment]
@luiz-antonio , podemos fechar essa issue?

**Comment by luiz-antonio** [comment]
Se for apenas aquela tabela, Sim. Já dei o GRANT necessário.
