### ISSUE TITLE
DOC: Reativar ajax na página de edição para compatibilizar com o Jaws

### ISSUE THREAD

**Issue by crivano** [projeto-siga/siga#560]
Esse ajax precisou ser desativado no commit https://github.com/projeto-siga/siga/commit/976092646a662f55856342b6ba6133f93ac04299 , pois causava problemas com o CKEDITOR. Quando for refeito, isso precisa ser testado com muita calma.

**Comment by esredson** [comment]
Acho que seria interessante, em casos como esse, insistirmos um pouco em solucionar as incompatibilidades entre os recursos, procurando não optar por desabilitar um deles. Abraços!

**Comment by esredson** [comment]
Referente à solicitação JFRJ-SR-2015/00295, na lista de melhorias do Siga-Doc
