### ISSUE TITLE
[legado] Erro de sintaxe em query

### ISSUE THREAD

**Issue by raphaelpaiva** [projeto-siga/siga#561]
Segue a stacktrace:

[ExceptionErroSintaxe.txt](https://github.com/projeto-siga/siga/files/99450/ExceptionErroSintaxe.txt)

**Comment by crivano** [comment]
@raphaelpaiva , acho que é um caso muito particular de uma consulta incomum no legado. Vou fechar, mas se estiver ocorrendo com muita frequência e atrapalhando alguma coisa, peço para reabrir.
