### ISSUE TITLE
SR: busca rápida por solicitação não está funcionando

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#567]

**Comment by raphaelpaiva** [comment]
Alguma possibilidade de adicionar um feedback na busca? De vez em quando ela demora, mas não tem nenhuma indicação de que a requisição está sendo atendida. Acho que podia ter um ajaxwheel, ou algo do tipo.

**Comment by crivano** [comment]
Ótima ideia, @raphaelpaiva . Já temos isso funcionando na página de busca do GSA, talvez possamos usar o mesmo código...

**Comment by rafaela00castro** [comment]
Resolvido no commit 2a5653c
