### ISSUE TITLE
Doc: Remover marcas de documentos

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#568]
Implementar remoção de marcas (pendente de assinatura, aguardar devolução) atribuídas de forma equivocada pelo usuário ou que não façam mais sentido existirem, pelo Siga-Doc (para usuários administradores), evitando apagá-las diretamente no banco;

**Comment by esredson** [comment]
Relacionada à issue #839

**Comment by esredson** [comment]
Ver #1109
