### ISSUE TITLE
Usuário e senha não estão auto completando na página de login do sigaidp

### ISSUE THREAD

**Issue by hodrigohamalho** [projeto-siga/siga#57]
Acho que é o javascript do placeholder.

**Comment by hodrigohamalho** [comment]
coloquei a versão em homologação e lá o chrome faz o preenchimento dos campos de forma automática sem problemas... To achando que isso é coisa do navegador mesmo

**Comment by kmacedovarela** [comment]
Testei no IE, no ambiente de homologação e funcionou.
