### ISSUE TITLE
Doc: Marcas são calculadas erradas em caso de movimentações excedentes (webwork)

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#573]
Na versão webwork do Siga, um erro frequente e que ocasiona abertura recorrente de chamados são movimentações gravadas no banco de forma repetida para a mesma operação, o que é proveniente de lentidão no sistema.

Exemplo: 

![captura_de_tela_012716_101609_am](https://cloud.githubusercontent.com/assets/4949149/12613250/9a1dc51a-c4df-11e5-960e-84ec0ad4fb8a.jpg)

Nesse caso, ocorreram vários recebimentos tanto pela SGS quando pela SID, o que gerou erro na marca "Aguardando andamento", que foi definida para as duas lotações.

**Comment by Chrystinne** [comment]
Estratégia para evitar abertura de chamados para esta situação: Verificar se é possível desconsiderar movimentações repetidas no cálculo dos marcas, visto que a motivação para abertura de chamados é quase sempre o erro nas marcas e não a repetição em si.

**Comment by crivano** [comment]
@Chrystinne , será que o mesmo erro ocorre no vRaptor? Não sei de devemos nos empenhar para corrigir problemas do WW.

**Comment by Chrystinne** [comment]
@crivano Ainda tenho dúvida se vai ocorrer no vraptor. Conversando com @andresousa17, a gente acha que esse problema ocorre quando se tenta movimentar documentos volumosos enquanto o sistema está muito lento. Mas não sei se temos pessoas usando o vrpator que trabalhem com processos muito grandes, com vários volumes. E tb não sei se o vraptor já ficou tão lento a ponto de causar esse problema. Em todo caso, acho que valeria a pena ignorar as movimentações repetidas no cálculo das marcas.

**Comment by Chrystinne** [comment]
Corrigindo já na versão vraptor, claro.

**Comment by crivano** [comment]
Ok

**Comment by raphaelpaiva** [comment]
@Chrystinne @crivano a questão da carga baixa no vraptor ainda me preocupa bastante... Existe alguma infra pra testes de carga que possamos trabalhar? Acham interessante?

**Comment by crivano** [comment]
@raphaelpaiva , já usamos o JMeter em algumas ocasiões. E gostaria de aumentar a carga na serie1cabrio expandindo o uso para outras secretarias e também para power-users.

Fazer testes de carga e todos os módulos do Siga, na versão vRaptor, como um requisito para colocá-la em produção seria um suicídio ao meu ver. Mesmo quando tínhamos o apoio de uma fábrica e um mentoring não conseguimos fazer tais testes. Entre outros problemas, precisaríamos de um ambiente para isso. 

Se não me engano, chegamos a fazer alguns testes quando tínhamos montado o ambiente siga-beta. @Markenson , vc lembra de algum resultado?

No mais a versão vRaptor nos parece mais leve que a WebWork, o que seria um bom indicativo.

Outra coisa, você saberia dizer como anda a carga na serie1cabrio? Suportaria o dobro de usuários?

**Comment by Markenson** [comment]
O teste de carga foi feito pelo pessoal do mentoring na máquina classec250 (antecessora da serie1cabrio). Na época a garantia era de 30 usuários simultâneos, mas a máquina dividia recursos com diversas outras aplicações.

**Comment by raphaelpaiva** [comment]
@crivano Não falei no sentido de ser um requisito pra ir pra produção não :). Concordo plenamente com você que devemos aumentar a abrangência do canário!

Eu só estou meio preocupado. Com a exceção do TP, que vamos deployar a versão com fix hoje, o doc está beeeem estável, com consumo de memória muito tranquilo.

Sei lá...

@Markenson 30 usuários simultâneos não parece pouco?

**Comment by Markenson** [comment]
@raphaelpaiva Sim, é pouco. Na época (não sei se continua assim) não tínhamos recursos de máquinas e era o que dava pra atender. Para garantir uma qualidade na validação da aplicação, a ideia era colocar poucas pessoas, porém estratégicas, para utilizar o sistema em vez de toda uma lotação. Com a entrada da serie1cabrio a capacidade melhorou, mas não houveram novos testes.

**Comment by raphaelpaiva** [comment]
Entendi!

**Comment by esredson** [comment]
Enquanto a repetição de movimentações ainda ocorre, é necessário que a rotina de marcação não interprete isso como se tivesse que multiplicar as marcas.

**Comment by esredson** [comment]
Ver #741
