### ISSUE TITLE
GERAL: Padronizar estrutura de LOGs

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#574]
Como os Logs emitidos pelos sistemas não utilizam uma forma padrão (às vezes são emitidos via console ou não usam uma estrutura definida), é difícil desabilitá-los, selecioná-los ou alterar seus respectivos níveis de detalhes via gerenciamento do servidor de aplicações.

Esta issue foi aberta com o objetivo de padronizar a emissão de logs nos sistemas.

**Comment by raphaelpaiva** [comment]
Existe um outro problema fundamental, além do formato: o que se deve logar.

Existem **muitas** exceções de negócio que são logadas, inclusive com a stacktrace. [Abri Issues para algumas que encontrei](https://github.com/projeto-siga/siga/issues/created_by/raphaelpaiva). Exceções de negócio são tratáveis e devem ser exibidas como mensagens para o usuário, elas não tem valor para os logs dos servidores.

**Comment by Markenson** [comment]
@raphaelpaiva Provavelmente você deve conseguir inibir boa parte desses logs de negócio através das configurações do Jboss impedindo especificamente br.gov.jfrj.siga.base.AplicacaoException. Mas como não há padronização, provavelmente outras mensagens devem continuar sendo exibidas.
