### ISSUE TITLE
SIGA: Duplicação de identidades ao clicar no "Esqueci minha senha"

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#579]
Marcos Fragoso reportou que um um usuário ficou com duas identidades ativas (na base de desenvolvimento) após clicar em "Esqueci minha senha" e, com isso, o usuário não conseguia acessar o sistema. Ele resolveu excluindo uma das identidades diretamente no banco de dados, mas precisamos confirmar se isso está realmente acontecendo.

O problema ocorreu na siga-dev (vraptor).

**Comment by crivano** [comment]
Me lembro de algo semelhante ter ocorrido comigo, mas talvez seja apenas numa situação muito especifica.

Toda vez que se clica em "Esqueci minha senha" o sistema gera um novo registro. O problema seria se ficassem dois registros com HIS-ATIVO=1, o que não ocorreu nos testes.

Vou fechar a issue e reabrimos se voltar a ocorrer.
