### ISSUE TITLE
SR: Alguns anexos não são listados

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#581]
Reportado por Herval:

O chamado TRF2-SR-2016/99374 possui dois anexos ALTER_GENERATION03.ddl e SigaPMPvs001.pdf. Na versão 4.x os anexos são listados corretamente, mas na versão 5.x apenas o pdf está na lista.

![image](https://cloud.githubusercontent.com/assets/2985140/12751405/27b5eb82-c9a4-11e5-84be-4fd43056946e.png)

![image](https://cloud.githubusercontent.com/assets/2985140/12751424/43098696-c9a4-11e5-8c7c-bdcd9c185dde.png)

**Comment by rafaela00castro** [comment]
Para ficar registrado: feita alteração no exibir.jsp e arquivo.tag para acertar a descrição do arquivo que estava duplicada na listagem de movimentações ao exibir a solicitação.
