### ISSUE TITLE
Falta o 'Justiça Federal' no header do canário

### ISSUE THREAD

**Issue by raphaelpaiva** [projeto-siga/siga#582]
Provavelmente é uma property. Sabem qual é?
![header-canario](https://cloud.githubusercontent.com/assets/485947/12751696/cea26532-c9a5-11e5-9fd7-5bdb16fe2b80.png)
![header-webwork](https://cloud.githubusercontent.com/assets/485947/12751697/cea31ad6-c9a5-11e5-8a7b-c59c5c78abcf.png)

**Comment by crivano** [comment]
siga.cabecalho.titulo=Justiça Federal

**Comment by raphaelpaiva** [comment]
@crivano thx!
