### ISSUE TITLE
GERAL: Criar logger para leitura de properties

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#584]
Para auxiliar na depuração de problemas, seria interessante poder configurar um logger que exiba qual propriedade foi lida e qual valor retornado.

**Comment by crivano** [comment]
@Markenson: que tal se sempre que ocorrer um erro, logarmos a url, os parameters, o nome do thread, o tempo de execução e o user-principal. Isso ajudaria bastante no debug, né? Ficaria parecido com o log da GAE, só que apenas quando ocorrer erro.

Uma referência: http://edwin.baculsoft.com/2014/04/logging-http-request-parameters-using-http-servlet/

**Comment by Markenson** [comment]
@crivano  O commit e6ee225e73be3db35204b88b50d4 já inclui a url quando ocorre um erro, bastaria aperfeiçoá-lo (outra issue talvez?). 

Para esta issue, na verdade a ideia era criar um logger exclusivo do carregador de propriedades que só seria ativado quando necessário (mesmo que não tenha ocorrido um erro explícito). Isso é útil para responder questões do tipo "qual foi o valor obtido para a propriedade x" ou "qual foi a string chave que o servidor montou ao tentar ler uma propriedede y? seguiu a hierarquia esperada?" ou ainda "troquei a propriedade na console do jboss, o sevidor já percebeu a mudança sem reiniciar?").

**Comment by crivano** [comment]
@Markenson: sim, vou criar outra issue. Tks.
