### ISSUE TITLE
IDP: Erro ao clicar back

### ISSUE THREAD

**Issue by crivano** [projeto-siga/siga#585]
Reportado por @luiz-antonio :+1: 

Esse é um erro comum, quando estamos na página de LOGIN e creio que o IDP expira. Executo um BACK no navegador (IE, no caso) e retiro o “idp” (fica //siga/siga) e a página entra.

![image001](https://cloud.githubusercontent.com/assets/4137623/12758602/3be9f740-c9c4-11e5-97a0-1f2d5b76551f.png)

Encontro muitas ocorrências desta no LOG do Apache.

**Comment by crivano** [comment]
Não sei se é algo que possamos resolver. Talvez a solução seja simplesmente filtrar para não aparecer no log. Parece ser um problema intrínseco do JBoss e do Picketlink.

**Comment by luiz-antonio** [comment]
Vou tentar redirecionamento condicional pelo apache.

**Comment by adrigrassi** [comment]
retirando o idp da url http://siga.jfrj.jus.br/sigaidp o sistema entra.
