### ISSUE TITLE
ORA-20101: Não é permitido alterar: eletrônico, com conteúdo, tipo mov. 11 e sem mov. canceladora.

### ISSUE THREAD

**Issue by raphaelpaiva** [projeto-siga/siga#587]
Pessoal, parece que é uma regra de negócios tratada diretamente no banco. Confirmam? Não seria melhor validar isso antes de tentar gravar?

[exceptionORA20101.txt](https://github.com/projeto-siga/siga/files/114432/exceptionORA20101.txt)

**Comment by luiz-antonio** [comment]
Isso é um a TRIGGER que implementa uma regra de segurança contra alteração/exclusão (Before Update or Delete on SIGA.EX_DOCUMENTO).

**Comment by raphaelpaiva** [comment]
Será que é possível fazer a mesma verificação na aplicação? Sem excluir a trigger, claro.

**Comment by crivano** [comment]
@raphaelpaiva , em tese o sistema já tem essa lógica implementada e esse trigger não deveria ser disparado nunca.

Ocorre muitas vezes? Ocorre no vraptor?

**Comment by raphaelpaiva** [comment]
Reparei hoje, na versão webwork. Creio que não ocorra muitas vezes não.

**Comment by raphaelpaiva** [comment]
O @luiz-antonio acabou de comentar que ocorre na vraptor tb, apesar de ser raro.
