### ISSUE TITLE
Melhorias na classe br.gov.jfrj.siga.base.Correio

### ISSUE THREAD

**Issue by raphaelpaiva** [projeto-siga/siga#596]
Pessoal,

Tentei comentar nos respectivos commits, mas a maior parte deles é em um commit de mais de 3 mil arquivos, e o chrome trava :laughing: então resolvi abrir a issue.

Na linha 164: `Multipart mp = new MimeMultipart("alternative");`

Tenho quase 100% de certeza que esta linha está relacionada com o log
`[br.com.caelum.vraptor.interceptor.multipart.CommonsUploadMultipartInterceptor] (http-/0.0.0.0:8080-15) Request contains multipart data. Try to parse with commons-upload.`
Talvez possamos investigar o porquê deste 'warning'.

Na linha 204: `catch (final Exception e) {throw e;}` Este catch pode ser apagado. Ele não faz absolutamente nenhum tratamento e só serve pra aumentar e deixar mais confusa a stacktrace. Deixando a exceção 'estourar' no método deixa a stacktrace mais enxuta, neste caso onde não há tratamento.

Na linha 81: `catch (Exception e) { Logger.getLogger("siga.email").warning("Servidor de e-mail indisponÃ­vel: " + servidorEmail);;}` Temos dois problemas: um ';' a mais e damos catch numa exceção sem dizer nada sobre a mesma. Essa mensagem de erro é a mesma coisa que ligarem pra gente e falarem "Olha, o siga não funciona" sem dar detalhes do que está havendo :wink: .
Aqui eu peço encarecidamente: Não dêem printstacktrace, mas coloquem e.getMessage() e e.getCause().getMessage(). Vai nos ajudar MUITO!

**Comment by crivano** [comment]
@raphaelpaiva , as alterações foram realizadas. No entanto, o warning não apareceu nos testes e imagino que realmente não seja essa a parte do código que o produz, já que se trata de um warning do vraptor e esse código nem tem dependência nessa biblioteca.
