### ISSUE TITLE
Erro de interface - "módulo indisponível"

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#60]
O erro é intermitente. A mensagem "módulo indisponível" aparece na tela inicial do Siga, conforme ilustrado na imagem:

![modulo indisponivel](https://cloud.githubusercontent.com/assets/4949149/5725185/e6ba137e-9b37-11e4-9ba3-6d1cdd7270db.png)

**Comment by Chrystinne** [comment]
Como observei que este erro também ocorre na Hmg, acrescentei o label [HMG] nesta issue.

**Comment by kmacedovarela** [comment]
Quando dá esse erro, os seguinte log é lançado:
16:17:25,516 ERROR [br.gov.jfrj.siga.libs.webwork.SigaExceptionHandler] (http-localhost/127.0.0.1:8443-4) Código do tipo de marca (Processos ou Expedientes) não foi informado URL: https://localhost:8443/sigaex/expediente/doc/gadget.action?idTpFormaDoc=1&apenasQuadro=true&_=1422296241685 User: RJ13286: java.lang.Exception: Código do tipo de marca (Processos ou Expedientes) não foi informado
	at br.gov.jfrj.webwork.action.ExGadgetAction.execute(ExGadgetAction.java:71) [classes:]

**Comment by hodrigohamalho** [comment]
Corrigido, caso volte a acontecer, favor reabrir.
