### ISSUE TITLE
SR: envio de e-mail está síncrono

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#601]
Tornar o envio assíncrono no SR, GC e outros. Opções: 
1. fazer como https://github.com/projeto-siga/siga/blob/master/siga-ex/src/main/java/br/gov/jfrj/siga/ex/util/Notificador.java
2. Usar o código feito pelo mentoring para a SESGEP
3. Usar o JMS (https://en.wikipedia.org/wiki/Java_Message_Service)

**Comment by raphaelpaiva** [comment]
Sou a favor de usar mensageria. Na ufrj implementamos o serviço utilizando o [RabbitMQ](https://www.rabbitmq.com). Lá era oportuno utilizar pois tínhamos váááários processos que se beneficiariam de uma fila de processamento, não sei se é o caso daqui.

Com o envio assíncrono, conseguimos que a aplicação não trave (ou falhe) esperando o envio do email, porém, se houver falha na comunicação com o servidor de emails ou qualquer outro tipo de erro, a notificação não será enviada. Com filas de processamento, podemos garantir que a mensagem será enviada, mesmo que falhe.

**Comment by esredson** [comment]
O que acham, @crivano, @rafaela00castro, @Chrystinne e @Markenson? Vale a pena já partirmos pra isso quando formos atacar o problema, talvez aplicando a todo o Siga?

**Comment by raphaelpaiva** [comment]
Posso conseguir a implementação de lá para analise do código!

**Comment by Markenson** [comment]
Não sei se vocês concordam, mas como é raro acontecer o tipo de problema que tivemos no envio de e-mails ontem, acho que podemos seguir duas frentes:

A. **Imediata** (nesta issue). Fazendo o que for mais simples dos itens 1 ou 2 descritos pelo @esredson 

B. **Definitiva** (outra issue/projeto). Adotarmos algo mais robusto como o serviço de mensageria, pois isso inclusive beneficiaria outros sistemas além do SIGA (essa é uma oportunidade para avaliarmos o quanto isso agrega de valor à instituição). Algumas atividades que poderiam ser executadas seriam:

	- Comparação dos frameworks existentes para saber qual seria mais adequado; 
	- Adequação de códigos por parte da nossa equipe e (possivelmente as outras equipes de desenvolvimento);
	- Disponibilização do ambiente por parte do pessoal de infraestrutura.
	

@raphaelpaiva Se realmente a linha da mensageria for adotada, seria muito legal se você conseguisse essa implementação.

**Comment by crivano** [comment]
Sou a favor. Podemos usar a própria implementação de mensageria do JBoss...

**Comment by raphaelpaiva** [comment]
@Markenson concordo 110% com a sua colocação. A solução de mensageria é definitiva e com certeza não é rápida de implementar :smile: Vou dar uma olhada no HornetQ do JBoss. Eu nunca usei.

Existem outros processos no sistema que requerem processamento em batch ou processamento assíncrono?

**Comment by esredson** [comment]
Blz. Vou então já usar a solução do Siga-Doc de modo provisório, considerando que é simples de implementar e trará ganho imediato na performance. Vai resolver também o problema na montagem da URL nos e-mails de notificação sobre solicitações, pois o Siga-Sr vai passar a obter o endereço a partir da property, como o Siga-Doc faz. Depois partimos pra solução definitiva. Aí, a @rafaela00castro pode assumir, já que tinha começado a trabalhar nessa parte há um tempo mas teve de deixar de lado.

**Comment by esredson** [comment]
Ver #618
