### ISSUE TITLE
SR: termo de atendimento sem a descrição do chamado

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#602]
Termo de atendimento nem sempre mostra a descrição do chamado. Por exemplo, TRF2-SR-2015/05589.04, relatado pelo PC.

**Comment by rafaela00castro** [comment]
![captura_de_tela_031017_045213_pm](https://cloud.githubusercontent.com/assets/8461113/23811088/34e72590-05b3-11e7-903d-59de43cf25cb.jpg)

**Comment by rafaela00castro** [comment]
![captura_de_tela_031017_050228_pm](https://cloud.githubusercontent.com/assets/8461113/23811119/58a6f19a-05b3-11e7-8794-e42697cd50e9.jpg)
