### ISSUE TITLE
[Siga-Doc] Erro de interface (encoding)

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#61]
- Ilustração:

![erro-encoding-oficio](https://cloud.githubusercontent.com/assets/4949149/5725417/c3785964-9b39-11e4-9ff4-3f51b1df10dd.png)

- Como reproduzir:

Na página de criação de novo documento (https://siga-dev/sigaex/expediente/doc/editar.action), selecionar "Tipo" Ofício.

**Comment by AndDeluiz** [comment]
@Chrystinne 
Foram alteradas as configurações de localização no JBoss, que estavam incorretas.
Entretanto, mesmo assim reproduzi o erro no ambiente Docker. A Karina @kmacedovarela reproduziu o mesmo problema na volvofh16, mas não conseguiu no novo ambiente de homologação.
Continuaremos verificando.

**Comment by Chrystinne** [comment]
@AndDeluiz Esse erro ocorre no Siga-dev. O @hodrigohamalho informou que o ambiente de homologação novo (http://siga-hmg) estará indisponível hoje. 
Mas devido ao problema reportado em #73, não consigo mais testar as alterações que fiz no Siga-dev.

**Comment by kmacedovarela** [comment]
Pode voltar a testar, issue #73 fechada

**Comment by hodrigohamalho** [comment]
Testei essa issue em homologação e o problema não ocorre. 
Parece ser especificamente do ambiente de desenvolvimento com docker. 

Como é um erro que não vai refletir em produção, vou focando em outros erros e depois volto neste.

**Comment by kmacedovarela** [comment]
Modelos freemarker que foram salvos com problema de encoding permanecerão com problemas até que seja salvo novamente com as devidas correções pois foi já foi salvo com erro.
Os novos modelos salvos não possuirão problemas de encoding.

O problema de encoding foi resolvido em resolvido em 92079df090efc70aafc9990cc383013318fe834b
