### ISSUE TITLE
SR: Permitindo cancelar movimentação que não é a última

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#610]
Se a última movimentação não pudesse ser desfeita, não deveria testar a anterior. Por exemplo, está sendo possível cancelar um término de pendência incluído antes da finalização do rascunho. Potencial para inconsistências.

**Comment by Chrystinne** [comment]
Esse erro não ocorre mais. No caso específico do cancelamento do término da pendência, não é mais possível que seja cancelado antes da solicitação deixar de ser rascunho, por dois motivos: 1- O sistema não habilita o link "Desfazer Término de Pendência" enquanto a solicitação for rascunho; 2- Não permite que uma solicitação deixe de ser rascunho caso possua pendência.
