### ISSUE TITLE
GC: no Internet Explorer, não é possível definir cor de fonte

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#612]
No Chrome, o erro não acontece. O problema é que, ao selecionar um texto no editor do Siga-GC, a seleção é desfeita quando se clica no botão de cor de fonte, fazendo com que a cor não se aplique a nenhum texto. É possível, no entanto, definir cor inserindo diretamente o código HTML. Verificar se há uma versão mais nova do editor em que isso esteja corrigido para o IE.

**Comment by Chrystinne** [comment]
![captura_de_tela_092216_112708_am](https://cloud.githubusercontent.com/assets/4949149/18752036/804cb472-80b7-11e6-9390-805c33285154.jpg)

Esse problema não ocorre mais no IE.
