### ISSUE TITLE
GERAL: Passar a usar serviço de mensageria

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#618]
Fazer com que todo o Siga use o mesmo serviço de mensageria. Ver também a issue #601.

**Comment by raphaelpaiva** [comment]
Conversei com o Márcio, ele explicou como funciona o serviço de emails aqui.

Temos 2 servidores: master e explorer. Podemos usar isso em nosso favor: balanceando os dois ou fail-over.

Outra coisa que ele falou que podemos usar é que é possível abrir uma sessão e autenticar apenas uma vez para enviar vários emails, como o outlook faz, ao invés abrir uma conexão e autenticar toda vez. Vou dar uma pesquisada pra ver se acho alguma lib que integre com o exchange.
