### ISSUE TITLE
DOC: Entrevista do modelo está sendo exibida incorretamente

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#619]
Quando o modelo é o primeiro da lista de uma espécie, a entrevista não é exibida corretamente. 

No exemplo abaixo, o primeiro modelo da espécie "Declaração" é "Declaração Ajuda de Custo para Moradia". Ele possui um campo chamado "Localidade" que não é exibido inicialmente. Apenas após clicar no link "editar" o campo se torna visível.

![issue](https://cloud.githubusercontent.com/assets/2985140/13080002/fd02cc60-d4ad-11e5-8d2e-e65ac4057805.gif)

**Comment by crivano** [comment]
@Markenson , dessa vez vc se superou! Esse Screen-o-matic é espetacular!

Vou ter que instalar isso aqui também! :)

**Comment by Chrystinne** [comment]
@Markenson Que legal!!

**Comment by Markenson** [comment]
:+1:

**Comment by raphaelpaiva** [comment]
@Markenson muito maneiro!!

**Comment by crivano** [comment]
Ahaha, agora está funcionando! Fiz até um filminho, mas salvei como MP4 e o GitHub só aceita GIF. Ok, vcs acreditam, né?

**Comment by crivano** [comment]
@Markenson , agora sim! Tks!

![closes619](https://cloud.githubusercontent.com/assets/4137623/13111804/1159ff6e-d56f-11e5-8062-038f0ac03afc.gif)
