### ISSUE TITLE
[Siga-Doc] Erro ao incluir modelo jsp (requerimento de férias)

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#62]
Erro (intermitente) ao incluir o modelo jsp de requerimento de férias.

- Ilustração:
![erro-requerimento-ferias](https://cloud.githubusercontent.com/assets/4949149/5725749/d79fc3d4-9b3c-11e4-8960-894b8df28822.png)

- Como reproduzir:
Na página de criação de novo documento (https://siga-dev/sigaex/expediente/doc/editar.action), selecionar "Tipo" Requerimento e "Modelo" SGP: Férias (servidor p/ superior hierárquico)

**Comment by kmacedovarela** [comment]
@Chrystinne pode verificar se continua ocorrendo? Esse erro pode ter ocorrido devido a uma reinicialização.

**Comment by Chrystinne** [comment]
@kmacedovarela É intermitente, mas testei novamente e ocorreu.

**Comment by Chrystinne** [comment]
@kmacedovarela Tem outro erro que ocorre no requerimento de férias. Mesmo quando o modelo jsp é incluído com sucesso, ele não se comporta como deveria. Vou cadastrar outra issue detalhando esse problema.

**Comment by kmacedovarela** [comment]
Tentei reproduzir várias vezes, inclusive enquanto analisava a issue #66 e não aconteceu. 
Caso volte a acontecer, favor reabrir a issue.
