### ISSUE TITLE
[Play] Erro no botão ao clicar no botão [...] 

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#63]
·         Ao clicar no botão [...] para buscar pessoas, lotações, etc, a partir do Siga-Sr ou do Siga-Gc, aparece a mensagem da imagem anexa (erroCliqueBotaoSelecao.png)

![errocliquebotaoselecao](https://cloud.githubusercontent.com/assets/253186/5726263/217da0a8-9b41-11e4-9ca4-f33f5b886a2e.png)

Reportado por: @esredson

**Comment by kmacedovarela** [comment]
@hodrigohamalho  quando for verificar a issue #65 se der já verifica esta também.

**Comment by hodrigohamalho** [comment]
@Chrystinne  tem como me ajudar a reproduzir este erro?

**Comment by Chrystinne** [comment]
@hodrigohamalho Sim, Rodrigo. Vou tentar reproduzir esse erro na siga-dev.

**Comment by Chrystinne** [comment]
@hodrigohamalho Consegui reproduzir tanto no Siga-Gc quanto no Siga-Sr. 

1) No Siga-Gc:
Testei o botão [...] em três lugares da aplicação. Um apresenta problema e os outros dois estão ok.
Vamos ao problema:
Na página de criação de conhecimento (https://siga-dev/sigagc/app/editar), em "Edição" escolher a opção "Grupo" e, em seguida, clicar no botão [..]. Esta ação deveria abrir uma tela de busca, mas não está surtindo nenhum efeito. (Vide imagem abaixo)

![captura_de_tela_011615_122438_pm](https://cloud.githubusercontent.com/assets/4949149/5777538/a4d12d0e-9d7a-11e4-8ac9-c2cd7f7b9fc8.jpg)


2) No Siga-Sr:
Na página de cadastro de nova solicitação (https://siga-dev/sigasr/solicitacao/editar), clicar no botão [...], conforme ilustrado na imagem abaixo. A ação deveria abrir uma tela de busca, mas não está surtindo nenhum efeito.
![captura_de_tela_011615_122918_pm](https://cloud.githubusercontent.com/assets/4949149/5777608/4bd7b26c-9d7b-11e4-87bc-23caefe89f5e.jpg)
