### ISSUE TITLE
DOC: Lista de modelos permitidos não estão iguais entre a versão 4.x e 5.x

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#636]
A seguinte permissão foi atribuída à T2SEMGET:

Pode criar (todos os modelos). 

Após isso, na versão 4.x todos os modelos estavam disponíveis para a T2SEMGET, mas o mesmo não ocorreu na versão 5.x. Seguem imagens com exemplo:

![image](https://cloud.githubusercontent.com/assets/2985140/13289320/66f96f2a-daee-11e5-974d-d7b0531f62cb.png)

![image](https://cloud.githubusercontent.com/assets/2985140/13289373/8e4293d6-daee-11e5-9d26-d0b5b68e3ac8.png)

**Comment by crivano** [comment]
Esse era um problema que fazia com que o primeiro item da lista fosse omitido. Já está resolvido na 5.0.1
