### ISSUE TITLE
DOC: Cadastro de modelo com barra de rolagem no meio do texto

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#640]
Ao editar um modelo do freemarker na versão 5.x uma barra de rolagem aparece no meio do texto e ocasionando problema nos modelos ao salvar.

![image](https://cloud.githubusercontent.com/assets/2985140/13299388/b94fe652-db19-11e5-8338-f58f963e74f3.png)

![image](https://cloud.githubusercontent.com/assets/2985140/13299376/a6b54546-db19-11e5-91a1-c8087f524a53.png)

**Comment by crivano** [comment]
Só não consegui resolver o problema da largura ser limitada a 100%. Parece que quando a altura é automática, a largura fica automática também.
