### ISSUE TITLE
WF: Ao acessar a url antiga da tarefa (via e-mail) o sistema apresenta erro

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#643]
É necessário mapear a url antiga na versão 5.x

**Comment by crivano** [comment]
Na verdade, quando a v5 estiver plenamente implantada isso não será problema. Não sei se devemos investir nesses paleativos ou se aceitamos que isso é temporário e seguimos em frente...

**Comment by Markenson** [comment]
Beleza, fecho esta issue direto?

**Comment by crivano** [comment]
Eu acho que sim.
