### ISSUE TITLE
DOC: Criar rotina que restringe o acesso a determinados documentos

### ISSUE THREAD

**Issue by crivano** [projeto-siga/siga#644]
Precisaremos fazer isso pois alguns documentos não deveriam ser públicos, mas foram marcados dessa forma.

**Comment by crivano** [comment]
Já tenho um protótipo da tela, e já fiz uma rotina genérica para controlar várias operações ajax em lote:

![trocandonivelsigiloemlote](https://cloud.githubusercontent.com/assets/4137623/13476398/7286c4d8-e0a6-11e5-9e1c-c2989370b383.gif)

**Comment by raphaelpaiva** [comment]
:clap: Muito legal!
