### ISSUE TITLE
[Play] Campo seleção não funciona o submit

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#65]
·         Numa das telas do Siga-Sr, a informação gerada pelo campo Seleção (aquele mesmo, que contém o [...]) não está sendo enviada no submit (itemNaoInformado.png). Ainda preciso debugar para saber exatamente o que está havendo, mas imaginei que valia a pena mencionar aqui porque nós não nos deparamos com esse erro até hoje. Aliás, eu já conseguiria fazer o debug remoto nesse servidor?

![itemnaoinformado](https://cloud.githubusercontent.com/assets/253186/5726339/85736ec6-9b41-11e4-9a64-23ddf1dc36aa.png)

reportado por @esredson

**Comment by kmacedovarela** [comment]
@esredson  este erro é conhecido, o @hodrigohamalho  já corrigiu ele em outros locais. 
Não precisa debugar, vamos verificar.

Obrigada

**Comment by hodrigohamalho** [comment]
@Chrystinne tem como me ajudar a reproduzir este erro?

**Comment by Chrystinne** [comment]
@hodrigohamalho Sim. Vou tentar reproduzir esse erro na siga-dev.

**Comment by Chrystinne** [comment]
@hodrigohamalho Semelhante ao problema reportado na issue #63. 

-Como reproduzir:
Cadastrar uma nova solicitação (https://siga-dev/sigasr/solicitacao/editar); Preencher os campos "descrição" e "Produto, Serviço ou Sistema relacionado à Solicitação". O preenchimento deste último não está surtindo efeito. Veja ilustração abaixo: 
![captura_de_tela_011615_125234_pm](https://cloud.githubusercontent.com/assets/4949149/5777979/8c21dbd8-9d7e-11e4-9ac2-54afa1dbd165.jpg)
