### ISSUE TITLE
SR: situação Fora do Prazo não foi aplicada 

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#658]
Conforme informado pelo George, as solicitações abertas por ele para teste não tiveram a marca "Fora do Prazo" inserida.

ver solicitações: TRF2SR201621342 e TRF2SR201621341 em produção.

De acordo com Edson, poder ser algum erro relacionado ao fato da solicitação ter sido aberta fora do horário do expediente.

**Comment by rafaela00castro** [comment]
@edson, realmente o problema de LazyInitializationException no getAcordos() era o serviço OPENSAVE habilitado. Desabilitei e consegui cadastrar a solicitação.

**Comment by rafaela00castro** [comment]
@esredson, o método atualizarMarcas() no SrSolicitacao.java não está aplicando a marca "fora do prazo" pq o método getAtendimentoAtivo() que é usado para pegar o FimPrevisto e calcular o prazo, volta null quando a solicitação é aberta fora do prazo, como realmente tem que ser, já que não tem atendimento ativo. Vou alterar a lógica para pegar o fim previsto.

**Comment by raphaelpaiva** [comment]
Sugestão: Ao invés de retornar null, lançar uma exceção (tipo SolicitacaoForaDoPrazoException), já que é de fato, um caso excepcional. Nunca é bom dar semântica pra null.

**Comment by rafaela00castro** [comment]
OK, @raphaelpaiva! obrigada pela sugestão ;)
