### ISSUE TITLE
[Siga-Doc] Erro no requerimento de férias [modelo "SGP: Férias (servidor p/ supervisor hierárquico)"]

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#66]
-Ilustração:
![erro-marcacao-alteracao-de-ferias](https://cloud.githubusercontent.com/assets/4949149/5726342/8c1a715c-9b41-11e4-9a69-9683ba6fe8f2.png)

-Como reproduzir:
Na página de criação de novo documento (https://siga-dev/sigaex/expediente/doc/editar.action), selecionar "Tipo" Requerimento e "Modelo" SGP: Férias (servidor p/ superior hierárquico). Em "Dados complementares", "Selecione a opção desejada". Selecionar a opção "alteração" ou a opção "marcação" não produz o efeito desejado, o que ocorre é que a página é atualizada, mas não sofre alterações.

**Comment by kmacedovarela** [comment]
Problema identificado, estou verificando como resolver.

**Comment by kmacedovarela** [comment]
Este erro acontece devido ao problema de encoding no ambiente de desenvolvimento. 
Para exibir a página é realizada uma comparação entre strings, ou seja, as strings com caracteres especiais não se comportarão conforme esperado.

Favor testar essa issue no ambiente de homologação que está sem o problema de encoding:
https://siga-hmg/sigaex/expediente/doc/editar.action

**Comment by Chrystinne** [comment]
Erro não ocorre mais na Siga-Dev nem na Siga-Hmg.
