### ISSUE TITLE
GERAL: Logando indevidamente: Request contains multipart data.

### ISSUE THREAD

**Issue by crivano** [projeto-siga/siga#662]
Ocorre com muita frequência no log e precisamos estudar o motivo.

```
INFO  [br.com.caelum.vraptor.interceptor.multipart.CommonsUploadMultipartInterceptor] (http-/0.0.0.0:8080-7) Request contains multipart data. Try to parse with commons-upload.
```

**Comment by crivano** [comment]
@raphaelpaiva , vou pesquisar e te aviso se descobrir algo.

**Comment by raphaelpaiva** [comment]
@crivano provavelmente é o que você falou mesmo. O vraptor captura esse problema quando envia um multipart. Talvez no código do envio de email, quando monta o multipart, dê pra usar o do commons-upload.

**Comment by crivano** [comment]
@raphaelpaiva , descobri que basta mandar um arquivo via http para o servidor, tipo quando anexamos um pdf a um documento existente, que essa mensagem aparece no log. Não tem nada a ver com o código do email.

A questão é que isso não é um bug, mas sim uma característica do vraptor. Se olhar bem, essa não é uma mensagem de warning ou error, é apenas um info. Pelo texto, parece que ele está dizendo que devemos tentar fazer o parse de outra maneira, mas não é o caso. O que ele está tentando dizer é que ele vai usar comons-upload para tentar fazer o parse.

Ou seja: a solução é configurar o log4j para suprimir INFO de br.com.caelum.vraptor.interceptor.multipart.CommonsUploadMultipartInterceptor nos servidores de produção.

**Comment by crivano** [comment]
Em tempo, veja a linha de código que produz esse log:

https://github.com/caelum/vraptor/blob/master/vraptor-core/src/main/java/br/com/caelum/vraptor/interceptor/multipart/CommonsUploadMultipartInterceptor.java#L94

**Comment by raphaelpaiva** [comment]
Putz, Boa! My bad :smile:
