### ISSUE TITLE
GERAL: limpeza e ajuste de propriedade

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#664]
Verificar todas as propriedades de todos os módulos, eliminar as desnecessárias e padronizar as restantes.

**Comment by esredson** [comment]
Os parâmetros abaixo estão definidos nas properties do siga e provavelmente sem uso (estão sendo referenciados em aplicações de sincronismos e alguns códigos de testes). Precisamos verificar a real necessidade e efetuar a remoção caso não haja necessidade deles.

c3p0.max_size 
c3p0.max_statements 
c3p0.min_size 
homolo.c3p0.timeout
