### ISSUE TITLE
Recuperar senha e sou um novo usuário em loop infinito

### ISSUE THREAD

**Issue by hodrigohamalho** [projeto-siga/siga#67]
Ao clicar em recuperar senha ou sou um novo usuário, os links são interceptados pelo IDP, com isso apenas usuários já cadastrados conseguem usar o sistema.
Isso impacta fortemente no ambiente de homologação, pois nenhum usuário do sigarh está conseguindo se cadastrar no sistema.

**Comment by kmacedovarela** [comment]
Preparando disponibilização.
