### ISSUE TITLE
DOC: Código do expediente não aparece no título

### ISSUE THREAD

**Issue by raphaelpaiva** [projeto-siga/siga#670]
Pessoal,

Assumi que o comportamento fosse o mesmo do SR e que deveria aparecer "SIGA - TRF2-MEM-2016/00125" no título. Atualmente fica "SIGA - ". Screenshot em anexo.

![title-sigaex](https://cloud.githubusercontent.com/assets/485947/13472543/20e25096-e094-11e5-9e40-5366da0ac5ab.PNG)

**Comment by Chrystinne** [comment]
Vou resolver essa issue, @crivano.

**Comment by Chrystinne** [comment]
![title_doc](https://cloud.githubusercontent.com/assets/4949149/13706877/ceae7554-e785-11e5-8eb4-39d0de2bf5f8.png)

**Comment by Chrystinne** [comment]
Resolvido no commit 1e76bff

**Comment by esredson** [comment]
A Chrys já tinha resolvido esse problema (Título da página de exibição de documentos aparece como "Siga - "). Verificar por que o ajuste não entrou na versão atual. 
![image](https://cloud.githubusercontent.com/assets/5264319/15191108/80ab5d98-1789-11e6-879a-9d678cc8c8ea.png)

**Comment by Chrystinne** [comment]
![captura_de_tela_061716_035809_pm](https://cloud.githubusercontent.com/assets/4949149/16161514/4a74a008-34a4-11e6-9fd9-83b0504e3f4e.jpg)

**Comment by Chrystinne** [comment]
Corrigido no develop. Fazer o merge para release-5.3.0

**Comment by Chrystinne** [comment]
Como acabei me confundindo e fiz a alteração no develop, ao invés de fazer no release-5.3.0 e depois fazer o merge com o develop, a alteração vai entrar apenas no release-5-3-1 e o merge será feito com o develop automaticamente.
