### ISSUE TITLE
GC: Rever classificações dos conhecimentos 

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#675]
Atualmente, o cadastro de classificações é case sensitive. Acredito que criar classificações diferentes para #sigadoc, #sigaDoc e #SigaDoc, por exemplo, pode complicar a vinculação dos conhecimentos às SRs. A ideia é fazer um filtro e armazenar/exibir a classificação com todos os caracteres em minúsculo.

**Comment by crivano** [comment]
Ótima ideia. Remover os acentos também é uma boa. Temos isso no siga-base,
se não me engano na classe Texto.java.

Em qui, 3 de mar de 2016 às 18:57, Chrystinne <notifications@github.com>
escreveu:

**Comment by Chrystinne** [comment]
Bem lembrado, @crivano. Vou remover os acentos, usando essa classe Texto.java. Nem tinha observado o comportamento quando a classificação tem acento. Ele quebra a string e salva só a parte anterior ao primeiro acento.
