### ISSUE TITLE
DOC: Ajustar o caminho do ckeditor

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#678]
O javascript do ckeditor está disponível em http://servidor/ckeditor/ckeditor/ckeditor.js (existe uma duplicação em 'ckeditor'). Para simplificar, o ideal seria http://servidor/ckeditor/ckeditor.js. 

Esta issue é de baixa prioridade, pois não impacta diretamente no funcionamento do sistema.

**Comment by raphaelpaiva** [comment]
Lembrem de notificar Eu, @rodrigo-ferreira  ou @luiz-antonio ao realizarem esta mudança, para que possamos acertar no apache também.
