### ISSUE TITLE
DOC: Nova versão não está estampando os PDFs

### ISSUE THREAD

**Issue by crivano** [projeto-siga/siga#689]

**Comment by Markenson** [comment]
O problema ocorre apenas na sigat. No canário está funcionando, conforme imagem abaixo. 

![image](https://cloud.githubusercontent.com/assets/2985140/13925767/60bb83e4-ef68-11e5-98e4-dd29e22cc8cd.png)

**Comment by Markenson** [comment]
O problema ocorre apenas na versão 5.1.0. Removendo do milestone v5.0.2.
