### ISSUE TITLE
DOC: Erro ao visualizar RTF

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#692]
Reportado no chamado JFRJ-SR-2016/31339 que no dia 08/03/2016 "Não foi possível visualizar o rtf da publicação a ser agendada no DJE: Documentos>Gerenciar Publicação DJE "
![captura_de_tela_031016_062342_pm](https://cloud.githubusercontent.com/assets/2985140/13685013/3b5a9ab4-e6ed-11e5-9cf9-d7aeb2ae0745.jpg)

**Comment by adrigrassi** [comment]
Este problema foi resolvido copiando os seguinte arquivos:
xhtml.dtd
xhtml-lat1.ent
xhtml-special.ent
xhtml-symbol.ent
para /home/jboss
