### ISSUE TITLE
Execução de script com usuário JBoss

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#70]
Verificar:
Quando executado pelo usuário jboss, o seguinte ocorre:

Stopping jboss-sigadoc (via systemctl):  Failed to issue method call: Access denied
[FAILED]
Problema acontece apenas no DC.

**Comment by hodrigohamalho** [comment]
isso o @AndDeluiz num tava vendo?

**Comment by kmacedovarela** [comment]
Resolvido no dc de produção, se ocorrer em outra máquina, reabrir issue.

**Comment by hodrigohamalho** [comment]
Tem que replicar pro ambiente de homologação...
