### ISSUE TITLE
SR: e-mail de anexação de arquivo está indo com tipo de movimentação vazio

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#700]
![captura_de_tela_031416_121947_pm](https://cloud.githubusercontent.com/assets/8461113/13749189/0c1e7bae-e9df-11e5-8635-362ef66ab395.jpg)

![captura_de_tela_031416_122005_pm](https://cloud.githubusercontent.com/assets/8461113/13749199/16f979de-e9df-11e5-973b-fdd7947ccedc.jpg)

**Comment by rafaela00castro** [comment]
Acrescentar ou verificar se está funcionando...

[ ] Descrição da movimentação
[ ] Descrição da solicitação filha
[ ] Notificação do atendente quando a sol. filha é fechada.

**Comment by Chrystinne** [comment]
![captura_de_tela_031317_051900_pm](https://cloud.githubusercontent.com/assets/4949149/23873542/26e0e0ca-0811-11e7-998a-b0b53326beec.jpg)
