### ISSUE TITLE
SR: Atribuição ao msm atendente ocorre mais de uma vez

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#703]
Atendendo um chamado no Siga-Sr que já havia sido atribuído a mim, percebi que houve uma nova atribuição quando gravei um andamento vazio (sem querer). Uma sugestão de melhoria seria verificar se já houve a atribuição antes de cadastrar uma nova.

**Comment by Chrystinne** [comment]
![captura_de_tela_031416_044409_pm](https://cloud.githubusercontent.com/assets/4949149/13757568/fabcf938-ea03-11e5-9bd6-5515bed66c9e.jpg)

**Comment by esredson** [comment]
Chrys, acho que o que ocorre é que o atendente é apagado no evento da anexação de arquivo (14/03 12:05). Abri a issue #705

**Comment by Chrystinne** [comment]
Acho que o problema estava relacionado a anexação mesmo (o que já foi resolvido na issue #765). Tentei reproduzir o erro e não ocorre mais.
