### ISSUE TITLE
SR: lista de substitutos está duplicando pessoas e incluindo fechadas

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#708]
Por exemplo, uma pessoa tem no banco mais de um id inicial (sendo que um desses ids não tem registro ativo), e está aparecendo mais de uma entrada com o nome dela na lista de atendentes substitutos. Ao montar a lista de substitutos, obter sempre a instância ativa da pessoa e desprezar a substituição em questão caso a pessoa não possua registro ativo.

**Comment by rafaela00castro** [comment]
Relacionado com a issue #1098

**Comment by Chrystinne** [comment]
O estranho é que isso ocorre para algumas lotações e outras não, como ilustrei na #1098
