### ISSUE TITLE
Diretório /var/run/jboss do script gerencia JBoss

### ISSUE THREAD

**Issue by hodrigohamalho** [projeto-siga/siga#71]
O Script cria os arquivos do processo do jboss dentro de /var/run/jboss. Porém esse diretório é removido quando a máquina é reiniciada. E se for subir com jboss o usuário jboss não tem permissão de escrita nesse diretório.

**Comment by AndDeluiz** [comment]
Este diretório não é utilizado para nenhuma funcionalidade nos scripts de inicialização nem no script domain.sh.
Vou retirar as referências no script de inicialização e testar.

**Comment by AndDeluiz** [comment]
Fiz os testes em homologação sem a referência a este diretório e tudo funciona perfeitamente com o script jboss-init.sh.
