### ISSUE TITLE
DOC: protocolo obtendo o usuário logado em vez do que gerou o protocolo

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#717]
"EM geral quando imprimimos um Protocolo criado por outra pessoa/setor, o cabeçalho "De:" utiliza o nome do usuário logado ao invés do usuário que realmente criou o protocolo."

TRF2-SR-2015/17603

**Comment by Chrystinne** [comment]
@esredson Eu já corrigi esse erro. Foi corrigido no commit bb31fa3, issue #515.
