### ISSUE TITLE
DOC: erro ao abrir anexos pela internet

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#719]
Não é possível abrir arquivos anexados quando o acesso ao sistema é feito pela internet, apresentando o erro abaixo:

Bad Request

Your browser sent a request that this server could not understand.
Reason: You're speaking plain HTTP to an SSL-enabled server port.
Instead use the HTTPS scheme to access this URL, please.
Hint: https://naked.jfrj.jus.br/
Apache/2.2.15 (Red Hat) Server at naked.jfrj.jus.br Port 443

TRF2-SR-2015/04587

**Comment by Markenson** [comment]
@raphaelpaiva Temos como acessar o canário via internet?

**Comment by raphaelpaiva** [comment]
@Markenson Eu acho que não.

@luiz-antonio pode confirmar?

**Comment by raphaelpaiva** [comment]
@Markenson Você quer dizer um usuário qualquer que esteja na regra de cair no canário, ou nós acessarmos para testes/manutenção?

**Comment by Markenson** [comment]
Nós mesmos para manutenção. Acho que o problema desta issue, na verdade, é com o HTTPS. Se tivermos como acessar com HTTPS internamente já atende.

**Comment by raphaelpaiva** [comment]
Entendi. Eu acho que é possível sim, mas eu não entendo da estrutura do acesso externo aqui. Vou consultar o Luiz (ele está de férias) na segunda pra ter certeza.

**Comment by Markenson** [comment]
OK. Sem problemas.

**Comment by Markenson** [comment]
Anexo aberto via proxy https para o canário, conforme imagem abaixo. Esta issue será encerrada visto que funciona sob https e não há acesso ao canário via internet.

![image](https://cloud.githubusercontent.com/assets/2985140/14087677/8da23454-f501-11e5-867c-c0d610cd9825.png)
