### ISSUE TITLE
Erro ao tentar ir para a página inicial do Siga

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#72]
Erro intermitente.

-Ilustração:
![erro_cabecalho_tag](https://cloud.githubusercontent.com/assets/4949149/5739904/7873084a-9be5-11e4-9b5a-6d1977e74fa0.png)

-Como reproduzir:
Navegando pelo menu principal do Siga: Siga->Página inicial

**Comment by kmacedovarela** [comment]
Relacionado à issue #39 .

**Comment by kmacedovarela** [comment]
Tentei reproduzir, mas não ocorreu.
Caso ocorra novamente, favor reabrir a issue
