### ISSUE TITLE
DOC: Erro na hierarquia de nomes dos modelos

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#721]
Reportado por Rafael (T212106) que embora tenha cadastrado um modelo com o nome "Ata: Ata de Registro de Preços" o sistema apresenta outros níveis de seleção.

![image](https://cloud.githubusercontent.com/assets/2985140/13789157/82fa751a-eac1-11e5-963c-42cb45af4556.png)

![image](https://cloud.githubusercontent.com/assets/2985140/13790354/cd1e4e6e-eac6-11e5-8a48-a34cbdd99ae0.png)

O problema foi percebido na hmg (release-5.1.0)

**Comment by rafaela00castro** [comment]
Com esse commit, a função ```selectChang``` deixa de ser chamada sempre. Passa a ficar somente com a chamada se um dos níveis dos campos de seleção sofrer uma alteração (código abaixo).

```
      return $select.off('change').on('change', function() {
        return selectChange($select);
      });
```

Acredito que o plugin não funcionava originalmente por completo porque estamos usando ele (select dinâmico) junto com postback.
