### ISSUE TITLE
Problema transacional na query de substituição

### ISSUE THREAD

**Issue by raphaelpaiva** [projeto-siga/siga#723]
Pessoal,

Desculpem pelo título, mas pela query, foi o que eu consegui extrair de informação da funcionalidade.

Isto tem acontecido o dia inteiro. Não sei se é um problema na query especificamente, mas parece que ela está sempre travada por alguma outra (que talvez sempre rode antes dela) na transação global.

Paraticamente só se vê este log no canário.

Em anexo a stacktrace completa, com o debug do filtro criado recentemente =D. Anexei a primeira que percebi do dia.

A query:
select dpsubstitu0_.ID_SUBSTITUICAO as ID_SUBST1_33_, dpsubstitu0_.DT_FIM_REG as DT_FIM_R2_33_, dpsubstitu0_.DT_FIM_SUBST as DT_FIM_S3_33_, dpsubstitu0_.DT_INI_REG as DT_INI_R4_33_, dpsubstitu0_.DT_INI_SUBST as DT_INI_S5_33_, dpsubstitu0_.ID_REG_INI as ID_REG_I6_33_, dpsubstitu0_.ID_LOTA_SUBSTITUTO as ID_LOTA_7_33_, dpsubstitu0_.ID_LOTA_TITULAR as ID_LOTA_8_33_, dpsubstitu0_.ID_SUBSTITUTO as ID_SUBST9_33_, dpsubstitu0_.ID_TITULAR as ID_TITU10_33_ from CORPORATIVO.DP_SUBSTITUICAO dpsubstitu0_ where (dpsubstitu0_.DT_INI_SUBST<sysdate or dpsubstitu0_.DT_INI_SUBST is null) and (dpsubstitu0_.DT_FIM_SUBST>sysdate or dpsubstitu0_.DT_FIM_SUBST is null) and ((dpsubstitu0_.ID_SUBSTITUTO is null) and (dpsubstitu0_.ID_LOTA_SUBSTITUTO in (select dplotacao1_.ID_LOTACAO from CORPORATIVO.DP_LOTACAO dplotacao1_ where dplotacao1_.ID_LOTACAO_INI=?)) or dpsubstitu0_.ID_SUBSTITUTO in (select dppessoa2_.ID_PESSOA from CORPORATIVO.DP_PESSOA dppessoa2_ where dppessoa2_.ID_PESSOA_INICIAL=?)) and (dpsubstitu0_.DT_FIM_REG is null); parameters: ; named parameters: {idSubstitutoIni=341050, idLotaSubstitutoIni=21458}; transformer: org.hibernate.transform.CacheableResultTransformer@110f2] for requestor [GlobalTransaction:<null>:324315:local]! Lock held by [GlobalTransaction:<null>:324314:local]

[lockHeldByNull.txt](https://github.com/projeto-siga/siga/files/174634/lockHeldByNull.txt)

**Comment by esredson** [comment]
O erro continua ocorrendo, e é possível que esteja relacionado a problemas de lentidão. Este arquivo é um trecho do que foi enviado por Luiz Antônio hoje: [unableToAcquireLock.txt](https://github.com/projeto-siga/siga/files/522773/unableToAcquireLock.txt)

**Comment by esredson** [comment]
#473

**Comment by Markenson** [comment]
Esse problema pode ser um bug do JBoss que só foi resolvido na versão 6.4.

Ref: https://bugzilla.redhat.com/show_bug.cgi?id=1270360

**Comment by Markenson** [comment]
A atualização da redhat que corrige esse bug é "Red Hat JBoss Enterprise Application Platform 6.4 Update 05"

Ref: 
https://access.redhat.com/jbossnetwork/restricted/softwareDetail.html?softwareId=40921&product=appplatform&version=6.4&downloadType=patches

**Comment by luiz-antonio** [comment]
Ótimo, mais um bom motivo pra migrarmos.
