### ISSUE TITLE
SR: falha no layout da página de exibição

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#726]
Em alguns casos, seções da barra lateral direita são exibidas abaixo da tabela de movimentações. Por exemplo, exibindo a solicitação TRF2-SR-2015/04541.33 desmarcando "Todo o Contexto", as listas de prioridade e os arquivos anexos aparecem deslocados

**Comment by Chrystinne** [comment]
Esse erro não ocorre mais (nem no Chrome e nem no IE).
