### ISSUE TITLE
SR: erro ao fechar automaticamente solicitação principal

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#727]
Quando solicitação principal está marcada para fechamento automático e a última filha é fechada, ocorre erro quando o sistema tenta fechar a principal, visto que não é permitido o fechamento com classificação "Atendimento de 1º Nível"

**Comment by Chrystinne** [comment]
O funcionamento do fechamento automático não está funcionando bem mesmo quando a ação da solicitação filha não é "Atendimento de 1º nível". Criei o chamado TRF2-SR-2017/00079 na base de testes pra verificar isso e quando fui fechar a solicitação filha, o sistema apresentou mensagem de erro ("Operação não permitida. Necessário escolher outra ação..."), mas mesmo assim fechou a filha e a principal.
