### ISSUE TITLE
Informações sobre Expedientes e Processos indisponíveis

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#73]
Fiz o deploy pelo JBoss Management (alterei o sigaex.war) e as informações sobre Expedientes e Processos que deveriam aparecer na página inicial do Siga ao fazer o login não estão disponíveis, conforme ilustrado na imagem: 
![captura_de_tela_011415_121923_pm](https://cloud.githubusercontent.com/assets/4949149/5740098/94159732-9be7-11e4-9c77-09968d9157f2.jpg)

**Comment by Chrystinne** [comment]
Só para constar, eu fiz um deploy anteriormente (há meia hora) e estava ok.

**Comment by kmacedovarela** [comment]
Poderia testar novamente? Se voltar a ocorrer, pode reabrir a issue! Obrigada!
