### ISSUE TITLE
GC: buscar por texto classifica como "Conhecimento_Sem_Classificacao" erradamente

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#730]
Buscando por @servico ao final aparecem "Conhecimento_Sem_Classificacao". Os primeiros da lista que verifiquei tinham classificação, apesar de estar nessa grupamento.

![captura_de_tela_031616_054041_pm](https://cloud.githubusercontent.com/assets/8461113/13828010/34975e50-eb9e-11e5-8655-a1d12d75131f.jpg)

![captura_de_tela_031616_054154_pm](https://cloud.githubusercontent.com/assets/8461113/13828052/605cb51c-eb9e-11e5-83ad-f29c3ced91b1.jpg)

**Comment by Chrystinne** [comment]
Esse problema não ocorre mais em produção. A classificação "Conhecimentos_Sem_Classificacao" não consta mais na lista de conhecimentos das funcionalidades Navegar e Buscar por texto.
