### ISSUE TITLE
DOC: ao mudar origem dá erro na exibição do ckeditor

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#736]
![giphy](https://cloud.githubusercontent.com/assets/8461113/13862085/b54fcb28-ec6f-11e5-93c8-6bde0a03c7c3.gif)

**Comment by rafaela00castro** [comment]
Teste na siga-hmg!

E valeu Markenson por apresentar essa ferramenta =)

**Comment by Markenson** [comment]
Valeu Rafa!
