### ISSUE TITLE
GC: selecionar grupo pela pop-up não está funcionando

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#740]
Erro reportado pela Nicole (SETMIC).
Para reproduzir erro: entrar na tela de edição do conhecimento. Alterar campo seleção de "Visualização" ou de "Edição" para a última opção "Lotação e grupo".
No input "Grupo" que aparecerá na tela, clicar no [...]

![sem titulo](https://cloud.githubusercontent.com/assets/8461113/13888428/2a9d8e78-ed20-11e5-8b1e-c97075e64226.png)

**Comment by Chrystinne** [comment]
O erro na seleção do grupo STI_SUPORTE_LOCAL já foi resolvido para os campos "Visualização" e "Edição", tanto no Chrome quanto no IE.
