### ISSUE TITLE
SR: criar trigger para evitar registros duplicados na tabela de movimentações

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#741]
A solicitação TRF2SR201622391.01 no dia 18/03 estava com as marcas Em Andamento (SESLAD) e Fechado (SESLAD). Isso ocorreu pq no dia 16/03 foram inseridas duas movimentações de reabertura com diferença de poucos milissegundos.

**Comment by esredson** [comment]
Ver #742, #573, #665

**Comment by raphaelpaiva** [comment]
Não seria melhor uma constraint unique?

**Comment by esredson** [comment]
Relacionado também a #897

**Comment by esredson** [comment]
Marcas duplicadas ocorrem também devido a movimentações de publicação no DJE duplicadas. Independente de estar resolvida a duplicação de movimentações, a rotina de marcas não deveria gerar marcas adicionais.
