### ISSUE TITLE
DOC: Repetição de movimentações

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#742]
Os problemas reportados no chamado JFRJ-SR-2016/31944 foram causados, em parte, por movimentações de definição de perfil repetidas. É necessário criar um mecanismo que impeça a repetição de movimentações mesmo durante instabilidades.

Este problema pode estar relacionado à issue #665.
Este problema foi percebido na versão 4.x do siga e provavelmente ocorre na versão 5.x.

**Comment by Markenson** [comment]
Essa issue pode estar relacionada à #741

**Comment by esredson** [comment]
Ver #741, #573, #665
