### ISSUE TITLE
DOC: Criação de documento atrelado a um dossiê

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#747]
Recebemos por e-mail (qui 17/03/2016 20:45) do Sr. Misael (CJF) a seguinte sugestão:

"(...) necessidade de criarmos na página de criação de documentos uma possibilidade de um “documento a ser juntado”. A ideia é permitir que seja criado o documento atrelado a um dossiê que será juntado oportunamente.
Esses documentos ficariam em uma lista após serem assinados para serem ordenados e juntados ao dossiê.
Esta providência destina-se a permitir que tarefas possam ser adiantadas mesmo antes de o dossiê chegar na  caixa.
"

**Comment by esredson** [comment]
TRF2-SR-2016/33887
