### ISSUE TITLE
WF: Erro ao criar um novo fluxo 

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#748]
O Sr. Misael (CJF) reportou o seguinte erro ao tentar abri um novo fluxo manualmente no ambiente sigat. Foi utilizado o login do Renato.

![image](https://cloud.githubusercontent.com/assets/2985140/13925335/b38c6e78-ef66-11e5-9bc1-378b3f554b3b.png)

**Comment by raphaelpaiva** [comment]
@Markenson Isso geralmente acontece quando um redeploy (ou reinício de uma instância) acabou de ser feito e acontece o primeiro acesso à uma página com uma "sessão" pré-existente.

**Comment by Markenson** [comment]
@raphaelpaiva obrigado. Agora está funcionando OK.
