### ISSUE TITLE
DOC: Transferência permitida com anexos pendentes de assinatura

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#749]
Foi reportado no chamado JFES-SR-2016/02073.02 um problema ocorrido com o documento JFES-PES-2013/00286 em que foi possível transferir um documento mesmo com anexos pendentes de assinatura, conforme imagem abaixo.

![image](https://cloud.githubusercontent.com/assets/2985140/13926637/091729e6-ef6c-11e5-9b46-8c6f03346f02.png)

**Comment by esredson** [comment]
Aparentemente, ocorria devido a terem as transferências sido feitas antes da obrigatoriedade da assinatura. Se não for este o caso, reabriremos a issue.
