### ISSUE TITLE
Erro encoding 

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#75]
-Ilustração:
![erro-encoding](https://cloud.githubusercontent.com/assets/4949149/5744479/4c3cc0b8-9c08-11e4-83e7-436321659cb4.png)

-Como reproduzir:
Na página de criação de documentos (http://siga-dev/sigaex/expediente/doc/editar.action), preencher o campo descrição (com um texto qualquer) e clicar em Ok;

**Comment by kmacedovarela** [comment]
Porque a issue foi fechada?

**Comment by Chrystinne** [comment]
@kmacedovarela Porque ficou duplicada com relação à #76, que permanece aberta.

**Comment by kmacedovarela** [comment]
:ok_hand:
