### ISSUE TITLE
[Siga-Doc] Erro encoding 

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#76]
-Ilustração:
![erro-encoding](https://cloud.githubusercontent.com/assets/4949149/5744479/4c3cc0b8-9c08-11e4-83e7-436321659cb4.png)

-Como reproduzir:
Na página de criação de documentos (http://siga-dev/sigaex/expediente/doc/editar.action), preencher o campo descrição (com um texto qualquer) e clicar em Ok;

**Comment by kmacedovarela** [comment]
O mesmo erro está ocorrendo na versailles veja imagem a seguir.
URL: http://versailles:8280/sigaex/expediente/doc/exibirAntigo.action?exibirCompleto=true&sigla=TMP-7702

![bug](https://cloud.githubusercontent.com/assets/253186/5746267/9a802898-9c15-11e4-89fb-1327c800aca8.PNG)

**Comment by Chrystinne** [comment]
@kmacedovarela Esse erro eu não tinha testado na versailles. Testei só o da #78.

**Comment by kmacedovarela** [comment]
Como não estava ocorrendo no ambiente de homologação, e está ocorrendo na versailles, a principio vou pausar esta investigação.

**Comment by kmacedovarela** [comment]
@Chrystinne caso o problema seja solucionado na versailles, por gentileza me avise.

**Comment by kmacedovarela** [comment]
Favor testar, se estiver ocorrendo, reabrir

**Comment by kmacedovarela** [comment]
O problema foi resolvido no ambiente de homologação apenas;
