### ISSUE TITLE
DOC: Garantir CP_SUBSTITUICAO.ID_SUBSTITUICAO único

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#762]
Foi reportado por Martellet um problema ao excluir substituições (vide TRF2-SR-2016/23133.01).

O problema ocorre porque existem duplicações de id para alguns registros de substituição anteriores a 2012.

Esta issue foi aberta para que seja garantida a unidade do campo CP_SUBSTITUICAO.ID_SUBSTITUICAO no sistema.

**Comment by esredson** [comment]
update corporativo.dp_substituicao set id_substituicao = (corporativo.dp_substituicao_seq.nextval)
where id_reg_ini is null and id_substituicao in (
        select id_substituicao from corporativo.dp_substituicao subst where exists (
                select 1 from corporativo.dp_substituicao
                where id_substituicao = subst.id_substituicao 
                and id_lota_substituto <> subst.id_lota_substituto
        ) 
);
update corporativo.dp_substituicao set id_reg_ini = id_substituicao where id_reg_ini is null;
update corporativo.dp_substituicao set dt_ini_reg = dt_ini_subst where dt_ini_reg is null;
