### ISSUE TITLE
SR: contador de "Em Elaboração" não confere com a tela de pesquisa

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#768]
Tela de solicitações da SEDGET

![captura_de_tela_040716_023111_pm](https://cloud.githubusercontent.com/assets/8461113/14360573/72a0e870-fccd-11e5-9dc1-972a3719a0b8.jpg)

![captura_de_tela_040716_023131_pm](https://cloud.githubusercontent.com/assets/8461113/14360584/7eba4dfe-fccd-11e5-8a2f-5ef01e05c91c.jpg)

Os outros contadores estão OK

**Comment by esredson** [comment]
A solicitação com problemas foi ajustada. Porém, outra issue foi aberta.
