### ISSUE TITLE
Erro no link "Exibir informações completas" 

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#77]
-Ilustração:
![exibir-informacoes-completas](https://cloud.githubusercontent.com/assets/4949149/5744599/4d8a0e0c-9c09-11e4-9595-a0a2ca2db233.png)

-Como reproduzir:
Na página de criação de documentos (http://siga-dev/sigaex/expediente/doc/editar.action), preencher o campo descrição (com um texto qualquer) e clicar em Ok; 
Clicar no link "Exibir informações completas";

**Comment by kmacedovarela** [comment]
Reparei que o arquivo "exibirAntigo" não consta no branch migracao-jboss6. 
Realizarei um novo merge com o branch develop hoje para que possamos ficar com a mesma versão entre os branches.

**Comment by kmacedovarela** [comment]
O erro foi resolvido porém será possível testar apenas após o fechamento da issue #79
