### ISSUE TITLE
DOC: problema na assinatura que pode causar bloqueio do token

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#772]
Caso informado pelo Gustavo sobre o bloqueio do token da usuária ao tentar assinar o documento JFRJ-SEC-2015/00181.
![captura_sem_titulo_040716_050313_pm](https://cloud.githubusercontent.com/assets/8461113/14365171/affe111a-fce2-11e5-9e78-6a4271ba567c.jpg)

![captura_sem_titulo_040716_050330_pm](https://cloud.githubusercontent.com/assets/8461113/14365182/ba8db5d6-fce2-11e5-8085-50ab60816dab.jpg)

**Comment by rafaela00castro** [comment]
Possíveis causas desse erro, conforme conversado com @markenson:
- Lentidão do servidor 
- Problema no navegador

Verificar se as rotinas de assinatura em lote continuam tentando assinar caso a autenticação no primeiro documento já falhe, conforme mencionado pelo George no e-mail do dia 07/04/16

**Comment by esredson** [comment]
Aparentemente, ocorria apenas na assinatura Java
