### ISSUE TITLE
GI: Permitir a visualização dos gestores de um grupo de distribuição

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#775]
Necessidade reportada por Sheyla (via e-mail, sexta-feira, 8 de abril de 2016 19:22).

Apenas pessoas com permissão para realizar configurações avançadas conseguem ver os gestores de um grupo de distribuição. Mesmo as pessoas com permissões comuns nos grupos de distribuição devem poder enxergar os gestores.

**Comment by esredson** [comment]
TRF2-SR-2016/33883
