### ISSUE TITLE
DOC: Subscritores devem assinar em ordem

### ISSUE THREAD

**Issue by crivano** [projeto-siga/siga#779]
O documento só deve estar disponível para assinatura por um subscritor quando o anterior já tiver assinado. Isso foi solicitado por Martellet conforme trecho de email a seguir: "O ganho esta exatamente nisso .. hoje existem diversos documentos que tenho que coassinar com colegas, unidade subordinadas à SETI. Só que estes documentos são anexados a um processo e o pessoal envia e_mail simultaneamente para todos assinarem ... só que cada um tem um papel especifico no documento, questões operacionais e técnicas que devem seguir uma ordem de evolução até que eu possa concordar ou dar anuência ou até ciência ... não tem sentido eu assinar antecipadamente ... poderia levar a um erro ...
Desta forma este procedimento faz com que muitas vezes eu entre no documento e não assino tendo em vista que aqueles que tem assiná-los antes não o fizeram ..."

**Comment by esredson** [comment]
Ver #1040
