### ISSUE TITLE
Erro ao abrir anexo na visualização do dossiê

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#78]
-Ilustração do erro:
![anexo-dossie](https://cloud.githubusercontent.com/assets/4949149/5744963/5139e4a2-9c0c-11e4-926a-da6417914096.png)

-Ilustração do link com erro:
![caminho-erro-link-anexo-dossie](https://cloud.githubusercontent.com/assets/4949149/5744964/55d07918-9c0c-11e4-9677-c32d92b5208c.png)

-Como reproduzir:
Na página de criação de documentos (http://siga-dev/sigaex/expediente/doc/editar.action), preencher o campo descrição (com um texto qualquer) e clicar em Ok; 
Clicar em "Anexar arquivo". Em seguida, clicar em "Escolher arquivo" e selecionar um arquivo pdf; Clicar em Ok e, em seguida, clicar em "Voltar";
Clicar em "Visualizar dossiê" e, do lado direito, clicar no link com o nome do arquivo pdf inserido no passo anterior, conforme ilustrado na imagem acima (Ilustração do link com erro);

**Comment by kmacedovarela** [comment]
Testarei novamente após o merge

**Comment by kmacedovarela** [comment]
O erro foi resolvido porém será possível testar apenas após o fechamento da issue #79

**Comment by kmacedovarela** [comment]
Vou testar

**Comment by kmacedovarela** [comment]
O erro persiste, vou verificar.

**Comment by kmacedovarela** [comment]
@Chrystinne o erro ocorre pois a aplicação redireciona para a url incorreta, referenciando diretamente o servidor.
Você pode reproduzir o mesmo problema na versailles, se acessar pelo apache. Repita o procedimento de teste a partir da url:
https://versailles/siga/

Para solucionar o problema, é necessário alterar a forma como a aplicação abre esta url, usando urls relativas. 

Seria possível que alguém da equipe de desenvolvimento resolvesse este erro para que possamos focar nos erros de JBoss? Qualquer dúvida estamos à disposição.

**Comment by Chrystinne** [comment]
@kmacedovarela Ok, vamos resolver.

**Comment by Chrystinne** [comment]
Resolvido!
