### ISSUE TITLE
GC: recurso 'Tomar Ciência' deveria dar permissão de acesso

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#782]
Quando uma lotação recebe uma notificação para tomar ciência de um conhecimento, ela não consegue acessá-lo se ele estiver com nível de acesso restrito à lotação que o criou,

**Comment by Chrystinne** [comment]
@esredson Esse erro também não consegui reproduzir. No ambiente local, criei o conhecimento TRF2-GC-2016/00009 com restrição de visualização e edição para lotação, no caso a SEMGET. Antes de notificar um usuário de outra lotação, tentei acessar o conhecimento estando logada como o Markenson (SEARSE), e o sistema impediu o acesso. Depois disso, notifiquei o Markenson e, ao tentar acessar novamente com o login dele, conseguir visualizar o conhecimento.

![captura_de_tela_041516_124326_pm](https://cloud.githubusercontent.com/assets/4949149/14566902/d8ffc196-0307-11e6-81cd-0d5cdd125e50.jpg)

**Comment by Chrystinne** [comment]
![captura_de_tela_041516_124719_pm](https://cloud.githubusercontent.com/assets/4949149/14567017/5a7167fc-0308-11e6-96d5-b7de8ab797e3.jpg)

**Comment by Chrystinne** [comment]
@esredson Agora consegui encontrar um erro. O usuário de outra lotação fica com permissão para acessar, mas depois que acessa o conhecimento, e é gerada a movimentação "ciente", ele não consegue realizar nenhuma outra movimentação no conhecimento, nem mesmo clicar em "Exibir movimentações completas". Tb não consegue acessar o conhecimento novamente. Nesse caso, ele deveria ficar com acesso permanente ao conhecimento?

**Comment by esredson** [comment]
@Chrystinne, penso que deveria, sim, porque a movimentação de dar ciência a um setor X é um ato explícito de quem já possui permissão sobre o conhecimento.

**Comment by Chrystinne** [comment]
Feito. Antes não era possível exibir movimentações completas após tomar ciência.

![captura_de_tela_041516_052841_pm](https://cloud.githubusercontent.com/assets/4949149/14574046/7fc83ffe-032f-11e6-90c9-759fcb5b5ce3.jpg)
