### ISSUE TITLE
GC: caixa de edição de classificação não fica habilitada

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#785]
A textarea não está saindo do modo readonly quando o titular tem permissão de editar classificação. O problema está ocorrendo quando o conhecimento não tem classificação.

**Comment by rafaela00castro** [comment]
Reabrindo issue porque alterei essa parte do código para resolver erro da issue #810. No entanto, provavelmente reinseri esse erro, apesar de manter aparentemente a mesma estrutura da solução acima ao verificar a permissão para "editarConhecimento".

**Comment by Chrystinne** [comment]
Testando em desenvolvimento e em produção, verifiquei esse problema não ocorre mais.

![captura_de_tela_092316_032826_pm](https://cloud.githubusercontent.com/assets/4949149/18797052/60854636-81a2-11e6-86ab-b64dda4d1226.jpg)
