### ISSUE TITLE
GC: não está sendo possível inserir classificações # em conhecimentos-âncora

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#786]
Aparentemente, ele deixa de ser âncora.

**Comment by esredson** [comment]
Lembrando, são os conhecimentos com classificação iniciando em ^

**Comment by Chrystinne** [comment]
@esredson pode mostrar um exemplo de conhecimento onde está ocorrendo esse erro? Testei localmente e não conseguir reproduzir. Testei no conhecimento JFRJ-GC-2014/00018 (http://localhost:8080/sigagc/app/exibir/JFRJGC201400018)

**Comment by Chrystinne** [comment]
![captura_de_tela_041416_065448_pm](https://cloud.githubusercontent.com/assets/4949149/14545060/8eee315e-0272-11e6-87ea-f97b59122c60.jpg)

**Comment by Chrystinne** [comment]
Na produção tb não deu erro. Ou será que estou testando errado?

![captura_de_tela_041416_070413_pm](https://cloud.githubusercontent.com/assets/4949149/14545243/d42693aa-0273-11e6-8cfb-26a5e83a1a55.jpg)

**Comment by esredson** [comment]
@chrys, conforme conversamos, o problema foi que tentei inserir a classificação # no próprio campo classificação e não no conteúdo.
