### ISSUE TITLE
GC: Cancelar Alterações está levando para a edição de novo conhecimento

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#787]
Quando se estivesse editando um conhecimento e se clicasse em Cancelar Alterações, deveria haver direcionamento para a tela de exibição do próprio conhecimento. O que está ocorrendo é o recarregamento da tela de edição com os dados vazios.

**Comment by Chrystinne** [comment]
@esredson Abri uma issue pra tratar esse erro que inclusive já foi fechada, #757. Corrigi no branch develop, commit 037c55ffeb9. Só que ele não entrou na versão de produção ainda. Falei com @Markenson para ver quando poderia entrar. Provavelmente na próxima versão ou podemos incluir em algum hot fix, caso algum precise ser feito.

**Comment by esredson** [comment]
Resolvido pela @Chrystinne
