### ISSUE TITLE
DOC: erro ao assinar portaria e anexo simultaneamente em lote

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#789]
Ver e-mail Renato de 14/04/16 12:32

**Comment by Markenson** [comment]
Teste de assinatura de apenas 1 portaria com 1 anexo
![recording](https://cloud.githubusercontent.com/assets/2985140/14617036/0c96b6ae-0583-11e6-94fc-bc98496f94b5.gif)

**Comment by Markenson** [comment]
Teste de assinatura de várias portarias com vários anexos.
![recording](https://cloud.githubusercontent.com/assets/2985140/14617076/3fa7eda6-0583-11e6-9f6f-ca5ff1084814.gif)

**Comment by Markenson** [comment]
Como não foi possível reproduzir o erro (vide testes acima), esta issue será fechada. Provavelmente o erro ocorreu devido a um problema momentâneo. Caso o problema volte a ocorrer, reabriremos esta issue.
