### ISSUE TITLE
Doc: Erro ao movimentar vias

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#791]
O Siga se perde quando tenta movimentar vias em documentos com mais de 20 vias, mais especificamente na 21ª via em diante, que são os casos de vias com a sigla Z. 
Tivemos um caso, reportado via Siga-SR, em que o sistema não permitia arquivar a via 24, apesar de não haverem impedimentos para isto. No debug, vimos que o Siga estava tentando fazer a movimentação na via 21, ao invés da 24.

**Comment by esredson** [comment]
@Chrystinne, vi que o problema já tinha sido abordado na #470. Acho que é questão de fechar mesmo. Inclusive, a query abaixo mostra que só existem dez documentos nessa situação, sendo que dois são de teste. 
`select * from siga.ex_documento where id_doc in (select distinct(id_doc) from siga.ex_mobil where id_tipo_mobil = 2 and num_sequencia > 21`
