### ISSUE TITLE
Adicionar informação de localidade no Corporativo

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#795]
Recebemos um chamado hoje requisitando a criação de um grupo cujo acesso deveria ser concedido apenas aos diretores de secretaria do interior. Como o Corporativo não tem informação de localidade associada às lotações, poderíamos acrescentar essa informação a partir da base de dados do RH.

**Comment by esredson** [comment]
Outro caso é quando ocorre mudança ou inclusão de localidade. Temos que solicitar ao pessoal que gerencia os servidores a atualização das properties em todas as máquinas.
