### ISSUE TITLE
GC: erro na classificação

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#799]
O conhecimento temporário tinha como classificação a mensagem "Esse conhecimento ainda não possui uma classificação". 
- [ ] **Fazer tratamento para permitir somente classificações dos tipos existentes (GC_TIPO_TAG).**
  Por existir esta classificação fora do padrão, qualquer operação no conhecimento dava erro. A exceção era lançada no método `atualizarTags`, pois ele não reconhece classificações fora do padrão. 
- [ ]  **Fazer com que esse método dê mensagens de exceção mais claras.**

![captura_de_tela_042016_052025_pm](https://cloud.githubusercontent.com/assets/8461113/14689097/2c2b0dfe-071c-11e6-8a16-cf1d7f3b77a3.jpg)

**Comment by rafaela00castro** [comment]
@Chrystinne, não como o conhecimento temporário que é visualizado nessa issue, conseguiu passar pelo erro da issue #810, que mostra erro ao tentar gravar solicitação com a mensagem "Esse conhecimento ainda..." na classificação.

**Comment by Chrystinne** [comment]
Fiz alguns testes e buscas nos conhecimentos (base local e produção) e, pelos resultados que obtive, este erro não está mais ocorrendo. Quem por ventura se deparar com ele novamente, favor reabrir esta issue.
