### ISSUE TITLE
GERAL: Facilitar a identificação do número da versão do sistema

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#800]
Atualmente o número da versão do sistema só aparece na pagina inicial. Facilitaria o atendimento ao usuário se o número da versão estivesse disponível em qualquer página.

**Comment by raphaelpaiva** [comment]
No SIGA da UFRJ nós colocávamos revisão (era svn, então era menos feio, mas meio desnecessário) e # do build do jenkins no footer, apenas para os administradores do sistema.

No caso da jfrj, acho que pode ficar no header do lado do título, o que acham?
