### ISSUE TITLE
IP Fixo

### ISSUE THREAD

**Issue by kmacedovarela** [projeto-siga/siga#81]
Remover a configuração de ip fixo no script jboss-custom.sh

**Comment by hodrigohamalho** [comment]
Eu quem criei essa configuração. Antes as máquinas vinham com os IPs todos configurados na interface eth0, de um tempo pra cá as interfaces começaram a vir com uns nomes meio randômicos dai quebrou essa lógica.

**Comment by AndDeluiz** [comment]
No RHEL/CentOS 7 a nomenclatura das interfaces de rede mudou. Vamos trabalhar com uma variável para indicação do IP que o JBoss deve fazer o bind.
