### ISSUE TITLE
SR: LazyInitializationException ao fechar chamado

### ISSUE THREAD

**Issue by raphaelpaiva** [projeto-siga/siga#814]
Aconteceu ao seguir os passos:
1. Clicar no link do email.
2. Clicar em fechar chamado
3. Clicar em Gravar.

Stacktrace em anexo.
[ExceptionSRFecharChamado.txt](https://github.com/projeto-siga/siga/files/245665/ExceptionSRFecharChamado.txt)

**Comment by raphaelpaiva** [comment]
* Deslogar e logar (testado no IE e Chrome) não funcionou.
* Entrar no chamado pela caixa de busca ao invés do link do email também não ajudou.

Uma coisa que me chamou a atenção: o chamado não é listado na minha "inbox".

**Comment by raphaelpaiva** [comment]
Consegui fechar na versão 4.x (axor)

**Comment by raphaelpaiva** [comment]
Não consigo fechar nenhum chamado na versão 5.x

**Comment by rafaela00castro** [comment]
@raphaelpaiva acredito que esse problema esteja ocorrendo somente para as solicitações do item Jboss. Poderia confirmar isso, quando estiver para fechar uma solicitação, tentando fechar pela versão 5.x.
