### ISSUE TITLE
GC: Erro ao inserir imagem no texto do conhecimento.

### ISSUE THREAD

**Issue by adrigrassi** [projeto-siga/siga#820]
Ao tentar inserir uma imagem no texto:
![erroinseririmagemcg1](https://cloud.githubusercontent.com/assets/5265327/15048897/e60813f6-12c1-11e6-8877-41a75fa3fc04.png)

Mostra o seguinte erro:
![erroinseririmagemcg](https://cloud.githubusercontent.com/assets/5265327/15048921/096e31b8-12c2-11e6-8c83-fb73a28bfd46.png)

**Comment by Chrystinne** [comment]
Consegui reproduzir o erro na produção (vraptor). Mas está mais complicado achar o erro porque fui debugar localmente e o erro não ocorre.

**Comment by rafaela00castro** [comment]
**Em produção**
![captura_de_tela_070616_023833_pm](https://cloud.githubusercontent.com/assets/8461113/16628246/513e63dc-4387-11e6-8445-7d9969a71522.jpg)

**na homolo**
![captura_de_tela_070616_024642_pm](https://cloud.githubusercontent.com/assets/8461113/16628523/74fe18ac-4388-11e6-8cd8-49b43d720f85.jpg)

**Comment by rafaela00castro** [comment]
Acredito que possa ser um problema da url relativa (/sigagc/app/baixar?id=3204), pode ser alguma configuração no apache de produção. 
Poderia tentar trocar tanto no `AppController.java - gravarArquivo` quanto no `editar.jsp` para pegar a url com `${linkTo[AppController].baixar}?id=3204`

**Comment by Chrystinne** [comment]
@rafaela00castro Vou tentar dessa forma.

**Comment by rafaela00castro** [comment]
Ao aplicar a sugestão de trocar para `${linkTo[AppController].baixar}?id=xxxx` percebi que essa alteração não irá resolver o problema em produção, visto que ele também retorna uma url relativa. 
Desculpa, @Chrystinne...

**Comment by rafaela00castro** [comment]
Será que agora agora vai?....rsrs.
Testei na serie1cabrio e também funcionou, logo funcionou em todos os ambientes menos no canario-domain.
Comparando os response headers, percebi a diferença: no canario-domain, o apache deve estar configurado para passar `Content-Type:text/plain`, se ele não for definido. Nos ambientes em que essa funcionalidade funcionada o content-type não vem no response header.

Então no gravarArquivo, temos que acrescentar 
`			HttpResult response = this.result.use(Results.http());`
	`response.addHeader("Content-Type", "text/html");`

para o navegador entender a resposta como html e não um texto.
Para confirmar a teoria, pesquisei por problema de [content-type e ckeditor](http://stackoverflow.com/questions/22781291/ckeditor-4-3-4-response-script-is-not-evaluated)
