### ISSUE TITLE
SR: verificar forma de impedir escalonamento para locais absurdos

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#825]
Analisar se valeria a pena impedir o escalonamento caso o setor não fosse atendente em nenhuma designação. Já ocorreram muitos escalonamentos para setores assim? Talvez, em vez de impedir, apenas mostrar um aviso antes de escalonar.

**Comment by Chrystinne** [comment]
Recebemos chamado (TRF2-SR-2016/33101.01) de membro de lotação não atendente de chamado (SAJ) informando que está recebendo e-mail sobre solicitações do Siga-SR. Isto aconteceu porque um chamado (TRF2-SR-2016/32540.02) foi escalonado para SAJ.
