### ISSUE TITLE
Habilitar SELINUX e configura-lo no ambiente de HMG

### ISSUE THREAD

**Issue by hodrigohamalho** [projeto-siga/siga#83]

**Comment by AndDeluiz** [comment]
Configuradas as regras para o Apache. Mapeadas portas TCP/UDP e criada política para acesso/uso dos arquivos de log pelo mod_cluster.
Configurado o SELinux para mode=enforcing.
Efetuar testes com Apache e comunicar caso exista algum erro.

**Comment by AndDeluiz** [comment]
Habilitei o SELinux em todas as máquinas do ambiente HMG após verificar que não haviam mensagens de bloqueio a recursos utilizados pelas aplicações.
Favor testar e reabrir o issue caso hajam problemas.
