### ISSUE TITLE
DOC: preenchimento automático incompleto

### ISSUE THREAD

**Issue by adrigrassi** [projeto-siga/siga#842]
Através do chamado TRF2-SR-2016/25631, usuária reportou que na Portaria(SG) não está vindo o texto do editor ao escolher um preenchimento automático.

**Comment by Markenson** [comment]
O problema ocorre porque o modelo portaria.jsp não carrega corretamente o preenchimento automático. Como o objetivo é migrar os documentos JSP para Freemarker, já alteramos o modelo Portaria (SG) para usar o freemarker, resolvendo o problema.
