### ISSUE TITLE
[Siga-GC] Erro encoding

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#85]
-Ilustração:
![captura_de_tela_011615_115639_am](https://cloud.githubusercontent.com/assets/4949149/5777099/bd18211e-9d76-11e4-857c-5f3014f5c87e.jpg)

-Como reproduzir:
Criar um novo conhecimento (https://siga-dev/sigagc/app/editar) e clicar em "Gravar";

**Comment by kmacedovarela** [comment]
Associada a issue #61

**Comment by kmacedovarela** [comment]
Adicionado novo módulo ao JBoss com as dependencias do projeto.
d5a01a2cac1bf95b2a51e3424fa2df41e6d220f2

**Comment by kmacedovarela** [comment]
Encontrei um erro semelhante no sigagc.

**Comment by kmacedovarela** [comment]
#97
