### ISSUE TITLE
DOC: Erro ao desentranhar anexo (PDF)

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#852]
Erro reportado no chamado JFRJ-SR-2016/36168.01

Ao desentranhar um anexo o sistema exibe a mensagem "não foi possível obter a numeração única automática das páginas da movimentação a ser cancelada". Esse problema não ocorre na versão 4.x.

**Comment by esredson** [comment]
Nova ocorrência: TRF2-SR-2016/26164.01

**Comment by Markenson** [comment]
Nova ocorrência JFRJ-SR-2016/36334.01

**Comment by adrigrassi** [comment]
Resolvida pelo commit 7d39a73c4d48497028c9b26540ebdf0cffbcf3f6
