### ISSUE TITLE
[Siga-GC] Erro ao criar novo conhecimento

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#86]
Ilustração:
![captura_de_tela_011615_115639_am](https://cloud.githubusercontent.com/assets/4949149/5777339/db951dc0-9d78-11e4-965c-3be278b84862.jpg)

-Como reproduzir:
Na página de criação de conhecimento (https://siga-dev/sigagc/app/editar), preencher os campos obrigatórios "Título" e "Texto" com uma informação qualquer e clicar em "Gravar".

**Comment by kmacedovarela** [comment]
Erro ainda sob análise.

**Comment by kmacedovarela** [comment]
Se ainda estiver ocorrendo no módulo do SigaGC , favor reportar.
