### ISSUE TITLE
DOC: GSA: drill down não aparecendo à esquerda

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#860]
No Siga-Teste, ao ser realizada a pesquisa, o usuário pode especificar a sua busca pelos filtros dispostos no lado esquerdo da tela. Entretanto na base de produção essas opções não estão disponíveis, o que dificulta a recuperação do documento.
Necessidade: Inserir os filtros na base de produção.

Rosiane, NUGED

**Comment by esredson** [comment]
![image](https://cloud.githubusercontent.com/assets/5264319/15338159/ff3973be-1c54-11e6-8696-f1ddd15c3c59.png)

**Comment by esredson** [comment]
![image](https://cloud.githubusercontent.com/assets/5264319/15338309/c7de4970-1c55-11e6-8869-1720dabad119.png)

**Comment by crivano** [comment]
Samuel fez a correção.
