### ISSUE TITLE
DOC: Erro ao tentar criar Boletim Interno TRF

### ISSUE THREAD

**Issue by adrigrassi** [projeto-siga/siga#865]
Ao escolher Boletim Interno TRF ou CJF ou SJES ocorre o seguinte erro:
![image](https://cloud.githubusercontent.com/assets/5265327/15364900/93b1a8be-1cf4-11e6-9a33-34c9b34e6792.png)

**Comment by adrigrassi** [comment]
Este erro está ocorrendo em Homologação.

**Comment by esredson** [comment]
Resolvido pela @adrigrassi no commit 4d856d46296e202508c0b8015490d225481dde5f e na conversão do Boletim Interno de JSP para Freemarker
