### ISSUE TITLE
[Siga-Sr] Pesquisa de solicitações

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#87]
-Ilustração:
![captura_de_tela_011615_031252_pm](https://cloud.githubusercontent.com/assets/4949149/5780519/5123b6dc-9d92-11e4-8e3e-7bd205750e71.jpg)

-Como reproduzir:
Acessar https://siga-dev/sigasr/solicitacao/buscar

**Comment by Chrystinne** [comment]
@hodrigohamalho Os campos mais à esquerda dos botões [...] não estão tendo o comportamento esperado. Ao preencher os campos com informações referentes à lotação ou pessoa, após evento onblur (teclar "tab" ou clicar fora do campo), estas devem aparecer por extenso do lado direito do botão [...]

![captura_de_tela_012115_041337_pm](https://cloud.githubusercontent.com/assets/4949149/5841996/76311e66-a188-11e4-9eb9-b20cda51ffb1.jpg)

**Comment by hodrigohamalho** [comment]
Corrigido.
