### ISSUE TITLE
DOC: fazer levantamento de modelos que ainda estão em jsp

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#873]
Isso gera dificuldade na manutenção, pois há duas tecnologias diferentes (JSP e Freemarker). Fazer uma lista desses modelos e abrir issues para migrá-los.

**Comment by esredson** [comment]
Atualmente, 131 dos 353 modelos em produção estão em JSP

**Comment by rafaela00castro** [comment]
Segue planilha que usamos para controle da migração dos modelos em JSP para Freemarker. https://docs.google.com/spreadsheets/d/1823TFMEzF-QjZwmSQ0cGjJQnr9NuDJ1wHwZVwE9xtfo/edit?usp=sharing
(está compartilhada com a equipe - logar na conta do google para visualização).

**Comment by esredson** [comment]
Fechando a issue. Seria inviável iniciarmos agora um esforço para migrar em massa os modelos. Achamos melhor migrar à medida que problemas forem aparecendo.
