### ISSUE TITLE
DOC: Incluir botão de citação no editor de textos

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#875]
Solicitado por Misael (CJF, email sex 20/05/2016 18:06) a liberação do botão de citação disponível na página de demonstração do Ckeditor, conforme imagem abaixo

![img](https://cloud.githubusercontent.com/assets/2985140/15443420/85d16182-1ebe-11e6-840b-d8e89d9ad187.png)

**Comment by esredson** [comment]
TRF2-SR-2016/33854
