### ISSUE TITLE
DOC: impedir que texto ultrapasse a margem na visualização de PDF

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#876]
Foi reportado no chamado TRF2-SR-2016/26508.01 que a tabela foi cortada na visualização de PDF embora esteja sendo exibida corretamente na visualização em PDF.

![img](https://cloud.githubusercontent.com/assets/2985140/15475582/32cbc854-20e1-11e6-9dec-2fd282f3d44b.png)

![img](https://cloud.githubusercontent.com/assets/2985140/15475654/84b81d0c-20e1-11e6-8697-2d3d09d7032e.png)

**Comment by EnzoGamaDS** [comment]
Não entendi muito bem o problema, mas como a issue ta aberta...
 Usa  :
        word-wrap: break-word;
        word-break: break-all;
        
       vai quebrar se ultrapassar a linha.

**Comment by EnzoGamaDS** [comment]
Em text-area costumo usar para quebrar os textos e impedir que ultrapasse o limite da caixa :

word-break: keep-all
