### ISSUE TITLE
[Siga-Sr] Inclusão de gestor

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#88]
-Ilustração:
![captura_de_tela_011615_033222_pm](https://cloud.githubusercontent.com/assets/4949149/5780863/116f7118-9d95-11e4-8456-d5bc6130b80f.jpg)

-Como reproduzir:
Na página de cadastro de item de configuração (http://versailles:8080/sigasr/item/editar), clicar no botão "Incluir" abaixo do rótulo "Gestores"; Problemas: O botão [...] não funciona e é possível incluir uma lotação inexistente como gestor;

O mesmo problema ocorre ao clicar no botão "Incluir" do "Fator de multiplicação por Solicitante". O botão [...] do Solicitante não funciona.

**Comment by Chrystinne** [comment]
@hodrigohamalho Ainda está com problemas. Além de abrir a pop-up ao clicar no botão [...]. Ao preencher a informação referente à Lotação ou Pessoa, após o evento onblur (teclar "tab" ou clicar fora do campo), o nome da lotação ou pessoa deve aparecer por extenso do lado direito do botão [...]

**Comment by hodrigohamalho** [comment]
Corrigido.
