### ISSUE TITLE
DOC: alteração e exclusão de configuração está exigindo reiniciar o servidor

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#886]
Alteração e exclusão no Ferramentas -> Cadastro de configurações não está se aplicando sem reiniciar o servidor. Uma lotação estava configurada para não receber documentos. Ao alterar ou excluir a configuração, o método podePorConfiguracao() continuou enxergando-a, até que eu reiniciei o servidor.

**Comment by esredson** [comment]
Reportado mais uma vez, pelo @Markenson, que a alteração de perfil não se aplicou imediatamente ao Siga-Gc. É possível que seja o mesmo problema

**Comment by adrigrassi** [comment]
@baylon é essa a issue!

**Comment by baylon** [comment]
Estamos com o mesmo problema no SIGATP... Modificações nas permissões só ocorrem depois de reiniciar o servidor.

**Comment by raphaelpaiva** [comment]
São Properties java? Se forem é por causa do sistema de cache de
propriedades. Eu não sei por que ele existe, mas acho que hoje em dia não
faz mais sentido. Será que não vale modificar?

**Comment by esredson** [comment]
Raphael, nesse caso, não são properties, não. Essas são configurações relativas às regras de negócio, e ficam no banco mesmo. Elas ficam num cache manual que mantemos na memória. Com certeza há soluções melhores, mas, por causa da complexidade envolvida (bem como do impacto), não pudemos nos dedicar a isso ainda.

**Comment by esredson** [comment]
Ocorreu novamente o problema agora, ao aplicar a permissão EDT_CLASS para uma lotação. Provavelmente, vai funcionar quando o servidor for reiniciado.
