### ISSUE TITLE
[Siga-Sr] Cadastro de Ação

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#89]
-Ilustração:
![captura_de_tela_011615_035454_pm](https://cloud.githubusercontent.com/assets/4949149/5781225/04a3427c-9d98-11e4-8a86-14e4f3067580.jpg)

-Como reproduzir:
Na página de cadastro de ação (https://siga-dev/sigasr/acao/editar), clicar no botão "Incluir", preencher os campos do formulário com dados quaisquer e clicar em "Gravar";

**Comment by kmacedovarela** [comment]
Problema identificado. Solução sendo implementada pelo @hodrigohamalho

**Comment by kmacedovarela** [comment]
Feito
