### ISSUE TITLE
DOC: Falta o nome "conteúdo" no campo de pesquisa

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#904]
Reportado por Misael (CJF) que está faltando o campo "conteúdo" na tela de pesquisa de documentos.

![image](https://cloud.githubusercontent.com/assets/2985140/15791308/f952fc62-29ac-11e6-8368-a3a5d07d4145.png)

**Comment by esredson** [comment]
Corrigido no modelo geral. Alterado também o ftl para não ter uma definição default do label e campo de busca, visto que depende do ambiente (331f694)
