### ISSUE TITLE
GC: ao editar conhecimento, a parte do título que esteja após aspas é cortada

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#915]
Talvez seja o mesmo problema da #599

**Comment by Chrystinne** [comment]
Explicando o problema e por que ele ocorre:

- Um determinado conhecimento contém aspas no título:

![issue915-1](https://cloud.githubusercontent.com/assets/4949149/18794560/64d5e6fc-8196-11e6-83e5-08c16f25ea1a.png)

- Ao clicar em editar, a parte do título que possui aspas é cortada:

![issue915-2](https://cloud.githubusercontent.com/assets/4949149/18794573/7942ea54-8196-11e6-8bc0-db6178823acd.png)

Isto porque as aspas estão fechando o atributo value do título (elemento do tipo input text):

![issue915-3](https://cloud.githubusercontent.com/assets/4949149/18794620/b8ed3f92-8196-11e6-9c0f-07123fe80111.png)

**Comment by Chrystinne** [comment]
Resolvido!

![captura_de_tela_092316_020827_pm](https://cloud.githubusercontent.com/assets/4949149/18794707/3a78419c-8197-11e6-994d-9a548133b7d7.jpg)

**Comment by esredson** [comment]
Quem é essa Jiu Uihuio idosa, do título do TMPGC-5584? rsrs

**Comment by Chrystinne** [comment]
hauhauahaua tb achei engraçado que eu digitei aleatoriamente e acabou saindo uma palavra em português :D
