### ISSUE TITLE
SR/GC: Às vezes, não vem a lista completa de conhecimentos relacionados

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#916]
Analisar por que, ao abrir solicitação e selecionar o item, algumas vezes a lista de conhecimentos relacionados, à direita, vem com alguns conhecimentos faltando. Na tentativa seguinte, a falha não ocorre.

**Comment by Chrystinne** [comment]
Testei em produção e esse problema não ocorre mais. Na verdade, a rotina que exibe os conhecimentos relacionados na abertura/edição de solicitações será usada como exemplo para corrigir o filtro de conhecimentos relacionados da exibição de um conhecimento (dentro no sistema GC), que está trazendo conhecimentos em excesso (não tão relacionados) ao conteúdo em questão (#1154).
