### ISSUE TITLE
[Siga-Doc] Erro na visualização de documento criado (Interno Importado)

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#92]
-Ilustração:
![captura_de_tela_011915_125203_pm](https://cloud.githubusercontent.com/assets/4949149/5802218/029f9fae-9fda-11e4-9536-586d544715c7.jpg)

-Como reproduzir:
Criar um novo documento; Em "Origem" escolher "Interno Importado"; Selecionar "digital"; Selecionar Tipo Memorando; Definir um subscritor para o documento e uma descrição qualquer; Clicar em Ok;

**Comment by kmacedovarela** [comment]
@Chrystinne  você consegue localizar a classe br.gov.jfrj.itextpdf.MyPD4ML no seu projeto? Se sim, pode me indicar sua localização?

O erro ocorre pois esta classe não existe. 
13:02:31,721 ERROR [stderr] (http-/10.10.0.68:8180-13) java.lang.ClassNotFoundException: br.gov.jfrj.itextpdf.MyPD4ML from [Module "deployment.sigaex.war:main" from Service Module Loader]

**Comment by Chrystinne** [comment]
@kmacedovarela Não fica no repositório principal do Siga. Fica no repositório de extensões (_git_jfrj_ext). O caminho é _git_jfrj_ext\siga-ext-conv-html\src\main\java\br\gov\jfrj\itextpdf

**Comment by hodrigohamalho** [comment]
@Chrystinne mas onde fica esse repositório ? Qual máquina ou servidor? Queria clonar ele mas não sei de onde pegar.

**Comment by Chrystinne** [comment]
@hodrigohamalho Segue o endereço: K:\ADMINISTRACAO\STI\CSIS\SESIA\01 Repositorios

**Comment by hodrigohamalho** [comment]
valeu!

**Comment by hodrigohamalho** [comment]
Ao tentar criar esse novo documento um ClassNotFound era gerado, corrigi isso mas em homologação continua aparecendo em branco o documento, vou debugar nesse ambiente pra tentar descobrir o que é...

**Comment by kmacedovarela** [comment]
Os devidos erros relacionados a migração para o  EAP 6 foram resolvidos. 

**Observação importante:**
O mesmo teste foi realizado nos três ambientes: desenvolvimento, homologação e produção, a conclusão foi a seguinte:

Este é um errado absolutamente relacionado a diferença de encodings no banco de dados e/ou a forma como a string está salva no banco e é processada no código. O erro ocorre devido aos caracteres especiais existentes no cabeçalho do documento no texto:

![a](https://cloud.githubusercontent.com/assets/253186/5884765/321400be-a349-11e4-9943-fadb90ea7789.PNG)
 
Esta diferença de encoding entre bancos gera uma diferença em todos os ambientes:
* Em desenvolvimento (pode ser reproduzido na versailles):
   * Caracteres exibidos de maneira incorreta: PODER JUDICIÃƒÆ'Ã'ÂRIO JUSTIÃƒÆ'Ã¢â'¬Â¡A FEDERAL

* Em homologação (ambiente espelho ao de produção):
   * Erro reportado nesta issue. Erro ao salvar o documento, que consequentemente é salvo em branco no banco, ocasionando os erros #93 e #94

* Em produção: 
   * Comportamento ideal, onde os erros #93 e #94 não ocorrem. 
![b](https://cloud.githubusercontent.com/assets/253186/5884791/a1d3dcbc-a349-11e4-876f-e9d46e4ef476.PNG)

Será aberta uma issue para que este problema seja analisado pela equipe, pois foge do escopo relacionado a migração, uma vez que o ambiente de produção demonstrou o comportamento ideal.

**Comment by Markenson** [comment]
Exite a possibilidade da exibição em branco não ser no encoding. No siga.properties há algumas propriedades com os ids de alguns modelos (isso precisa ser melhorado no futuro). Favor verificar quais valores estão configurados para as propriedades abaixo (extraídas da SIGAT)

siga.ex.treina.modelos.interno_importado = 1219
siga.ex.treina.modelos.processo_administrativo = 544
