### ISSUE TITLE
GC: Acentuação não é exibida corretamente no envio de notificação

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#921]
Reportado por Raphael (email, 10/06/2016 18:48) que a notificação do siga-gc está desformatada. Segue exemplo do conteúdo:

```
Informamos a lota&ccedil;&atilde;o SEINAP a respeito do conhecimento n&ordm; TRF2-GC-2016/00134, com o seguinte título: Assijus - Informações técnicas. Para acessar o conhecimento, acesse o endereço 
```

**Comment by Chrystinne** [comment]
![captura_de_tela_092216_012419_pm](https://cloud.githubusercontent.com/assets/4949149/18756871/dfcbb2a8-80c7-11e6-97bd-bac899dbd0db.jpg)

Resolvido!
