### ISSUE TITLE
[Siga-Doc] Erro na visualização de dossiê (Interno Importado)

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#93]
-Relacionado à #92 

-Ilustração:
![captura_de_tela_011915_125949_pm](https://cloud.githubusercontent.com/assets/4949149/5802334/0e6e30a6-9fdb-11e4-8557-ff5a4e97c255.jpg)

-Como reproduzir:
Criar documento Interno Importado (conforme indicado na #92); Clicar em "Visualizar dossiê";

**Comment by kmacedovarela** [comment]
#92
