### ISSUE TITLE
DOC: checkbox 'exibir anexos assinados' não está funcionando no Chrome

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#935]
Para reproduzir o erro:
- Entrar no TRF2-MEM-2016/02908, clicar no link 'Assinar anexos da Via'. Na tela de Anexos Pendentes de Assinatura, ao clicar no checkbox 'exibir anexos assinados', dispara o erro abaixo:

![captura_de_tela_062216_015102_pm](https://cloud.githubusercontent.com/assets/8461113/16275435/5cad0096-3880-11e6-9e6e-e6987fb2af1b.jpg)

![captura_de_tela_062216_015117_pm](https://cloud.githubusercontent.com/assets/8461113/16275456/6673405e-3880-11e6-8ce5-2ab10e7b22d5.jpg)

**Comment by rafaela00castro** [comment]
Verifiquei que no IE funciona:

- Quando não tem nenhum anexo assinado, mostra mensagem:

![captura_de_tela_062216_022301_pm](https://cloud.githubusercontent.com/assets/8461113/16276453/d4212888-3884-11e6-80b0-7775fee8aec9.jpg)

- Quando possui anexo assinado. Nesse caso, o botão de assinar deveria aparecer no final para mostrar para o usuário que ele assinará os anexos selecionados das duas "caixas" (anexos pendentes e anexos assinados)
![captura_de_tela_062216_022205_pm](https://cloud.githubusercontent.com/assets/8461113/16276425/b2769b8c-3884-11e6-97f5-4e08408d251b.jpg)

**Comment by esredson** [comment]
Resolvido
