### ISSUE TITLE
[Siga-Doc] Erro na visualização de impressão (Interno Importado)

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#94]
-Relacionado à #92;

-Ilustração:
![captura_de_tela_011915_010814_pm](https://cloud.githubusercontent.com/assets/4949149/5802430/3b00ebe4-9fdc-11e4-8c92-2a58a7499d8e.jpg)
 
-Como reproduzir:
Criar documento Interno Importado (conforme indicado na #92); Clicar em "Visualizar impressão"; A janela apresenta documento em branco;

**Comment by kmacedovarela** [comment]
#92
