### ISSUE TITLE
GC: Recuo nos títulos dos conhecimentos

### ISSUE THREAD

**Issue by crivano** [projeto-siga/siga#945]
Sugiro remover o recuo nos títulos dos conhecimentos (veja abaixo). Considerando que os parágrafos não têm recuo, fica bem estranho! :)

![captura_de_tela_062316_034550_pm](https://cloud.githubusercontent.com/assets/4137623/16315665/90e79586-3959-11e6-80d8-8b23885bd83f.jpg)

**Comment by Chrystinne** [comment]
Não sei se houve alguma mudança, mas testei o uso de títulos no ckeditor e não está adicionando recuos. 

Caso alguém perceba que estão sendo adicionados recuos, favor reabrir a issue, informando como reproduzir.
