### ISSUE TITLE
SR: eliminar registros do banco criados para os atributos vazios 

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#946]
Quando um usuário não preenchesse um atributo, não deveria ser criado registro na tabela. Com a implementação da solicitação TRF2-SR-2015/18539 será obrigatório o preenchimento dos atributos

**Comment by esredson** [comment]
Ver #1075

**Comment by rafaela00castro** [comment]
Quando entrou a versão [5.3.4](https://github.com/projeto-siga/siga/releases/tag/5.3.4) essa questão foi corrigida. Ver issue #1010.
Sendo assim somente cria registro de atributos preenchidos. mesmo para aqueles que não são obrigatórios.
