### ISSUE TITLE
[Siga-Doc] Botões "Pesquisar" e "Novo" duplicados 

### ISSUE THREAD

**Issue by Chrystinne** [projeto-siga/siga#95]
-Ilustração:
![captura_de_tela_011915_013101_pm](https://cloud.githubusercontent.com/assets/4949149/5802801/6955946a-9fdf-11e4-8369-a09d48b55c7d.jpg)

-Como reproduzir:
Acessar página inicial do Siga;

-Observação:
Na produção, estes botões estão disponíveis apenas abaixo de "Processos Administrativos"

**Comment by kmacedovarela** [comment]
Feito 
863fa935ce0b39a0a773ef54a7ac5cc27d7ed618
