### ISSUE TITLE
GC: Exibir gráficos do graph viz

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#951]
Seria interessante se siga-gc pudesse ler o código do [graph viz](http://www.graphviz.org/) e montasse diretamente o gráfico. Melhor ainda se um link do que apontasse para um código graph viz, fosse convertido diretamente (ex: https://raw.githubusercontent.com/projeto-siga/docker/master/doc/arch.gv), pois dessa forma, além de controlar a versão do gráfico no github, a documentação seria atualizada automaticamente.

O site [webgraphviz](http://www.webgraphviz.com/) pode ser um ponto de partida como exemplo para implementar essa funcionalidade.

**Comment by esredson** [comment]
TRF2-SR-2016/33848
