### ISSUE TITLE
SR: erro na exibição resumida da data com horário

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#957]
A solicitação TRF-Sr-2016/28737 foi aberta à 01:20. Ao acessar às 08:50, aparecia a informação de que o cadastro foi "ontem, às 01:20", embora tenha ocorrido no mesmo dia. Verificar se o erro é no SigaCalendar ou se pode ter ligação com o fato de o expediente começar às 11:00.

**Comment by Chrystinne** [comment]
![captura_de_tela_030717_044114_pm](https://cloud.githubusercontent.com/assets/4949149/23674496/e1c03876-0354-11e7-8499-2dd25dc7f1c5.jpg)

**Comment by Chrystinne** [comment]
Resolvido.
