### ISSUE TITLE
DOC: comunicação de alteração de frequência apagando os dados

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#964]
JFRJ-SR-2016/39459.01. O erro ocorre na versão 5.x. Embora eu não tenha conseguido reproduzir, parece estar relacionado aos vários refreshes. Como o modelo é em Freemarker, verificar qual componente passou a funcionar sem o uso do ajax.

**Comment by Chrystinne** [comment]
@esredson, eu e @Markenson também não conseguimos reproduzir o problema. Testamos a alteração de motivo, tanto na axor quando na versão 5.x e, em ambos, a alteração foi salva.

**Comment by Chrystinne** [comment]
Corrigido o modelo na base de desenvolvimento. Para simular os problema que estavam ocorrendo no modelo, foi realizado o seguinte teste: foi criado um documento e feito alguns lançamentos. Em seguida, alguns membros da lotação foram finalizados no corporativo. Ao editar o documento, o modelo continuou correto, mantendo os lançamentos adequadamente.

O mesmo procedimento de correção e testes foi realizado na base de homologação e em seguida o modelo foi alterado em produção.

Observação: Documentos deste tipo deverão ser criados a partir do zero. Não poderão ser editados modelos da versão antiga com bug, pois o modelo está perdendo as informações de lançamentos salvas na versão antiga.
