### ISSUE TITLE
GERAL: organizar a utilização dos caches e controle de transações

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#977]
Após todos os projetos webwork e Play! Framework serem migrados para o framework vraptor, as definições de transações (JTA) e uso do cache de segundo nível ficaram mescladas com as características do framework de origem. Isso precisa ser organizado.
1. No projeto docker, as configurações dos datasouces estão todas com jta="false"
2. Na nossa produção, alguns datasources estão com jta="true" e outras como jta="false"

![image](https://cloud.githubusercontent.com/assets/2985140/16595676/cdfcb462-42c6-11e6-9b36-89b2e2995c08.png)
1. Existem duas bibliotecas de caches diferentes em uso: ehcache e infinispan.

**Comment by esredson** [comment]
Relacionada à #900
