### ISSUE TITLE
[HMG] [Siga-Doc] Assinatura digital com capicom (IE) não está funcionando

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#98]
Ao fazer uma assinatura digital de documento no IE, usando a capicom, o sistema fica parado na etapa de gravação de assinatura, conforme imagem abaixo:

![image](https://cloud.githubusercontent.com/assets/2985140/5837400/0bab1d70-a166-11e4-95e5-53a1d0f5bcfb.png)

**Comment by hodrigohamalho** [comment]
Tem como mandar o fluxo pra reproduzir markenson, não precisa ser as imagens pode mandar via texto mesmo pra não te tomar muito tempo.

**Comment by Markenson** [comment]
1. Entre no documento JFRJ-BIE-2015/00001(http://siga-hmg/sigaex/expediente/doc/exibir.action?sigla=JFRJ-BIE-2015%2F00001-A)
2. Clique no link "Assinar"
3. Clique no botão marrom "Assinar documento"

**Comment by serggiobarata** [comment]
Olá, Hodrigo Ramalho.
Me chamo Serggio, carioca perdido pelo Pará.
Estou com o mesmo problema acima quando tento assinar documentos ou anexos no SIGA-DOC do Tribunal de Justiça onde trabalho. Também utilizo Windows 10 Pro com IE 11 (versão X64).
Você pode me ajudar a resolver isso? Nem o pessoal da informática do Tribunal conseguiu.
Att.
![sem titulo](https://user-images.githubusercontent.com/37607091/37693939-d971ba38-2cba-11e8-9f68-1e3e98545de5.png)
![sem titulo2](https://user-images.githubusercontent.com/37607091/37693940-d9d36aa8-2cba-11e8-886a-e3e9c5167fd2.png)

**Comment by crivano** [comment]
@hodrigohamalho , obrigado pela ajuda!

@serggiobarata , será que a Capicom está corretamente instalada no Windows 10? Ela não vem mais com o Windows e seria necessário instalar ela manualmente.

Já temos uma tecnologia bem melhor para produzir assinaturas digitas, agora usando o Chrome. O que vcs acham de fazer o upgrade? Entrem em contato que explico como proceder.

**Comment by serggiobarata** [comment]
Eu instalei a Capicom de um pacote da Microsoft, manualmente. Infelizmente o SIGA-DOC do TJPA só funciona com o IE. Como eu faço para conseguir usá-lo no Chrome ou em outros navegadores?

Att.
Antonio Sérgio Barata da Silva

De: Renato Crivano
Enviado:quarta-feira, 21 de março de 2018 09:55
Para: projeto-siga/siga
Cc:serggiobarata; Mention
Assunto: Re: [projeto-siga/siga] [HMG] [Siga-Doc] Assinatura digital com capicom (IE) não está funcionando (#98)

@hodrigohamalho , obrigado pela ajuda!
@serggiobarata , será que a Capicom está corretamente instalada no Windows 10? Ela não vem mais com o Windows e seria necessário instalar ela manualmente.
Já temos uma tecnologia bem melhor para produzir assinaturas digitas, agora usando o Chrome. O que vcs acham de fazer o upgrade? Entrem em contato que explico como proceder.

**Comment by serggiobarata** [comment]
Hummmm, não sei como faz isso, sou burro nestas coisas

Em qua, 21 de mar de 2018 08:47, Rodrigo Ramalho da Silva <
notifications@github.com> escreveu:

**Comment by mstarkRules** [comment]
> Olá, Hodrigo Ramalho.
> Me chamo Serggio, carioca perdido pelo Pará.
> Estou com o mesmo problema acima quando tento assinar documentos ou anexos no SIGA-DOC do Tribunal de Justiça onde trabalho. Também utilizo Windows 10 Pro com IE 11 (versão X64).
> Você pode me ajudar a resolver isso? Nem o pessoal da informática do Tribunal conseguiu.
> Att.
> ![sem titulo](https://user-images.githubusercontent.com/37607091/37693939-d971ba38-2cba-11e8-9f68-1e3e98545de5.png)
> ![sem titulo2](https://user-images.githubusercontent.com/37607091/37693940-d9d36aa8-2cba-11e8-886a-e3e9c5167fd2.png)

Fala, meu parceiro, @serggiobarata , também estou aqui pelo Pará, mas sou morador daqui mesmo hahaha

Tô respondendo esse tópico agora pq não achei nada de conteúdo sobre esse que vc estava precisando(e eu tbm), então se alguém estiver pesquisando sobre pode ser que isso ajude.

Resolução que encontrei:
Pra assinar com o SIGADOC vc precisa de:
-usar o Internet Explorer (que m** hein kk)
-ter os drivers corretos do seu certificado digital instalados
-instalar a tal biblioteca CAPICOM (o link está na própria pagina do SIGADOC qdo vc tentar assinar)

Se tiver com tudo isso e mesmo assim não estiver funcionando,
1 - abra o iexplorer
2 - vá em opções de internet
3 - na opção SEGURANÇA, na aba INTERNET, mude a opção de nível de segurança de MÉDIO-ALTO para MÉDIO.

Reinicie o processo de assinatura e veja se funcionou.
Se não funcionou, reinstale o CAPICOM e tente novamente.


Não sei exatamente que recurso de segurança do explorer bloqueia o processo de assinatura, mas foi a única que funcionou pra mim, após muuuitos testes.

Abraços!
