### ISSUE TITLE
SR: exibir carregando nas telas de administração

### ISSUE THREAD

**Issue by rafaela00castro** [projeto-siga/siga#980]
Deveria ser exibida a informação Carregando (blockUI) enquanto as dataTables são montadas

**Comment by rafaela00castro** [comment]
Usar também em todos os casos em que houvesse bloqueio do botão gravar. Assim, deveria chamar o jQuery.block(). Por exemplo, sempre que se der um submit.

**Comment by esredson** [comment]
Ver #1072
