### ISSUE TITLE
GC: o módulo de conhecimentos está sem o botão Pesquisar no gadget

### ISSUE THREAD

**Issue by esredson** [projeto-siga/siga#983]
Incluir o "Pesquisar Conhecimentos"

**Comment by conden** [comment]
É importante que o Menu Superior da página para onde o botão irá direcionar apresente as mesmas opções oferecidas pela página de pesquisa de solicitações, encurtando também o caminho até o menu de Administração dos Conhecimentos.
![menudesejado](https://cloud.githubusercontent.com/assets/20356321/16687669/76d3762c-44f0-11e6-89f3-ef39b92bb310.png)
