### ISSUE TITLE
[Siga-Doc] Tela em branco ao selecionar atendente em transferência em lote

### ISSUE THREAD

**Issue by Markenson** [projeto-siga/siga#99]
Ao selecionar um tipo de atendente na tela de transferência em lote a tela do sistema fica em branco. 

Como acessar:
1. Menu Siga/Módulos/Documentos 
2. Menu Documentos/Transferir em lote

Como reproduzir:
Altere o campo atendente de "Órgão integrado" para matrícula.

Ilustração:
![image](https://cloud.githubusercontent.com/assets/2985140/5837593/a067b44a-a167-11e4-9401-99a623413766.png)

**Comment by kmacedovarela** [comment]
Resolvido, se voltar a ocorrer, favor reabrir.
Adicionada a propriedade org.apache.tomcat.util.http.Parameters.MAX_COUNT ao JBoss
